### ISSUE TITLE
Liquibase.listUnrunChangeSets is executing DDL statement

### ISSUE THREAD

**Issue by endrejeges** [liquibase/liquibase#1052]
**Description**
Liquibase.listUnrunChangeSets wants to create DATABASECHANGELOG if it does not exist. The method should throw an exception if the DATABASECHANGELOG and/or the DATABASECHANGELOGLOCK table does not exist. Its is unexpected to see a DDL or a modification being executed while collecting unrun changesets.

**To Reproduce**
Execute the Liquibase.listUnrunChangeSets on an empty database.

**Stacktrace**
```
Wrapped by: java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398)
	... 61 common frames omitted
Wrapped by: liquibase.exception.DatabaseException: ORA-01031: insufficient privileges
 [Failed SQL: (1031) CREATE TABLE DML_USER.DATABASECHANGELOG (ID VARCHAR2(255) NOT NULL, AUTHOR VARCHAR2(255) NOT NULL, FILENAME VARCHAR2(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR2(10) NOT NULL, MD5SUM VARCHAR2(35), DESCRIPTION VARCHAR2(255), COMMENTS VARCHAR2(255), TAG VARCHAR2(255), LIQUIBASE VARCHAR2(20), CONTEXTS VARCHAR2(255), LABELS VARCHAR2(255), DEPLOYMENT_ID VARCHAR2(10))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:111)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:284)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1226)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1291)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1281)
```

**Expected behavior**
I would expect that an exception is thrown stating that the DATABASECHANGELOG or the DATABASECHANGELOGLOCK does not exist.

**Additional context**
I execute the changelogs in a separate container with a user (DDLDML_USER) having both DDL and DML privileges. To make sure that the application is started on a compatible database I check at startup if there are any unrun changeSets with a user (DML_USER) having no DDL, but only DML privileges (changing the current schema "ALTER SESSION SET CURRENT_SCHEMA=DDLDML_USER"). The above exception appeared when the alter schema was skipped for some reason. I caught the listUnrunChangeSets red handed trying to create the DATABASECHANGELOG table. I use "Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production" and Liquibase 3.8.7.

**Comment by SteveDonie** [comment]
Thanks for the bug report! We will definitely consider this for an upcoming release.

**Comment by ro-rah** [comment]
Could I get an opinion on this from the community?  @nvoxland ?  I think this is expected behavior.  The DATABASECHANGELOG* tables are liquibase metadata tables and should be managed by the liquibase process as it sees fit is my opinion.
