### ISSUE TITLE
Invalid type generated for SMALLINT type column in Postgresql 11

### ISSUE THREAD

**Issue by rsurducan** [liquibase/liquibase#1085]
**Description**
I'm using Postgresql 11 and Liquibase v3.8.8 (I had the same issue in v3.8.2).

For a column with type smallint:
`action_id smallint NOT NULL`
when running liquibase.generateChangeLog(..) the following change set will be generated.
`<changeSet author="xxx (generated)" id="1586384554298-1">
    <createTable tableName="usage_log">
        <column name="action_id" type="SMALLINT(5)">
            <constraints nullable="false"/>
        </column>
    </createTable>
</changeSet>`
When updating an empty schema with a database change log that contains the above mentioned change set, I'm getting the following error:
`     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
  Position: 63 [Failed SQL: (0) CREATE TABLE dest_schema.usage_log (action_id SMALLINT(5) NOT NULL)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646) ~[liquibase-core-3.8.8.jar:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[liquibase-core-3.8.8.jar:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[liquibase-core-3.8.8.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-3.8.8.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.8.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:175) ~[liquibase-core-3.8.8.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:168) ~[liquibase-core-3.8.8.jar:?]`

The problem is with the SMALLINT(5) type that is not valid.

**Expected behavior**
I was expecting the type for the column to be SMALLINT.
`        
<column name="action_id" type="SMALLINT">
  <constraints nullable="false"/>
</column>
`

**Comment by rsurducan** [comment]
I just found out that you released v3.8.9 where you address this issue. I verified and the type for the column is correct.
