### ISSUE TITLE
Facing VM crash issue while installing through mvn install

### ISSUE THREAD

**Issue by odidev** [liquibase/liquibase#1092]
I am trying to install the latest code from master via mvn install in the system and facing the following issue:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.601 s
[INFO] Finished at: 2020-04-15T05:45:05Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project liquibase-core: There are test failures.
[ERROR]
[ERROR] Please refer to /liquibase/liquibase-core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /liquibase/liquibase-core && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/liquibase/liquibase-core/target/jacoco.exec -jar /liquibase/liquibase-core/target/surefire/surefirebooter888239703614255696.jar /liquibase/liquibase-core/target/surefire 2020-04-15T05-45-04_395-jvmRun1 surefire17867843508185498400tmp surefire_0331711362811574271tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /liquibase/liquibase-core && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/liquibase/liquibase-core/target/jacoco.exec -jar /liquibase/liquibase-core/target/surefire/surefirebooter888239703614255696.jar /liquibase/liquibase-core/target/surefire 2020-04-15T05-45-04_395-jvmRun1 surefire17867843508185498400tmp surefire_0331711362811574271tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
```

Kindly suggest regarding the resolution of the issue.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-203) by [Unito](https://www.unito.io/learn-more)

**Comment by ro-rah** [comment]
Hi @odidev ,

Would you mind adding the log file refereed to in your ouptup?

> [ERROR] Error occurred in starting fork, check output in log

I don't have enough info to see what the underlying cause of the crash is.  Perhaps there is an issue with Liquibase or maybe the VM ran out of memory, just can't tell.

Thanks!

Ronak

**Comment by odidev** [comment]
Thanks @ro-rah for the quick response. Please find the log file for the "mvn clean install " command: [output.txt](https://github.com/liquibase/liquibase/files/4574463/output.txt)

Please do revert if something else is required from my end.

**Comment by molivasdat** [comment]
Thanks @odidev for reporting this.  Does this fail with a non-beta release of liquibase like v3.8.9?
Can you update your POM to use the latest stable release?

**Comment by odidev** [comment]
Hi @molivasdat , 

As per your suggestion I have tested the package with the latest stable release version v3.8.9. It is working fine and liquibase-core binary is built

**Comment by odidev** [comment]
The issue is resolved by @molivasdat suggestion so closing this ticket.
