### ISSUE TITLE
mixing parenthesis with comma does not work

### ISSUE THREAD

**Issue by robstoll** [liquibase/liquibase#1103]
## Environment
**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**:  none

**Database Vendor & Version**: mariadb

**Operating System Type & Version**: ubuntu 19.10

## Description
e.g. `"(local, cloud) and (test, pre-prod)"` fails with

```
liquibase.exception.UnexpectedLiquibaseException: Cannot parse expression (local
	at liquibase.util.ExpressionMatcher.matches(ExpressionMatcher.java:58)
	at liquibase.ContextExpression.matches(ContextExpression.java:90)
	at liquibase.ContextExpression.matches(ContextExpression.java:82)
	at liquibase.changelog.filter.ContextChangeSetFilter.accepts(ContextChangeSetFilter.java:42)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:70)
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:281)
	at liquibase.Liquibase.update(Liquibase.java:198)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
```

## Steps To Reproduce
See above

## Actual Behavior
See above

## Expected/Desired Behavior
should work the same way as:

`"(local or cloud) and (test or pre-prod)"`

**Comment by molivasdat** [comment]
Hi @robstoll .  Thanks for taking the time to write up this issue.  One additional question to help us evaluate this issue, where are you using the mixture of commas and paranthesis?  In the contexts, in the labels? Can you share the command you are using to see the error?

**Comment by robstoll** [comment]
in the yml, for instance:
```
databaseChangeLog:
  - changeSet:
      id: 1
      context: "(local, cloud) and (test, pre-prod)"
```

**Comment by molivasdat** [comment]
Thanks @robstoll. I think that should be good enough to process further.
