### ISSUE TITLE
Failed to read schema document dbchangelog-3.5.xsd

### ISSUE THREAD

**Issue by federico-piazza** [liquibase/liquibase#1154]
**Liquibase Version**:
We are using liquibase-gradle-plugin 1.2.4, I think this is using liquibase-core 3.4.2.

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Gradle dependency: `'org.liquibase:liquibase-gradle-plugin:1.2.4'`

**Database Vendor & Version**:
Docker image: mysql:5.7

**Operating System Type & Version**:
Docker image: gradle:6.2.1-jdk8

## Description

Liquibase stopped running our xml migration suddenly, there were no changes made. Our scripts with 2 years old started failing.

Similar problem to this:
https://github.com/liquibase/liquibase/issues/1038

## Steps To Reproduce

```
./gradlew :metadata-mysql:update -PrunList=test -PdbUrl=jdbc:mysql://mysql:3306/test -PdbUsername=root -PdbPassword=password
```

## Actual Behavior

```
Fri May 15 01:36:42 GMT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
INFO 5/15/20 1:36 AM: liquibase: Successfully acquired change log lock
WARNING 5/15/20 1:36 AM: liquibase: schema_reference.4: Failed to read schema document 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
INFO 5/15/20 1:36 AM: liquibase: Successfully released change log lock
Unexpected error running Liquibase: schema_reference.4: Failed to read schema document 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

SEVERE 5/15/20 1:36 AM: liquibase: schema_reference.4: Failed to read schema document 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
liquibase.exception.ChangeLogParseException: Error parsing line 8 column 106 of liquibase/changelog-test.xml: schema_reference.4: Failed to read schema document 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:114)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:17)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:227)
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-265) by [Unito](https://www.unito.io/learn-more)

**Comment by mariochampion** [comment]
hey @federico-piazza  -- are you still having this issue? Liquibase site was updated yesterday and potentially this link broke, but it should be good now.

I can reach this doc via curl and in the browser -- can you?

**Comment by federico-piazza** [comment]
@mariochampion it seems all is good now, thanks for letting me know. Closing this one.
