### ISSUE TITLE
Failed to create mysql function through sql statement in sqlFile

### ISSUE THREAD

**Issue by Allurx** [liquibase/liquibase#1195]
## Environment

**Liquibase Version**: 3.6.3

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: mysql 8.0.15

**Operating System Type & Version**: windows 10

## Description

**`;`** in the mysql function is considered to be the end of a sql statement, causing the creation of the function to fail

## Steps To Reproduce

I specified the sqlFile to be executed in the databaseChangeLog, there are many sql statements that create mysql functions, and one of the sql statements to get the last quarter value is as follows:
```sql
CREATE  FUNCTION `previous_quarter`() RETURNS tinyint(3)
    DETERMINISTIC
    COMMENT 'Returns the last quarter value'
BEGIN
	RETURN if(QUARTER(now()) = 1, 4, QUARTER(now()) - 1);
END;

other functions...
```
When my application starts and executes the function statement created above, a sql syntax exception occurs
## Actual Behavior
The console output sql syntax error exception
```java
Caused by: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 [Failed SQL: CREATE  FUNCTION `previous_quarter`() RETURNS tinyint(3)
    DETERMINISTIC
    COMMENT 'Returns the last quarter value'
BEGIN
	RETURN if(QUARTER(now()) = 1, 4, QUARTER(now()) - 1)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 26 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 31 common frames omitted
```
From the exception stack information, it can be found that the end identifier in the SQL statement is truncated, resulting in a SQL syntax error
## Expected/Desired Behavior
Expect multiple mysql function sql or multiple ddl statements to be executed correctly

## Additional Context
Can liquibase provide a delimiter strategy to split multiple sql statements in the same sql file, instead of splitting sql statements by **`;`**

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-306) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment]
Hi @Allurx Is this what you are looking for?
https://docs.liquibase.com/change-types/community/sql.html
(See the parameter for endDelimiter)

**Comment by Allurx** [comment]
I have read this document. In my question, I specified a sql script to be executed through sqlFle. This script contains many ddl statements, but the mysql function must use a `;`at the end of a statement. Liquibase splits the statement by `;` by default, which will eventually cause the `end` identifier in the function to be truncated.You can try the example I mentioned above, the console will output sql syntax error.

**Comment by molivasdat** [comment]
Hi @Allurx This worked for me when adding a / after the ; and setting the endDelimiter to /
Another way is that you can break up the file into multiple changesets.
```
<changeSet author="molivasdat" id="1">
        <sqlFile endDelimiter="/"
            path="./file.sql"  
            relativeToChangelogFile="true"/>
    </changeSet>
```

and file that looks like this
```
CREATE  FUNCTION `previous_quarter`() RETURNS tinyint(3)
            DETERMINISTIC
            COMMENT 'Returns the last quarter value'
        BEGIN
            RETURN if(QUARTER(now()) = 1, 4, QUARTER(now()) - 1);
        END;
/

other functions...
```

**Comment by Allurx** [comment]
I have just tested it, and it does execute normally.It seems that I must add endDelimiter to the end of each ddl.Thank you very much for your reply.

**Comment by molivasdat** [comment]
Closing issue as solved.
