### ISSUE TITLE
Liquibase JSON support requires an external jar file [snakeyaml-1.12.jar] installation

### ISSUE THREAD

**Issue by samuelowino** [liquibase/liquibase#1224]
## Environment

Linux Ubuntu 18.0.4, Java 8,9,11,12,13+

**Liquibase Version**:3.9 and previous versions

**Liquibase Integration & Version**:  maven

**Liquibase Extension(s) & Version**: None

**Database Vendor & Version**: MySQL

**Operating System Type & Version**: Ubuntu 18 LTS

## Description

**Liquibase json changelog files** written in json don't get inbuilt support, instead, it requires downloading **snakeyaml** jar file and addition to the classpath. The extra step of adding a jar file is already a huge inconvenience, considering the support can be inbuilt.
- The specific concern is that liquibase-json support requires additional configuration.

## Steps To Reproduce
- Add liquibase dependency to your build system as a dependency e.g. gradle/maven
- You will notice that you can not start work with json changelog files with the default setup

## Actual Behavior
The addition of the default liquibase jar file to classpath does not enable changelog-json-file support.

## Expected/Desired Behavior
The desired behaviour is that after adding liquibase to the classpath one should be able to use json changelog files without additional configuration.

**Comment by samuelowino** [comment]
@ro-rah I hope this issue can get priority, thanks

**Comment by ro-rah** [comment]
@samuelowino , thanks so much for getting this issue in. What a pain, I didn't know json usage had this issue. So glad we got the community to keep us honest!

**Comment by ro-rah** [comment]
@molivasdat and @nvoxland  , hey if you happen to be processing this, check out Samuel and mine interaction on the Twitter verse to get the context and the importance of this:
https://twitter.com/RonakRahman/status/1274348067651833856

I also shared with @samuelowino [How to Contribute Code](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core).

**Comment by mariochampion** [comment]
hey @nvoxland -- lets asynch condition this one. maybe you can add some color as to what you think about bundling snakeyaml, which seems to be apache 2.0, in an upcoming release?

**Comment by molivasdat** [comment]
Hi @samuelowino I just downloaded 3.9 and 3.10 and they include snakeyaml 1.24 in the lib directory.  Is there a dependency on a certain method included in an earlier version of snakeyaml for you?
I also looking at the dependencies in the maven POM file. which has
`

\<dependency>

      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>1.24</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>   
 `

We don't include the snakeyaml.jar file in the liquibase.jar file specifically since we include it zip file and in the POM file as a dependency because other users may require a different version of snakeyaml as part of their build process.

**Comment by nvoxland** [comment]
I think the optional=true setting on our pom definition makes it so that the snakeyaml is not automatically included as a dependency. 

We did not want to require snakeyaml as a dependency of liquibase because as an embeddable library, we try to be very careful about what additional jars we are forcing on people embedding liquibase in their product. 

I think the fix for this will be to add the snakeyaml as a non-optional dependency on the liquibase-maven-plugin. That should allow json/yaml to work out of the box with maven, without adding the dependency on embedders.

**Comment by Quezion** [comment]
```
liquibase.exception.UnknownChangelogFormatException: Cannot find parser that supports changelogmssql.json
	at liquibase.parser.ChangeLogParserFactory.getParser(ChangeLogParserFactory.java:55)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:376)
	at liquibase.Liquibase.validate(Liquibase.java:2245)
```
It took a day of debugging to reach this thread. We use Liquibase via the Java API directly in a Clojure codebase & couldn't upgrade past 3.7.0 due to the above error.

I had to go hunting this down manually to figure out why code for the JsonParser existed but that it wasn't recognized. So I took a look at the actual parsers initialized at runtime & noticed missing JSON.

```
> (.getParsers (ChangeLogParserFactory/getInstance))
[#object[liquibase.parser.core.formattedsql.FormattedSqlChangeLogParser 0x1570d9e1 "liquibase.parser.core.formattedsql.FormattedSqlChangeLogParser@1570d9e1"] #object[liquibase.parser.core.sql.SqlChangeLogParser 0x3bae50f5 "liquibase.parser.core.sql.SqlChangeLogParser@3bae50f5"] #object[liquibase.parser.core.xml.XMLChangeLogSAXParser 0x39bfa0a6 "liquibase.parser.core.xml.XMLChangeLogSAXParser@39bfa0a6"]]
```

I was going to add the JsonChangeLogParser to Factory myself, but I got this error which finally led me here.
```
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/constructor/BaseConstructor
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
	at java.base/java.lang.Class.getMethods(Class.java:1904)
```

Hope this saves someone else some time 🍀

**Comment by bobfoster** [comment]
Is there some way to get liquibase to _not_ use snakeyaml just because it is there. Liquibase depends on older versions of snakeyaml which apparently aren't compatible with 1.29.

23:16:13.029 [http-nio-8080-exec-8] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Cannot find the class definition 'liquibase/serializer/core/yaml/YamlSerializer$LiquibaseResolver.class' in classloader: Paral\
lelWebappClassLoader^M
  context: compcatalog^M
  delegate: false^M
----------> Parent Classloader:^M
java.net.URLClassLoader@5717c37^M
. Reason: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/resolver/Resolver
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/resolver/Resolver
