### ISSUE TITLE
Liquibase 4.0 problem when starting with jar

### ISSUE THREAD

**Issue by severn-everett** [liquibase/liquibase#1276]
## Environment
**Liquibase Version**: 4.0

**Liquibase Integration & Version**: Spring Boot 2.3

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: PostgreSQL 11

**Operating System Type & Version**: Windows 10

## Description
An [issue](https://github.com/jhipster/generator-jhipster/issues/12105) was reported in JHipster's project page that my own team is encountering as well: starting up a Spring Boot fat jar that contains Liquibase fails to conduct the database schema migrations due to an issue with there not being a file system available for the Spring Boot jar.

## Steps To Reproduce
* Create a Spring Boot fat jar that cointains Liquibase version 4.0.0.
* Launch the Spring Boot application by running `java -jar /path/to/springBootApp.jar`

## Actual Behavior
Liquibase fails to start due to a series of errors like the one below:

```
java.nio.file.FileSystemNotFoundException: null
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at liquibase.resource.ClassLoaderResourceAccessor.loadRootPaths(ClassLoaderResourceAccessor.java:63)
```

Liquibase will encounter this error for each of the files within the fat jar, e.g.

* "jar:file:/C:/path/to/foo.jar!/BOOT-INF/classes!/"
* "jar:file:/C:/path/to/foo.jar!/BOOT-INF/lib/foo-api.jar!/"
* "jar:file:/C:/path/to/foo.jar!/BOOT-INF/lib/foo-domain.jar!/"

## Expected/Desired Behavior
Liquibase can start up normally.

## Additional Context
[This](https://stackoverflow.com/questions/25032716/getting-filesystemnotfoundexception-from-zipfilesystemprovider-when-creating-a-p) looks like a relevant posting from StackExchange regarding what may be the underlying cause.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-392) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.1.1

**Comment by nvoxland** [comment]
Thanks, we'll have to take a look.

**Comment by molivasdat** [comment]
Hi @severn-everett Thanks for writing up this issue.  We will add this to the list of issues that we are reviewing.

**Comment by molivasdat** [comment]
This looks like it only affects users that package db-changelogs in another jar file withing the springboot.jar file.  I'm not minimizing the issue, just letting others know.

**Comment by jehadnasser** [comment]
I got the error with this:
```
mvn clean install
java -jar target/myproject-1.0-SNAPSHOT.jar -h
```
but not anymore using this:
```
mvn compile
mvn exec:java -Dexec.mainClass=com.abc.App
```
May someone find this useful.

**Comment by joliebig** [comment]
Hi,

I'm experiencing the same issue with the following setup:
liquibase: 4.0.0
spring-boot: 2.3.3.RELEASE
springframework: 5.2.8.RELEASE

```
2020-09-01 13:00:00,064 [main] WARN  liquibase.integration - Cannot create filesystem for url jar:file:/<absolute-path-to-jar-file>!/BOOT-INF/classes!/: null 
java.nio.file.FileSystemNotFoundException: null
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at liquibase.resource.ClassLoaderResourceAccessor.loadRootPaths(ClassLoaderResourceAccessor.java:63)
	at liquibase.resource.ClassLoaderResourceAccessor.init(ClassLoaderResourceAccessor.java:47)
	at liquibase.resource.ClassLoaderResourceAccessor.openStreams(ClassLoaderResourceAccessor.java:94)
	at liquibase.resource.AbstractResourceAccessor.openStream(AbstractResourceAccessor.java:17)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:25)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:223)
	at liquibase.Liquibase$1.run(Liquibase.java:194)
	at liquibase.Scope.lambda$child$0(Scope.java:159)
	at liquibase.Scope.child(Scope.java:170)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:137)
	at liquibase.Liquibase.runInScope(Liquibase.java:1790)
	at liquibase.Liquibase.update(Liquibase.java:183)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:322)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:270)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at <package-to-main-application>.Application.main(Application.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by RainerGanss** [comment]
Same as @joliebig

**Comment by dekar91** [comment]
I have the same problem. I've checked version 3.10.2 - everything is ok, but **4.0.0** fails with "Cannot create filesystem for url jar" on every **liquibaseRuntime** dependency.

There is the config, what fails:
```
    implementation "org.liquibase:liquibase-core:4.0.0"
    liquibaseRuntime "org.liquibase:liquibase-core4.0.0"
    liquibaseRuntime 'org.liquibase:liquibase-groovy-dsl:2.1.2'
    liquibaseRuntime 'org.postgresql:postgresql'

    liquibaseRuntime "org.liquibase.ext:liquibase-hibernate5:4.0.0"
```

**Comment by dtrouillet** [comment]
Same error with Liquibase 4.0.0 and Spring Boot 2.3.1 (in same jar package).

**Comment by alan-czajkowski** [comment]
i get this error when running: `mvn liquibase:generateChangeLog`

**pom.xml**:
```
...
  <properties>

    <liquibase.version>4.0.0</liquibase.version>
    <liquibase.propertyFile>${project.basedir}/src/main/resources/db/liquibase.properties</liquibase.propertyFile>

  </properties>
...
<plugin>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-maven-plugin</artifactId>
        <version>${liquibase.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>generateChangeLog</goal>
            </goals>
            <configuration>
              <propertyFile>${liquibase.propertyFile}</propertyFile>
            </configuration>
          </execution>
        </executions>
      </plugin>
...
```

**Comment by dtrouillet** [comment]
Unfortunately, same issue with liquibase 4.1.0

**Comment by krusche** [comment]
We would appreciate if this bug could be fixed asap! Let us know if we can somehow help

**Comment by XSwifter** [comment]
Still reproduces on 4.1.0 version

**Comment by DanielFran** [comment]
I confirm, it still happens

**Comment by nvoxland** [comment]
Thanks, I'll take a look at it

**Comment by nvoxland** [comment]
I ended up rewriting the SpringResourceAccessor in 4.1.x to use Spring's resource loader more directly.

Could anyone try the current 4.1.x branch code against their environment and make sure it's working for you?

**Comment by RainerGanss** [comment]
thx, will have a look early next week.

**Comment by matejsp** [comment]
We have the same problem with 4.1.0. However it does not happen in all microservices that we use liquibase. It happens in one where we use XML changelog format. In other with YAML it does not. We reverted back to 3.10.2.

**Comment by RainerGanss** [comment]
ehm, than who can reopen it? I Can´t

**Comment by r2liquibase** [comment]
Hi, @RainerGanss ! See my edited comment above to resolve the issue.

**Comment by RainerGanss** [comment]
Hi @r2liquibase my bad! 

**4.1.1 fixed the issue**. 

Sorry and thx for the quick reply.

**Comment by r2liquibase** [comment]
Wonderful, @RainerGanss ! So happy to hear that! Thank you!

**Comment by StasPerekrestov** [comment]
Just tried 4.1.1. 
It works, but now it writes the issue description to stdout as a warning.
```
##      liquibase.com/support                     ##
##                                                ##
####################################################
Starting Liquibase at 16:00:55 (version 4.1.1 #10 built at 2020-10-12 19:24+0000)
[INFO] Executing on Database: jdbc:postgresql://localhost:5432/my-db?currentSchema=public
[INFO] Successfully acquired change log lock
[WARNING] Cannot create filesystem for url file:/Users/.../my-project/database/target/test-classes: /Users/.../my-project/database/target/test-classes
java.nio.file.NoSuchFileException: /Users/.../my-project/database/target/test-classes
    at jdk.nio.zipfs.ZipFileSystem.<init> (ZipFileSystem.java:160)
    at jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem (ZipFileSystemProvider.java:125)
    at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem (ZipFileSystemProvider.java:120)
    at ja...
....
   at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:61)
[INFO] Reading from databasechangelog
[INFO] Successfully released change log lock
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.975 s
[INFO] Finished at: 2020-11-03T16:01:05+02:00
[INFO] ------------------------------------------------------------------------
```
