### ISSUE TITLE
Liquibase 4.x.x endDelimiter doesn't work

### ISSUE THREAD

**Issue by iignateva** [liquibase/liquibase#1458]
## Environment
**Liquibase Version**: 4.1.0

**Liquibase Integration & Version**: spring boot

**Database Vendor & Version**: oracle

## Description
I tried to migrate on v4.1.0 (from 3.10.1) and got an error on <sqlFile> changeSet execution:

 Reason: liquibase.exception.DatabaseException: ORA-01735: invalid ALTER TABLE option
 [Failed SQL: (1735) alter table TABLE_ONE add field_one   number null/
alter table TABLE_TWO add field_one  number null]

## Steps To Reproduce
```
 <changeSet author="author" id="123">
        <sqlFile endDelimiter="/" path="sql_patches/my_patch.sql"
                 splitStatements="true"/>
        <rollback/>
    </changeSet>

```

my_patch.sql contains 2 sql-commands splitted by "/"

```
alter table TABLE_ONE add field_one   number null/
alter table TABLE_TWO add field_one  number null/
```

Log:
Successfully released change log lock
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
HandlerMethod details: 
...

Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set changelog/db.changelog-migrated-changesets.xml::my_patch.sql::author:
     Reason: liquibase.exception.DatabaseException: ORA-01735: invalid ALTER TABLE option
 [Failed SQL: (1735) alter table TABLE_ONE add field_one   number null/
alter table TABLE_TWO add field_one  number null]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:112)
	at liquibase.Liquibase$1.run(Liquibase.java:206)
	at liquibase.Scope.lambda$child$0(Scope.java:159)
	at liquibase.Scope.child(Scope.java:170)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:137)
	at liquibase.Liquibase.runInScope(Liquibase.java:1790)
	at liquibase.Liquibase.update(Liquibase.java:183)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:167)

```
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261)
... 16 more
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-756) by [Unito](https://www.unito.io/learn-more)

**Comment by iignateva** [comment]
I compared 4.1.0 with v3.10.1 and figured out the difference 
method isDelimiter (liquibase.util.StringUtil) were changed 
3.10.1 
`if (endDelimiter.length() == 1) {
                return piece.toLowerCase().equalsIgnoreCase(endDelimiter.toLowerCase());
}
`

4.1.0
`
if (endDelimiter.length() == 1) {
                if ("/".equals(endDelimiter)) {
                    if (previousPiece != null && !previousPiece.endsWith("\n")) {
                        return false;
                    }
                }
                return piece.toLowerCase().equalsIgnoreCase(endDelimiter.toLowerCase());
}`

**Comment by iignateva** [comment]
I replaced "/" with "/$
