### ISSUE TITLE
loadUpdateData broken for clob/text fields in 3.10.3

### ISSUE THREAD

**Issue by jwesselink** [liquibase/liquibase#1489]
## Environment
**Liquibase Version**: 3.10.3

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PostgreSQL 11

**Operating System Type & Version**: Mac OSX 10.15.7

## Description
After updating to version 3.10.3 I was unable to run a loadUpdateData changeset.

`
<changeSet id="id" author="me" runAlways="false">
  <loadUpdateData tableName="table" primaryKey="id" file="file.csv"/>
</changeSet>
`

This resulted in the following exception:

`
Caused by: java.lang.UnsupportedOperationException: Executable Prepared Statements are not supported for LoadUpdateDataChange yet . Very sorry.
	at liquibase.change.core.LoadUpdateDataChange.createPreparedStatement(LoadUpdateDataChange.java:79)
	at liquibase.change.core.LoadDataChange.generateStatements(LoadDataChange.java:486)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1256)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:622)
	... 94 more
`

It only seems to happen for CLOB fields (PostgreSQL `text` data type)

I checked older versions and in version 3.10.2 this still works. 

It looks like this was caused by a change in #1431 (line 477 & 478 of `LoadDataChange.java`)

The if condition is changed in this pr, the if condition always resolves to `true` when `needsPreparedStatement = true`. But in the older version of the code, the if would never be true if `hasPreparedStatementsImplemented()` returns `false`

Note that a CLOB field results in a `needsPreparedStatement = true` but `LoadUpdateDataChange` has no support for PreparedStatements (hasPreparedStatementsImplemented() returns false). This seems illogical, but this is how the old version of the code worked.

## Steps To Reproduce
List the steps to reproduce the behavior.

* Create a loadUpdateData changeset and make sure it updates a field of type CLOB 

## Actual Behavior
UnsupportedOperationException:
`
Caused by: java.lang.UnsupportedOperationException: Executable Prepared Statements are not supported for LoadUpdateDataChange yet . Very sorry.
	at liquibase.change.core.LoadUpdateDataChange.createPreparedStatement(LoadUpdateDataChange.java:79)
	at liquibase.change.core.LoadDataChange.generateStatements(LoadDataChange.java:486)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1256)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:622)
	... 94 more
`

## Expected/Desired Behavior
loadUpdateData is executed successfully

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-835) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.2.0

**Comment by molivasdat** [comment]
Hi @jwesselink Thanks for writing up this issue.  We have a fix associated with this issue.  We are looking at incorporating it into our next release.

**Comment by nvoxland** [comment]
The merged PR #1495 resolves this issue for 4.2.0

**Comment by lgrammel** [comment]
Are there any plans to backport this fix into 3.10.x?

**Comment by molivasdat** [comment]
Hi @lgrammel Checking with product management whether there will be a another 3.10.x version or not and whether this will be backported.

**Comment by lfgcampos** [comment]
Seems like the answer is no 😢
