### ISSUE TITLE
No validation errors when <property> definitions wrong

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#1566]
## Environment

**Liquibase Version**: 3.10

**Liquibase Integration & Version**: Spring boot

## Description

If a changelog includes a `<property dbms="postgresql"/>` entry, there is no validation error saying that name or file is required. 

Instead, a NullPointerException is thrown:

```
Caused by: java.lang.NullPointerException
    at liquibase.changelog.ChangeLogParameters.findParameter(ChangeLogParameters.java:155) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.ChangeLogParameters.getValue(ChangeLogParameters.java:146) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.isDbmsMatch(DatabaseChangeLog.java:470) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.isDbmsMatch(DatabaseChangeLog.java:464) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:336) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:305) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:565) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:348) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:305) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:565) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:348) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:305) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:216) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.Liquibase.update(Liquibase.java:189) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.Liquibase.update(Liquibase.java:178) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366) ~[liquibase-core-3.10.0.jar:?]
    at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314) ~[liquibase-core-3.10.0.jar:?]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
....
```

## Expected/Desired Behavior

An useful validation error such as "property defined in x/y/z.xml requires either a name/value or a file attribute".

This validation should apply to all changelog formats, not just xml.

**Comment by FBurguer** [comment]
There is not  NullPointerException but there isnt any validation either on liquibase 4.17.2.

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
