### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range

### ISSUE THREAD

**Issue by lorddev** [liquibase/liquibase#1573]
## Environment
Windows
**Liquibase Version**:
Liquibase Community 3.10.2 by Datical
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
postgres 12
**Operating System Type & Version**:
Windows 10 Pro

## Description
A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
* Ensure private information is redacted.

I'm running a liquibase changelog from Powershell in Windows. Java says String index out of range. In the past I've seen this happen due to new line characters or BOM. I've tried changing the encoding on the file and inspected it in Notepad++ with all characters shown, but I haven't found any problems.

```
13:41:07.368 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: String index out of range: 872
liquibase.exception.MigrationFailedException: Migration failed for change set (redacted).xml::(redacted)::aaron:
     Reason: java.lang.StringIndexOutOfBoundsException: String index out of range: 872
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:659)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:97)
        at liquibase.Liquibase.update(Liquibase.java:201)
        at liquibase.Liquibase.update(Liquibase.java:178)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1639)
        at liquibase.integration.commandline.Main.run(Main.java:303)
        at liquibase.integration.commandline.Main.main(Main.java:159)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 872
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.base/java.lang.String.charAt(String.java:709)
        at liquibase.util.StringUtils.getLastBlockComment(StringUtils.java:565)
        at liquibase.util.StringUtils.stripSqlCommentsAndWhitespacesFromTheEnd(StringUtils.java:637)
        at liquibase.sqlgenerator.core.CreateProcedureGenerator.removeTrailingDelimiter(CreateProcedureGenerator.java:110)
        at liquibase.sqlgenerator.core.CreateProcedureGenerator.generateSql(CreateProcedureGenerator.java:74)
        at liquibase.sqlgenerator.core.CreateProcedureGenerator.generateSql(CreateProcedureGenerator.java:25)
        at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
        at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:222)
        at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:105)
        at liquibase.executor.jvm.JdbcExecutor.access$600(JdbcExecutor.java:43)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:412)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:87)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:159)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1276)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1258)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:622)
        ... 7 common frames omitted
```

## Steps To Reproduce
List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

```
PS C:\projects\(redacted)\postgresql\application_core> liquibase --classpath=liquibase\postgresql-42.2.10.jar --changeLogFile=liquibase\changelog.xml --url=jdbc:postgresql://localhost:5432/(redacted) --username=(redacted) --password=PROMPT --logLevel=debug update
```

## Actual Behavior
String out of index exception occurs

## Expected/Desired Behavior
Shouldn't give string out of range exceptions.

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-989) by [Unito](https://www.unito.io/learn-more)

**Comment by lorddev** [comment]
The issue was that the text of the changelog file was commented out.
