### ISSUE TITLE
Derby CLOB: generate Changelog with diffType data: excpetion

### ISSUE THREAD

**Issue by ses1112** [liquibase/liquibase#1601]
## Environment

**Liquibase Version**: 4.1.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
installed

**Liquibase Extension(s) & Version**: 
-

**Database Vendor & Version**:
derby with driver-version 10.15.2.0

**Operating System Type & Version**:
Windows 10

## Description

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

## Steps To Reproduce
I have following table:

`CREATE TABLE UNTITLED (ID CHAR(36) NOT NULL, DATE_EDIT TIMESTAMP, DATE_NEW TIMESTAMP, USER_EDIT VARCHAR(63), USER_NEW VARCHAR(63), TEST CLOB(2147483647), PRIMARY KEY (ID));
`

With following data:

`INSERT INTO ADITO.UNTITLED (ID, DATE_EDIT, DATE_NEW, USER_EDIT, USER_NEW, TEST) 
	VALUES ('12                                  ', '2020-12-23 12:40:32.919', '2020-12-23 12:40:32.919', '4', '3', 'aretewrargareartadfdfads');
`

Now i have following liquibase.properties:

`changeLogFile: myChangelog.xml
url: jdbc:derby://localhost:1527/basic_data
username: user
password: password
driver: org.apache.derby.jdbc.ClientDriver
classpath: C:/entwicklungszweige/master/ao/application/designer/target/aditodesigner/aditoonline/modules/derbyclient.jar;C:/entwicklungszweige/master/ao/application/designer/target/aditodesigner/aditoonline/modules/ext/de.adito.aditoweb.packages.lwdatabase/org-apache-derby/derbyshared.jar;C:/entwicklungszweige/master/ao/application/designer/target/aditodesigner/aditoonline/modules/ext/de.adito.aditoweb.packages.lwdatabase/org-apache-derby/derbytools.jar;C:/Users/s.seemann/.m2/repository/org/apache/derby/derby/10.15.2.0/derby-10.15.2.0.jar
includeObjects: table:UNTITLED
diffTypes: data`

Now i want to execute following command:

`liquibase generateChangelog`

It occurs following error:

`[2020-12-23 12:43:44] SEVERE [liquibase.integration] Unerwarteter Fehler bei der Ausf³hrung von Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: java.sql.SQLException: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: java.sql.SQLException: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:251)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1519)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:361)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.Scope.child(Scope.java:222)
        at liquibase.Scope.child(Scope.java:226)
        at liquibase.integration.commandline.Main$1.run(Main.java:360)
        at liquibase.integration.commandline.Main$1.run(Main.java:193)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:145)
        at liquibase.integration.commandline.Main.run(Main.java:193)
        at liquibase.integration.commandline.Main.main(Main.java:156)
Caused by: liquibase.command.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: java.sql.SQLException: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:24)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:249)
        ... 14 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: java.sql.SQLException: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:203)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:85)
        at liquibase.command.core.GenerateChangeLogCommand.run(GenerateChangeLogCommand.java:74)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:19)
        ... 15 more
Caused by: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: java.sql.SQLException: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:186)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:127)
        ... 18 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: java.sql.SQLException: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
        at liquibase.diff.output.changelog.core.MissingDataChangeGenerator.fixMissing(MissingDataChangeGenerator.java:121)
        at liquibase.diff.output.changelog.ChangeGeneratorChain.fixMissing(ChangeGeneratorChain.java:48)
        at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixMissing(ChangeGeneratorFactory.java:95)
        at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:302)
        at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:226)
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:133)
        ... 23 more
Caused by: java.sql.SQLException: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
        at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:123)
        at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:325)
        at org.apache.derby.client.am.ClientResultSet.getString(ClientResultSet.java:1112)
        at liquibase.util.JdbcUtils.getResultSetValue(JdbcUtils.java:92)
        at liquibase.diff.output.changelog.core.MissingDataChangeGenerator.fixMissing(MissingDataChangeGenerator.java:92)
        ... 28 more
Caused by: ERROR XCL18: Stream oder LOB-Wert kann nicht mehrmals abgerufen werden
        at org.apache.derby.client.am.ClientResultSet.checkLOBMultiCall(ClientResultSet.java:5532)
        at org.apache.derby.client.am.ClientResultSet.getString(ClientResultSet.java:1091)
        ... 30 more`

## Expected/Desired Behavior
no error

**Comment by molivasdat** [comment]
Hi @ses1112 Thanks for writing up this issue.  We will add this to our list of issues to review.

**Comment by ses1112** [comment]
> 
> 
> Hi @ses1112 Thanks for writing up this issue. We will add this to our list of issues to review.

We have now a solution, it is actually not the best style, but it works for us:

[https://github.com/aditosoftware/liquibase/commit/b422454f82372cf4ebebf9cbe57dcecf18149494](url)

**Comment by FBurguer** [comment]
Still an issue on liquibase `4.15`. Looks like the fix could work, we are investigating further. Thanks for submiting the issue and a possible fix!

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
