### ISSUE TITLE
Relative Path error when using the includeAll tag and Springboot

### ISSUE THREAD

**Issue by mbohls** [liquibase/liquibase#1657]
## Environment
**Liquibase Version**: v4.1.1 and v4.2.2 (it was working in 4.0.0 and 4.1.0)

**Liquibase Integration & Version**: SpringBoot 2.3.1

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**:  MariaDB

**Operating System Type & Version**:  Windows

## Description
Use of the includeAll tag results in "error parsing classpath".  The same configuration works with LB v4.0.0 and v4.1.0.

## Steps To Reproduce
Use these changelogs:

[db.changelog-1.0.0.yaml.txt](https://github.com/liquibase/liquibase/files/5881979/db.changelog-1.0.0.yaml.txt)
[db.changelog-master.yaml.txt](https://github.com/liquibase/liquibase/files/5881980/db.changelog-master.yaml.txt)
[db.changelog-0.0.0.yaml.txt](https://github.com/liquibase/liquibase/files/5881981/db.changelog-0.0.0.yaml.txt)

## Actual Behavior
The "liquibase update" command errors.

`Caused by: liquibase.exception.ChangeLogParseException: Error parsing classpath:/db/changelog/db.changelog-master.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:88) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:337) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:229) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2277) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:215) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:201) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:321) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.2.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	... 24 common frames omitted
Caused by: liquibase.exception.SetupException: Error parsing /db/changelog/db.changelog-0.0.0.yaml
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:373) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:320) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:82) ~[liquibase-core-4.2.2.jar:na]
	... 37 common frames omitted
Caused by: liquibase.exception.ChangeLogParseException: Error parsing /db/changelog/db.changelog-0.0.0.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:88) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:586) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:365) ~[liquibase-core-4.2.2.jar:na]
	... 39 common frames omitted
Caused by: liquibase.exception.SetupException: The file file:/C:/dev/repos/pas-audit-groups/target/classes/db/changelog/changes/v0/0300-createTable-Appointment.xml was not found in
...
Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:547) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:414) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:320) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:82) ~[liquibase-core-4.2.2.jar:na]
`

## Expected/Desired Behavior
The "liquibase update" command should be successful when using includeAll in the changelogs.

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1157) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.3.1,Liquibase 4.3.1

**Comment by molivasdat** [comment]
#1595 may be related or the same issue.

**Comment by nvoxland** [comment]
PR #1664 should fix this.
