### ISSUE TITLE
Checksums change between 2 liquibase versions: moving from 3.6.3 to 3.8.9

### ISSUE THREAD

**Issue by BenjaminLeg** [liquibase/liquibase#1681]
## Environment
**Liquibase Version**: 3.8.9 and up until 3.10.3

**Liquibase Integration & Version**: Spring-Boot 2.3.7-RELEASE

**Database Vendor & Version**: Postgresql 12.3

**Operating System Type & Version**: Base Docker image postgres:12.3 (on Ubuntu 20.04LTS)

## Description
A clear and concise description of the issue being addressed.

Trying to move our services from Spring Boot 2.1.7-RELEASE to 2.3.7-RELEASE we updated the Spring Cloud Starter Parent from Greenwitch SR3 to Horxton SR8, causing liquibase core to move from version 3.6.3 to 3.8.9.

The resulting problems are:

* SERIAL and BIGSERIAL are not defined correctly anymore, but we are already aware of the issue, it forced us to change the id type of the tables that were using SERIAL and BIGSERIAL
* The checksums generated are different from the previously generated checksums for some of them, and that's the biggest issue here. It mostly appears on sequence creation.

## Steps To Reproduce
Tested on versions 3.8.9 / 3.10.3:
Create a db.changelog.yaml file with the following:

```yaml
databaseChangeLog:
  - changeSet:
        id: create_sequence
        author: blegros
        changes:
          - createSequence:
              sequenceName: hibernate_sequence
              dataType: int
              startValue: 1
```

Compile and run it against a postgresql database with liquibase version 3.6.3 
Then compile and run the same against a postgresql database with liquibase version 3.8.9 and above 

## Actual Behavior
The second changelog fails telling the checksum has changed, whereas it did not change.

```bash

 :: Spring Boot ::        (v2.3.7.RELEASE)

2021-02-10 18:13:55.627  INFO 1 --- [           main] .d.c.j.ReporterDbChangelogJobApplication : Starting ReporterDbChangelogJobApplication vLATEST-SNAPSHOT on cfb3df16d233 with PID 1 (/opt/app.jar started by root in /opt)
2021-02-10 18:13:55.629  INFO 1 --- [           main] .d.c.j.ReporterDbChangelogJobApplication : No active profile set, falling back to default profiles: default
2021-02-10 18:13:56.255  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-02-10 18:13:56.326  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-02-10 18:13:56.987  INFO 1 --- [           main] liquibase.executor.jvm.JdbcExecutor      : SELECT COUNT(*) FROM reporter.databasechangeloglock
2021-02-10 18:13:56.989  INFO 1 --- [           main] liquibase.executor.jvm.JdbcExecutor      : SELECT COUNT(*) FROM reporter.databasechangeloglock
2021-02-10 18:13:56.990  INFO 1 --- [           main] liquibase.executor.jvm.JdbcExecutor      : SELECT LOCKED FROM reporter.databasechangeloglock WHERE ID=1
2021-02-10 18:13:57.002  INFO 1 --- [           main] l.lockservice.StandardLockService        : Successfully acquired change log lock
2021-02-10 18:13:57.891  INFO 1 --- [           main] liquibase.executor.jvm.JdbcExecutor      : SELECT MD5SUM FROM reporter.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2021-02-10 18:13:57.892  INFO 1 --- [           main] liquibase.executor.jvm.JdbcExecutor      : SELECT COUNT(*) FROM reporter.databasechangelog
2021-02-10 18:13:57.893  INFO 1 --- [           main] l.c.StandardChangeLogHistoryService      : Reading from reporter.databasechangelog
2021-02-10 18:13:57.893  INFO 1 --- [           main] liquibase.executor.jvm.JdbcExecutor      : SELECT * FROM reporter.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2021-02-10 18:13:57.924  INFO 1 --- [           main] l.lockservice.StandardLockService        : Successfully released change log lock
2021-02-10 18:13:57.925  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:
     2 change sets check sum
          db/changelog/db.changelog-0.0.1-schema.yaml::create_sequence::blegros was: 8:429535ae082ee4f6e2a6ac96c0fda205 but is now: 8:ac82b4375a3a1938211cfb42fb6708de
          db/changelog/db.changelog-4-schema.yaml::create_evse_error_count_by_evse_and_day::CENSORED was: 8:2759dc99875de2ae1e31bef2ce9bb633 but is now: 8:bcbea2524165b30bd3ba0f627172e394

2021-02-10 18:13:57.926  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-02-10 18:13:57.929  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2021-02-10 18:13:57.936  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-02-10 18:13:57.939 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:
     2 change sets check sum
          db/changelog/db.changelog-0.0.1-schema.yaml::create_sequence::blegros was: 8:429535ae082ee4f6e2a6ac96c0fda205 but is now: 8:ac82b4375a3a1938211cfb42fb6708de
          db/changelog/db.changelog-4-schema.yaml::create_evse_error_count_by_evse_and_day::CENSORED was: 8:2759dc99875de2ae1e31bef2ce9bb633 but is now: 8:bcbea2524165b30bd3ba0f627172e394

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at com.CENSORED.reporter.db.changelog.job.ReporterDbChangelogJobApplication.main(ReporterDbChangelogJobApplication.java:10) ~[classes!/:LATEST-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:LATEST-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[app.jar:LATEST-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:LATEST-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:LATEST-SNAPSHOT]
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     2 change sets check sum
          db/changelog/db.changelog-0.0.1-schema.yaml::create_sequence::blegros was: 8:429535ae082ee4f6e2a6ac96c0fda205 but is now: 8:ac82b4375a3a1938211cfb42fb6708de
          db/changelog/db.changelog-4-schema.yaml::create_evse_error_count_by_evse_and_day::CENSORED was: 8:2759dc99875de2ae1e31bef2ce9bb633 but is now: 8:bcbea2524165b30bd3ba0f627172e394

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:288) ~[liquibase-core-3.8.9.jar!/:na]
	at liquibase.Liquibase.update(Liquibase.java:198) ~[liquibase-core-3.8.9.jar!/:na]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.9.jar!/:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366) ~[liquibase-core-3.8.9.jar!/:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314) ~[liquibase-core-3.8.9.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	... 26 common frames omitted

```

To Be Noticed: it works if the script is run with liquibase 3.7.0. But it fails anyway on another checksum with a table creation using a DATE field type (which I guess is guilty here). This last phase is true for liquibase 3.7.0 / 3.8.9 / 3.10.3.
You can see here that there are several changelogs that are run (4 in total), the first one is the one I pasted, the fourth contains the DATE type definition.

## Expected/Desired Behavior
The script should run smoothly, not telling that the checksum changed.

Also I tested to move back to Liquibase 3.6.3 but it is not compatible with Spring-Boot 2.3.7-RELEASE.

**Comment by molivasdat** [comment]
Hi @BenjaminLeg Thanks for writing up this issue. Yes we did change how the checksum is calculated between 3.6.3 and 3.8.9.  There may be several ways to approach this.  
One is to add the previous checksum to the changeset, for example `<validCheckSum>7:19f99d93fcb9909c7749b7bd45678af2</validCheckSum>`
2 is to clear the checksum and generate new ones.
3. others

**Comment by dahamr** [comment]
We recently upgraded to spring-boot 2.3.9 which includes liquibase at 3.8.9. Now we are experiencing the same problem. We have over a hundred services with hundreds of changesets. Option 1 would require tooling to generate a new set of changesets. Option 2 is not even a consideration since this software is already in production and used by customers. I don't have great suggestions for a 3rd option but here goes:

- provide a compatibility mode enabled by env var that performs the old calculation
- the change seems to match the criterial for major rev and maintain previous behavior at 3.x with compatibility for spring-boot 2.3.9

**Comment by dahamr** [comment]
I've dug deeper into our failures and learned that only a few changesets are getting new checksums. I retract my comment. <validCheckSum> is a fine workaround.

**Comment by kataggart** [comment]
solution provided to users; please re-open if persists/doesn't work. Thanks!
