### ISSUE TITLE
Answering prompt auto-registration for liquibase-base with "N" leads to CommandExecutionException

### ISSUE THREAD

**Issue by joliebig** [liquibase/liquibase#1690]
## Environment
**Liquibase Version**: 4.3.0

**Liquibase Integration & Version**: spring boot (2.4.2); spring (5.3.3)

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: Postgres 13

**Operating System Type & Version**: Windows 10

## Description
I'm using liquibase with spring boot without any additional liquibase.properties file. We configure liquibase solely via spring's application properties.

## Steps To Reproduce
During maven integration tests started from the command line, we start a service using liquibase during pre-integration phase. After starting the service application a prompt for auto-registration for liquibase hub appears. Not answering the prompt, we hit a timeout and the integrations tests do not run and the build fails.

## Actual Behavior
 Answering the prompt with `[N]` results in the following Exception:
`
2021-02-12 18:04:20,057 [restartedMain] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1159)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at com.volkswagenag.daem.repositoryservice.Application.main(Application.java:18)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: liquibase.exception.DatabaseException: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.Liquibase$16.run(Liquibase.java:1770)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.Liquibase.runInScope(Liquibase.java:2343)
        at liquibase.Liquibase.dropAll(Liquibase.java:1757)
        at liquibase.Liquibase.dropAll(Liquibase.java:1741)
        at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:338)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:273)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
        ... 24 common frames omitted
Caused by: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:24)
        at liquibase.Liquibase$16.run(Liquibase.java:1768)
        ... 35 common frames omitted
Caused by: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.core.DropAllCommand.run(DropAllCommand.java:134)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:19)
        ... 36 common frames omitted
Caused by: java.lang.NullPointerException: null
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:253)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
        at liquibase.hub.HubUpdater.writeToPropertiesFile(HubUpdater.java:456)
        at liquibase.hub.HubUpdater.register(HubUpdater.java:361)
        at liquibase.command.core.DropAllCommand.run(DropAllCommand.java:119)
        ... 37 common frames omitted
`

## Expected/Desired Behavior
No exception.

## Screenshots (if appropriate)
* 

## Additional Context
-

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1221) by [Unito](https://www.unito.io/learn-more)

**Comment by mariochampion** [comment]
hey @joliebig  -- sorry for the issue! we are actually in final testing for a 4.3.1 release aimed for today, and then the fix for this is in 4.3.2 which we estimate for about 10 days after that. thanks for your patience!

**Comment by molivasdat** [comment]
Hi @joliebig This is a duplicate of #1689 We are going to fix it under that issue number.  We plan to fix it in 4.3.2

**Comment by joliebig** [comment]
Version [v.4.3.2](https://github.com/liquibase/liquibase/releases/tag/v4.3.2) fixes my problem. Thanks.
