### ISSUE TITLE
setColumnRemarks fails due to missing columnDataType

### ISSUE THREAD

**Issue by tonny1983** [liquibase/liquibase#1726]
## Environment

**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: spring boot 2.4.2

**Database Vendor & Version**: MySQL 5.7.27

**Operating System Type & Version**: macOS 11.2.2

## Description

The [document](https://docs.liquibase.com/change-types/community/set-column-remarks.html?Highlight=setColumnRemarks) lists 5 available attributes for `setColumnRemarks` without a attribute called `columnDataType`. However, when running the application, it causes en exception as:

```
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          columnDataType is required for setColumnRemarks on mysql, liquibase/schema/data_table.yaml::1::tc

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:299) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:236) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Liquibase$$Lambda$1197/0000000035346C20.run(Unknown Source) ~[?:?]
	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Scope$$Lambda$1198/000000003377E280.run(Unknown Source) ~[?:?]
	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Liquibase.runInScope(Liquibase.java:2322) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:216) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:322) ~[liquibase-core-4.3.1.jar:?]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:275) ~[liquibase-core-4.3.1.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-5.3.3.jar:5.3.3]
	... 124 more
```

## Steps To Reproduce

There is the change-log file in YAML as follows:

```YAML
databaseChangeLog:
  - changeSet:
      id: 1
      author: tc
      dbms: mysql
      changes:
        - createTable:
            tableName: DATA_TABLE
            columns:
              - column:
                  name: _ID
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: DATA_FIELD
                  type: varchar(255)
        - setColumnRemarks:
            tableName: DATA_TABLE
            columnName: _ID
            remarks: primary key
```

## Additional Context
If appending the `columnDataType` attribute according to the exception stated, the application runs as expected. And the `columnDataType` seems be indeed necessary for the `ALTER TABLE` statement in mysql (although its value is just as the as the `type` field in `column`), so the document might be revised.

**Comment by molivasdat** [comment]
Hi @tonny1983 Thanks for writing up this issue with clear recreation steps.  I was able to easily recreate this with 5.7.33 and Liquibase 4.3.1.  It appears that the code to fix column comments may have changed this.  In 4.2.2 it is able to run but creates a remark/comment on the table instead of the column.  In 4.3.1 it appears you need an extra type info for the alter table statement to be executed.

**Comment by FBurguer** [comment]
This is still an issue on liquibase `4.15`. You can workaround it if you specify `columnDataType` on `setColumnRemarks`

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
