### ISSUE TITLE
Liquibase pollutes System.out in a Spring Boot application

### ISSUE THREAD

**Issue by monrealis** [liquibase/liquibase#1741]
Liquibase writes directly to System.out instead of writing through a configured logger in a Spring Boot Application. This is unexpected to the consumer of System.out, which expects, for example, JSON in System.out.

Liquibase version: 4.3.1
Spring boot version: 2.4.3
Message: Skipping auto-registration

Stack trace:

```
	at liquibase.ui.ConsoleUIService.sendMessage(ConsoleUIService.java:45)
	at liquibase.hub.HubUpdater.register(HubUpdater.java:372)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:242)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2322)
	at liquibase.Liquibase.update(Liquibase.java:216)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:322)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1153)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:907)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
```

![image](https://user-images.githubusercontent.com/2280367/109807520-af84fc00-7c2e-11eb-833d-3b59091bc094.png)

The only property related to liquibase in Spring Boot configuration:

```yaml
spring:
  liquibase:
    change-log: classpath:db-changelog.xml
```

**Comment by Gama11** [comment]
We have 400 lines of "Skipping auto-registration" in our CI logs while running database tests... :/

**Comment by filiphr** [comment]
This is happening because the default `UIService` is the `ConsoleUIService`. What I don't understand is why is there even a `UIService` configured by default. I understand that you need one and it does make sense to use one when using via `java -jar`. However, when using Liquibase as a library it doesn't make sense to use that.

**Comment by tomacla** [comment]
After reading source code, I've managed to remove this message by calling this line before liquibase initialization. I don't see any side effect for now.

`Scope.enter(Map.of(Scope.Attr.ui.name(), new LoggerUIService()));`

**Comment by andygoossens** [comment]
On a somehow related note, that message is logged at "warning" level as well. I would prefer seeing that message at "info" level instead so that the startup of my Spring Boot app remains warning-free. All other things that get logged at warning level in HubUpdater seem to be some kind of problem (e.g. sync failed, unable to lock, unable to write to a file, account creation failure, ...), however skipping the auto-registration is simply a user decision or the default behaviour (when using LoggerUIService).

According to Spring Boot developers, Liquibase seems to be lacking an API for disabling the Liquibase Hub (as mentioned in https://github.com/spring-projects/spring-boot/issues/26867) which would have been a way to avoid seeing the `Skipping auto-registration` message.

But you should be able to avoid this message (whether that came through System.out or logging) by disabling the Liquibase Hub by mentioning `liquibase.hub.mode=off` in `liquibase.properties`. (see [Liquibase docs](https://docs.liquibase.com/workflows/liquibase-community/creating-config-properties.html))

**Comment by marcusportmann** [comment]
> After reading source code, I've managed to remove this message by calling this line before liquibase initialization. I don't see any side effect for now.
> 
> `Scope.enter(Map.of(Scope.Attr.ui.name(), new LoggerUIService()));`
> 
> I didn't find any other way to override the UI service and documentation is not helping on that point

I encountered the same issue when embedding Liquibase in my application to manage my database.

What worked for me was turning off Hub support before executing the updates.

```
          // Initialize the in-memory database using Liquibase changeSets.
          LiquibaseConfiguration.getInstance().getConfiguration(HubConfiguration.class).setLiquibaseHubMode("OFF");

          try (Connection connection = dataSource.getConnection()) {
            liquibase.database.Database database = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(connection));

            for (String changeLogFile : LIQUIBASE_CHANGE_LOG_FILES) {
              Liquibase liquibase =
                  new Liquibase(
                      changeLogFile, new ClassLoaderResourceAccessor(), database);
              liquibase.update(new Contexts(), new LabelExpression());
              liquibase.update(new Contexts("test"), new LabelExpression());
            }
          }
```

The important line is:

 LiquibaseConfiguration.getInstance().getConfiguration(HubConfiguration.class).setLiquibaseHubMode("OFF");

**Comment by piotrp** [comment]
I'm not sure about original reporter's issue, but with regular Spring Boot application there's still a single "Skipping auto-registration" line printed to console during startup. Tested on Spring Boot 2.5.5, which uses Liquibase 4.3.5.

**Comment by runeflobakk** [comment]
Upgrading Liquibase from 4.4.3 to 4.7.1, I also experience lots of lines like `Running Changeset: ...` which seems to be output directly to System.out, and I have to use the workaround by @tomacla to set the LoggerUIService. Was this the default before? What makes Liquibase "think" it should communicate directly to the console instead of using a logger, as it did before? Does it think it is being used as a CLI application, even though it is being used as a library? This is in the context of a DropWizard app, but I see that apparently the same issue exists with Spring Boot.

Are there any abstractions instead of invoking `Scope.enter(..)` that should be used to put Liquibase in a "library mode" instead of "CLI mode"?

**Comment by filiphr** [comment]
This fix partially solves the issues in this issue. It only solves it when using the `SpringLiquibase`. However, there is still a problem when Liquibase is being used as a library.

See:
* https://github.com/liquibase/liquibase/issues/1741#issuecomment-848210687
* https://github.com/liquibase/liquibase/issues/1741#issuecomment-892501130
* https://github.com/liquibase/liquibase/issues/1741#issuecomment-1037569651

I think that the default `UiService` in `Scope` (https://github.com/liquibase/liquibase/blob/5aabc25f4fbeef918d16e046945073b4bb4377d4/liquibase-standard/src/main/java/liquibase/Scope.java#L95) should be replaced with the `LoggerUiService` instead of the `ConsoleUiService`. Then in the liquibase standalone mode you can configure the `ConsoleUiService` as a default, but keep the `LoggerUiService` in the embedded mode

**Comment by filipelautert** [comment]
Makes sense @filiphr  !

**Comment by chadlwilson** [comment]
For what it's worth this seems related to #3651 which is complaining about the same thing, in a non-Spring context.
