### ISSUE TITLE
liquibase.ignoreRecycleBinWarning cannot be set in liquibase.properties

### ISSUE THREAD

**Issue by zholub** [liquibase/liquibase#1750]
## Environment
**Liquibase Version**: 4.2.2
**Liquibase Integration & Version**:  CLI
**Database Vendor & Version**: Oracle 12.2
**Operating System Type & Version**: Windows 10

## Description
Documentation at https://docs.liquibase.com/workflows/liquibase-community/creating-config-properties.html says about **Additional Liquibase properties**:
_You can include the following properties in the liquibase.properties file as of Liquibase 4.1. [...] liquibase.ignoreRecycleBinWarning_
When I set this property in my liquibase.properties, Liquibase exists with an error.
Anyway, there is a typo in the documentation itself: liquibase.ignoreRecycleBinWarning=<false|**fasle**>

## Steps To Reproduce
Set **liquibase.ignoreRecycleBinWarning** in liquibase.properties and run liquibase with --defaultsFile:
`liquibase --defaultsFile dev.properties --changeLogFile db/changelog/db.changelog-master.xml updateSQL`

## Actual Behavior
```
liquibase.exception.CommandLineParsingException: Unknown parameter: 'liquibase.ignoreRecycleBinWarning'
        at liquibase.integration.commandline.Main.parsePropertiesFile(Main.java:1030)
        at liquibase.integration.commandline.Main.parseDefaultPropertyFileFromFile(Main.java:747)
        at liquibase.integration.commandline.Main.parseDefaultPropertyFiles(Main.java:709)
        at liquibase.integration.commandline.Main.parseOptions(Main.java:1161)
        at liquibase.integration.commandline.Main$1.run(Main.java:259)
        at liquibase.integration.commandline.Main$1.run(Main.java:193)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:145)
        at liquibase.integration.commandline.Main.run(Main.java:193)
        at liquibase.integration.commandline.Main.main(Main.java:156)
```

## Expected/Desired Behavior
Liquibase accepts the property as other properties listed in documentation.

**Comment by molivasdat** [comment]
Hi @zholub Thanks for writing up this issue.  We will add it to the list of issues we are processing and update the misspelled documentation.

**Comment by molivasdat** [comment]
I have also created and issue on our docs page.
You can also submit PRs to fix the documentation.
Here is the one that I fixed
https://github.com/Datical/liquibase-docs/pull/107
and to submit additional fixes for the documentation.
https://github.com/Datical/liquibase-docs/pulls

**Comment by FBurguer** [comment]
Looks like it works for liquibase `4.15`. Try upgrading to our latest version and see if it works for you. If not, please let us know and we will have a second look on it. Thanks!
