### ISSUE TITLE
Liquibabse commands are failing for other databases when mongodb jars are also present on classpath

### ISSUE THREAD

**Issue by AshwaniPratap8** [liquibase/liquibase#1782]
Hi,

The liquibase commands for oracle database are failing when mongo-driver and liquibase-mongo extension jars are present on the LIQUIBASE_HOME/lib folder. They run fine if I remove mongo related jars. We managed to run this command when the MongoDB driver is not in the lib folder.

It looks like liquibase is picking the wrong driver. The scenario is like the following:
Place the oracle and the MongoDB driver inside the lib folder and try to execute against Oracle.

Below are various details;

I am using Liquibase 4.3.1 version.

Below jars were present on my LIQUIBASE_HOME/lib folder while running it for Oracle database.
liquibase-mongodb-4.3.1.jar
mongo-java-driver-3.9.1.jar
ojdbc8-12.2.0.1.0.jar

I ran the following command. I ran it without classpath and driver as well and got the same error.
liquibase --driver=oracle.jdbc.driver.OracleDriver --classpath=C:\apps\liquibase-4.3.1\lib\ojdbc8-12.2.0.1.0.jar --url=jdbc:oracle:thin:@blrdev000330.bpc.broadcom.net:1521:EE --username=system --password=oracle --logLevel=debug history

Please find below debug logs.

[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.license.LicenseService instance liquibase.pro.license.keymgr.DaticalTrueLicenseService
[2021-04-01 12:33:02] INFO [liquibase.integration] No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro features.
Liquibase Community 4.3.1 by Datical
####################################################

_ _ _ _
| | () () |
| | _ __ _ _ _ | |_ __ _ ___ ___
| | | |/ _ | | | | | '_ \ / _ / __|/ _ \
| || | (| | || | | |) | (| _ \ __/
_/|_, |_,||./ _,|/__|
| |
|_|
Get documentation at docs.liquibase.com
Get certified courses at learn.liquibase.com
Free schema change activity reports at
https://hub.liquibase.com
####################################################
Starting Liquibase at 12:33:02 (version 4.3.1 #26 built at 2021-02-12 17:41+0000)
[2021-04-01 12:33:02] FINE [liquibase.integration] Liquibase Hub URL: https://hub.liquibase.com
[2021-04-01 12:33:02] FINE [liquibase.integration] Liquibase Hub Mode: all
[2021-04-01 12:33:02] FINE [liquibase.resource] Adding path C:\Users\ashwanipratap. to resourceAccessor liquibase.resource.FileSystemResourceAccessor
[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.CockroachDatabase
[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DB2Database
[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Db2zDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DerbyDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Firebird3Database
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.FirebirdDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.H2Database
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.HsqlDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.InformixDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Ingres9Database
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MSSQLDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MariaDBDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MockDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MySQLDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.OracleDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.PostgresDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SQLiteDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseASADatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.UnsupportedDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.ext.mongodb.database.MongoLiquibaseDatabase
[2021-04-01 12:33:03] FINE [liquibase.database] Properties:
[2021-04-01 12:33:03] FINE [liquibase.database] Key:‘user’ Value:‘system’
[2021-04-01 12:33:03] FINE [liquibase.database] Key:‘password’ Value:’**********’
[2021-04-01 12:33:03] FINE [liquibase.database] Connecting to the URL:‘jdbc:oracle:thin:@blrdev000330.bpc.broadcom.net:1521:EE’ using driver:‘oracle.jdbc.driver.OracleDriver’
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
For more information, please use the --logLevel flag
[2021-04-01 12:33:03] SEVERE [liquibase.integration] Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:131)
at liquibase.integration.commandline.Main.doMigration(Main.java:1412)
at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:364)
at liquibase.Scope.lambda$child$0(Scope.java:160)
at liquibase.Scope.child(Scope.java:169)
at liquibase.Scope.child(Scope.java:159)
at liquibase.Scope.child(Scope.java:138)
at liquibase.integration.commandline.Main$1.run(Main.java:363)
at liquibase.integration.commandline.Main$1.run(Main.java:193)
at liquibase.Scope.child(Scope.java:169)
at liquibase.Scope.child(Scope.java:145)
at liquibase.integration.commandline.Main.run(Main.java:193)
at liquibase.integration.commandline.Main.main(Main.java:156)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:217)
at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:176)
at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:141)
at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:96)
… 12 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:36)
at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:214)
… 15 more
Caused by: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:104)
at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:33)
… 16 more
Caused by: java.lang.IllegalArgumentException: The connection string contains invalid user information. If the username or password contains a colon (:slight_smile: or an at-sign (@) then it must be urlencoded
at com.mongodb.ConnectionString.(ConnectionString.java:309)
at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:96)
… 17 more

Please look into this and suggest the resolution.

Thanks!
Ashwani

**Comment by molivasdat** [comment]
Hi @AshwaniPratap8 Thanks for bringing this issue to our attention.  Today Liquibase does it's very best to figure out details of the configuration with as few details as possible.  For instance, the database connection driver without the user providing an explicit driver for the database.  As we have added databases, that has become more complicated in terms of figuring out what to use when, if there is not explicit information provided and to support backward compatibility.
We will look into this and I will get with the team to see what can be done in this situation.  One workaround that MAY work would be to move the driver jars into their own directories outside of lib and then refer to the at runtime using liquibase.properties or commandline parameters as you connect to the various databases, mongo or oracle.  I say may because I have not tried it but I use liquibase to connect to different databases and put them in the classpath at runtime.  This has pros and cons when using a shared environment for builds and deployments.

**Comment by ofyaniv** [comment]
> Hi @AshwaniPratap8 Thanks for bringing this issue to our attention. Today Liquibase does it's very best to figure out details of the configuration with as few details as possible. For instance, the database connection driver without the user providing an explicit driver for the database. As we have added databases, that has become more complicated in terms of figuring out what to use when, if there is not explicit information provided and to support backward compatibility.
> We will look into this and I will get with the team to see what can be done in this situation. One workaround that MAY work would be to move the driver jars into their own directories outside of lib and then refer to the at runtime using liquibase.properties or commandline parameters as you connect to the various databases, mongo or oracle. I say may because I have not tried it but I use liquibase to connect to different databases and put them in the classpath at runtime. This has pros and cons when using a shared environment for builds and deployments. By the way, lib is always in the classpath and adding --classpath appends to liquibase classpath and does not replace the classpath. This is why you would still see the error if you did not move the jars out of lib.

Hi @molivasdat 
Thank you for your prompt response.

The above Liquibase CLI is explicitly specifying the Oracle driver ( --driver ) and explicitly specifying the Oracle ojdbc jar ( --classpath ):
--------------------------------------------
--driver=oracle.jdbc.driver.OracleDriver --classpath=C:\apps\liquibase-4.3.1\lib\ojdbc8-12.2.0.1.0.jar
--------------------------------------------

So in this case, the user has explicitly provided which driver and which classpath should be used. In this case, Liquibase doesn't need to guess/figure out which configuration should be used - as it is explicitly specified by the command line arguments.

Should we use a different folder ( other than lib ) for storing all the required drivers?
We would like to have a single folder location for storing all required drivers - so users can easily extend the Liquibase integration without any need to update the integration source code.

Having a single location for all drivers is working fine with all other drivers except for MongoDB driver.
Once the MongoDB driver is present at the lib folder - Liquibase is picking it although the specified driver and classpath are specifying Oracle.

This is a blocker issue.

Kind regards
 Ofer
