### ISSUE TITLE
liquibase.lockservice.StandardLockService does not detect that parallel running thread/application has created DATABASECHANGELOGLOCK table

### ISSUE THREAD

**Issue by stalbrecht** [liquibase/liquibase#1816]
## Environment
**Liquibase Version**: 4.3.3

**Liquibase Integration & Version**: CDI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Microsoft SQLServer 2017 with jdbc driver com.microsoft.sqlserver:mssql-jdbc:jar:8.4.1.jre8

**Operating System Type & Version**:
Linux with kernel version 5.11

## Description
When there are several threads, all executing database migration, then eventually the StandardLockService gets an error while trying to create the DATABASECHANGELOGLOCK table in one of the threads. This is expected behavior, but, it does not detect the reason for the error, that is, it does not detect that the error is caused by somebody other already has created that table, and thus the migration step fails for this thread.
Reason:

* The StandardLockService checks whether the exception message contains the string "exists"
* the caught exception's message does not contain "exists", it is 'There is already an object named 'DATABASECHANGELOGLOCK' in the database. [Failed SQL: (2714) CREATE TABLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED bit NOT NULL, LOCKGRANTED datetime2(3), LOCKEDBY nvarchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]'

## Steps To Reproduce
List the steps to reproduce the behavior.

* Use a 'fresh' schema, i.e. a database schema without the liquibase lock tables
* Execute liquibase migration from several threads or processes in parallel, each using that 'fresh' schema to hold the liquibase tables
* Since error is influenced by timing of execution, it might not occur for each attempt to reproduce it.
* Since the StandardLockService is part of liquibase core, it should play no role whether the migration is executed via ant/cli/cdi

## Actual Behavior
The thread or process getting that error terminates the migration with an error.

## Expected/Desired Behavior
The thread or process getting that error detects that the error is caused by liquibase tables being created by another thread/process,tries to get the lock, and continues migration.
The desired behavior already is kind of implemented, the only errorneous part is the failing detection for the reason of the error.

## Additional Context
**Excerpt from Stacktrace:**
Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.LockException: liquibase.exception.DatabaseException: There is already an object named 'DATABASECHANGELOGLOCK' in the database. [Failed SQL: (2714) CREATE TA
BLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED bit NOT NULL, LOCKGRANTED datetime2(3), LOCKEDBY nvarchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]
	at liquibase.integration.cdi.CDILiquibase.onStartup(CDILiquibase.java:127)
	... 96 more
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: There is already an object named 'DATABASECHANGELOGLOCK' in the database. [Failed SQL: (2714) CREATE TABLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED
 bit NOT NULL, LOCKGRANTED datetime2(3), LOCKEDBY nvarchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:294)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:212)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:220)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2369)
	at liquibase.Liquibase.update(Liquibase.java:217)
	at liquibase.Liquibase.update(Liquibase.java:203)
	at liquibase.integration.cdi.CDILiquibase.performUpdate(CDILiquibase.java:137)
	at liquibase.integration.cdi.CDILiquibase.onStartup(CDILiquibase.java:125)
	... 96 more
Caused by: liquibase.exception.DatabaseException: There is already an object named 'DATABASECHANGELOGLOCK' in the database. [Failed SQL: (2714) CREATE TABLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED bit NOT NULL, LOCKGRANTED datetime
2(3), LOCKEDBY nvarchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:134)
	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:101)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:251)
	... 107 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: There is already an object named 'DATABASECHANGELOGLOCK' in the database.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
	... 112 more

**StandardLockService implementation starting at line 111**:
           } catch (DatabaseException e) {
                if ((e.getMessage() != null) && e.getMessage().contains("exists")) {
                    //hit a race condition where the table got created by another node.
                    Scope.getCurrentScope().getLog(getClass()).fine("Database lock table already appears to exist " +
                            "due to exception: " + e.getMessage() + ". Continuing on");
                }  else {
                    throw e;
                }
            }

**Comment by stalbrecht** [comment]
Hi @molivasdat, same database and same schema for creating the liquibase tables.
