### ISSUE TITLE
NullPointerException inside SecureLogFilter.isLoggable

### ISSUE THREAD

**Issue by timestudybuddy** [liquibase/liquibase#1858]
I am running from OSX homebrew and connecting to a Mysql database.  A temporary workaround is to run without --loglevel=info

Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "filteredMessage" is null
	at liquibase.integration.commandline.Main$SecureLogFilter.isLoggable(Main.java:2159)
	at java.logging/java.util.logging.Handler.isLoggable(Handler.java:346)
	at java.logging/java.util.logging.StreamHandler.isLoggable(StreamHandler.java:237)
	at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:194)
	at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.logp(Logger.java:1283)
	at liquibase.logging.core.JavaLogger.log(JavaLogger.java:23)
	at liquibase.logging.core.CompositeLogger.log(CompositeLogger.java:29)
	at liquibase.logging.core.CompositeLogger.log(CompositeLogger.java:29)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:50)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:45)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:638)

**Comment by molivasdat** [comment]
Hi @timestudybuddy Can you provide a little context and update the description with the template I added?

**Comment by cimmone** [comment]
I can replicate this behavior with an implementation of CustomSqlMigration that does not override the default message method 'getConfirmationMessage'. If you specify a logging level that calls that method, it doesn't handle the default value of null returned from CustomSqlMigration.getConfirmationMessage().

**Comment by nikosmoum** [comment]
I have also hit this issue, in the same way that @cimmone has mentioned. Setting the --log-level (to any value), and having a custom task that returns `null` from the `getConfirmationMessage` method.

**Comment by nikosmoum** [comment]
Additionally, this doesn't happen only with `integration.commandline.Main$SecureLogFilter.isLoggable`, but also with `integration.commandline.LiquibaseCommandLine$SecureLogFilter.isLoggable`
