### ISSUE TITLE
Noninteger Database Minor Version Numbers Not Allowed

### ISSUE THREAD

**Issue by r2liquibase** [liquibase/liquibase#1884]
## Environment

**Liquibase Version**:

4.3.5

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

CLI via Liquibase Test Harness

**Liquibase Extension(s) & Version**: 

Cassandra Extension 4.3.4

**Database Vendor & Version**:

Cassandra 4.0-rc1

**Operating System Type & Version**:

Docker on Centos

## Description

Liquibase running against Cassandra 4.0-rc1 throws error:

```
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: [JDBC Driver]For input string: "0-rc1"
	at liquibase.database.AbstractJdbcDatabase.getDatabaseMinorVersion(AbstractJdbcDatabase.java:251)
	at liquibase.harness.change.ChangeObjectTests.apply #testInput.changeObject against #testInput.databaseName #testInput.version; verify generated SQL and DB snapshot(ChangeObjectTests.groovy:33)
Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: [JDBC Driver]For input string: "0-rc1"
	at liquibase.database.jvm.JdbcConnection.getDatabaseMinorVersion(JdbcConnection.java:93)
	at liquibase.database.AbstractJdbcDatabase.getDatabaseMinorVersion(AbstractJdbcDatabase.java:249)
	... 1 more
Caused by: java.sql.SQLException: [JDBC Driver]For input string: "0-rc1"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at liquibase.database.jvm.JdbcConnection.getDatabaseMinorVersion(JdbcConnection.java:91)
	... 2 more
Caused by: java.lang.NumberFormatException: For input string: "0-rc1"
	... 6 more
```

## Steps To Reproduce

Use Cassandra 4.0-rc1. Run Liquibase.

## Additional Context

I overrode getDatabaseMinorVersion in CassandraDatabase to always throw `0`. But this is going to be a problem for any database that has a noninteger minor version.

**Comment by molivasdat** [comment]
I think we might need to update the method that is being called in the extension.
jdbc spec for minor version is an int.
https://docs.datastax.com/en/drivers/java-dse/1.9/com/datastax/driver/core/VersionNumber.html

**Comment by molivasdat** [comment]
@r2liquibase This is a problem with the Cassandra driver being used.  The JDBC spec has getDatabaseMinorVersion() returning an int from the java.sql.DatabaseMetaData class definition.  The driver looks to be trying to create an int from 0-rc1 which cause a SQLException to occur and they are passing that SQL Exception up the stack.
If Cassandra is allowing x.y-releasecandidate type names the driver needs to be able to strip out the -releaasecandidate portion of the name to be able to return an int per specification. (https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getDriverMinorVersion())
The fix needs to go into the driver for release candidate type of database builds.
