### ISSUE TITLE
Failed to insert a row into DATABASECHANGELOG in MySQL Group Replication

### ISSUE THREAD

**Issue by iamKyun** [liquibase/liquibase#1918]
## Environment
**Liquibase Version**: 4.3.5

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MySQL 8.0.25 (MySQL Group Replication)

**Operating System Type & Version**: CentOS 7

## Description
Application failed to start up with an error: The table does not comply with the requirements by an external plugin.

## Steps To Reproduce
1. Create a spring boot project from start.spring.io and add liqubibase to denpencies.
1. Using `MySQL Group Replication` as datasource 
1. Copy changelog files to resources folder and start up the application.
1. Failed to start up with an error: The table does not comply with the requirements by an external plugin.

The error "The table does not comply with the requirements by an external plugin." means table needs a primary key, but not found in the table `DATABASECHANGELOG `.

MySQL Group Replication requires tables must have an explicit primary key defined. 

## Additional Context
logs:

    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.DatabaseException: The table does not comply with the requirements by an external plugin. [Failed SQL: (3098) INSERT INTO `playground-course`.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1624203425452-1', 'Kyun (generated)', 'db/changelog/master.xml', NOW(), 1, '8:3c2977cfb3a71734e2ee2ad8f05f5011', 'createTable tableName=course', '', 'EXECUTED', NULL, NULL, '4.3.5', '4242629052')]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.7.jar:5.3.7]
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.7.jar:5.3.7]
    	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.0.jar:2.5.0]
    	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.5.0.jar:2.5.0]
    	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.5.0.jar:2.5.0]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) [spring-boot-2.5.0.jar:2.5.0]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) [spring-boot-2.5.0.jar:2.5.0]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) [spring-boot-2.5.0.jar:2.5.0]
    	at com.iamkyun.playground.course.CourseApplication.main(CourseApplication.java:11) [classes/:na]
    Caused by: liquibase.exception.LiquibaseException: liquibase.exception.DatabaseException: The table does not comply with the requirements by an external plugin. [Failed SQL: (3098) INSERT INTO `playground-course`.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1624203425452-1', 'Kyun (generated)', 'db/changelog/master.xml', NOW(), 1, '8:3c2977cfb3a71734e2ee2ad8f05f5011', 'createTable tableName=course', '', 'EXECUTED', NULL, NULL, '4.3.5', '4242629052')]
    	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Liquibase.lambda$null$0(Liquibase.java:272) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:222) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Liquibase.lambda$update$1(Liquibase.java:271) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Liquibase.runInScope(Liquibase.java:2369) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Liquibase.update(Liquibase.java:217) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Liquibase.update(Liquibase.java:203) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:321) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:275) ~[liquibase-core-4.3.5.jar:na]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.7.jar:5.3.7]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.7.jar:5.3.7]
    	... 16 common frames omitted
    Caused by: liquibase.exception.DatabaseException: The table does not comply with the requirements by an external plugin. [Failed SQL: (3098) INSERT INTO `playground-course`.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1624203425452-1', 'Kyun (generated)', 'db/changelog/master.xml', NOW(), 1, '8:3c2977cfb3a71734e2ee2ad8f05f5011', 'createTable tableName=course', '', 'EXECUTED', NULL, NULL, '4.3.5', '4242629052')]
    	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:134) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.changelog.StandardChangeLogHistoryService.setExecType(StandardChangeLogHistoryService.java:390) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.database.AbstractJdbcDatabase.markChangeSetExecStatus(AbstractJdbcDatabase.java:1135) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:60) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:222) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:222) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.Scope.child(Scope.java:226) ~[liquibase-core-4.3.5.jar:na]
    	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66) ~[liquibase-core-4.3.5.jar:na]
    	... 34 common frames omitted
    Caused by: java.sql.SQLException: The table does not comply with the requirements by an external plugin.
    	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
    	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.25.jar:8.0.25]
    	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:762) ~[mysql-connector-java-8.0.25.jar:8.0.25]
    	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:646) ~[mysql-connector-java-8.0.25.jar:8.0.25]
    	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
    	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
    	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389) ~[liquibase-core-4.3.5.jar:na]
    	... 59 common frames omitted
    
    Process finished with exit code 1

**Comment by molivasdat** [comment]
Hi @iamKyun Thanks for creating this issue.  We will add it to the list of issues that we are processing.  Not sure that this is a primary key issue.  The create table for mysql for the DATABASECHANGELOG table is as follows which has a primary key.
```
CREATE TABLE playground_course.DATABASECHANGELOGLOCK (
ID INT NOT NULL, 
`LOCKED` BIT(1) NOT NULL, 
LOCKGRANTED datetime NULL, 
LOCKEDBY VARCHAR(255) NULL, 
CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));
```

**Comment by JerryFlood** [comment]
Hi Mike 

As of 4.4.2 the DATABASECHANGELOG does not have a primary key. This is the table causing the above failure. 

You provided the create for DATABASECHANGELOGLOCK, which does have a primary key. in 4.4.2 as you indicated.

Later
Jerry

**Comment by silentbalanceyh** [comment]
Any update on this issue, I met this issue again and could not process liquibase auto now, when we upgraded to mysql 8.x, the application has been broken.

**Comment by kataggart** [comment]
@silentbalanceyh can you please explain what you mean by liquibase auto? Thanks

**Comment by kataggart** [comment]
Closing for now; @silentbalanceyh if you can provide more detail to my question, please feel free and we can reopen. Thanks!

**Comment by ia-jladew** [comment]
This issue is actually a simple one. I get the same issue when running Liquibase from the command line:
`Unexpected error running Liquibase: The table does not comply with the requirements by an external plugin. [Failed SQL: (3098) INSERT INTO schema.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'liquibase', 'changelog-mysql.sql', NOW(), 1, '8:46ea95d6727b34e6c559a1c5ddc8ee33', 'sql', '', 'EXECUTED', NULL, NULL, '4.15.0', '1893877308')]`

The Issue is GROUP REPLICATION on MySQL 5.7 and 8.0 requires any table to contain a PK. That said as a test I altered the ID to have a PK and the command now works.

Liquibase documentation explicitly states the ID column is not created with a PK because it could cause problems being this is the changeset ID.
How does Liquibase recommend to handle? I was thinking adding a new ID column with an auto increment ID.
Regards,
Jason

**Comment by kataggart** [comment]
thanks @ia-jladew -- to summarize, you are facing the issue that a.) MySQL requires a PK and b.) we don't add a PK in DATABASECHANGELOG, is that correct?

**Comment by ia-jladew** [comment]
Correct. Very simple problem and I am sure that is the issue of the original post.
Group Replication Requirements - https://dev.mysql.com/doc/refman/5.7/en/group-replication-requirements.html
I handled it simply by adding a new auto incrementing PK column.

**Comment by molivasdat** [comment]
@ia-jladew Thanks for the workaround.  It appears that if you use MYSQL in standalone mode, it does not require a PK on tables but once you add the database to a cluster(group replication), MYSQL requires that tables in databases have a PK.

**Comment by mohammed6688** [comment]
I faced the same issue and the workaround that @ia-jladew mentioned worked fine, but I am using keycloak user management system that uses liquibase to manage db changesets so it's not easy to add a new column to DATABASECHANGE table in it, so it will be so better if there was an environment variable by setting it the DATABASECHANGE table created with a PK and its default option is to work with no PK.
