### ISSUE TITLE
dropPrimaryKey fails on PostgreSQL

### ISSUE THREAD

**Issue by gjvoosten** [liquibase/liquibase#1933]
## Environment

**Liquibase Version**: 4.4.0

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: PostgreSQL 13

**Operating System Type & Version**: Docker

## Description

Given the following databaseChangeLog for a table `"camelCase"`:
```
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

  <changeSet id="add-camelCase-table" author="gjvoosten" dbms="postgresql">
    <createTable tableName="camelCase">
      <column name="id" type="int" autoIncrement="true" >
        <constraints primaryKey="true" nullable="false" />
      </column>
    </createTable>
  </changeSet>

  <changeSet id="drop-primaryKey-constraint" author="gjvoosten" dbms="postgresql">
    <dropPrimaryKey tableName="camelCase" />
  </changeSet>

</databaseChangeLog>
```
Liquibase 4.3.5 creates a primary key constraint `"camelcase_pkey"` (i.e. all lowercase), and dropping it works.
With Liquibase 4.4.0, the primary key constraint it **creates** is `"camelCase_pkey"` (i.e. camelCase), but the constraint it tries to **drop** is `"camelcase_pkey"` which fails with the error:
```
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations.xml::drop-primaryKey-constraint::gjvoosten:
     Reason: liquibase.exception.DatabaseException: ERROR: constraint "camelcase_pkey" of relation "camelCase" does not exist
  Where: SQL statement "alter table public."camelCase" drop constraint camelCase_pkey"
PL/pgSQL function inline_code_block line 7 at EXECUTE [Failed SQL: (0) DO $$ DECLARE constraint_name varchar;
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'camelCase' AND TABLE_SCHEMA = 'public';
    EXECUTE 'alter table public."camelCase" drop constraint ' || constraint_name;
END $$;]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
        at liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
        at liquibase.Scope.lambda$child$0(Scope.java:166)
        at liquibase.Scope.child(Scope.java:175)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:144)
        at liquibase.Scope.child(Scope.java:228)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
        at liquibase.Scope.lambda$child$0(Scope.java:166)
        at liquibase.Scope.child(Scope.java:175)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:144)
        at liquibase.Liquibase.runInScope(Liquibase.java:2363)
        at liquibase.Liquibase.update(Liquibase.java:211)
        at liquibase.Liquibase.update(Liquibase.java:197)
        at liquibase.Liquibase.update(Liquibase.java:193)
        at liquibase.Liquibase.update(Liquibase.java:185)
        at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:65)
        at io.dropwizard.migrations.DbCommand.run(DbCommand.java:55)
        at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at mil.dds.anet.AnetApplication.main(AnetApplication.java:86)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set migrations.xml::drop-primaryKey-constraint::gjvoosten:
     Reason: liquibase.exception.DatabaseException: ERROR: constraint "camelcase_pkey" of relation "camelCase" does not exist
  Where: SQL statement "alter table public."camelCase" drop constraint camelCase_pkey"
PL/pgSQL function inline_code_block line 7 at EXECUTE [Failed SQL: (0) DO $$ DECLARE constraint_name varchar;
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'camelCase' AND TABLE_SCHEMA = 'public';
    EXECUTE 'alter table public."camelCase" drop constraint ' || constraint_name;
END $$;]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:672)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
        at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
        at liquibase.Scope.lambda$child$0(Scope.java:166)
        at liquibase.Scope.child(Scope.java:175)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:144)
        at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110)
        at liquibase.Scope.lambda$child$0(Scope.java:166)
        at liquibase.Scope.child(Scope.java:175)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:144)
        at liquibase.Scope.child(Scope.java:228)
        at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
        at liquibase.Scope.lambda$child$0(Scope.java:166)
        at liquibase.Scope.child(Scope.java:175)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:144)
        at liquibase.Scope.child(Scope.java:228)
        at liquibase.Scope.child(Scope.java:232)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
        ... 23 more
Caused by: liquibase.exception.DatabaseException: ERROR: constraint "camelcase_pkey" of relation "camelCase" does not exist
  Where: SQL statement "alter table public."camelCase" drop constraint camelCase_pkey"
PL/pgSQL function inline_code_block line 7 at EXECUTE [Failed SQL: (0) DO $$ DECLARE constraint_name varchar;
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'camelCase' AND TABLE_SCHEMA = 'public';
    EXECUTE 'alter table public."camelCase" drop constraint ' || constraint_name;
END $$;]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
        ... 43 more
Caused by: org.postgresql.util.PSQLException: ERROR: constraint "camelcase_pkey" of relation "camelCase" does not exist
  Where: SQL statement "alter table public."camelCase" drop constraint camelCase_pkey"
PL/pgSQL function inline_code_block line 7 at EXECUTE
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy34.execute(Unknown Source)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
        ... 48 more
```

## Steps To Reproduce

Run the databaseChangeLog above on Liquibase 4.3.5 and 4.4.0 to see the problem.

## Actual Behavior

Liquibase 4.3.5 works correctly, Liquibase 4.4.0 fails.

## Expected/Desired Behavior

Liquibase 4.4.0 should work the same way as 4.3.5, i.e. use the same constraint name.

**Comment by molivasdat** [comment]
Hi @gjvoosten Thanks for the excellent write up of this issue.  We will add this to the list of issues that we are processing.

**Comment by nvoxland** [comment]
Added PR #1974 that should fix the issue

**Comment by gjvoosten** [comment]
@nvoxland After checking out your `postgresql-drop-pk` branch, building locally with `mvn -DskipTests install` (`-DskipTests` because of a failing test where the expected result needs updating with the new SQL) and using `org.liquibase:liquibase-core:4.4.2-local-SNAPSHOT` as a dependency, I can confirm that this works for all three cases in the **Expected/Desired Behavior** above.
