### ISSUE TITLE
Transaction started too early to end up in idle-in-transaction timeout since Liquibase 3.10

### ISSUE THREAD

**Issue by Adduh** [liquibase/liquibase#1937]
## Environment

**Liquibase Version**: everything between 3.10.x until 4.4.0

**Liquibase Integration & Version**: Spring Boot 2.4/2.5

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: Postgres 13

**Operating System Type & Version**: Linux

## Description
Somewhere between 3.8.9 (still working correctly) and 3.10.3 (definitively misbehaving), the behaviour how the transactions are initiated must have been changed. 
Now a DB transaction is opened at the beginning and if you have a lot of Liquibase script files to be parsed, the transaction will be idle for too long until the Liquibase changes are actually applied, thus leading to an idle-in-transaction timeout.

## Steps To Reproduce

- create Spring Boot project with Liquibase and Postgres as Database (Postgres version doesn't really matter)
- Create a lot of Liquibase scripts (parsing of the files should take some time. e.g. longer than 1 second)
- Lower the `idle_in_transaction_session_timeout`. e.g. to 1 second
- Run the application

## Actual Behavior

On Application startup, Liquibase will open a transaction (I assume to create the dbchangeloglock) and then it will parse all the Liquibase script files. Before the first Liquibase changes are executed, the transaction meanwhile is already idle for too long and throws this exception:
```
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: terminating connection due to idle-in-transaction timeout
at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1163) ~[liquibase-core-3.10.3.jar:na]
at liquibase.database.core.PostgresDatabase.rollback(PostgresDatabase.java:396) ~[liquibase-core-3.10.3.jar:na]
at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:251) ~[liquibase-core-3.10.3.jar:na]
... 183 common frames omitted
Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: terminating connection due to idle-in-transaction timeout
at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:362) ~[liquibase-core-3.10.3.jar:na]
at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1161) ~[liquibase-core-3.10.3.jar:na]
... 185 common frames omitted
Caused by: org.postgresql.util.PSQLException: FATAL: terminating connection due to idle-in-transaction timeout
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.18.jar:42.2.18]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.18.jar:42.2.18]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.18.jar:42.2.18]
at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:857) ~[postgresql-42.2.18.jar:42.2.18]
at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:900) ~[postgresql-42.2.18.jar:42.2.18]
at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:396) ~[HikariCP-3.4.5.jar:na]
at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java) ~[HikariCP-3.4.5.jar:na]
at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:359) ~[liquibase-core-3.10.3.jar:na]
... 186 common frames omitted
```

## Expected/Desired Behavior
Close the initial transaction after securing the dbchangeloglock and create new transaction directly before applying the changes, so that there is no idle-in-transaction timeout happening while parsing the Liquibase script files.

## Additional Context
The as of now latest version 4.4.0 is also affected.

With Spring Boot version 2.4, Liquibase was pulled in as version `3.10.3`, but which could still be downgraded to not affected version `3.8.9`.
With Spring Boot version 2.5, Liquibase version is 4 is used, and you cannot easily downgrade because of the breaking API changes.

**Comment by molivasdat** [comment]
Hi @Adduh Thanks for creating this issue.  We will take a look and add this to the list of issues that we are processing.

**Comment by nvoxland** [comment]
@Adduh is your 1 second timeout an example for replicating the issue? Or is your actual timeout close to that short?

**Comment by erpel** [comment]
We‘re running into this with a 10 second timeout in our environments.

**Comment by Adduh** [comment]
> @Adduh is your 1 second timeout an example for replicating the issue? Or is your actual timeout close to that short?

The 1 second was chosen to make it easier to reproduce it reliably.
With 10 seconds timout we got the problem in some services depending on the load of the system and on other services during different states of the liquibase migrations (I think during/after/before the snapshot)

**Comment by nvoxland** [comment]
Thanks for the clarification

**Comment by tati-qalified** [comment]
I was able to reproduce this bug with liquibase version 4.23.0, though it took many different scripts and the idle-in-transaction-session-timeout set under 1s.
This seems to be an issue for extreme stress cases.

**Comment by tati-qalified** [comment]
I've tested this bug with liquibase version 4.23.0, and it doesn't seem to be an issue anymore.
I set the `idle_in_transaction_session_timeout` to 500ms and created around 9 liquibase scripts with multiple changesets. The process ran for around 3,5 seconds, and there were no errors about timeouts. All changelogs were ran as expected.

I will be closing this issue, but feel free to reopen it if the problem persists.

**Comment by filipelautert** [comment]
As confirmed by @tati-qalified above, this was resolved as of Liquibase 4.23.0. The transaction management was improved so parsing no longer holds an idle transaction open.

Closing this out — if you're still hitting this on a recent version, feel free to re-open.
