### ISSUE TITLE
Illegal char warnings on Windows when using wildcard classpath

### ISSUE THREAD

**Issue by dewa-actico** [liquibase/liquibase#1940]
## Environment
Windows

**Liquibase Version**:
4.4.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
spring boot

**Operating System Type & Version**:
Windows 10

## Description
The following exception occurs when using a wildcard classpath (ie. `java -cp lib\*`):

```
java.nio.file.InvalidPathException: Illegal char <*> at index 22: C:/.../*
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:1.8.0_282]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:1.8.0_282]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:1.8.0_282]
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[?:1.8.0_282]
        at sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:166) ~[?:1.8.0_282]
        at sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:92) ~[?:1.8.0_282]
        at java.nio.file.Paths.get(Paths.java:138) ~[?:1.8.0_282]
        at liquibase.resource.ClassLoaderResourceAccessor.loadRootPaths(ClassLoaderResourceAccessor.java:67) ~[liquibase-core-4.4.0.jar!/:?]
        at liquibase.resource.ClassLoaderResourceAccessor.loadRootPaths(ClassLoaderResourceAccessor.java:90) ~[liquibase-core-4.4.0.jar!/:?]
        at liquibase.resource.ClassLoaderResourceAccessor.loadRootPaths(ClassLoaderResourceAccessor.java:90) ~[liquibase-core-4.4.0.jar!/:?]
        at liquibase.resource.ClassLoaderResourceAccessor.init(ClassLoaderResourceAccessor.java:51) ~[liquibase-core-4.4.0.jar!/:?]
```

## Steps To Reproduce
Starting Liquibase Bean.

## Actual Behavior
Warning as described above.

## Expected/Desired Behavior
Scanning through all matched jars? Or ignoring them?

**Comment by molivasdat** [comment]
Hi @dewa-actico Thanks for creating this issue.  I understand the wildcard issue but can you give a more specific example of how to recreate this.  This way we can make sure that we fix the right issue for you.
