### ISSUE TITLE
issues with liquibase diff when testing with azure sql server 12 - Adventure Works  example database 

### ISSUE THREAD

**Issue by gabrielcuadrosinkafarma** [liquibase/liquibase#1958]
## Environment
**Liquibase Version**: 4.3

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: CLI 

**Database Vendor & Version**: MICROSOFT SQL SERVER 12.00.214 

**Operating System Type & Version**: WINDOW 10 home 64 BIT 

## Description
A clear and concise description of the issue being addressed.

I have the following error when i tried to compare a sql server snapshot with a onlien database , the error are coming from this code 

https://github.com/liquibase/liquibase/blob/4.3.x/liquibase-core/src/main/java/liquibase/util/ObjectUtil.java
https://github.com/liquibase/liquibase/blob/4.3.x/liquibase-core/src/main/java/liquibase/database/OfflineConnection.java
https://github.com/liquibase/liquibase/blob/4.3.x/liquibase-core/src/main/java/liquibase/structure/core/Data.java

i am updating the document.json in txt file 
[documento.txt.txt](https://github.com/liquibase/liquibase/files/6741348/documento.txt.txt)

i am giving all the error log but the important thing is in here 

```
Caused by: liquibase.exception.LiquibaseParseException: liquibase.parser.core.ParsedNodeException: liquibase.exception.UnexpectedLiquibaseException: Cannot call public liquibase.structure.core.Index liquibase.structure.core.Index.setTable(liquibase.structure.core.Table) with value of type java.lang.String
```

```
[2021-06-30 08:31:51] GRAVE [liquibase.integration] Unexpected error running Liquibase: Cannot parse snapshot offline:mssql?snapshot=documento.json&catalog=samepldb&version=12.00.2148&productName=Microsoft SQL Server&caseSensitive=true
liquibase.exception.DatabaseException: liquibase.exception.UnexpectedLiquibaseException: Cannot parse snapshot offline:mssql?snapshot=documento.json&catalog=samepldb&version=12.00.2148&productName=Microsoft SQL Server&caseSensitive=true
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:131)
        at liquibase.integration.commandline.Main.createReferenceDatabaseFromCommandParams(Main.java:2050)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1484)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:364)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.integration.commandline.Main$1.run(Main.java:363)
        at liquibase.integration.commandline.Main$1.run(Main.java:193)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:145)
        at liquibase.integration.commandline.Main.run(Main.java:193)
        at liquibase.integration.commandline.Main.main(Main.java:156)
Caused by: liquibase.exception.UnexpectedLiquibaseException: Cannot parse snapshot offline:mssql?snapshot=documento.json&catalog=samepldb&version=12.00.2148&productName=Microsoft SQL Server&caseSensitive=true
        at liquibase.database.OfflineConnection.<init>(OfflineConnection.java:111)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:186)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:175)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:96)
        ... 13 more
Caused by: liquibase.exception.LiquibaseParseException: liquibase.parser.core.ParsedNodeException: liquibase.exception.UnexpectedLiquibaseException: Cannot call public liquibase.structure.core.Index liquibase.structure.core.Index.setTable(liquibase.structure.core.Table) with value of type java.lang.String
        at liquibase.parser.core.yaml.YamlSnapshotParser.parse(YamlSnapshotParser.java:62)
        at liquibase.database.OfflineConnection.<init>(OfflineConnection.java:101)
        ... 17 more
Caused by: liquibase.parser.core.ParsedNodeException: liquibase.exception.UnexpectedLiquibaseException: Cannot call public liquibase.structure.core.Index liquibase.structure.core.Index.setTable(liquibase.structure.core.Table) with value of type java.lang.String
        at liquibase.snapshot.DatabaseSnapshot.load(DatabaseSnapshot.java:632)
        at liquibase.parser.core.yaml.YamlSnapshotParser.parse(YamlSnapshotParser.java:55)
        ... 18 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: Cannot call public liquibase.structure.core.Index liquibase.structure.core.Index.setTable(liquibase.structure.core.Table) with value of type java.lang.String
        at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:143)
        at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:172)
        at liquibase.snapshot.DatabaseSnapshot.load(DatabaseSnapshot.java:597)
        ... 19 more
```

this is my current liquibase properties file, the sql server is hosted in azure and the database is the adventures work sample database that comes by default 

```
#driver: com.mysql.jdbc.Driver
#url: jdbc:mysql://localhost:3306/example2
driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
url: jdbc:sqlserver://sqlservergabriel89.database.windows.net:1433;databaseName=samepldb
#url: offline:mssql?snapshot=schema_before1.json&catalog=samepldb&version=12.00.2148&productName=SalesLT&caseSensitive=true
classpath: mssql-jdbc-9.2.1.jre8.jar
#classpath: mysql-connector-java-8.0.25
username: user2
password: **********
#username: root
#password: *********
logLevel: debug
changeLogFile: mydatabase_changelog.mssql.sql
#diffChangeLogFile=mydatabase_diffchangelog.mssql.sql
#outputChangeLogFile=mydatabase_outputchangelog.mssql.sql
#changeLogFile: mydatabase_changelog.xml
defaultSchemaName: SalesLT 
defaultCatalogName: samepldb
#referenceUrl: offline:mssql?snapshot=schemabefore.json
referenceUrl: offline:mssql?snapshot=documento.json&catalog=samepldb&version=12.00.2148&productName=Microsoft SQL Server&caseSensitive=true
#referenceUrl: offline:mysql?snapshot=schema_before.json
#referenceDefaultSchemaName: SalesLT
#referenceDefaultCatalogName: samepldb 
outputDefaultCatalog: true 
outputDefaultSchema: true 
includeCatalog: true 
includeSchema: true
```

## Steps To Reproduce
List the steps to reproduce the behavior.

*  deploy a azure sql server and use a adventuresworks example database provided by azure
* make a snapshot of database 

```
./liquibase.bat --defaultSchemaName=SalesLT --defaultCatalogName=samepldb --outputDefaultCatalog=true --outputDefaultSchema=true --includeCatalog=true --includeSchema=true --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver --classpath=mssql-jdbc-9.2.1.jre8.jar "--url=jdbc:sqlserver://sqlservergabriel89.database.windows.net:1433;databaseName=samepldb" "--username=user2" "--password=*****" --outputFile=documento.json --logLevel=debug snapshot --snapshotFormat=json 
```

* do a 

```
./liquibase.bat  diff
```

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.

testing with sample database adventurers work in sql server fails

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

testing with sample database adventurers work in sql should work

**Comment by gabrielcuadrosinkafarma** [comment]
the adventure table have user defined data types, does liquibase can know about this data types? i dont think it can because , i dont see the definition in the snapshot i take but i dont know if this is related with the error mentioned above 
![image](https://user-images.githubusercontent.com/83834262/124042372-4fc91280-d9ce-11eb-9d06-d831278c2b55.png)

**Comment by gabrielcuadrosinkafarma** [comment]
i tried with liquibase pro trial license but still cant retrieve defined data types, please in would like some suport about this case ,thanks!

**Comment by molivasdat** [comment]
Hi @gabrielcuadrosinkafarma Thanks for submitting this issue. I'm not sure that user defined types are supported in snapshots in Liquibase at this time.

**Comment by FBurguer** [comment]
This issue have gone stale. If you think we should add defined types support, you can always submit an enhancement request and/or a PR with a solution for this. Im closing this issue for now. But feel free to re-open it
