### ISSUE TITLE
Diff Command Works But Diff-Changelog And Generate-Changelog Fails

### ISSUE THREAD

**Issue by Roebou** [liquibase/liquibase#1966]
## Environment

**Liquibase Version*4.4.0*:

**Liquibase Integration & Version**:
Starting Liquibase at 12:45:29 (version 4.4.0 #11 built at 2021-06-09 16:36+0000)
Liquibase Version: 4.4.0
Liquibase Community 4.4.0 by Datical

**Liquibase Extension(s) & Version**: 
Starting Liquibase at 12:45:29 (version 4.4.0 #11 built at 2021-06-09 16:36+0000)
Liquibase Version: 4.4.0
Liquibase Community 4.4.0 by Datical

**Database Vendor & Version**:
Postgresql  (psql (13.3 (Ubuntu 13.3-1.pgdg20.04+1)))
PostgreSQL JDBC Driver 42.2.22

**Operating System Type & Version**:
Linux dev-platform 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## Description
I have a scenario where I only have a single developer database where I am making changes. After installation of my application, I would like to perform a generate-changelog which will be my initial / master starting point. After that, I would like to make changes via my application to the database contents (insert, update, delete) and manually change the database schema. I then want to run another generate-changelog and compare the two changelogs to get the difference between the changelogs. I need to be able to capture both the schema make-up as well as my data in my tables. I am not sure if there is perhaps an easier way of doing this and any pointers would greatly be appreciated.

After reading up a bit, I came to an article (https://www.liquibase.org/blog/comparing-two-states-database-schema) which gives them steps to perform a snapshot of a database, then make changes, then compare the initial snapshot against the new database state. When running through the steps, it keeps erroring when attempting to create a changelog between the snapshot and the current database schema. Please see below for steps to re-create.

**Step 1:** - This works without any issues and it generates a snapshot file. The snapshot
liquibase --defaultSchemaName=test --outputFile=test.yaml snapshot --snapshotFormat=yaml
`
Starting Liquibase at 12:58:35 (version 4.4.0 #11 built at 2021-06-09 16:36+0000)
Liquibase Version: 4.4.0
Liquibase Community 4.4.0 by Datical
Logs saved to /test/Liquibase/test_project/liquibase.log
Output saved to  /test/Liquibase/test_project/insight.yaml
Liquibase command 'snapshot' was executed successfully.
`

**Step 2** - I change a column's value and inserted a new row.

**Step 3** - Attempting to run the diff command which works without issues.
liquibase --url=offline:postgresql?snapshot=test_project/test.yaml --referenceUrl=jdbc:postgresql://localhost:5432/test --referenceUsername=test --referencePassword=test --referenceDefaultSchemaName=test --outputFile=test.txt --changeLogFile=test.yaml diff
`Starting Liquibase at 13:02:47 (version 4.4.0 #11 built at 2021-06-09 16:36+0000)
Liquibase Version: 4.4.0
Liquibase Community 4.4.0 by Datical

Diff Results:
Logs saved to /test/Liquibase/test_project/liquibase.log
Output saved to /test/Liquibase/test_project/test.txt
Liquibase command 'diff' was executed successfully.`

**test.txt output:**
Reference Database: test @ jdbc:postgresql://localhost:5432/test (Default Schema: test)
Comparison Database: test @ offline:postgresql?snapshot=test.yaml (Default Schema: test)
Compared Schemas: test
Product Name:
     Reference:   'PostgreSQL'
     Target: 'Offline postgresql'
Product Version: EQUAL
Missing Catalog(s): NONE
Unexpected Catalog(s): NONE
Changed Catalog(s): NONE
Missing Column(s): 
     test.b_rtfm_ref_true_false_measure.test_rtfm3
Unexpected Column(s): 
     lower((c_name)::text)
     lower((c_surname)::text)
     lower((p_name)::text)
     test.b_rtfm_ref_true_false_measure.test_rtfm2
Changed Column(s): 
     test.interface.i_secondary_identifier
          defaultValue changed from 'sys_guid())::character varying(32' to 'public.sys_guid())::character varying(32'
     test.logical_column.lc_id
          defaultValue changed from 'sys_guid()' to 'public.sys_guid()'
Missing Foreign Key(s): NONE
Unexpected Foreign Key(s): NONE
Changed Foreign Key(s): NONE
Missing Index(s): NONE
Unexpected Index(s): NONE
Changed Index(s): 
     ind1_b_p ON test.person(lower((p_name)::text), p_cell_no)
          columns changed from '[test.person.lower((p_name)::text), test.person.p_cell_no]' to '[test.person.p_cell_no]'
     ind1_ca_c ON test.customer(lower((c_surname)::text), lower((c_name)::text))
          columns changed from '[test.customer.lower((c_surname)::text), test.customer.lower((c_name)::text)]' to '[null]'
Missing Primary Key(s): NONE
Unexpected Primary Key(s): NONE
Changed Primary Key(s): NONE
Missing Schema(s): NONE
Unexpected Schema(s): NONE
Changed Schema(s): NONE
Missing Sequence(s): NONE
Unexpected Sequence(s): NONE
Changed Sequence(s): NONE
Missing Table(s): NONE
Unexpected Table(s): NONE
Changed Table(s): NONE
Missing Unique Constraint(s): NONE
Unexpected Unique Constraint(s): NONE
Changed Unique Constraint(s): NONE
Missing View(s): NONE
Unexpected View(s): NONE
Changed View(s): NONE

**Step 4** - Attempting to run diff-changelog ends up returning null pointers.
liquibase --url=offline:postgresql?snapshot=test.yaml --referenceUrl=jdbc:postgresql://localhost:5432/test --referenceUsername=test --referencePassword=test --referenceDefaultSchemaName=test --outputFile=test.txt --changeLogFile=test2.yaml diff-changelog
`Starting Liquibase at 13:13:08 (version 4.4.0 #11 built at 2021-06-09 16:36+0000)
Liquibase Version: 4.4.0
Liquibase Community 4.4.0 by Datical

BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed.
Unexpected error running Liquibase: java.lang.NullPointerException

Logs saved to /test/Liquibase/test_project/liquibase.log
Output saved to /test/Liquibase/test_project/test.txt
`

**test.txt output:**
[EMPTY]

**liquibase.log output:** - I only added the last part of the file, near the error.
[2021-07-04 13:13:48] FINE [liquibase.configuration] No configuration value for liquibase.generateChangesetCreatedValues aka liquibase.generateChangeSetCreatedValues found
[2021-07-04 13:13:48] FINE [liquibase.configuration] Configuration liquibase.generateChangesetCreatedValues is using the default value of false
[2021-07-04 13:13:48] FINE [liquibase.configuration] No configuration value for liquibase.pro.sql.inline found
[2021-07-04 13:13:48] FINE [liquibase.configuration] Configuration liquibase.pro.sql.inline is using the default value of false
[2021-07-04 13:13:48] FINE [liquibase.diff] ChangedObjectChangeGenerator type order:     liquibase.structure.core.Catalog    liquibase.structure.core.ForeignKey    liquibase.structure.core.Schema    liquibase.structure.core.Sequence    liquibase.structure.core.Table    liquibase.structure.core.Column    liquibase.structure.core.PrimaryKey    liquibase.structure.core.UniqueConstraint    liquibase.structure.core.Index    liquibase.structure.core.View
[2021-07-04 13:13:48] FINE [liquibase.configuration] No configuration value for liquibase.liquibaseCatalogName aka liquibase.catalogName found
[2021-07-04 13:13:48] FINE [liquibase.configuration] No configuration value for liquibase.liquibaseSchemaName aka liquibase.schemaName found
[2021-07-04 13:13:48] FINE [liquibase.configuration] No configuration value for liquibase.generatedChangesetIdsContainsDescription aka liquibase.generatedChangeSetIdsContainsDescription found
[2021-07-04 13:13:48] FINE [liquibase.configuration] Configuration liquibase.generatedChangesetIdsContainsDescription is using the default value of false
[2021-07-04 13:13:48] SEVERE [liquibase.integration] java.lang.NullPointerException
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at liquibase.command.CommandScope.execute(CommandScope.java:153)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:306)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:289)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:83)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at liquibase.integration.commandline.Main$1.run(Main.java:444)
	at liquibase.integration.commandline.Main$1.run(Main.java:222)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.Main.run(Main.java:222)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:147)
	... 14 more
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:207)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1600)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:399)
	at liquibase.Scope.lambda$child$0(Scope.java:166)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.integration.commandline.Main$1.run(Main.java:398)
	... 20 more
Caused by: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at liquibase.command.CommandScope.execute(CommandScope.java:153)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:205)
	... 27 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:199)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:85)
	at liquibase.command.core.InternalDiffChangelogCommandStep.run(InternalDiffChangelogCommandStep.java:61)
	at liquibase.command.CommandScope.execute(CommandScope.java:147)
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:182)
	at liquibase.Scope.lambda$child$0(Scope.java:166)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:127)
	... 31 more
Caused by: java.lang.NullPointerException
	at liquibase.diff.output.changelog.core.ChangedIndexChangeGenerator$1.toString(ChangedIndexChangeGenerator.java:117)
	at liquibase.diff.output.changelog.core.ChangedIndexChangeGenerator$1.toString(ChangedIndexChangeGenerator.java:114)
	at liquibase.util.StringUtil.join(StringUtil.java:208)
	at liquibase.diff.output.changelog.core.ChangedIndexChangeGenerator.fixChanged(ChangedIndexChangeGenerator.java:122)
	at liquibase.diff.output.changelog.ChangeGeneratorChain.fixChanged(ChangeGeneratorChain.java:137)
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixChanged(ChangeGeneratorFactory.java:118)
	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:274)
	at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:222)
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:133)
	... 36 more

**Comment by molivasdat** [comment]
Hi @Roebou Thanks for writing up this issue.  I was unware that yaml based snapshots were supported outside of Liquibase Pro.

**Comment by nvoxland** [comment]
The snapshot command supports outputting the snapshot in yaml/json formats. It's just the "diff" command that has a pro-only json-formatted report.

The issue appears to be in how we're handling the computed column in the index. Even though the snapshot command passes, the yaml file includes a "column" listing for 
```
    - column:
        computed: true
        descending: false
        name: lower((name)::text)
```
which should not be there since it's not an actual column.

The code that handles that is a big deep in the snapshot code, so it will take a little bit of fighting to get it resolved.

**Comment by nvoxland** [comment]
I checked whether this was fixed by #2173 but it looks like it was not, unfortunately. Will still likely take a bit of work to get fixed up.

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
