### ISSUE TITLE
IDEA logs contains errors

### ISSUE THREAD

**Issue by baev** [liquibase/liquibase#2082]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description

Every millisecond (!!!) the following error is appeared in IDEA's logs:

```
2021-09-08 12:48:43,010 [418783120]  ERROR - red.platform.impl.ChunkManager - IntelliJ IDEA 2021.1.2  Build #IU-211.7442.40 
2021-09-08 12:48:43,010 [418783120]  ERROR - red.platform.impl.ChunkManager - JDK: 11.0.11; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-09-08 12:48:43,010 [418783120]  ERROR - red.platform.impl.ChunkManager - OS: Mac OS X 
2021-09-08 12:48:43,011 [418783121]  ERROR - red.platform.impl.ChunkManager - Last Action: GotoDeclaration 
2021-09-08 12:48:43,011 [418783121]  ERROR - red.platform.impl.ChunkManager - /Users/baev/.gradle/caches/modules-2/files-2.1/org.liquibase/liquibase-core/4.4.3/20bcb8d97a8619c7d184f03d7247dfb85f8a9f7a/liquibase-core-4.4.3-sources.jar!/var/jenkins/workspace/liquibasePro/4.4.x/53/liquibase/liquibase-dist/target/archive/GETTING_STARTED.txt 
java.io.FileNotFoundException: /Users/baev/.gradle/caches/modules-2/files-2.1/org.liquibase/liquibase-core/4.4.3/20bcb8d97a8619c7d184f03d7247dfb85f8a9f7a/liquibase-core-4.4.3-sources.jar!/var/jenkins/workspace/liquibasePro/4.4.x/53/liquibase/liquibase-dist/target/archive/GETTING_STARTED.txt
	at com.intellij.openapi.vfs.impl.ZipHandlerBase.getEntryCrc(ZipHandlerBase.java:83)
	at com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.getEntryCrc(JarFileSystemImpl.java:143)
	at com.intellij.indexing.shared.platform.hash.SharedIndexCrcArchiveHashProvider.computeHash(SharedIndexCrcArchiveHash.kt:31)
	at com.intellij.indexing.shared.platform.impl.SharedIndexChunk.tryEnumerate(ChunkManager.kt:100)
	at com.intellij.indexing.shared.platform.impl.ChunkManager.tryEnumerateContentHash(ChunkManager.kt:33)
	at com.intellij.indexing.shared.platform.impl.SharedIndexChunkConfigurationImpl.tryEnumerateContentHash(SharedIndexChunkConfigurationImpl.java:243)
	at com.intellij.indexing.shared.platform.impl.CompositeInvertedIndex.tryIndexWithoutContent(CompositeInvertedIndex.java:47)
	at com.intellij.indexing.shared.platform.impl.SharedIndexFileIndexingStatusProcessor.tryIndexFileWithoutContent(SharedIndexFileIndexingStatusProcessor.java:79)
	at com.intellij.util.indexing.UnindexedFilesFinder.tryIndexWithoutContentViaInfrastructureExtension(UnindexedFilesFinder.java:200)
	at com.intellij.util.indexing.UnindexedFilesFinder.lambda$getFileStatus$2(UnindexedFilesFinder.java:141)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:577)
	at com.intellij.util.indexing.UnindexedFilesFinder.lambda$getFileStatus$3(UnindexedFilesFinder.java:98)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.util.indexing.UnindexedFilesFinder.getFileStatus(UnindexedFilesFinder.java:54)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$collectIndexableFilesConcurrently$12(UnindexedFilesUpdater.java:370)
	at com.intellij.openapi.vfs.VfsUtilCore$1.visitFileEx(VfsUtilCore.java:277)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:293)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(VfsUtilCore.java:273)
	at com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(VfsUtilCore.java:266)
	at com.intellij.util.indexing.roots.IndexableFilesIterationMethods.iterateRoots(IndexableFilesIterationMethods.kt:31)
	at com.intellij.util.indexing.roots.IndexableFilesIterationMethods.iterateRoots$default(IndexableFilesIterationMethods.kt:24)
	at com.intellij.util.indexing.roots.LibraryIndexableFilesIteratorImpl.iterateFiles(LibraryIndexableFilesIteratorImpl.kt:48)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$collectIndexableFilesConcurrently$13(UnindexedFilesUpdater.java:386)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$6.run(PushedFilePropertiesUpdaterImpl.java:349)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.lambda$invokeConcurrentlyIfPossible$16(PushedFilePropertiesUpdaterImpl.java:356)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

BTW `liquibase-core-4.4.3-sources.jar` contains some files from Jenkins workspace (`/var/jenkins/workspace/liquibasePro/4.4.x/**`), it doesn't seem right

**Comment by molivasdat** [comment]
Hi @baev Thanks for writing up this issue.  We will add it to the list of issues we are processing.

**Comment by derkoe** [comment]
It seems that there are some files added to the source JAR that do not belong there:

```
$ unzip -l $MAVEN_REPO/repository/org/liquibase/liquibase-core/4.3.5/liquibase-core-4.3.5-sources.jar | grep '/var'
        0  04-29-2021 18:31   /var/
        0  04-29-2021 18:31   /var/jenkins/
        0  04-29-2021 18:31   /var/jenkins/workspace/
        0  04-29-2021 18:31   /var/jenkins/workspace/liquibasePro/
        0  04-29-2021 18:31   /var/jenkins/workspace/liquibasePro/4.3.x/
        0  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/
        0  04-29-2021 18:35   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/
        0  04-29-2021 18:27   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/
        0  04-29-2021 18:28   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/
        0  04-29-2021 18:27   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/
        0  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/
        0  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/sql/
        0  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/xml/
        0  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/lib/
        0  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/
     2783  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/README.txt
    16375  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/cddl1.txt
     2932  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/sql/liquibase.properties
      950  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/start-h2.bat
      796  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/xml/blank.changelog.xml
     1723  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/xml/sample.changelog.xml
     3225  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/lib/liquibase_autocomplete.sh
     9115  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/apache-2.0.txt
     7377  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/epl-1.0.txt
     1844  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/liquibase
     1913  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/plexus.txt
    10613  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/GETTING_STARTED.txt
     1481  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/xml/liquibase.sqlplus.conf
     2578  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/lib/liquibase_autocomplete_mac.bash
     1262  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/bsd-2-clause.txt
    11576  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/cpl-1.0.txt
     1024  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/mit.txt
     1021  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/liquibase.bat
     2859  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/README.txt
      218  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/sql/blankchangelog.h2.sql
      456  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/sql/samplechangelog.h2.sql
     1168  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/start-h2
     2930  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/examples/xml/liquibase.properties
    11518  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/Liquibase Pro EULA Software License Subscription and Support Agreement.txt
      697  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/isc.txt
    25355  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/licenses/lgpl-3.0.txt
      908  04-29-2021 18:23   /var/jenkins/workspace/liquibasePro/4.3.x/62/liquibase/liquibase-dist/target/archive/UNINSTALL.txt

```

The files are packed with an absolute path (which is actually an attack against the [Zip Slip vulnerability](https://snyk.io/research/zip-slip-vulnerability).

**Comment by molivasdat** [comment]
@derkoe and @baev I'm not sure what changed but that directory structure in that jar for var has been there since 3.9.0.  We will continue to look into it.

**Comment by nvoxland** [comment]
We've overhauled the build system including how the sources are built.

The last bit of the changes in #2224 should address this.
