### ISSUE TITLE
NumberFormatException while diffChangelog

### ISSUE THREAD

**Issue by xpoinsard** [liquibase/liquibase#2116]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Oracle 12c and Postgresql 12

**Operating System Type & Version**: Ubuntu 20.04

## Description

Tried to generate a diffChangelog from an Oracle database to a Postgresql database 

## Steps To Reproduce

```
liquibase  --changeLogFile=mychangelog.postgresql.sql --outputFile=mydiff.txt \
--driver=org.postgresql.Driver --referenceDriver=oracle.jdbc.OracleDriver \
--url="jdbc:postgresql:XXX" --username=UUU --password=PPP \
--referenceUrl="jdbc:oracle:thin:YYY" --referenceUsername=UU2 --referencePassword=PP2 --referenceDefaultSchemaName=ZZZ \
diffChangeLog
```

## Actual Behavior
```
[2021-09-24 17:59:11] GRAVE [liquibase.integration] java.lang.NumberFormatException: For input string: "*"
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.command.CommandScope.execute(CommandScope.java:153)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:317)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:289)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:83)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.integration.commandline.Main$1.run(Main.java:447)
	at liquibase.integration.commandline.Main$1.run(Main.java:225)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.Main.run(Main.java:225)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:147)
	... 14 more
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:207)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1607)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:402)
	at liquibase.Scope.lambda$child$0(Scope.java:166)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.integration.commandline.Main$1.run(Main.java:401)
	... 20 more
Caused by: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.command.CommandScope.execute(CommandScope.java:153)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:205)
	... 27 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:199)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:85)
	at liquibase.command.core.InternalDiffChangelogCommandStep.run(InternalDiffChangelogCommandStep.java:61)
	at liquibase.command.CommandScope.execute(CommandScope.java:147)
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:182)
	at liquibase.Scope.lambda$child$0(Scope.java:166)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:127)
	... 31 more
Caused by: java.lang.NumberFormatException: For input string: "*"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at liquibase.datatype.core.NumberType.toDatabaseDataType(NumberType.java:50)
	at liquibase.diff.output.changelog.core.MissingTableChangeGenerator.fixMissing(MissingTableChangeGenerator.java:144)
	at liquibase.diff.output.changelog.ChangeGeneratorChain.fixMissing(ChangeGeneratorChain.java:48)
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixMissing(ChangeGeneratorFactory.java:95)
	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:298)
	at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:222)
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:133)
	... 36 more

Unexpected error running Liquibase: java.lang.NumberFormatException: For input string: "*"

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.command.CommandScope.execute(CommandScope.java:153)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:317)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:289)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:83)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.integration.commandline.Main$1.run(Main.java:447)
	at liquibase.integration.commandline.Main$1.run(Main.java:225)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.Main.run(Main.java:225)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:147)
	... 14 more
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:207)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1607)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:402)
	at liquibase.Scope.lambda$child$0(Scope.java:166)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.integration.commandline.Main$1.run(Main.java:401)
	... 20 more
Caused by: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.command.CommandScope.execute(CommandScope.java:153)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:205)
	... 27 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:199)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:85)
	at liquibase.command.core.InternalDiffChangelogCommandStep.run(InternalDiffChangelogCommandStep.java:61)
	at liquibase.command.CommandScope.execute(CommandScope.java:147)
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "*"
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:182)
	at liquibase.Scope.lambda$child$0(Scope.java:166)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:127)
	... 31 more
Caused by: java.lang.NumberFormatException: For input string: "*"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at liquibase.datatype.core.NumberType.toDatabaseDataType(NumberType.java:50)
	at liquibase.diff.output.changelog.core.MissingTableChangeGenerator.fixMissing(MissingTableChangeGenerator.java:144)
	at liquibase.diff.output.changelog.ChangeGeneratorChain.fixMissing(ChangeGeneratorChain.java:48)
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixMissing(ChangeGeneratorFactory.java:95)
	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:298)
	at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:222)
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:133)
	... 36 more
```

## Expected/Desired Behavior
no error

**Comment by molivasdat** [comment]
Hi @xpoinsard Thanks for creating this issue.  I am not even sure that this is supported since there is only one driver that is being used to connect to the databases.

**Comment by LonwoLonwo** [comment]
Hello.
As I see in the stack trace 

```
Caused by: java.lang.NumberFormatException: For input string: "*"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at liquibase.datatype.core.NumberType.toDatabaseDataType(NumberType.java:50)
```

it can be related to my PR https://github.com/liquibase/liquibase/pull/1906

**Comment by filipelautert** [comment]
The crash in `NumberType.toDatabaseDataType()` was fixed — the `parseInt` call now has a `NumberFormatException` catch (PR #1906, merged July 2022). Oracle's `NUMBER(*)` no longer causes a crash during diffChangeLog.

Closing this out — if you're still hitting this on a recent version, feel free to re-open.
