### ISSUE TITLE
Multithreading error: StackOverflowError in configuration value code

### ISSUE THREAD

**Issue by jamey-clari** [liquibase/liquibase#2153]
## Environment
**Liquibase Version**: 4.5.0

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: n/a

**Database Vendor & Version**: PostgreSQL 12.7

**Operating System Type & Version**: Max OSX 11.6

## Description
Since updating our project to Liquibase v4.5.0 many unit tests are now failing with a StackOverflowError due to what looks like an unbounded recursion getting configuration values.

Caused by: java.lang.StackOverflowError
	at liquibase.Scope.getCurrentScope(Scope.java)
	at liquibase.configuration.pro.EnvironmentValueProvider.lookupProvidedValue(Unknown Source)
	at liquibase.configuration.AbstractMapConfigurationValueProvider.getProvidedValue(AbstractMapConfigurationValueProvider.java:52)
	at liquibase.configuration.LiquibaseConfiguration.getCurrentConfiguredValue(LiquibaseConfiguration.java:123)
	at liquibase.configuration.ConfigurationDefinition.getCurrentConfiguredValue(ConfigurationDefinition.java:93)
	at liquibase.license.pro.DaticalTrueLicenseService.licenseIsInstalled(Unknown Source)
	at liquibase.license.pro.DaticalTrueLicenseService.licenseIsValid(Unknown Source)
	at liquibase.configuration.pro.EnvironmentValueProvider.lookupProvidedValue(Unknown Source)
	at liquibase.configuration.AbstractMapConfigurationValueProvider.getProvidedValue(AbstractMapConfigurationValueProvider.java:52)
	at liquibase.configuration.LiquibaseConfiguration.getCurrentConfiguredValue(LiquibaseConfiguration.java:123)
	at liquibase.configuration.ConfigurationDefinition.getCurrentConfiguredValue(ConfigurationDefinition.java:93)
	at liquibase.license.pro.DaticalTrueLicenseService.licenseIsInstalled(Unknown Source)
	at liquibase.license.pro.DaticalTrueLicenseService.licenseIsValid(Unknown Source)
	at liquibase.configuration.pro.EnvironmentValueProvider.lookupProvidedValue(Unknown Source)
	at liquibase.configuration.AbstractMapConfigurationValueProvider.getProvidedValue(AbstractMapConfigurationValueProvider.java:52)
	at liquibase.configuration.LiquibaseConfiguration.getCurrentConfiguredValue(LiquibaseConfiguration.java:123)
	at liquibase.configuration.ConfigurationDefinition.getCurrentConfiguredValue(ConfigurationDefinition.java:93)
	... and on and on

## Steps To Reproduce
This I'm still struggling with.  If I run a single-threaded test then things work but if I run a multithreaded test where threads may contend for creating a new DB and using Liquibase to create the initial schema then we seem to reliably (every time I run the test) see this infinite recursion that includes various `.pro` packaged classes.

I tried compiling Liquibase v4.5.0 from source and using that jar with my project and that jar DOES NOT have the `.pro` packaged classes and doesn't fail with the unbounded configuration recursion.

## Actual Behavior
Our software and unit test create 20 threads each that will try and establish a connection to an as-yet uncreated DB.  Each thread requests a handle to a connection pool, the first thread making such request triggers creation of the DB and a new connection pool to it.  During pool initialization we use liquibase (Liquibase.update API) to apply a changelog creating the initial schema for the new DB.  The DB and pool creation are serialized so the first thread creates the DB, the pool, and performs the associated liquibase update initialization operation.  Once this is done a reference to the pool is returned to all all callers/threads.  When I run this with only a single thread trying to get the pool I have no problems, multiple threads (5 or more) pretty reliably breaks with the unbounded configuration recursion mentioned above.

## Expected/Desired Behavior
No unbounded recursion trying to read configuration, perhaps no use of `.pro` classes if these are contributing to the problem.

## Screenshots (if appropriate)
n/a

## Additional Context
I apologize that this isn't more tightly conveyed with a simple unit test but I can't reproduce under simpler conditions.  I think there is something about the multiple liquibase update operations in close proximity in time that is leaving some internal state in a weird place causing the configuration recursion to spiral.  Unfortunately the stack depth is great enough that the part of the stack that initiates the problem is truncated and not available.  At a high level I'm mostly curious if the use of the `.pro` packaged stuff like EnvironmentValueProvider is expected in the community 4.5.0 release and if there is something unintentional here going on here with this release.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-2156) by [Unito](https://www.unito.io)

**Comment by nvoxland** [comment]
We do release just a single jar file which includes all of liquibase (both the free portion as well as the paid code). So the pro functionality is supposed to be there, just not enabled if you do not have a pro license.

We've not been able to replicate the issue you're seeing with the current 4.6.2 version. It's possible it has been fixed, but I'm not seeing a "smoking gun" commit so far.

Can you see if you're still seeing it with 4.6.2? If so, are you able to provide more of a test case?

**Comment by kevin-atx** [comment]
@jamey-clari - we are going to go ahead and close this issue as unreproducible. If you are still having this problem with the latest version of Liquibase, please feel free to reopen this ticket or create a new one.

**Comment by jamey-clari** [comment]
@kevin-atx - Fair enough.  We have been on 4.20.0 for some months now after a not non-painful upgrade from 3.x.  I cannot recall why we didn't move all the way to 4.5 or higher but we had some reason.  Times are busy so I'm not sure when I'll have the chance to move to 4.6.2 or higher.  I've not see this issue recently though that I recall so that is a good sign and we will be back here if we have similar problems going to 4.6 or higher in the future.  Thanks!
