### ISSUE TITLE
Liquibase dependency on java.desktop module

### ISSUE THREAD

**Issue by dconnelly** [liquibase/liquibase#2162]
## Environment

Java 17

**Liquibase Version**:

4.5.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

Maven

**Liquibase Extension(s) & Version**: 

N/A

**Database Vendor & Version**:

Postgres 9.x

**Operating System Type & Version**:

MacOS 11.6

## Description

While attempting to build a minimal JRE for running a Dropwizard application, we discovered that Liquibase actually requires the `java.desktop` module due to a dependency on` java.beans`. Given that this is not a desktop application is seems like a strange requirement. Unfortunately, migrations fail due to the following error:
```
java.lang.Exception: java.lang.NoClassDefFoundError: java/beans/IntrospectionException
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:87)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
	Suppressed: java.lang.Exception: java.lang.NoClassDefFoundError: Could not initialize class com.yammer.lookup.service.LookupIntegrationTest
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.afterAll(DropwizardExtensionsSupport.java:40)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$14(ClassBasedTestDescriptor.java:434)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$15(ClassBasedTestDescriptor.java:434)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllCallbacks(ClassBasedTestDescriptor.java:434)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:216)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:78)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:149)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:149)
		... 29 more
	Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.yammer.lookup.service.LookupIntegrationTest
		at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
		at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
		at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
		at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
		at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
		at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
		at java.base/java.lang.reflect.Field.get(Field.java:425)
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.getDropwizardExtension(DropwizardExtensionsSupport.java:149)
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.afterAll(DropwizardExtensionsSupport.java:50)
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.afterAll(DropwizardExtensionsSupport.java:36)
		... 39 more
Caused by: java.lang.NoClassDefFoundError: java/beans/IntrospectionException
	at liquibase.parser.core.formattedsql.FormattedSqlChangeLogParser.parse(FormattedSqlChangeLogParser.java:224)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:224)
	at liquibase.Scope.lambda$child$0(Scope.java:177)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:176)
	at liquibase.Scope.child(Scope.java:155)
	at liquibase.Liquibase.runInScope(Liquibase.java:2404)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.Liquibase.update(Liquibase.java:193)
	at liquibase.Liquibase.update(Liquibase.java:185)
	at com.yammer.lookup.service.PostgresTestContainer.lambda$start$0(PostgresTestContainer.java:50)
	at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32)
	at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.inTransaction(LocalTransactionHandler.java:208)
	at org.jdbi.v3.core.Handle.inTransaction(Handle.java:460)
	at org.jdbi.v3.core.Handle.useTransaction(Handle.java:472)
	at org.jdbi.v3.core.Jdbi.lambda$useTransaction$6(Jdbi.java:391)
	at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:342)
	at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:358)
	at org.jdbi.v3.core.Jdbi.useTransaction(Jdbi.java:391)
	at com.yammer.lookup.service.PostgresTestContainer.start(PostgresTestContainer.java:47)
	at com.yammer.lookup.service.DbIntegrationTest.<clinit>(DbIntegrationTest.java:12)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.getDropwizardExtension(DropwizardExtensionsSupport.java:149)
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:97)
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:83)
	... 37 more
Caused by: java.lang.ClassNotFoundException: java.beans.IntrospectionException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 71 more
```

The dependency seems to be coming from `liquibase.change.AbstractChange`. After a cursory glance, it looks like the code may just be using `java.beans` for basic bean introspection (setters and getters). The problem with the `java.desktop` dependency is that it brings in the whole of `java.awt` as well as a bunch of desktop specific features, but there is likely a way of achieving the same result using pure reflection instead. I will see if I can put something together in a PR.

## Steps To Reproduce

Run Liquibase migrations under Java 11+ w/o the java.desktop module.

## Actual Behavior

Fails with above exception when running migrations.

## Expected/Desired Behavior

Migrations should run without a `java.desktop` dependency.

**Comment by molivasdat** [comment]
Hi @dconnelly Thanks for bringing this issue to our attention.  If you have a PR that will fix this issue, that would be great.  We will add this to the list of issues that we are processing.

**Comment by tenor-dev** [comment]
Just a small reminder :-)

**Comment by kevin-atx** [comment]
@dconnelly (or anyone else) - did you get a chance to see what it would take to remove the java.desktop dependency? If you figure it out and submit a PR, we'll review it with the goal of getting it integrated back into Liquibase Core.
