### ISSUE TITLE
PostgreSQL 14 FUNCTION BEGIN ATOMIC syntax generating errors

### ISSUE THREAD

**Issue by mmauger** [liquibase/liquibase#2186]
## Environment

**Liquibase Version**: Community 4.3.1

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: None

**Database Vendor & Version**: PostgreSQL 14; JDBC Driver 42.3.1

**Operating System Type & Version**: MacOS Darwin Kernel Version 20.6.0

## Description

In PostgreSQL 14 there is support in FUNCTIONs/PROCEDUREs for native SQL code in a `BEGIN ATOMIC ...; END` block rather than embedding the code in a string. The advantage is that dependency tracking can be implemented by the database so that `DROP ... CASCADE` can drop impacted stored procedures. 

The new syntax is accepted but an error is raised when it is run thru Liquibase; the text is accepted in PSQL. Liquibase is reporting an issue with the semicolon in the `BEGIN ATOMIC` block yet shows it is sending the whole statement in the error message (`endDelimiter` is set to an empty string and `splitStatements` is set to false).

## Steps To Reproduce

I have the files shown below when I run the following command:

> liquibase --driver=org.postgresql.Driver --username mmauger --url jdbc:postgresql://localhost:5432/mmauger --changeLogFile changeLog.yml --logLevel debug update

* `changeLog.yml`
```
databaseChangeLog:
  - include:
      file: good.sql            # uses AS $$ ... $$ syntax for function body
  - include:
      file: bad.sql             # uses PG 14 BEGIN ATOMIC ...; END syntax for function body
```

* `good.sql`
```
--liquibase formatted sql
--changeset  good:bug  runAlways:true  endDelimiter:""  splitStatements:false  stripComments:false

create or replace function xyzxx ()
returns numeric
language sql
as $$
    select 1
$$

--rollback  DROP FUNCTION xyzxx
--
```

* `bad.sql`
```
--liquibase formatted sql
--changeset  bad:bug  runAlways:true  endDelimiter:""  splitStatements:false  stripComments:false

create or replace function xyzxx ()
returns numeric
language sql
begin atomic
    select 1;
end

--rollback  DROP FUNCTION xyzxx
--
```

## Actual Behavior

When I run liquibase I get the following log messages for `good.sql`:
```
[2021-11-04 18:35:27] FINE [liquibase.changelog] Running Changeset:good.sql::bug::good
[2021-11-04 18:35:27] FINE [liquibase.executor] Changeset good.sql::bug::good
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 0 row(s) affected
[2021-11-04 18:35:27] FINE [liquibase.changelog] Reading ChangeSet: good.sql::bug::good
[2021-11-04 18:35:27] FINE [liquibase.database] Executing Statement: create or replace function xyzxx ()
returns numeric
language sql
as $$
    select 1
$$

--
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 0 row(s) affected
[2021-11-04 18:35:27] INFO [liquibase.changelog] Custom SQL executed
[2021-11-04 18:35:27] INFO [liquibase.changelog] ChangeSet good.sql::bug::good ran successfully in 44ms
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 1 row(s) affected
```

But the following for `bad.sql`:
```
[2021-11-04 18:35:27] FINE [liquibase.changelog] Running Changeset:bad.sql::bug::bad
[2021-11-04 18:35:27] FINE [liquibase.executor] Changeset bad.sql::bug::bad
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 0 row(s) affected
[2021-11-04 18:35:27] FINE [liquibase.changelog] Reading ChangeSet: bad.sql::bug::bad
[2021-11-04 18:35:27] FINE [liquibase.database] Executing Statement: create or replace function xyzxx ()
returns numeric
language sql
begin atomic
    select 1;
end

--
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 0 row(s) affected
[2021-11-04 18:35:27] FINE [liquibase.executor] Release Database Lock
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 0 row(s) affected
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] INFO [liquibase.lockservice] Successfully released change log lock
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 0 row(s) affected
[2021-11-04 18:35:27] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2021-11-04 18:35:27] FINE [liquibase.executor] 0 row(s) affected
Unexpected error running Liquibase: Migration failed for change set bad.sql::bug::bad:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at end of input
  Position: 91 [Failed SQL: (0) create or replace function xyzxx ()
returns numeric
language sql
begin atomic
    select 1;
end

--]
For more information, please use the --logLevel flag
[2021-11-04 18:35:27] SEVERE [liquibase.integration] Unexpected error running Liquibase: Migration failed for change set bad.sql::bug::bad:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at end of input
  Position: 91 [Failed SQL: (0) create or replace function xyzxx ()
returns numeric
language sql
begin atomic
    select 1;
end

--]
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set bad.sql::bug::bad:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at end of input
  Position: 91 [Failed SQL: (0) create or replace function xyzxx ()
returns numeric
language sql
begin atomic
    select 1;
end

--]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:273)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:272)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2322)
	at liquibase.Liquibase.update(Liquibase.java:216)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1764)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:364)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.integration.commandline.Main$1.run(Main.java:363)
	at liquibase.integration.commandline.Main$1.run(Main.java:193)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:145)
	at liquibase.integration.commandline.Main.run(Main.java:193)
	at liquibase.integration.commandline.Main.main(Main.java:156)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set bad.sql::bug::bad:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at end of input
  Position: 91 [Failed SQL: (0) create or replace function xyzxx ()
returns numeric
language sql
begin atomic
    select 1;
end

--]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:672)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Scope.child(Scope.java:226)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
	... 26 more
Caused by: liquibase.exception.DatabaseException: ERROR: syntax error at end of input
  Position: 91 [Failed SQL: (0) create or replace function xyzxx ()
returns numeric
language sql
begin atomic
    select 1;
end

--]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1275)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1257)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	... 46 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 91
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
	... 51 more

```

## Expected/Desired Behavior

The script `bad.sql` will create the desired function as it does in PSQL. 
```
$ psql -X mmauger mmauger -f good.sql -c '\sf xyzxx'
CREATE FUNCTION
CREATE OR REPLACE FUNCTION public.xyzxx()
 RETURNS numeric
 LANGUAGE sql
AS $function$
    select 1
$function$

$ psql -X mmauger mmauger -f bad.sql -c '\sf xyzxx'
CREATE FUNCTION
CREATE OR REPLACE FUNCTION public.xyzxx()
 RETURNS numeric
 LANGUAGE sql
BEGIN ATOMIC
 SELECT 1;
END
```

## Additional Context

I can continue using the old syntax, but the lack of dependency tracking is going to become a challenge as the system is maintained and references to impacted objects are hidden and rely upon manual searching through the source code.

**Comment by molivasdat** [comment]
Thanks for letting us know about this issue @mmauger   We will add this to the list issues to process.

**Comment by nvoxland** [comment]
I've looked at this for a bit, and I'm not sure where the problem is. It almost seems like a postgresql JDBC driver issue, but I don't know enough about the new BEGIN ATOMIC syntax in 14 to know for sure. 

What I found was:

1. Liquibase is sending the SQL you specify to postgresql correctly
2. Even if I test making pretty generic JDBC calls with the create function call, it still fails with the not-very-helpful "syntax error and end of input" message.

For 2, I tried running:
```
            final Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:54322/lbadmindb", "lbadminuser", "LbRootPass1");
            final PreparedStatement preparedStatement = connection.prepareStatement("create or replace function xyzxx ()\n" +
                    "returns void\n" +
                    "language sql\n" +
                    "begin atomic\n" +
                    "select 1;" +
                    "end;");
            preparedStatement.execute();
```
which gave the same error, and that is well outside any liquibase code, even though it works fine in pgsql.

The "syntax error at end of input" seems to be based on what is in the begin atomic block, because it does work if I take out the `select 1;` from the above example.

But that is valid sql and I tried a bunch of other valid sql with and without ;'s and it always gave the same error.

**So, I'm wondering if it's a postgresql jdbc problem? But does anyone who knows more about the postgresql logic have other ideas on what it could be?**

**Comment by mmauger** [comment]
> The "syntax error at end of input" seems to be based on what is in the begin atomic block, because it does work if I take out the select 1; from the above example.

The `select 1` is invalid if the function "returns void" but what if its "return numeric"?

In the meantime, I'll confirm the JDBC conflict and submit a bug report to the PG team (unless you have done so already)

**Comment by ForJobsGit** [comment]
If you set the connection property "preferQueryMode" to "simple" or "extendedForPrepared", then the driver will not attempt to split the statement into multiple commands. It will get sent as-is and executed via the simple protocol rather than the parse / bind / execute extended protocol. I tried this out locally and confirmed that I'm able to create a SQL standard body procedure on PG 14.

https://postgrespro.ru/list/thread-id/2571450?ysclid=l779hi96793448119

**Comment by tati-qalified** [comment]
This is not an issue anymore in liquibase version 4.23.0

**Comment by filipelautert** [comment]
As confirmed by @tati-qalified, this is no longer an issue as of Liquibase 4.23.0. The PostgreSQL 14 `BEGIN ATOMIC` function syntax now works correctly.

Closing this out — if you're still hitting this on a recent version, feel free to re-open.
