### ISSUE TITLE
loadData and loadUpdateData + relativeToChangelogFile fails when using a logicalFilePath

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2281]
## Description

Like #1277 but with loadData and loadUpdateData

**Comment by smainz** [comment]
Doesn't #2073 fix this?
Maybe loadUpdateData is not covered.

**Comment by nvoxland** [comment]
I thought it should have, and it seemed the same as your #2060 PR so tried to combine the two.

I'll do a bit more testing to see what is missing/wrong.

**Comment by nvoxland** [comment]
I tried a variety of setups with 4.6.3 but was not able to reproduce issues.  I tried with both the CLI and with spring.

Could someone who is having problems give a sample directory structure and details on how they are running liquibase?

**Comment by lalo-mx** [comment]
@nvoxland Example with the sqlFile  file error [sample-liquidbase-4.6.2.zip](https://github.com/liquibase/liquibase/files/7764067/sample-liquidbase-4.6.2.zip). The error is not happening with 3.8.6.
 I just realized that you mentioned 4.6.3. Where could I get that version?

**Comment by joaoqalves** [comment]
I can reproduce this problem. I have both Liquibase in Spring and `liquibase-maven-plugin`. In the Spring one, it works without any problem. But when running `liquibase:status` on Maven it shows me it would need to run all the database migrations.

# Database CSV export

```csv
id,author,filename,dateexecuted,orderexecuted,exectype,md5sum,description,comments,tag,liquibase,contexts,labels,deployment_id
01-create-first-tables,joaoqalves,classpath:db/changelog/01-create-first-tables.xml,2022-01-04 16:25:56.878316,1,EXECUTED,8:7119a6ddd5a46c6747e3f1b823b09035,"createTable tableName=configuration; createTable tableName=shedlock; createTable tableName=user; addUniqueConstraint constraintName=uk_user_slug, tableName=user; createTable tableName=team; createIndex indexName=idx_team_marca_id, tableName=team; ...",,,3.10.2,,,1309956214
02-populate-init-data,operez,classpath:db/changelog/02-populate-init-data.xml,2022-01-04 16:25:58.371892,2,EXECUTED,8:3cff518d7668d8a48734e036277d2540,loadData tableName=user; loadData tableName=statistic_type; loadData tableName=week,,,3.10.2,,,1309956214
03-create-prizes-tables,joaoqalves,classpath:db/changelog/03-create-prizes-table.xml,2022-01-04 16:25:58.442448,3,EXECUTED,8:475d9c9f3ed3f8711f362344b8002993,createTable tableName=prize,,,3.10.2,,,1309956214
04-populate-prizes-data,joaoqalves,classpath:db/changelog/04-populate-prizes-data.xml,2022-01-04 16:25:58.899903,4,EXECUTED,8:6118ad1309a4161cc8604ae3829a2748,loadData tableName=prize,,,3.10.2,,,1309956214
05-add-new-statistic-type,joaoqalves,classpath:db/changelog/05-add-new-statistic-type.xml,2022-01-04 16:25:59.274246,5,EXECUTED,8:263f6121ce984a14fcda5eef1b1b39ae,loadData tableName=statistic_type,,,3.10.2,,,1309956214
06-skip-week,joaoqalves,classpath:db/changelog/06-skip-week.xml,2022-01-04 16:25:59.284239,6,EXECUTED,8:f2c0eab9e4dc2d85a38291d8c83826aa,addColumn tableName=week,,,3.10.2,,,1309956214
07-week-matches,joaoqalves,classpath:db/changelog/07-week-matches.xml,2022-01-04 16:25:59.309414,7,EXECUTED,8:3dd34cab61bc90d2c49f67fa19249f80,addColumn tableName=week,,,3.10.2,,,1309956214
08-substitutions-users,joaoqalves,db/changelog/08-substitutions-users.xml,2022-01-05 09:22:16.26741,8,EXECUTED,8:58ddb2cadae22c09e01ee2643b8617b9,addColumn tableName=user,,,4.6.2,,,1370936104
```


# POM file configurations

```xml
        <liquibase.sql.url>jdbc:postgresql://localhost:5432/lfm</liquibase.sql.url>
        <liquibase.sql.username>postgres</liquibase.sql.username>
        <liquibase.sql.password>password</liquibase.sql.password>
        <liquibase.sql.driver>org.postgresql.Driver</liquibase.sql.driver>
        <liquibase.sql.changelogfile>src/main/resources/db/liquibase-changelog.xml</liquibase.sql.changelogfile>

        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>4.6.2</version>
        </dependency>

<plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>4.6.2</version>
                <configuration>
                    <changeLogFile>${liquibase.sql.changelogfile}</changeLogFile>
                    <driver>${liquibase.sql.driver}</driver>
                    <url>${liquibase.sql.url}</url>
                    <username>${liquibase.sql.username}</username>
                    <password>${liquibase.sql.password}</password>
                    <verbose>true</verbose>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>update</goal>
                            <goal>status</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>${postgresql.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

# Result from Plugin execution

```
[INFO] Reading from databasechangelog
8 change sets have not been applied to postgres@jdbc:postgresql://localhost:5432/lfm
     src/main/resources/db/changelog/01-create-first-tables.xml::01-create-first-tables::joaoqalves
     src/main/resources/db/changelog/02-populate-init-data.xml::02-populate-init-data::operez
     src/main/resources/db/changelog/03-create-prizes-table.xml::03-create-prizes-tables::joaoqalves
     src/main/resources/db/changelog/04-populate-prizes-data.xml::04-populate-prizes-data::joaoqalves
     src/main/resources/db/changelog/05-add-new-statistic-type.xml::05-add-new-statistic-type::joaoqalves
     src/main/resources/db/changelog/06-skip-week.xml::06-skip-week::joaoqalves
     src/main/resources/db/changelog/07-week-matches.xml::07-week-matches::joaoqalves
     src/main/resources/db/changelog/08-substitutions-users.xml::08-substitutions-users::joaoqalves
```

# Liquibase changelog file

```xml
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

    <include file="changelog/01-create-first-tables.xml" relativeToChangelogFile="true"/>
    <include file="changelog/02-populate-init-data.xml" relativeToChangelogFile="true"/>
    <include file="changelog/03-create-prizes-table.xml" relativeToChangelogFile="true"/>
    <include file="changelog/04-populate-prizes-data.xml" relativeToChangelogFile="true" />
    <include file="changelog/05-add-new-statistic-type.xml" relativeToChangelogFile="true" />
    <include file="changelog/06-skip-week.xml" relativeToChangelogFile="true" />
    <include file="changelog/07-week-matches.xml" relativeToChangelogFile="true" />
    <include file="changelog/08-substitutions-users.xml" relativeToChangelogFile="true" />
</databaseChangeLog>
```

**Comment by nvoxland** [comment]
Thank you, @joaoqalves, I'll take another look.

**Comment by erik-meuwese-topicus** [comment]
I checked out tag v4.7.0 changed line liquibase.integration.spring.SpringResourceAccessor:146 in method getCompletePath(String relativeTo, String path). I replaced `resourceLoader` with `new DefaultResourceLoader(resourceLoader.getClassLoader())` then our liquibase 3.10.3 changeSets with `<sqlFile path="example.sql"  relativeToChangelogFile="true"/>` work without any changes.`

Our case:
Spring boot application 2.6.2 (latest spring-boot version)
In the application.yml
```
   liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
```
In db.changelog-master.xml located in src/main/resources/liquibase
`   <include file="example/example.xml" relativeToChangelogFile="true"/>`
In example.xml located in src/main/resources/liquibase/example
`   <sqlFile path="example.sql" relativeToChangelogFile="true"/>`
example.sql is located in src/main/resources/liquibase/example

The workaround and fix for liquibase seems to be the change of liquibase.integration.spring.SpringResourceAccessor:146 

The cause of the problem is Spring's AnnotationConfigReactiveWebServerApplicationContext which extends ReactiveWebServerApplicationContext which extends GenericReactiveWebApplicationContext which extends GenericApplicationContext which extends AbstractApplicationContext which extends DefaultResourceLoader and implements ResourceLoader

The DefaultResourceLoader.getResource() works with new DefaultResourceLoader(classloader). However GenericApplicationContext overrides this method. And in GenericApplicationContext.getResources() the resourceLoader is cast to ResourcePatternResolver.

ResourcePatternResolver implements ResourceLoader

I think the same ResourcePatternResolver is also used in getResource(...). It uses the same field ResourceLoader resourceLoader; as getResources(...) without the cast.

I was unclear which implementation of ResourcePatternResolver Spring injects in to this resourceLoader. Any way the resourceLoader is null while debugging so it calls super.getResource() which is DefaultResourceLoader.getResource()

When evaluating on my break point at liquibase.integration.spring.SpringResourceAccessor:146
```
((AnnotationConfigReactiveWebServerApplicationContext) resourceLoader).getResourcePatternResolver().getResource(relativeTo).exists(); // returns false
((AnnotationConfigReactiveWebServerApplicationContext) resourceLoader).getResource(relativeTo).exists(); // returns false
resourceLoader.getResource(relativeTo).exists(); // returns false
new DefaultResourceLoader(resourceLoader.getClassLoader()).getResource(relativeTo).exists(); // returns true
```

new DefaultResourceLoader().getResource() and AnnotationConfigReactiveWebServerApplicationContext.getResource() should be the same code.

The result of resourceLoader.getResource(relativeTo):
```
rootResource = {FilteredReactiveWebContextResource@13641} "ReactiveWebContext resource [liquibase/example/example.xml]"
 path = "liquibase/example/example.xml"
```
 
The result of new DefaultResourceLoader(ClassUtils.getDefaultClassLoader()).getResource(relativeTo):
```
rootResource = {DefaultResourceLoader$ClassPathContextResource@13656} "class path resource [liquibase/example/example.xml]"
 path = "liquibase/example/example.xml"
 classLoader = {RestartClassLoader@13647} 
 clazz = null
```
 
Spring filters the Resource returned by the getResource() from AnnotationConfigReactiveWebServerApplicationContext and wraps it as FilteredReactiveWebContextResource. The comment in FilteredReactiveWebContextResource: "Resource implementation that replaces the org.springframework.web.context.support.ServletContextResource in a reactive web application. exists() always returns false in order to avoid exposing the whole classpath in a non-servlet environment."


`Resource rootResource = new DefaultResourceLoader(resourceLoader.getClassLoader()).getResource(relativeTo)` might be a solution on liquibase.integration.spring.SpringResourceAccessor:146?

**Comment by up185014** [comment]
Hi team and @nvoxland 

Issue with 4.x version which i can't see related issue with 3.10.3 for the path given to changelog file.
when upgrade to 4.x below releative path issue coming. please resolve this issue, its thr since 4.x intial verison released.
have been asked many times to resolve it, but no solution given, and now same with 4.8.0. alos ,as vulnerabilities have come before 4.8.0 so has to move to 4.8.0 or latest but this relative path issue not leeting to move.

Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:99)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
        at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:224)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.Liquibase.runInScope(Liquibase.java:2405)
        at liquibase.Liquibase.update(Liquibase.java:211)
        at liquibase.Liquibase.update(Liquibase.java:197)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
        ... 55 more

**Comment by erik-meuwese-topicus** [comment]
https://github.com/liquibase/liquibase/pull/2758

**Comment by lynnjo** [comment]
I'm also facing the same problem since upgrading to the 4.x loads.  Our project runs liquibase in a docker.  We have no problems running any of the commands with Docker scripts, but many of our users need Singularity, which does not run as root.  All liquibase commands fail when Singularity wraps our docker image - "Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter."

This may not be new information, but I'm adding to let you know of other scenarios where this fails.  At this point I feel the only solution is to drop back to a 3.x version

**Comment by danilmalkin** [comment]
Worked for me in 4.12.0 but broke again in 4.13.0.

### Part of change log file
`<changeSet id="id-name" author="author-name">
        <sqlFile path="sqlFile.sql"
                 relativeToChangelogFile="true"
                 splitStatements="true"
                 stripComments="false"
                 endDelimiter="\nDELIM"
        />
    </changeSet>`

### Result from Plugin execution
`[java] Exception in thread "main" liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: java.io.IOException: The file sqlFile.sql was not found in the configured search path:
     [java]     - Spring resources
     [java] More locations can be added with the 'searchPath' parameter.
     [java]     at liquibase.Liquibase.runInScope(Liquibase.java:2405)
     [java]     at liquibase.Liquibase.update(Liquibase.java:208)
     [java]     at liquibase.Liquibase.update(Liquibase.java:194)
     [java]     at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314)
     [java]     at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
     [java]     at com.our.package.liquibase.LiquibaseVerifier.executeChangeLog(LiquibaseVerifier.java:146)
     [java]     at com.our.package.liquibase.LiquibaseVerifier.execute(LiquibaseVerifier.java:62)
     [java]     at com.our.package.Bootstrap.main(Bootstrap.java:76)
     [java] Caused by: liquibase.exception.UnexpectedLiquibaseException: java.io.IOException: The file sqlFile.sql was not found in the configured search path:
     [java]     - Spring resources
     [java] More locations can be added with the 'searchPath' parameter.
     [java]     at liquibase.change.AbstractSQLChange.generateCheckSum(AbstractSQLChange.java:203)
     [java]     at liquibase.changelog.ChangeSet.generateCheckSum(ChangeSet.java:312)
     [java]     at liquibase.sqlgenerator.core.UpdateChangeSetChecksumGenerator.generateSql(UpdateChangeSetChecksumGenerator.java:33)
     [java]     at liquibase.sqlgenerator.core.UpdateChangeSetChecksumGenerator.generateSql(UpdateChangeSetChecksumGenerator.java:16)
     [java]     at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
     [java]     at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:220)
     [java]     at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:105)
     [java]     at liquibase.executor.jvm.JdbcExecutor.access$400(JdbcExecutor.java:39)
     [java]     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:410)
     [java]     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
     [java]     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
     [java]     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
     [java]     at liquibase.changelog.StandardChangeLogHistoryService.replaceChecksum(StandardChangeLogHistoryService.java:376)
     [java]     at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:75)
     [java]     at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:300)
     [java]     at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1910)
     [java]     at liquibase.Liquibase.lambda$update$1(Liquibase.java:223)
     [java]     at liquibase.Scope.lambda$child$0(Scope.java:180)
     [java]     at liquibase.Scope.child(Scope.java:189)
     [java]     at liquibase.Scope.child(Scope.java:179)
     [java]     at liquibase.Scope.child(Scope.java:158)
     [java]     at liquibase.Liquibase.runInScope(Liquibase.java:2400)
     [java]     ... 7 more
     [java] Caused by: java.io.IOException: The file sqlFile.sql was not found in the configured search path:
     [java]     - Spring resources
     [java] More locations can be added with the 'searchPath' parameter.
     [java]     at liquibase.change.core.SQLFileChange.openSqlStream(SQLFileChange.java:130)
     [java]     at liquibase.change.AbstractSQLChange.generateCheckSum(AbstractSQLChange.java:189)
     [java]     ... 28 more
`

**Comment by danilmalkin** [comment]
Worked for me in 4.12.0 but broke again in 4.13.0.

### Part of change log file
```
<changeSet id="id" author="author">
        <sqlFile path="file.sql"
                 relativeToChangelogFile="true"
                 splitStatements="true"
                 stripComments="false"
                 endDelimiter="\nDELIM"
        />
    </changeSet>
```

### Result from Plugin execution
```
[java] Exception in thread "main" liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: java.io.IOException: The file file.sql was not found in the configured search path:
     [java]     - Spring resources
     [java] More locations can be added with the 'searchPath' parameter.
     [java]     at liquibase.Liquibase.runInScope(Liquibase.java:2405)
     [java]     at liquibase.Liquibase.update(Liquibase.java:208)
     [java]     at liquibase.Liquibase.update(Liquibase.java:194)
     [java]     at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314)
     [java]     at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
     [java]     at com.our.package.liquibase.LiquibaseVerifier.executeChangeLog(LiquibaseVerifier.java:146)
     [java]     at com.our.package.liquibase.LiquibaseVerifier.execute(LiquibaseVerifier.java:62)
     [java]     at com.our.package.Bootstrap.main(Bootstrap.java:76)
     [java] Caused by: liquibase.exception.UnexpectedLiquibaseException: java.io.IOException: The file file.sql was not found in the configured search path:
     [java]     - Spring resources
     [java] More locations can be added with the 'searchPath' parameter.
     [java]     at liquibase.change.AbstractSQLChange.generateCheckSum(AbstractSQLChange.java:203)
     [java]     at liquibase.changelog.ChangeSet.generateCheckSum(ChangeSet.java:312)
     [java]     at liquibase.sqlgenerator.core.UpdateChangeSetChecksumGenerator.generateSql(UpdateChangeSetChecksumGenerator.java:33)
     [java]     at liquibase.sqlgenerator.core.UpdateChangeSetChecksumGenerator.generateSql(UpdateChangeSetChecksumGenerator.java:16)
     [java]     at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
     [java]     at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:220)
     [java]     at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:105)
     [java]     at liquibase.executor.jvm.JdbcExecutor.access$400(JdbcExecutor.java:39)
     [java]     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:410)
     [java]     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
     [java]     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
     [java]     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
     [java]     at liquibase.changelog.StandardChangeLogHistoryService.replaceChecksum(StandardChangeLogHistoryService.java:376)
     [java]     at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:75)
     [java]     at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:300)
     [java]     at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1910)
     [java]     at liquibase.Liquibase.lambda$update$1(Liquibase.java:223)
     [java]     at liquibase.Scope.lambda$child$0(Scope.java:180)
     [java]     at liquibase.Scope.child(Scope.java:189)
     [java]     at liquibase.Scope.child(Scope.java:179)
     [java]     at liquibase.Scope.child(Scope.java:158)
     [java]     at liquibase.Liquibase.runInScope(Liquibase.java:2400)
     [java]     ... 7 more
     [java] Caused by: java.io.IOException: The file file.sql was not found in the configured search path:
     [java]     - Spring resources
     [java] More locations can be added with the 'searchPath' parameter.
     [java]     at liquibase.change.core.SQLFileChange.openSqlStream(SQLFileChange.java:130)
     [java]     at liquibase.change.AbstractSQLChange.generateCheckSum(AbstractSQLChange.java:189)
     [java]     ... 28 more
```

### Package Structure
```
├── pom.xml
├── src
│   ├── assembly
│   │   └── assembly.xml
│   └── main
│       └── resources
│           ├── changelog.xml
│           ├── init.sql
│           └── file.sql
```

**Comment by danilmalkin** [comment]
> @nvoxland wondering if the searchPath from 4.13 could be used to resolve whatever @danilmalkin is facing?

@kataggart Yeah, I forgot to mention it. I used searchPath and it worked fine. But it looks like a workaround not a solution
Updated original comment

**Comment by kataggart** [comment]
@danilmalkin what do you mean by using searchPath is a workaround and not a solution?

**Comment by danilmalkin** [comment]
@kataggart I debugged SpringResourceAccessor.
Issue for me in [this line](https://github.com/liquibase/liquibase/blob/d2d634f7987a34f0ff1153a14a807a7bb02db611/liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java#L147)
We don't have a "/" prefix before our files. In this case, the regex doesn't match our `relativeTo="changeLog.xml"` and doesn't replace it. I tried with regex `/?[^/]+$` and it works fine.

**Comment by danilmalkin** [comment]
after releasing the fix in 4.16.0 works for me

**Comment by twittwer** [comment]
It worked in 4.16.1, but after update to 4.17.0 it's broken again.
@uwe42

**Comment by vvalencia-cl** [comment]
The version 4.17.2 it's still broken.
This affects the migration to Spring Boot 3.0.1, as it is the version chosen in the dependency management.
https://docs.spring.io/spring-boot/docs/3.0.1/reference/html/dependency-versions.html

**Comment by vvalencia-cl** [comment]
This issue seems to be fixed in 4.19.0, with #3355
I've have updated it in my Spring Boot 3.0.1 and it works fine

**Comment by nbrugger-tgm** [comment]
Also `java.io.FileNotFoundException: JAR entry db/1.4.0/../init_objects/procedures.sql not found in /<absolutePath>/build/libs/core-1.15.0-dev.jar` appears now if i am using relativePath (`4.19.0`)

is `..` in relative paths (using jars) not allowed? Because the file `db/init_objects/procedures.sql` exists in the jar

**Comment by xak2000** [comment]
Most reports here are about `<include>` tag.

I had similar problem with `<loadUpdateData>` tag.

With these file locations:
```
src/main/resources/db/changelog/db.changelog-2.0.xml
src/main/resources/db/changelog/data/country.csv
```

And `db.changelog-2.0.xml` contains:

```
<loadUpdateData tableName="country" primaryKey="id" file="data/country.csv" relativeToChangelogFile="true">
```

With Liquibase **4.17.2** (current default in the latest spring-boot v3.0.5) I had the following error:

```
java.io.FileNotFoundException: C:\Users\me\project-name\target\classes\db\changelog\..\data\country.csv
```

For some reason `..\` was added to the path making it incorrect as there is no `db\data\country.csv`.

After manually overriding Liquibase version to **4.21.1** (the latest at the moment) the problem is fixed. I'm not sure what commit exactly fixed this, but this information could be useful for next people who have the same problem.

To manually override Liquibase in a spring-boot project it's enough to add `<liquibase.version>4.21.1</liquibase.version>` into the `<properties>` section.

**Comment by sachin234s** [comment]
Hi Team,

Recently we had updated the liquibase library from 4.8.0 to 4.21.1 and we are noticing the below issue when we are executing liquibase.update on a single changeset which is present externally

Caused by: liquibase.exception.DatabaseException: Error creating configured table through liquibase, error liquibase.exception.ChangeLogParseException: The file **/var/opt/SIU/tracing_data_15.xml** was not found in the configured search path:
- /opt/SIU/plugins/com.hp.usage.migratedb_10.11.0/commons-text-1.10.0.jar
- /opt/SIU/plugins/com.hp.usage.migratedb_10.11.0/derbyclient-10.15.2.0.jar
- /opt/SIU/plugins/com.hp.usage.migratedb_10.11.0/extension-1.0.1-SNAPSHOT-patched.jar
- /opt/SIU/plugins/com.hp.usage.migratedb_10.11.0/liquibase-core-4.21.1.jar
- /opt/SIU/plugins/com.hp.usage.migratedb_10.11.0/migratedb.jar
- /opt/SIU/plugins/com.hp.usage.migratedb_10.11.0/opencsv-5.7.1.jar
- /opt/SIU/plugins/com.hp.usage.migratedb_10.11.0/timesten-types-1.0.1-SNAPSHOT-patched.jar

The code is simple liquibase.update below which used to work with earlier version of library

conn = _dataSource.getConnection();
Database database = DatabaseFactory
.getInstance()
.findCorrectDatabaseImplementation(new JdbcConnection(conn));
ResourceAccessor resourceAccessor = new StreamResourceAccessor(Files.readString(path));
liquibase = new Liquibase(tracingFilePath, resourceAccessor, database);
liquibase.validate();
liquibase.update(CONTEXT);

could you please help me to proceed?

**Comment by rivancic** [comment]
@xak2000 I'm having exact same issue nested changelog relative path was suddenly suffixed with "../". Though at first we tried to fix it with again specifying the child part of the path manual upgrading to new version is the way to go even though now version isn't aligned with our SpringBoot framework version.
Thanks you saved my day!

**Comment by slogic** [comment]
On 4.21.1 still not fixed. I even tried to use searchPath to "patch" it but with no luck:

`The file C:/Work/IdeaProjects/okr-skif/modules/skif-migration/skif-common-migration-pg/target/database/changelog/changelog-master-ci.xml was not found in the configured search path:

    - C:\Work\IdeaProjects\okr-skif\modules\skif-migration\skif-common-migration-pg\target\database\changelog
    - C:\Work\IdeaProjects\okr-skif\modules\skif-migration\skif-common-migration-pg\target\database\changelog\base
    - C:\Work\IdeaProjects\okr-skif\modules\skif-migration\skif-common-migration-pg\target\database\sql`

PS. Run via liquibase plugin from IDE.

**Comment by lukasz-cpu** [comment]
Hello, 

I have the same problem with this. After upgrade I have error:

Unexpected error running Liquibase: java.io.IOException:
Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.

Problem was not happening before....

**Comment by MalloD12** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!

**Comment by MalloD12** [comment]
Additionally, we have recently merged PRs related to these topics (`relativeToChangelogfile` and `logicalFilepath`). As mentioned before, please feel free to open a new issue.

Thanks,
Daniel.
