### ISSUE TITLE
includeAll cannot process directories in embedded jar files

### ISSUE THREAD

**Issue by hayeskl** [liquibase/liquibase#2352]
## Environment
Grails 5.0.3

**Liquibase Version**:
4.6.2

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Core

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:
Mac Monterey 12.1

## Description

A clear and concise description of the issue being addressed.
When running the application as a jar file the migrations are not found.  The following error is returned:

liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'current/'
        at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:553)
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:409)
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:318)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
        ... 96 more
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'current/'
        at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:544)
        ... 99 more

## Steps To Reproduce

Package migrations into jar file relative to changeLogFile
Build a spring bootable jar for application and include the jar with migrations
run the spring bootable jar

## Actual Behavior
The above exception is thrown because ClassLoaderResourceAccessor cannot parse the resource path:
jar:file:/Users/khayes/griffin.git/trifleet/build/libs/trifleet-12.0.0.jar!/BOOT-INF/lib/common-12.0.0-plain.jar!/current/

## Expected/Desired Behavior
Migrations should be loaded from the embedded jar file

**Comment by hayeskl** [comment]
This issue is fixed with https://github.com/liquibase/liquibase/pull/2353

**Comment by hayeskl** [comment]
I've confirmed that this issue still exists with liquibase 4.24.0.
