### ISSUE TITLE
Not working includeObjects in properties file

### ISSUE THREAD

**Issue by abrayko** [liquibase/liquibase#2393]
## Environment

**Liquibase Version**: 4.7.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Oracle 19

**Operating System Type & Version**: docker

## Description

Exception on generateChangeLog 

## Steps To Reproduce

liquibase.properties:

```
url: jdbc:oracle:thin:@...
classpath: /liquibase/changelog
includeSchema: true
schemas: EPC
includeObjects: "table:TPRODUCT_SPEC_*"
```

CLI command:

`docker run --rm --network=host -v /home/art/art_work/_projects/epc/db_ora/liquibase:/liquibase/changelog liquibase/liquibase --defaultsFile=/liquibase/changelog/config/stage/liquibase.properties --log-level=INFO --changeLogFile=/liquibase/changelog/changelog/changelog.xml generateChangeLog`

## Actual Behavior

```
Liquibase Version: 4.7.0
Liquibase Community 4.7.0 by Liquibase
[2022-01-21 08:46:22] WARNING [liquibase.configuration] Potentially ignored key(s) in file /liquibase/changelog/config/stage/liquibase.properties
 - 'liquibaseSchemaName'
[2022-01-21 08:46:23] SEVERE [liquibase.integration] java.lang.ClassNotFoundException: liquibase.structure.core."table
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: liquibase.structure.core."table
	at liquibase.command.CommandScope.execute(CommandScope.java:163)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: liquibase.structure.core."table
	at liquibase.integration.commandline.Main$1.run(Main.java:443)
	at liquibase.integration.commandline.Main$1.run(Main.java:221)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:221)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:157)
	... 14 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: java.lang.ClassNotFoundException: liquibase.structure.core."table
	at liquibase.diff.output.StandardObjectChangeFilter.parseFilter(StandardObjectChangeFilter.java:57)
	at liquibase.diff.output.StandardObjectChangeFilter.<init>(StandardObjectChangeFilter.java:34)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1563)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.integration.commandline.Main$1.run(Main.java:397)
	... 20 more
Caused by: java.lang.ClassNotFoundException: liquibase.structure.core."table
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at liquibase.diff.output.StandardObjectChangeFilter.parseFilter(StandardObjectChangeFilter.java:53)
	... 28 more
```

**Comment by kataggart** [comment]
Thanks for this. Have you tried removing the quotes from 
"table:TPRODUCT_SPEC_*"

?

**Comment by abrayko** [comment]
Works without quotes
