### ISSUE TITLE
Slow NetUtil.getLocalHostName in Windows WSL2

### ISSUE THREAD

**Issue by maio** [liquibase/liquibase#2440]
## Environment

**Liquibase Version**: org.liquibase:liquibase-core:4.7.1

**Operating System Type & Version**: Windows 11 / WSL2

**Java Version**: 17

## Description

I noticed that application startup with Liquibase takes more than it used to. After some investigation I found out
that time is spent in `LockDatabaseChangeLogGenerator` - more specifically in `NetUtil.getLocalHostName()` call.

This call takes 1+ seconds to finish.

## Steps To Reproduce

Call  `NetUtil.getLocalHostName()`.

## Actual Behavior

Call takes more than one second to finish and returns incorrect local hostname (seems like some internal WSL IP address).

## Expected/Desired Behavior

Call finishes in few milliseconds with correct hostname. 

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/18138/151697341-c6e46e85-4c58-411e-89e1-2bdaa1b2aab1.png)

## Additional Context

BTW `InetAddress.getLocalHost().hostName` from JDK seems to work fine (it's fast and returns correct hostname).

**Comment by estigma88** [comment]
This is happening to me in the following environment:

**Spring Boot**: 2.7.1
**Liquibase Version**: org.liquibase:liquibase-core:4.9.1
**Operating System Type & Version**: Ubuntu 20.04.5 LTS
**Java Version**: 17

The following are the Spring Boot logs, it takes more than 10 seconds to finish.

```
2023-02-07 23:02:24.294 DEBUG [ingress-manager,,] 21674 --- [           main] liquibase.servicelocator                 : Loaded liquibase.sqlgenerator.SqlGenerator instance liquibase.sqlgenerator.core.InsertOrUpdateGeneratorSybaseASA
2023-02-07 23:02:24.295 DEBUG [ingress-manager,,] 21674 --- [           main] liquibase.servicelocator                 : Loaded liquibase.sqlgenerator.SqlGenerator instance liquibase.sqlgenerator.core.InsertSetGenerator
2023-02-07 23:02:34.304 DEBUG [ingress-manager,,] 21674 --- [           main] liquibase.servicelocator                 : Loaded liquibase.sqlgenerator.SqlGenerator instance liquibase.sqlgenerator.core.LockDatabaseChangeLogGenerator
2023-02-07 23:02:34.305 DEBUG [ingress-manager,,] 21674 --- [           main] liquibase.servicelocator                 : Loaded liquibase.sqlgenerator.SqlGenerator instance liquibase.sqlgenerator.core.MarkChangeSetRanGenerator
```

Also, I executed the same code as @maio and this was the result:

![image](https://user-images.githubusercontent.com/27821251/217433504-f70a8fbd-5f6e-4abe-9272-92c77ced7a12.png)

This directly affects the Spring Boot start-up time, including integration tests where we start the app multiple times in a test suite.

**Comment by pelusanchez** [comment]
This is also happening in Mac OS Ventura 13.1.

Spring Boot: 2.7.0
Liquibase Version: org.liquibase:liquibase-core:4.9.1
Operating System Type & Version: Mac OS Ventura 13.1
Java Version: 17

As a workaround, this is happening if many network interfaces exists (From a VPN). Liquibase is picking one of the VPN interfaces and trying to resolve the hostname. If the VPN is disabled, this does not happen anymore.

**Comment by bpg168** [comment]
This issue is also happening in my laptop, but goes away when I disconnect from my home Wifi.
It seems that when connected to my home wifi it is falling on to resolving the IPv6 address. In my case I am using an H2 in-memory database, so disconnecting from wifi works for me, as the database anyway in localhost.

OS: Ubuntu 23.10 (on Lenovo IdeaPad 5 15ITL05 Ua)
Spring: 3.2.4

Stack trace when hangs (truncating the springboot frames,
```
"main" #1 prio=5 os_prio=0 cpu=2605.16ms elapsed=4.23s tid=0x0000739db8025580 nid=0x4849a runnable  [0x0000739dbdf10000]
   java.lang.Thread.State: RUNNABLE
        at java.net.Inet6AddressImpl.getHostByAddr(java.base@17.0.8/Native Method)
        at java.net.InetAddress$PlatformNameService.getHostByAddr(java.base@17.0.8/InetAddress.java:940)
        at java.net.InetAddress.getHostFromNameService(java.base@17.0.8/InetAddress.java:662)
        at java.net.InetAddress.getHostName(java.base@17.0.8/InetAddress.java:605)
        at java.net.InetAddress.getHostName(java.base@17.0.8/InetAddress.java:577)
        at liquibase.util.NetUtil.getLocalHostName(NetUtil.java:79)
        at liquibase.sqlgenerator.core.LockDatabaseChangeLogGenerator.<clinit>(LockDatabaseChangeLogGenerator.java:30)
```

sample code reproducible
```
public static void main(String[] args) throws UnknownHostException {
    System.out.println(new Date());
    NetUtil.getLocalHostName();
    System.out.println(new Date());
}
```

**Comment by aaronlinv** [comment]
**Liquibase Version:** 4.27.0
**Operating System:** macOS 15.1
**Java Version:** Azul Zulu 17.0.17

I encountered a similar issue: when using the public DNS `114.114.114.114`, `NetUtil.getLocalHostName()` hangs for about 30 seconds

After checking [NetUtil.java](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/util/NetUtil.java#L21), I found that:

`NetUtil.getLocalHostName()` iterates over local network interfaces to get IP addresses and calls `InetAddress.getHostName()` to perform a reverse lookup on private IPs (such as `192.168.10.2`)

Most public DNS servers (like Alibaba DNS `223.5.5.5` or Google DNS) return **NXDOMAIN** when they can’t resolve a private IP,
but `114.114.114.114` gives no response, causing the native Java reverse lookup to block

```sh
# Duration: 0.228s
nslookup 192.168.10.2 223.5.5.5
Server:		223.5.5.5
Address:	223.5.5.5#53

** server can't find 2.10.168.192.in-addr.arpa: NXDOMAIN
```

```sh
# Duration: 15.137s
nslookup 192.168.10.2 114.114.114.114
;; connection timed out; no servers could be reached
```

As a result, Liquibase initialization speed is affected by the performance of DNS reverse lookups
**The most effective solution for now is to use a DNS server that responds faster to reverse queries**
