### ISSUE TITLE
Getting NoSuchMethodError: ... 'hibernate.id.enhanced.SequenceStyleGenerator.generatorKey()'

### ISSUE THREAD

**Issue by JanCizmar** [liquibase/liquibase#2456]
## Environment

**Liquibase Version**:
4.7.1
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
liquibase.gradle 2.0.4
spring boot 2.6.2
hibernate 5.6.3

**Database Vendor & Version**:
PostgreSQL
**Operating System Type & Version**:
Mac

## Description
When I run diffChangelog gradle task I am getting this output error:

```
[2022-02-02 16:38:26] SEVERE [liquibase.integration] Unexpected error running Liquibase: 'java.lang.Object org.hibernate.id.enhanced.SequenceStyleGenerator.generatorKey()'
java.lang.NoSuchMethodError: 'java.lang.Object org.hibernate.id.enhanced.SequenceStyleGenerator.generatorKey()'
	at liquibase.ext.hibernate.snapshot.SequenceSnapshotGenerator.addTo(SequenceSnapshotGenerator.java:63)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:82)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:188)
	at liquibase.command.core.InternalDiffCommandStep.createReferenceSnapshot(InternalDiffCommandStep.java:188)
	at liquibase.command.core.InternalDiffCommandStep.createDiffResult(InternalDiffCommandStep.java:98)
	at liquibase.command.core.InternalDiffChangelogCommandStep.run(InternalDiffChangelogCommandStep.java:49)
	at liquibase.command.CommandScope.execute(CommandScope.java:157)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:218)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1601)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.integration.commandline.Main$1.run(Main.java:397)
	at liquibase.integration.commandline.Main$1.run(Main.java:221)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:221)
	at liquibase.integration.commandline.Main.main(Main.java:164)
```

## Additional Context
It seems like there is an incompatibility between hibernate 5.6.3 and liquibase 4.7.1.
There is also this question on stack owerflow:
https://stackoverflow.com/questions/70628527/liquibase-hibernate-missing-sequencestylegenerator-generatorkey-error

**Comment by famod** [comment]
That method was removed here: https://github.com/hibernate/hibernate-orm/commit/9a14200ca2028f005cd129989004bfef1e52c843#diff-ca1cb640560157e9e605374e6f9c94bb061bd20e0e185fcec9abe6ea88f3cbd6

Hi @yrodiere! FYI ⬆️, not sure that change was meant to be as "breaking" as it is now for Liquibase.

**Comment by yrodiere** [comment]
@famod It wasn't. TBH that particular ticket was hard to implement, because it meant changing lots of files. We're discovering new incompatibilities by the day; it seems I did very crappy work. The irony is that those (extensive) changes were for the benefit of Quarkus users...

I'll add the method back if I can. Is there an easy way to reproduce the problem, so I can check there aren't other problematic backwards-incompatible changes? I wasn't aware liquibase was digging deep into the internals of ORM like this...

**Comment by JanCizmar** [comment]
> Is there an easy way to reproduce the problem, so I can check there aren't other problematic backwards-incompatible changes?
It's in our [main](https://github.com/tolgee/server). If you run `./gradlew diffChangelog` you would be maybe able to reproduce it. (If you're lucky) 😀

**Comment by yrodiere** [comment]
Thanks.

Tracking the problem on the ORM side as https://hibernate.atlassian.net/browse/HHH-15069

**Comment by yamennassif** [comment]
although this is fixed (as it seems) how can we integrate it on our project? i can't see the fix when i build my gradle

**Comment by yrodiere** [comment]
You'll need to upgrade to Hibernate ORM 5.6.6.Final, which hasn't been released yet. I don't know when it will be released, probably in the next few weeks.

**Comment by JanCizmar** [comment]
Hey! I solved it by downgrading Spring to 2.5.10, so I don't know. But I guess it's fixed. 😄
