### ISSUE TITLE
Snowflake: snapshot fails in GetViewDefinitionStatement when a materialized view exists

### ISSUE THREAD

**Issue by excelosaurus** [liquibase/liquibase#2548]
### Overview
On Snowflake, the snapshot command fails with
`GRAVE [liquibase.integration] Expected single row from liquibase.statement.core.GetViewDefinitionStatement@xxxxxxx but got 0`
whenever there exists a materialized view in a schema.

### Repro
In Snowflake, ensure at least one materialized view exists in the schema to snapshot.
Example:
```
create or replace materialized view test_mv
    as
    select someColumn1, someColumn2 from someSchema.someTable;
```

liquibase.properties file:
```
url: jdbc:snowflake://xxxxxx.aws.snowflakecomputing.com/?db=someDatabase&role=someRole&warehouse=someWarehouse&authenticator=externalbrowser
liquibaseSchemaName: LIQUIBASE
defaultCatalogName: someDatabase
defaultSchemaName: someSchema
driver: net.snowflake.client.jdbc.SnowflakeDriver
classpath: C:/liquibase-4.7.1/lib/liquibase-snowflake-4.7.1.jar;C:/liquibase-4.7.1/lib/snowflake-jdbc-3.13.14.jar
liquibase.hub.mode=off
```
Command line:
`liquibase --outputFile=snapshot.json --username=xxx snapshot --snapshotFormat=json --logLevel=FINE`

Output:
```
[2022-02-15 16:36:35] GRAVE [liquibase.integration] Expected single row from liquibase.statement.core.GetViewDefinitionStatement@xxxxxxxx but got 0
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Error getting jdbc:snowflake://xxx.aws.snowflakecomputing.com:443/ view with liquibase.statement.core.GetViewDefinitionStatement@xxxxxx
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
```

### Possible Cause
Snowflake lists materialized views in `INFORMATION_SCHEMA.TABLES`, with field `TABLE_TYPE = 'MATERIALIZED VIEW'`. Liquibase possibly queries `INFORMATION_SCHEMA.VIEWS` and finds nothing.

**Comment by FBurguer** [comment]
I got the same error after trying to use `liquibase drop-all`.
