### ISSUE TITLE
loadData file case change on Windows causes checksum to fail

### ISSUE THREAD

**Issue by firehooper** [liquibase/liquibase#2601]
## Environment
Windows Adoptium JRE 11 32bit
**Liquibase Version**:
4.7.1
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI
**Liquibase Extension(s) & Version**: 
N/A
**Database Vendor & Version**:
MSSQL 13.0.6300.2
**Operating System Type & Version**:
Windows 10 Pro 64bit

## Description
We use loadData in many changeSets to configure feature toggle sets per client.  We recently upgraded to 4.7.1 from 3.0.7 and started getting failing changesets because of a case change from the underlying file compared to the xml attribute file under loadData .  The same changSet's did not produce these error in 3.0.7.  These are guarded with `<preConditions onFail="CONTINUE" onFailMessage="... (its ok!)">` .  

We tried some of the bypass mechanisms and none seem to be able to skip this validation.  If a precondition fails then it seems this should disregard loadData during validation, but I guess it probably executes those after the checkSum in the current implementation? Maybe allowing overriding the checkSum for a changeSet would work? Would you recommend building this into a CustomTaskChange or maybe adding additional attributes or modify existing to suppress?

```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.7.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">
	<changeSet author="me" id="1" runOnChange="true" runAlways="true" onValidationFail="MARK_RAN" failOnError="false" ignore="true">
		<preConditions onFail="CONTINUE" onFailMessage="... (its ok!)">
			<sqlCheck expectedResult="1">select 0</sqlCheck>
		</preConditions>
		<comment>Replace all data in TEST_TABLE</comment>
		<delete tableName="TEST_TABLE"/>
		<!-- can we add an attribute for case insensitive or allow not exists or suppress checksum of file or ...? -->
		<loadData tableName="TEST_TABLE" file="./csv/i-dont-exist-or-wrong-case-on-windows.csv" quotchar="'">
			<column name="Key" type="STRING"/>
			<column name="Value" type="STRING"/>
		</loadData>
	</changeSet>
</databaseChangeLog>
```

## Steps To Reproduce

```
docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Testing123#" -p 1433:1433 mcr.microsoft.com/mssql/server:2019-latest ms-sql-server
./liquibase.bat --changeLogFile=changelog.xml --logLevel=info --hub-mode=off --logFile=liquibase.log --classpath=sqljdbc4.jar --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver --url=jdbc:sqlserver://localhost --username=sa --password="Testing123#" migrate
```

[reproduce_csv_missing.zip](https://github.com/liquibase/liquibase/files/8186964/reproduce_csv_missing.zip)

## Actual Behavior
```liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: File './csv/i-dont-exist-or-wrong-case-on-windows.csv' not found
	at liquibase.command.CommandScope.execute(CommandScope.java:163)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: File './csv/i-dont-exist-or-wrong-case-on-windows.csv' not found
	at liquibase.integration.commandline.Main$1.run(Main.java:443)
	at liquibase.integration.commandline.Main$1.run(Main.java:221)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:221)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:157)
	... 14 more
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: File './csv/i-dont-exist-or-wrong-case-on-windows.csv' not found
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:289)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:231)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2405)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1871)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.integration.commandline.Main$1.run(Main.java:397)
	... 20 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: File './csv/i-dont-exist-or-wrong-case-on-windows.csv' not found
	at liquibase.change.core.LoadDataChange.generateCheckSum(LoadDataChange.java:860)
	at liquibase.changelog.ChangeSet.generateCheckSum(ChangeSet.java:306)
	at liquibase.changelog.ChangeSet.toString(ChangeSet.java:909)
	at liquibase.changelog.ChangeLogIterator.createKey(ChangeLogIterator.java:178)
	at liquibase.changelog.ChangeLogIterator.alreadySaw(ChangeLogIterator.java:186)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:95)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Scope.child(Scope.java:247)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
	... 36 more
```

## Expected/Desired Behavior
Allow CSV files that will not be used in a changeSet to either not exist (and/or be case sensitive on Windows) via an error override or loadData attribute.

## Additional Context
This is run in many environments via CLI that we cannot control.  I understand providing errors up front and validation against the checkSum early probably prevents some errors for other folks, but it would be useful for us to not validate the CSV file existence.

**Comment by tati-qalified** [comment]
Hi @firehooper, sorry for the late reply.

The way Liquibase handles changesets is as follows: it parses the code into SQL statements, generates the checksums, and then tries to execute them. The file specified in loadData is needed in order to generate the checksum value, and it is case sensitive, though it might not have been so in version 3.0.7.
Preconditions are checked when executing the changes.

You can see this when you run `update-sql` with a correct file name in loadData and the precondition you specified in your code, 
```
<preConditions onFail="CONTINUE" onFailMessage="... (its ok!)">
	<sqlCheck expectedResult="1">select 0</sqlCheck>
</preConditions>
```
The changeset will be parsed into SQL statements, and there will be no errors because of the failing precondition.

You are welcome to download the Liquibase source code and modify it so that it behaves in the way you'd prefer, but we will not be changing it at this time.

Thank you,
Tatiana
