### ISSUE TITLE
LONG columns in Oracle dictionary tables causing “Stream has already been closed” Exception

### ISSUE THREAD

**Issue by ponziani** [liquibase/liquibase#2613]
## Environment

**Liquibase Version**: 3.8.0 (probably 4.8.0 as well)

**Liquibase Integration & Version**: java

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Oracle

**Operating System Type & Version**: Linux Ubuntu & Windows

## Description

While executing some changeSets an SQLexception might get thrown.

## Steps To Reproduce

Behaviour is not reproducable, but does happen regularly.

## Actual Behavior

`
Caused by: java.sql.SQLException: Stream has already been closed
    at oracle.jdbc.driver.LongAccessor.getBytesInternal(LongAccessor.java:129)
    at oracle.jdbc.driver.Accessor.getBytes(Accessor.java:940)
    at oracle.jdbc.driver.LongAccessor.getString(LongAccessor.java:156)
    at oracle.jdbc.driver.CharCommonAccessor.getObject(CharCommonAccessor.java:616)
    at oracle.jdbc.driver.GeneratedStatement.getObject(GeneratedStatement.java:235)
    at oracle.jdbc.driver.GeneratedScrollableResultSet.getObject(GeneratedScrollableResultSet.java:306)
    at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:351)
    at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:351)
    at liquibase.util.JdbcUtils.getResultSetValue(JdbcUtils.java:80)
    at liquibase.executor.jvm.ColumnMapRowMapper.getColumnValue(ColumnMapRowMapper.java:73)
    at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$GetNotNullConstraintsResultSetCache$1.getColumnValue(JdbcDatabaseSnapshot.java:934)
    at liquibase.executor.jvm.ColumnMapRowMapper.mapRow(ColumnMapRowMapper.java:35)
    at liquibase.executor.jvm.RowMapperNotNullConstraintsResultSetExtractor.extractData(RowMapperNotNullConstraintsResultSetExtractor.java:43)
    at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$GetNotNullConstraintsResultSetCache.extract(JdbcDatabaseSnapshot.java:940)
    at liquibase.snapshot.ResultSetCache$ResultSetExtractor.cachedExecuteAndExtract(ResultSetCache.java:295)
    at liquibase.snapshot.ResultSetCache$ResultSetExtractor.executeAndExtract(ResultSetCache.java:274)
    at liquibase.snapshot.ResultSetCache$ResultSetExtractor.executeAndExtract(ResultSetCache.java:266)
    at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$GetNotNullConstraintsResultSetCache.oracleQuery(JdbcDatabaseSnapshot.java:917)
    at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$GetNotNullConstraintsResultSetCache.fastFetchQuery(JdbcDatabaseSnapshot.java:872)
    at liquibase.snapshot.ResultSetCache$SingleResultSetExtractor.fastFetch(ResultSetCache.java:393)
    at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:76)
`

## Expected/Desired Behavior

No more exception.

## Additional Context

Some resources on the web 

* https://blog.jooq.org/oracle-long-and-long-raw-causing-stream-has-already-been-closed-exception/
* https://stackoverflow.com/questions/10174951/hibernate-custom-type-to-avoid-caused-by-java-sql-sqlexception-stream-has-al

The column SEARCH_CONDITION from table USER_CONSTRAINTS and the column DATA_DEFAULT from ALL_TAB_COLS are both LONG columns.

After I removed DATA_DEFAULT from the code and replaced the value of SEARCH_CONDITION by NULL, the problem has gone away. However I assume that breaks some other functionality.

**Comment by kataggart** [comment]
Thanks for the details @ponziani we will take a look.

**Comment by ponziani** [comment]
@kataggart any feedback on this ?

**Comment by kataggart** [comment]
@ponziani it's in the queue for development, but we unfortunately have not been able to get to it yet -- we, of course, welcome any PRs from the Community to address the issue as well. That always helps things move along quicker. Thanks!

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
