### ISSUE TITLE
Stackoverflow occurred (difficult to diagnose) when accidentally leaving .sql suffix off file.

### ISSUE THREAD

**Issue by jpz** [liquibase/liquibase#2621]
## Environment

Linux

**Liquibase Version**:  4.8.0

**Liquibase Integration & Version**:  CLI 

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:  postgres

**Operating System Type & Version**:   Linux

## Description

I have been maintaining a set of SQL change logs, I failed to put an ".sql" suffix on one of the change logs.  Note the topmost change log was specified like this:

```
databaseChangeLog:
  - includeAll:
      path: changelogs
```

which recursively searches the "./changelogs/" directory.  

I placed a "--liquibase formatted sql" changelog in this directory, without the ".sql" suffix.

The console reported this rather unhelpful error.  

```
Unexpected error running Liquibase: Unknown reason
```

Inspecting the log, I saw a stackoverflow with thousands of recursions here:

```
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:302)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
        ...
```

Ideally this should fail gracefully, or report some error.   I believe this should be easily reproducible.

**Comment by kataggart** [comment]
@jpz Thanks for the suggestion! We will look into improving the error. Definitely would be helpful.

**Comment by FBurguer** [comment]
Following the steps you listed I tried having 2 changelogs with the same changeset, one with .sql suffix and other one with .txt suffix, didnt get the same error, and got a warning.
```
[2022-07-25 12:43:10] INFO [liquibase.changelog] Reading resource: changelogs/test.sql
[2022-07-25 12:43:10] INFO [liquibase.changelog] Reading resource: changelogs/test2.txt
[2022-07-25 12:43:10] WARNING [liquibase.changelog] included file mchangelog.postgresql.yml/changelogs/test2.txt is not a recognized file type
```
Maybe it got fixed or has to do with the specific content  of your changelog.
If you keep having the same issue, can you share your full stack trace? Thanks!
