### ISSUE TITLE
Error reading changelog file: Found 2 files that match

### ISSUE THREAD

**Issue by Dapengsechs** [liquibase/liquibase#2628]
## Environment

**Liquibase Version**: 4.3.5, 4.7.1

**Liquibase Integration & Version**: helm template

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: DB2

**Operating System Type & Version**: Win10

## Description
We have changelog files that have **file names** with german letters.
Before we use liquibase version 3.10.2, there is no problem.
But after we update the verstion to 4.3.5 or 4.7.1, there is alwasy error.
And I tried using fileEncoding or outputEncoding in liquibase.properties to use UTF-8. But it doesn’t help.

There are already questions asked in forum. But no solutions there are provided.
https://forum.liquibase.org/t/liquibase-4-unable-to-work-with-changelog-files-that-have-utf8-characters-in-their-name/5869
https://forum.liquibase.org/t/liquibase-4-utf-8-not-recognized/4944

`[2022-03-10 13:09:50] SEVERE [liquibase.integration] Error Reading Changelog File: Found 2 files that match migration/i18n/20.1.0/AR-9349-INFO-Spalte-überlappt-sich-Visuel-mit-der-Icons-in-der-Tabelle.xml: file:/home/liquibase/migration/i18n/20.1.0/AR-9349-INFO-Spalte-überlappt-sich-Visuel-mit-der-Icons-in-der-Tabelle.xml, file:/home/liquibase/migration/i18n/20.1.0/AR-9349-INFO-Spalte-%c3%bcberlappt-sich-Visuel-mit-der-Icons-in-der-Tabelle.xml
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: liquibase.exception.SetupException: Error Reading Changelog File: Found 2 files that match migration/i18n/20.1.0/AR-9349-INFO-Spalte-überlappt-sich-Visuel-mit-der-Icons-in-der-Tabelle.xml: file:/home/liquibase/migration/i18n/20.1.0/AR-9349-INFO-Spalte-überlappt-sich-Visuel-mit-der-Icons-in-der-Tabelle.xml, file:/home/liquibase/migration/i18n/20.1.0/AR-9349-INFO-Spalte-%c3%bcberlappt-sich-Visuel-mit-der-Icons-in-der-Tabelle.xml
	at liquibase.command.CommandScope.execute(CommandScope.java:163)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)`

## Steps To Reproduce

If the changelog file names contains non ASCII characters, there will be this error.

**Comment by kataggart** [comment]
likely same issue as reported https://github.com/liquibase/liquibase/issues/2620

**Comment by FBurguer** [comment]
If its the same issue as [#2620](https://github.com/liquibase/liquibase/issues/2620) it got fixed on 4.14
