### ISSUE TITLE
Liquibase fails to start with a Nullpointer exception when Environment contains an empty string Key

### ISSUE THREAD

**Issue by feltonma91** [liquibase/liquibase#2631]
Below is is the result of adding the key value pair ("     ","Test") to the Env vars 

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.15.jar:5.3.15]
	... 24 more
Caused by: java.lang.NullPointerException
	at liquibase.configuration.AbstractMapConfigurationValueProvider.keyMatches(AbstractMapConfigurationValueProvider.java:140) ~[liquibase-core-4.8.0.jar:?]
	at liquibase.configuration.pro.EnvironmentValueProvider.keyMatches(Unknown Source) ~[liquibase-core-4.8.0.jar:?]
	at liquibase.configuration.AbstractMapConfigurationValueProvider.lookupProvidedValue(AbstractMapConfigurationValueProvider.java:105) ~[liquibase-core-4.8.0.jar:?]
	at liquibase.configuration.pro.EnvironmentValueProvider.lookupProvidedValue(Unknown Source) ~[liquibase-core-4.8.0.jar:?]
	at liquibase.configuration.AbstractMapConfigurationValueProvider.getProvidedValue(AbstractMapConfigurationValueProvider.java:52) ~[liquibase-core-4.8.0.jar:?]
	at liquibase.configuration.LiquibaseConfiguration.getCurrentConfiguredValue(LiquibaseConfiguration.java:123) ~[liquibase-core-4.8.0.jar:?]
...

I believe this due to the code found in EnvironmentValueProvider and AbstractMapConfigurationValueProvider

    protected boolean keyMatches(String var1, String var2) {
        var2 = StringUtil.trimToNull(var2);
        if (super.keyMatches(var1, var2)) {
            return true;
        } else if ((var1 = StringUtil.toKabobCase(var1.replace(".", "-"))).equalsIgnoreCase(var2)) {
            return true;
        } else {
            return var1.replace("-", "_").equalsIgnoreCase(var2);
        }
    }

    protected boolean keyMatches(String wantedKey, String storedKey) {
        if (storedKey.equalsIgnoreCase(wantedKey)) {
            return true;
        }

        wantedKey = StringUtil.toKabobCase(wantedKey);
        if (storedKey.equalsIgnoreCase(wantedKey)) {
            return true;
        }

        wantedKey = wantedKey.replace(".", "-");
        if (storedKey.equalsIgnoreCase(wantedKey)) {
            return true;
        }

        //check for everythingSmashedTogether case insensitively
        wantedKey = wantedKey.replace("-", "");
        if (storedKey.equalsIgnoreCase(wantedKey)) {
            return true;
        }

        return false;
    }

the super class keyMatches method is doing a String.equals() on the null returned when var2 is empty my suggestion is to use StringUtil.trimToEmpty() instead of StringUtil.trimToNull

likewise I would also recommend reordering the vars that are checked in the super class 
so instead of 

storedKey.equalsIgnoreCase(wantedKey)

we should do 

wantedKey.equalsIgnoreCase(storedKey)

**Comment by wwillard7800** [comment]
Thanks for the research.  I have replicated the issue, and confirmed that StringUtil.trimToEmpty() fixes it.  The same issue happens in the CLI.

To set the variable with an empty name, I launched the application in Bash with:

env " "="TEST" java -jar springboot.jar

Is that how you reproduced it?  I couldn't find any other way of setting the variable that way.

**Comment by wwillard7800** [comment]
The PR will be helpful.  Thank you.

**Comment by feltonma91** [comment]
Good morning I just wanted to follow up to see what a typical ETA for these types of fixes to be released would be. Thanks
