### ISSUE TITLE
 Unexpected error running Liquibase: jakarta/persistence/EntityManager

### ISSUE THREAD

**Issue by WolfAlm** [liquibase/liquibase#2662]
I was solving one problem that was described here(https://github.com/liquibase/liquibase/issues/2456). Unfortunately, another one has already occurred =  Unexpected error running Liquibase: jakarta/persistence/EntityManager. What do I have to do?

`Starting Liquibase at 03:58:08 (version 4.8.0 #1581 built at 2022-02-18 21:43+0000)
Liquibase Version: 4.8.0
Liquibase Community 4.8.0 by Liquibase

Unexpected error running Liquibase: jakarta/persistence/EntityManager

For more information, please use the --log-level flag

> Task :diffChangeLog FAILED

Execution failed for task ':diffChangeLog'.
> Process 'command 'C:\Users\WolfAlm\.jdks\corretto-16.0.2\bin\java.exe'' finished with non-zero exit value 1

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':diffChangeLog'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
`

**Comment by filipelautert** [comment]
This was reported against Liquibase 4.8.0 with `liquibase-hibernate5`. The Hibernate extension has since been updated to `liquibase-hibernate6` with proper Jakarta persistence support. This classpath issue should no longer occur with current versions. Closing as outdated — if you're still experiencing issues, please open a new issue with your current dependency versions.
