### ISSUE TITLE
In StandardChangeLogHistoryService  SnapshotGeneratorFactory.getInstance().getDatabaseChangeLogTable should return null id table not exist

### ISSUE THREAD

**Issue by gpolekar** [liquibase/liquibase#2674]
## Environment

**Liquibase Version**: 4.9.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: Snowflake

**Database Vendor & Version**:NA

**Operating System Type & Version**: Amazon Linux 2

## Description

In **StandardChangeLogHistoryService.java**
changeLogTable = SnapshotGeneratorFactory.getInstance().getDatabaseChangeLogTable(new SnapshotControl
                (database, false, Table.class, Column.class), database);

Should return null if DATABASECHANGELOG table is not present or not created. (We are running liquibase first time)

## Steps To Reproduce

-Create empty database on snowflake.
-Add sample change set
-run liquibase update from command line

## Actual Behavior
It throws error:
`SEVERE [liquibase.integration] Unexpected error running Liquibase: SQL compilation error:
Object 'DB.PUBLIC.DATABASECHANGELOG' does not exist or not authorized.
liquibase.exception.DatabaseException: Error executing SQL SELECT MD5SUM FROM "PUBLIC".DATABASECHANGELOG WHERE MD5SUM IS NOT NULL: SQL compilation error:
Object 'LPM_DEV.PUBLIC.DATABASECHANGELOG' does not exist or not authorized.
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:95)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:163)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:171)
	at liquibase.executor.jvm.JdbcExecutor.queryForList(JdbcExecutor.java:236)
	at liquibase.executor.jvm.JdbcExecutor.queryForList(JdbcExecutor.java:231)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:245)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1913)`

## Expected/Desired Behavior
Should create DATABASECHANGELOG first and then proceed for select.

**Comment by gpolekar** [comment]
If possible can the fix will be available for version 4.5.x
