### ISSUE TITLE
customChange with any attribute fails due to SAXParseException

### ISSUE THREAD

**Issue by kdebski85** [liquibase/liquibase#2678]
## Environment

**Liquibase Version**: 
4.9.0

**Liquibase Integration & Version**: 
liquibase.integration.commandline.Main

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
DB2

**Operating System Type & Version**:
Windows

**Java Version**: 
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode)

## Description

Liquibase cannot execute customChange with any attribute in Java 11

## Steps To Reproduce

Copy example changeset from https://docs.liquibase.com/change-types/custom-change.html

```xml
<changeSet id="21" author="nvoxland">
        <customChange class="liquibase.change.custom.ExampleCustomTaskChange" helloTo="world"/>
 </changeSet>
```

Try executing it in OpenJDK 11

## Actual Behavior
```
Caused by: liquibase.exception.SetupException: Error parsing line 12 column 95 of database/boa-global-db-liquibase-structure/common-init.xml: cvc-complex-type.3.2.2: Attribute 'helloTo' is not allowed to appear in element 'customChange'.
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:371)
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:318)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
        ... 22 more
Caused by: liquibase.exception.ChangeLogParseException: Error parsing line 12 column 95 of database/boa-global-db-liquibase-structure/common-init.xml: cvc-complex-type.3.2.2: Attribute 'helloTo' is not allowed to appear in element 'customChange'.
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:113)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
        at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:587)
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:363)
        ... 24 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 95; cvc-complex-type.3.2.2: Attribute 'helloTo' is not allowed to appear in element 'customChange'.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:511)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3587)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:2992)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2286)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:849)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:105)
        ... 27 more
```

## Expected/Desired Behavior
Changeset should be executed

**Comment by kdebski85** [comment]
As a workaround, I can use:
```xml
<changeSet id="21" author="nvoxland">
        <customChange class="liquibase.change.custom.ExampleCustomTaskChange">
               <param name="helloTo" value="world"/>
        </customChange>
 </changeSet>
```
The example at https://docs.liquibase.com/change-types/custom-change.html should probably be fixed.
