### ISSUE TITLE
ClassCastException: class java.util.BitSet cannot be cast to class java.lang.Boolean (java.util.BitSet and java.lang.Boolean

### ISSUE THREAD

**Issue by john2home** [liquibase/liquibase#2702]
## Environment

**Liquibase Version**:
4.8.0 and 4.9.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
java class

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
MariaDB 10.6.7

**Operating System Type & Version**:
Windows 10
Java Adoptium 11.0.14+1
mariadb-java-client 3.0.4

## Description
The liquibase.listlocks() throws a ClassCastException

## Steps To Reproduce
liquibase is called from a java class like:
`
final liquibase.database.Database database = DatabaseFactory.getInstance()				  .findCorrectDatabaseImplementation(new JdbcConnection(db.getConnection()));
String changelogFile = "./changelog.xml";
try (final Liquibase liquibase = new Liquibase(changelogFile, ressourceAccessor, database))
{
if (liquibase.listLocks() != null && liquibase.listLocks().length > 0)
{
	liquibase.forceReleaseLocks();
}
...
`
The liquibase.listlocks() throws the following exception:
`
Caused by: java.lang.ClassCastException: class java.util.BitSet cannot be cast to class java.lang.Boolean (java.util.BitSet and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at liquibase.lockservice.StandardLockService.listLocks(StandardLockService.java:425) ~[liquibase-core-4.9.1.jar:?]
	at liquibase.Liquibase.listLocks(Liquibase.java:1936) ~[liquibase-core-4.9.1.jar:?]
`
It seems that the MariaDB datatype bit(1) from column databasechangeloglock.locked is returned as BitSet with mariadb-connector 3.0.4 and not as Boolean

## Actual Behavior
a ClassCastException

## Expected/Desired Behavior
no ClassCastException

**Comment by john2home** [comment]
from org.mariadb.jdbc:mariadb-java-client:3.0.6 this error no longer occurs
