### ISSUE TITLE
Samples of changelog.xml in documenation have wrong path to xsd files

### ISSUE THREAD

**Issue by mkobylarz** [liquibase/liquibase#2707]
## Environment

**Liquibase Version**: 4.9.1

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: Oracle 19

**Operating System Type & Version**: Linux Mint 20.3

## Description

I believe these snippets of changelog.xml in documentation are wrong:
https://docs.liquibase.com/concepts/changelogs/working-with-changelogs.html
https://docs.liquibase.com/tools-integrations/springboot/springboot.html

String `http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.0.xsd` should actually be:
`http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.xsd` (without trailing `.0`)

Such files (without `.0`) can be found in liquibase-core.jar and can be accessed via http.

## Steps To Reproduce

Make empty springboot application with empty changelog.xml taken from documentation and try to run it.

## Actual Behavior
Exception during application startup:

```
Caused by: liquibase.exception.ChangeLogParseException: liquibase.parser.core.xml.XSDLookUpException: Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.0.xsd locally: liquibase.secureParsing is set to 'true' which does not allow remote lookups. Set it to 'false' to allow remote lookups of xsd files.
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:137) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:224) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2405) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314) ~[liquibase-core-4.9.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.9.1.jar:na]
	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46) ~[spring-boot-autoconfigure-2.6.5.jar:2.6.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.17.jar:5.3.17]
	... 18 common frames omitted
Caused by: liquibase.parser.core.xml.XSDLookUpException: Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.0.xsd locally: liquibase.secureParsing is set to 'true' which does not allow remote lookups. Set it to 'false' to allow remote lookups of xsd files.
	at liquibase.parser.core.xml.LiquibaseEntityResolver.resolveEntity(LiquibaseEntityResolver.java:49) ~[liquibase-core-4.9.1.jar:na]
	at java.xml/com.sun.org.apache.xerces.internal.util.EntityResolver2Wrapper.resolveEntity(EntityResolver2Wrapper.java:178) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1134) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:663) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2695) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2070) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3079) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637) ~[na:na]
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:105) ~[liquibase-core-4.9.1.jar:na]
```

## Expected/Desired Behavior
Taking empty changelog.xml from documentation should be correct out of the box.

## Screenshots (if appropriate)
![obraz](https://user-images.githubusercontent.com/18023231/161208525-f3f046c5-aa1d-4e3a-91cc-284659b4fd21.png)
![obraz](https://user-images.githubusercontent.com/18023231/161210896-02ec080d-d9f1-4078-854f-23f7132c87e0.png)

**Comment by kataggart** [comment]
submitted internal docs ticket https://datical.atlassian.net/browse/PD-2574

**Comment by nvoxland** [comment]
I created a docs PR for it

**Comment by myegoni** [comment]
Hi @nvoxland, I'm having the same error as describe in this issue with the reference to xsd http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd in changelogs such as shown in the examples [here](https://docs.liquibase.com/concepts/changelogs/xml-format.html).

This is causing startup issues with Spring Boot with the same message as mentioned above:
`liquibase.parser.core.xml.XSDLookUpException: Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd locally: liquibase.secureParsing is set to 'true' which does not allow remote lookups. Set it to 'false' to allow remote lookups of xsd files.`

I have tried using all versions above **4.9** for this xsd but all fail the same way despite I'm able to navigate to the file and download it directly from a browser.
Changing manually the URL to http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.xsd does not generate the error.

I've been unable to find more details regarding this problem except for this issue. Is there a particular configuration to implement or am I missing something for this to work with the `dbchangelog-latest.xsd`?

I know this task is already closed and I can open a new issue if needed.

**Comment by kataggart** [comment]
@myegoni that would be great if you could create a new issue. Thanks! Definitely don't want your issue getting lost.

**Comment by myegoni** [comment]
Hi @kataggart, I've submitted the problem in this issue: #3120
Thanks!

**Comment by Adriansun** [comment]
dbchangelog-4.17.xsd works ok. 18 + 19 does not work. What gives? Spring Boot 3.0.2.

**Comment by FabriceReneCorail** [comment]
I had the same issue , on my personnal project. And yep i changed manually the url http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.xsd  and it's working now but we i still can't explain why the parsing of the file embedded didn't work...

**Comment by aaron-splicer** [comment]
FYI, I got the "secureParsing is set to 'true' which does not allow remote lookups." problem when the http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.xxx.xxx.xsd did not correlate to the proper liquibase version in pom.xml.
