### ISSUE TITLE
firebird needs schema specification to run liquibase drop-all

### ISSUE THREAD

**Issue by FBurguer** [liquibase/liquibase#2874]
Liquibase Version:
4.10.0

Liquibase Integration & Version: 
Core: //master/2708/0a9d6d/2022-05-23 15:17+0000, Pro: master/1291/728a05/2022-05-19T14:28:39Z

Database Vendor & Version:
Firebird jdbc: 3.0.6
Firebird docker conteiner: 4.0.1
Firebird api-connector 1.5

Operating System Type & Version:
Windows 10
Java 8

Description

`--schemas=*dbName*` is needed for running liquibase on a firebird database (its an odd behavior when it is not needed on other database types like mySQL)

Steps To Reproduce

1. Run a Firebird docker container
(Download firebird connector-api-1.5, its not included with liquibase)
2. Specify the user, pass, url and a changelog on your `liquibase.properties` or in the liquibase command 
3. Run `liquibase update`
4. Run `liquibase drop-all`

Actual Behavior
Liquibase cant run the command succesfully and it outputs the next error:
```
[2022-05-24 15:15:49] SEVERE [liquibase.integration] java.lang.NullPointerException
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:336)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:301)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:91)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.integration.commandline.Main$1.run(Main.java:443)
        at liquibase.integration.commandline.Main$1.run(Main.java:221)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:221)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1825)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:397)
        ... 26 more
Caused by: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:115)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 33 more
Caused by: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:97)
        ... 34 more


Unexpected error running Liquibase: java.lang.NullPointerException

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:336)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:301)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:91)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.integration.commandline.Main$1.run(Main.java:443)
        at liquibase.integration.commandline.Main$1.run(Main.java:221)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:221)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1825)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:397)
        ... 26 more
Caused by: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:115)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 33 more
Caused by: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:97)
        ... 34 more

```

Expected/Desired Behavior
Liquibase runs `liquibase drop-all` succesfully 

Additional Context
Checked on a mySQL database and it doesnt have that behavior

**Comment by FBurguer** [comment]
When `liquibase drop-all` fails, it does not drop all the tables but it drops `DATABASECHANGELOGLOCK`
![image](https://user-images.githubusercontent.com/90205432/170
![image](https://user-images.githubusercontent.com/90205432/170322668-fd37bc2a-3624-4b3b-95d2-a9f4c6a81203.png)
322643-3077fc52-982e-4523-838d-3cf13a787bf0.png)

**Comment by XDelphiGrl** [comment]
Nicely documented bug, @FBurguer! Thank you for the attention to detail!
