### ISSUE TITLE
Original exception is swallowed when liquibase fails to create connection to db

### ISSUE THREAD

**Issue by osigida** [liquibase/liquibase#2978]
## Environment

**Liquibase Version**:4.11

**Liquibase Integration & Version**:CLI

**Liquibase Extension(s) & Version**: ?

**Database Vendor & Version**: mySql

**Operating System Type & Version**: alpine

**Infrastructure Type/Provider**: GCP

## Description

when liquibase failed to establish a connection, the original exception is swallowed and then it is difficult to debug

stack trace looks like: 
```
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:mysql:... with driver com.mysql.jdbc.Driver.  Could not create connection to database server.
	at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:35)
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:214)
	... 30 more
Caused by: liquibase.exception.DatabaseException: Connection could not be created to jdbc:mysql:... with driver com.mysql.jdbc.Driver.  Could not create connection to database server.
	at liquibase.database.jvm.JdbcConnection.open(JdbcConnection.java:54)
	at com.datical.liquibase.ext.database.jvm.ProJdbcConnection.open(Unknown Source)
	at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
	... 31 more
```

**Comment by kataggart** [comment]
resolved by different PR; see @nvoxland comment on #2979
