### ISSUE TITLE
Liquibase Throws Lexical While Processing Thai Charaters

### ISSUE THREAD

**Issue by shudshi** [liquibase/liquibase#3013]
## Environment

**Liquibase Version**: 4.12.0

**Liquibase Integration & Version**: liquibase.jar

**Database Vendor & Version**: MySQL 5.7

## Description

Liquibase is not handling Thai characters very well. It throws "liquibase.util.grammar.TokenMgrError" while executing the SQL below from a `.sql` file. The SQL container Thai string `การโต้แย้ง`. Please note that our Java program contains JVM argument `-Dfile.encoding=UTF-8` and also has `useUnicode=true&characterEncoding=UTF-8` in the MySQL connect string.

```
INSERT INTO CXXXXXXXXXXXXXXXXXXXXE (CXXXXXXXXXXXXXXD, DATEADDED, DATEMODIFIED, LOCALEID, NAME, RXXXXXXD, SXXXXXXXXXXG, NXXXXXXXXXXXXXXN, CXXXXXXXXXXXXN, MXXXXXXXXXN) VALUES ('6XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX7',current_timestamp,current_timestamp,'th_TH','การโต้แย้ง','eXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1',NULL,NULL,NULL,NULL);
```

Full error stack:
```
liquibase.util.grammar.TokenMgrError: Lexical error at line 1, column 264.  Encountered: "\u0e49" (3657), after : ""
	at liquibase.util.grammar.SimpleSqlGrammarTokenManager.getNextToken(SimpleSqlGrammarTokenManager.java:1378) ~[liquibase-4.12.0.jar:?]
	at liquibase.util.grammar.SimpleSqlGrammar.getNextToken(SimpleSqlGrammar.java:109) ~[liquibase-4.12.0.jar:?]
	at liquibase.util.SqlParser.parse(SqlParser.java:40) ~[liquibase-4.12.0.jar:?]
	at liquibase.util.StringUtil.processMultiLineSQL(StringUtil.java:64) ~[liquibase-4.12.0.jar:?]
	at liquibase.change.AbstractSQLChange.generateStatements(AbstractSQLChange.java:238) ~[liquibase-4.12.0.jar:?]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1276) ~[liquibase-4.12.0.jar:?]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:661) ~[liquibase-4.12.0.jar:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56) ~[liquibase-4.12.0.jar:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-4.12.0.jar:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-4.12.0.jar:?]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:247) ~[liquibase-4.12.0.jar:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65) ~[liquibase-4.12.0.jar:?]
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-4.12.0.jar:?]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-4.12.0.jar:?]
	at liquibase.Liquibase.runInScope(Liquibase.java:2405) ~[liquibase-4.12.0.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-4.12.0.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-4.12.0.jar:?]
```

## Side Note

I knew nothing about Thai, but it is worth to review the entire language support against Thai.

**Comment by filipelautert** [comment]
Fixed in PR #5506 (merged Feb 2024) which expanded the SQL parser's character range to support all UTF-8 symbols (`\u00A1-\uFF65`), including Thai characters.

Closing this out — if you're still hitting lexical errors on a recent version, feel free to re-open.
