### ISSUE TITLE
Liquibase throwing error on script that works in SQLcl and on the previous liquibase version against Oracle Database

### ISSUE THREAD

**Issue by tschf** [liquibase/liquibase#3040]
## Environment

**Liquibase Version**: 4.12.0

**Database Vendor & Version**: Oracle Database, 19c

**Operating System Type & Version**: Oracle Linux 8

## Description

When I run update on the latest version (4.12.0), liquibase is throwing an ORA-06550 - where I don't think it should.
But if I run the same script directly in sqlplus, it works fine.
If I rollback to version 4.9.1, it is also working fine.

## Detailed info

Given the following script:

```
declare
  l_file_clob clob;
begin
  l_file_clob := apex_string.join_clob(apex_t_varchar2(
    '    cy.log(`getDialogBody for className="${dialogClassName}"`);',
    '    return cy.get("iframe", { log: false } )'
  ));

end;
/
```

My corresponding change log file looks like this:

```
# Liquibase Changelog
# This file is auto-generated.
databaseChangeLog:
- changeSet:
    author: trent
    id: 202204061610388755
    runOnChange: true
    changes:
    - sqlFile:
        dbms: oracle
        encoding: utf8
        endDelimiter: /
        splitStatements: true
        stripComments: true
        path: example.sql
    rollback:
    - empty: null
```

On 4.12.0, it shows this:

```
$ /opt/liquibase-4.12.0/liquibase --changelog-file example.sql.yml update
Starting Liquibase at 15:14:07 (version 4.12.0 #3073 built at 2022-06-17 05:59+0000)
Liquibase Version: 4.12.0
Liquibase Community 4.12.0 by Liquibase
[2022-07-05 15:14:19] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-07-05 15:14:48] INFO [liquibase.changelog] Reading from ACDC.DATABASECHANGELOG
Running Changeset: example.sql.yml::202204061610388755::trent
[2022-07-05 15:14:58] INFO [liquibase.lockservice] Successfully released change log lock
[2022-07-05 15:14:58] SEVERE [liquibase.integration] ORA-06550: line 7, column 5:
PLS-00103: Encountered the symbol "    return cy.get("iframe", { log: false" when expecting one of the following:

   ( - + case mod new not null <an identifier>
   <a double-quoted delimited-identifier> <a bind variable>
   continue avg count current exists max min prior sql stddev
   sum variance execute forall merge time timestamp interval
   date <a string literal with character set specification>
   <a number> <a single-quoted SQL string> pipe
   <an alternatively-quoted string literal with character 

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Migration failed for change set example.sql.yml::202204061610388755::trent:
     Reason: liquibase.exception.DatabaseException: ORA-06550: line 7, column 5:
PLS-00103: Encountered the symbol "    return cy.get("iframe", { log: false" when expecting one of the following:

   ( - + case mod new not null <an identifier>
   <a double-quoted delimited-identifier> <a bind variable>
   continue avg count current exists max min prior sql stddev
   sum variance execute forall merge time timestamp interval
   date <a string literal with character set specification>
   <a number> <a single-quoted SQL string> pipe
   <an alternatively-quoted string literal with character 
 [Failed SQL: (6550) declare
  l_file_clob clob;
  l_file_blob blob;
begin
  l_file_clob := apex_string.join_clob(apex_t_varchar2(
    '    cy.log(`getDialogBody for className="${dialogClassName}"`);',
    '    return cy.get("iframe", { log: false]
        at liquibase.command.CommandScope.execute(CommandScope.java:162)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:336)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:301)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:91)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Migration failed for change set example.sql.yml::202204061610388755::trent:
     Reason: liquibase.exception.DatabaseException: ORA-06550: line 7, column 5:
PLS-00103: Encountered the symbol "    return cy.get("iframe", { log: false" when expecting one of the following:

   ( - + case mod new not null <an identifier>
   <a double-quoted delimited-identifier> <a bind variable>
   continue avg count current exists max min prior sql stddev
   sum variance execute forall merge time timestamp interval
   date <a string literal with character set specification>
   <a number> <a single-quoted SQL string> pipe
   <an alternatively-quoted string literal with character 
 [Failed SQL: (6550) declare
  l_file_clob clob;
  l_file_blob blob;
begin
  l_file_clob := apex_string.join_clob(apex_t_varchar2(
    '    cy.log(`getDialogBody for className="${dialogClassName}"`);',
    '    return cy.get("iframe", { log: false]
        at liquibase.integration.commandline.Main$1.run(Main.java:443)
        at liquibase.integration.commandline.Main$1.run(Main.java:221)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:221)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
        at liquibase.command.CommandScope.execute(CommandScope.java:156)
        ... 20 more
```

Connected to SQLcl:

```
SQLcl: Release 22.2 Production on Tue. Jul. 05 15:17:58 2022

Copyright (c) 1982, 2022, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c EE High Perf Release 19.0.0.0.0 - Production
Version 19.13.0.0.0

xgbu_ace_atat_gat_168: acdc> !cat example.sql
declare
  l_file_clob clob;
  l_file_blob blob;
begin
  l_file_clob := apex_string.join_clob(apex_t_varchar2(
    '    cy.log(`getDialogBody for className="${dialogClassName}"`);',
    '    return cy.get("iframe", { log: false } )'
  ));
end;
/
xgbu_ace_atat_gat_168: acdc> @example.sql

PL/SQL procedure successfully completed.
```

Execute via 4.9.1:

```
╰> /opt/liquibase/liquibase --changelog-file example.sql.yml update
Starting Liquibase at 15:18:50 (version 4.9.1 #1978 built at 2022-03-28 19:39+0000)
Liquibase Version: 4.9.1
Liquibase Community 4.9.1 by Liquibase
[2022-07-05 15:19:01] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-07-05 15:19:31] INFO [liquibase.changelog] Reading from ACDC.DATABASECHANGELOG
Running Changeset: example.sql.yml::202204061610388755::trent
[2022-07-05 15:19:39] INFO [liquibase.changelog] SQL in file example.sql executed
[2022-07-05 15:19:40] INFO [liquibase.changelog] ChangeSet example.sql.yml::202204061610388755::trent ran successfully in 775ms
[2022-07-05 15:19:41] INFO [liquibase.lockservice] Successfully released change log lock
Liquibase command 'update' was executed successfully.
```

..

Furthermore, in my example code.

If I modfy this line:
```
    '    return cy.get("iframe", { log: false } )'
```

to this:
```
    '    return cy.get("iframe")'
```
(that is, remove the bit `{ log: false }`

it is also working on 4.12.0

```
╰> cat example.sql
declare
  l_file_clob clob;
  l_file_blob blob;
begin
  l_file_clob := apex_string.join_clob(apex_t_varchar2(
    '    cy.log(`getDialogBody for className="${dialogClassName}"`);',
    '    return cy.get("iframe")'
  ));
end;
> /opt/liquibase-4.12/liquibase --changelog-file example.sql.yml update
Starting Liquibase at 15:22:40 (version 4.12.0 #3073 built at 2022-06-17 05:59+0000)
Liquibase Version: 4.12.0
Liquibase Community 4.12.0 by Liquibase
[2022-07-05 15:22:51] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-07-05 15:23:21] INFO [liquibase.changelog] Reading from ACDC.DATABASECHANGELOG
Running Changeset: example.sql.yml::202204061610388755::trent
[2022-07-05 15:23:30] INFO [liquibase.changelog] SQL in file example.sql executed
[2022-07-05 15:23:30] INFO [liquibase.changelog] ChangeSet example.sql.yml::202204061610388755::trent ran successfully in 745ms
[2022-07-05 15:23:32] INFO [liquibase.lockservice] Successfully released change log lock
Liquibase command 'update' was executed successfully.

**Comment by kataggart** [comment]
This should be fixed with #2984 which is in the release that is about to come out! I will let you know when it's available. Thanks.

**Comment by kataggart** [comment]
@tschf v4.13 is out now. Closing this now, please let us know if you continue to face any issues. Thanks!!

**Comment by tschf** [comment]
Excellent - thank you for the update. I've just tested the new version it working well now :)
