### ISSUE TITLE
Liquibase 4.13.0 breaks migration using 'addAtPosition' on h2

### ISSUE THREAD

**Issue by andre-aktivconsultancy** [liquibase/liquibase#3094]
## Environment

**Liquibase Version**:
4.13.0
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
spring-boot
**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
H2 2.1.214

**Operating System Type & Version**:
Ubuntu 21.10
 
**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
-

## Description

When updating from Liquibase 4.12.0 to 4.13.0 we notice migrations fail with the following error:
```
liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          addAtPosition is not allowed on h2, db/changelog/changes/202111221630.xml::xx:xx
```

## Steps To Reproduce
We have a migration containing the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd"
  objectQuotingStrategy="QUOTE_ONLY_RESERVED_WORDS">
  <changeSet id="1627309304232-8" author="xx">
    <addColumn  tableName="xx" >
      <column name="xx"
              position="2"
              type="varchar(50)">
      </column>
    </addColumn>
  </changeSet>
</databaseChangeLog>
```

## Actual Behavior
On version 4.13.0 this results in the following error:

```
2022-07-21 12:58:27,480 ERROR | main | org.springframework.boot.SpringApplication              | Application run failed 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          addAtPosition is not allowed on h2, db/changelog/changes/202111221630.xml::xx::xx

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:132)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:43)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$8(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$9(ClassBasedTestDescriptor.java:363)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:362)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$instantiateAndPostProcessTestInstance$6(ClassBasedTestDescriptor.java:283)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:282)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:272)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:271)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:102)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:101)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          addAtPosition is not allowed on h2, db/changelog/changes/202111221630.xml::xx::xx

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:307)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:228)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2400)
	at liquibase.Liquibase.update(Liquibase.java:208)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 89 common frames omitted
```

## Expected/Desired Behavior
The migration to succeed

**Comment by hylkevds** [comment]
Not just on H2, also on PostgreSQL.

**Comment by kataggart** [comment]
Hi @andre-aktivconsultancy and @hylkevds.

Neither H2 nor Postgres natively support addAtPosition functionality. The error you are now receiving is more correct, whereas in the past Liquibase used to just do nothing and carry on when receiving that instruction in those platforms. We are moving towards having these types of failures called out, so you are made aware of when commands are not successful. So before, while you didn't receive this error, the database was also not actually being updated in the manner you were requesting.

Are you looking to use the same changelog on multiple different database platforms, where one does support addAtPosition and the other does not?

**Comment by hylkevds** [comment]
I'm mainly interested in my changelogs not breaking, any your change breaks them both ways...
Leaving the postition="x" in breaks things, removing the attribute also breaks things, since the signature of the changeset breaks.

And yes, there is also the thing about different platforms, which is one of the main selling points for Liquibase :)

**Comment by nvoxland** [comment]
If you change your changeset, the checksum changes (as you noticed). Liquibase will flag that, but we have the `<validCheckSum>` tag for you to specify the alternate/old checksums that you know are OK. In this case, you know the checksum for the version with the position attribute is an expected change so it's a good time to use the validCheckSum tag.

The ability to work with different platforms is an important part of Liquibase and something we're always trying to balance and preserve. But just silently ignoring something you are asking for like position just because a database doesn't support it doesn't seem right either. Even in that case, it's not really cross-database because you will still end up with differences in column positions so good to make sure you are understanding that difference.

So if you are using only databases that don't support the position attribute, it's best to just take it off since it's not actually valid and claiming something is happening that actually isn't. 

If you do support multiple databases and some support position and some don't and you are OK with that difference, your easiest route is probably to use <modifySql dbms="..."> to append the position clause when you need it. It's less "magical" but when it comes to database schema setup, I think the less magic/surprises the better.

**Comment by dbyron-sf** [comment]
> If you do support multiple databases and some support position and some don't and you are OK with that difference, your easiest route is probably to use to append the position clause when you need it. It's less "magical" but when it comes to database schema setup, I think the less magic/surprises the better.

Would you mind giving some examples of how to "append the position clause when you need it"?

Assuming for the moment that I knew the mechanics of how to do it, the question of "when you need it" is a tough one, at least for me.  Liquibase knows though, right?  I totally agree with less magic, but having a way to indicate "do this where supported" would be super helpful.  Yes, it's not really cross-database support, but at least the migration functions, and does the best it can.

**Comment by nvoxland** [comment]
In going through what is supposed to be supported for "addAtPosition" I couldn't find any databases that actually support that. Firebird was the closest on allowing it for "alter column" but it didn't look like it supported it on the "add column" statement.

But, an hypothetical example at least, is like:

```
    <changeSet id="1" author="example">
        <addColumn tableName="test">
            <column name="new_col" type="int"/>
        </addColumn>
        <modifySql dbms="firebird">
            <append value=" position 4"/>
        </modifySql>
    </changeSet>
```
which will work on all databases by not trying to specify the position, and if you are on (only) firebird it takes whatever sql gets generated for the normal statement and appends ` position 4` to the end of the string before executing it.

That "modifySql" tag is a general escape hatch for any syntax not supported in the change functions, and can also work well for having that change function setup be the "cross-database base" and then let you build up the database-specific changes you are OK applying.

**Comment by dbyron-sf** [comment]
Thank you!  Good to know you you're talking about modifySql.  Am I right that I only get one modifySql per changeSet?  With multiple columns, each with their own afterColumn attribute (and not all after the same column), I haven't been able to come up with the right modifySql to adjust them all.

**Comment by nvoxland** [comment]
You can have as many modifySql tags as you'd like. And within each you can have as many append/prepend/replace/regExpReplace tags as you need in there.

It's generally most readable to have a single modifySql block (or one per dbms type) and then put however many changes you need in there.

Also: if you have suggestions on new general-purpose solutions to the problem of how to balance cross-database vs. expectations feel free to open issues describing them. Always looking for ways to make Liquibase easier to use.

**Comment by dbyron-sf** [comment]
> You can have as many modifySql tags as you'd like. And within each you can have as many append/prepend/replace/regExpReplace tags as you need in there.

I should have asked a different question.  Having multiple modifySql tags per changeSet is likely helpful.  What I (think I) really want, is to add modifySql to individual columns in an addColumn...Like, if today I have:
```
- changeSet:
    id: partition-updated-executions
    author: rzienert
    changes:
    - addColumn:
        tableName: orchestrations
        columns:
        - column:
            name: partition
            type: varchar(32)
            afterColumn: legacy_id
        - column:
            name: updated_at
            type: bigint
            afterColumn: build_time
```
how do I get the equivalent of `afterColumn` with modifySql?

**Comment by hylkevds** [comment]
The modifySql approach (I would not call it a solution) also has the problem that it is DB-specific. It has to be separately added for each current and future DBMS that supports column-positioning. Meaning that to support an additional DBMS, you have to change lots of changesets, that then all have a new hash, that need to be _manually_ updated in a second round of edits.
I'm using Liquibase to have less work, not more!

I'd also very much prefer a warning instead of a failure. Even if that warning has to be explicitly turned on.

**Comment by kataggart** [comment]
Thanks for all the input and feedback. We absolutely will consider something like a warning that has to be turned on. I do think it's important that end-users are told explicitly that your changelog is not resulting in the database change in your changeset because it is not supported by that database. Stay tuned.

**Comment by dbyron-sf** [comment]
Things have been quiet here and on https://github.com/liquibase/liquibase/issues/3091.  Is this still on your radar for a fix @kataggart ?

**Comment by tabbyf00** [comment]
Hey, @dbyron-sf. Karen's out on PTO, but we plan to talk about this during standup tomorrow to see if there's any update before she returns.

**Comment by dbyron-sf** [comment]
Thanks @tabbyf00!

**Comment by mjaggard** [comment]
> Hey, @dbyron-sf. Karen's out on PTO, but we plan to talk about this during standup tomorrow to see if there's any update before she returns. 

For those outside the US, PTO means holiday. I googled it.

**Comment by kataggart** [comment]
@dbyron-sf This is currently in our RFE backlog, but we are not able to prioritize it at this time. Of course, PRs to help move along community requested enhancements are always welcome!

**Comment by dbyron-sf** [comment]
Still hoping to get some traction on this.  In case the request isn't clear, what we’d like is a way to preserve the older functionality.  If a migration specifies afterColumn but a particular dbms doesn’t support it (e.g. postgres), liquibase ignores it.  The current functionality means that our existing migrations break, so we can’t upgrade without doing something at least a little painful:
* removing afterColumn so we lose the benefit of it from databases that support it (e.g. mysql)
* adjusting the migrations to do afterColumn using custom sql
And if we do either of those, it means a dance to specify multiple hashes so things continue to work for people who have run the existing migrations with older versions of liquibase.

So the request is for an option to restore the "best effort" functionality.

**Comment by nvoxland** [comment]
Yeah, @dbyron-sf, I hear your request for best effort functionality.  What makes it a larger feature request is that we want it to be something that is useful and makes sense in the general case, not just in "addAtPosition" or whatever.

I'm going to close this issue as "won't do" in favor of making #3094 the more broad feature request where we can all collaborate. I added a comment to that issue to continue the discussion there.

**Comment by dbyron-sf** [comment]
> I'm going to close this issue as "won't do" in favor of making #3094 the more broad feature request where we can all collaborate. I added a comment to that issue to continue the discussion there.

I think you mean #3091 here, but yes.  And thank you!

**Comment by nvoxland** [comment]
Yes, you are right. Thanks for finding the right one
