### ISSUE TITLE
DOUBLE with precision doesn't work anymore with H2 database

### ISSUE THREAD

**Issue by bilak** [liquibase/liquibase#3099]
## Environment

**Liquibase Version**: `4.9.1` and `4.13.0`

**Liquibase Integration & Version**: jar - application tests/integration tests

**Database Vendor & Version**: `H2` `2.1.214`

**Operating System Type & Version**: macos monterey 12.4

## Description

Liquibase doesn't translate `DOUBLE` field to correct value in H2 database. It's translated directly to DOUBLE but that type is [not supported](http://www.h2database.com/html/datatypes.html) by H2. 

## Steps To Reproduce

```
databaseChangeLog:
- changeSet:
    id: 1
    author: author
    comment: initial schema
    changes:
    - createTable:
        columns:
        - column:
            name: double_val
            type: DOUBLE(20)
        tableName: double_test
```

```
 Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "CREATE TABLE double_test (double_val DOUBLE[*](20))"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE double_test (double_val DOUBLE(20)) [42001-214] [Failed SQL: (42001) CREATE TABLE double_test (double_val DOUBLE(20))]

	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:262)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:261)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2400)
	at liquibase.Liquibase.update(Liquibase.java:208)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at liquibase.Liquibase.update(Liquibase.java:190)
	at liquibase.Liquibase.update(Liquibase.java:182)
```

## Actual Behavior
We've migrated from spring boot `2.4.5` to `2.7.2` where also liquibase (`3.10.3` - > `4.9.1`) and h2 (`1.4.200` -> `2.1.214`) versions changed and columns with `DOUBLE(xy)` were working previously.

## Expected/Desired Behavior
Column with `DOUBLE(xy)` is correctly translated.

**Comment by bilak** [comment]
the same issue is present also for BIGING (e.g. `BIGINT(19)`)

**Comment by ErrorProne** [comment]
exact same problem with liquibase 4.15.0
