### ISSUE TITLE
MigrationFailedException while updating version from 3.8.9 to 4.10.0 

### ISSUE THREAD

**Issue by PavelEzhkov** [liquibase/liquibase#3125]
## Environment

**Liquibase Version**: 3.8.9, 4.10.0 

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: no

**Database Vendor & Version**: postgres 11.5

**Operating System Type & Version**: MacOs

## Description

We are trying to update liquibase core version from 3.8.9 to 4.10.0 and get MigrationFailedException when run our old scripts

## Steps To Reproduce
our script looks like: 
`<createTable tableName="xxx" schemaName="schema" remarks="remarks">
            <column name="xxx_id" type="bigserial" remarks="remarks">
                <constraints primaryKey="true"/>
...
        <createSequence sequenceName="xxx_id_seq" schemaName="schema"/>
        <addDefaultValue tableName="xxx" schemaName="schema"
                         columnName="xxx_id"
                         defaultValueSequenceNext="xxx_id_seq"/>`

## Actual Behavior
script fails
`liquibase.exception.MigrationFailedException: Migration failed for change set classpath:db/changelog/scriptname.xml:
     Reason: liquibase.exception.DatabaseException: ERROR: column "xxx_id" of relation "xxx" is an identity column [Failed SQL: (0) ALTER TABLE schema.xxx ALTER COLUMN  xxx_id SET DEFAULT nextval('schema.xxx_id_seq')]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:696)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Scope.child(Scope.java:247)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65)
	... 196 common frames omitted
...
Caused by: org.postgresql.util.PSQLException: ERROR: column "xxx_id" of relation "xxx" is an identity column
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
	... 221 common frames omitted`

## Expected/Desired Behavior
script will run

**Comment by PavelEzhkov** [comment]
to add 
I've changed `bigserial` to `bigint` and script run successfully, but we can't change the script

**Comment by kataggart** [comment]
@nvoxland I am guessing this has something to do with the changes made https://github.com/liquibase/liquibase/pull/874#, but I admit to not fully understanding the relationship with all the moving parts here.

**Comment by PavelEzhkov** [comment]
I debug it with different versions and 
4.10.0 with bigserial type generated script looks like: CREATE TABLE .xxx (xxx_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,...
then 4.10.0 with bigint  and 3.8.9 CREATE TABLE .xxx (xxx_id BIGINT NOT NULL

maybe it can help you somehow

**Comment by lbadam** [comment]
I'm going to close this issue as it is 2 years old. If you still have this issue, please retest with a more recent version (currently latest is 4.29.2) and reopen. Thanks!
