### ISSUE TITLE
picocli class not found error reported when querying for liquibase version

### ISSUE THREAD

**Issue by hemabs** [liquibase/liquibase#3160]
hi, 

**Environment**

Liquibase Version: 4.8.0
Liquibase Integration & Version: CLI - downloaded liquibase-4.8.0.tar.gz fie from https://github.com/liquibase/liquibase/releases/tag/v4.8.0
Liquibase Extension(s) & Version: N/A
Database Vendor & Version: postgres (PostgreSQL) 9.6.13
Operating System Type & Version: CentOS 7

**Description**
we are moving from liquibase 2.0.1 version to liquibase 4.8 version in CentOS VM. Liquibase untarred files from liquibase-4.8.0.tar.gz are put here:
ls -lrt /usr/local/lib/liqui*
-rwxr-xr-x 1 root root    2180 Jul 31 21:08 /usr/local/lib/liquibase
-rwxr-xr-x 1 root root 6688205 Jul 31 21:08 /usr/local/lib/liquibase.jar

It complains about picocli class not found error when queried for liquibase version. 
So, we added the picocli-4.6.1.jar in path: /usr/local/lib and in /usr/local/jre/lib. This is the PATH env variable:
echo $PATH
/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/jre/bin:/usr/local/jre/lib:/usr/local/lib

But still complains of below error:
$ /usr/local/lib/liquibase --version
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: picocli/CommandLine$Model$ArgSpec
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: picocli.CommandLine$Model$ArgSpec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more

Below is where jre is download and put in the VM:

$ ls -lrt /usr/local/jre
total 44
-rwxr-xr-x  1 root root  123 Jul 27 03:01 release
-rwxr-xr-x  1 root root  955 Jul 27 03:01 Welcome.html
-rwxr-xr-x  1 root root  190 Jul 27 03:01 THIRDPARTYLICENSEREADME.txt
-rwxr-xr-x  1 root root  190 Jul 27 03:01 THIRDPARTYLICENSEREADME-JAVAFX.txt
-rwxr-xr-x  1 root root   46 Jul 27 03:01 README
-rwxr-xr-x  1 root root   44 Jul 27 03:01 LICENSE
-rwxr-xr-x  1 root root 3244 Jul 27 03:01 COPYRIGHT
drwxr-xr-x  2 root root 4096 Jul 27 03:12 bin
drwxr-xr-x  4 root root 4096 Jul 27 03:12 legal
drwxr-xr-x  3 root root 4096 Jul 27 03:12 plugin
drwxr-xr-x 15 root root 4096 Aug  4 11:18 lib

JRE version is 1.8.0_321.

Could you please help what is wrong here?

**Comment by kataggart** [comment]
@hemabs Can you start with a new install, untar the file and then leave things where they are?

**Comment by hemabs** [comment]
Thanks @kataggart, the solution suggested above worked for us. Earlier we were just moving liquibase and liquibase.jar file selectively from the downloads.

**Comment by kataggart** [comment]
WOO HOO!!! So glad @hemabs !
