### ISSUE TITLE
StringIndexOutOfBoundsException if date is set to 1970-01-01

### ISSUE THREAD

**Issue by MDoswaldSchiller** [liquibase/liquibase#3317]
When running liquibase on a host that has no date set (and it is therefore set to 1970-01-01, e.g. because the battery of the RTC is empty), the AbstractChangeLogHistoryService.generateDeploymentId method throws an exception:

```
 java.lang.StringIndexOutOfBoundsException: begin -4, end 6, length 6<CR><LF>
                at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)<CR><LF>
                at java.base/java.lang.String.substring(Unknown Source)<CR><LF>
                at java.base/java.lang.String.substring(Unknown Source)<CR><LF>
                at liquibase.changelog.AbstractChangeLogHistoryService.generateDeploymentId(AbstractChangeLogHistoryService.java:131)<CR><LF>
                at liquibase.Liquibase.lambda$update$1(Liquibase.java:229)<CR><LF>
                at liquibase.Scope.lambda$child$0(Scope.java:180)<CR><LF>
                at liquibase.Scope.child(Scope.java:189)<CR><LF>
                at liquibase.Scope.child(Scope.java:179)<CR><LF>
                at liquibase.Scope.child(Scope.java:158)<CR><LF>
                at liquibase.Liquibase.runInScope(Liquibase.java:2405)<CR><LF>
                ... 14 more<CR><LF>
```

The root cause can be found in the implementation of generateDeploymentId:

```
String dateString = String.valueOf(new Date().getTime());
this.deploymentId = dateString.substring(dateString.length() - 10);
```
The method assumes that the time in milliseconds converted to a string results in a string that has at least length 10. If the date is close to the start of the era (1970-01-01) this may not be the case and the substring call fails with an exception because the index is negative.

**Comment by FBurguer** [comment]
Hi, can you give us a little more context on the situation? Like the changeset that is failing and with which db you are getting the problem? Thanks!

**Comment by MDoswaldSchiller** [comment]
Hi, 
I am using sqlite as a database. The changeset I am using is just inserting a table with some columns. But I believe it has nothing to do with either the database or the changeset. I just run liquibase.update("production") on my liquibase object. This will call the runInScope method which will in turn generate the deploymentId before any changeset is actually run. But that already fails.

So the cause of the problem is, as stated above, not the database or changelog, but the code mentioned above that will cause an exception as soon as new Date().getTime() returns a number smaller than 1000000000. The exception will happen with any database or changelog.
To reproduce, you therefore need to set the time of your system to e.g. 1970-01-01 01:00:00 (note that you may need to adapt that depending on your timezone because java.util.Date.getTime() returns the milliseconds since 1970-01-01 00:00:00 GMT)
