### ISSUE TITLE
generateChangeLog - SEVERE [liquibase.integration] Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by ia-jladew** [liquibase/liquibase#3334]
## Environment
MacBook
**Liquibase Version**:
4.16.1
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
NA
**Liquibase Extension(s) & Version**: 
NA

**Database Vendor & Version**:
mysql  Ver 14.14 Distrib 5.7.37, for Linux (x86_64)

**Operating System Type & Version**:
Ubuntu 18.04.6 LTS x86_64
**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
VM - vmware

## Description
I want to generate a base line against my production schema. I ran the following command:
liquibase --changelog-file=db.customercare.changelog-baseline.mysql.sql --logLevel=DEBUG generateChangeLog

I'll put the full debug statement in a file.

SEVERE [liquibase.integration] Index 0 out of bounds for length 0
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at liquibase.command.CommandScope.execute(CommandScope.java:179)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:353)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liq
[debug-file.txt](https://github.com/liquibase/liquibase/files/9700464/debug-file.txt)
uibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:318)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

I will put the debug info in a file.

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

**Comment by ia-jladew** [comment]
Same error occurs using the Windows binaries.
Also exporting to XML gets same error as well.

**Comment by nvoxland** [comment]
It seems to be an issue with the snapshot logic in how it's storing the column information of an index. In particular, in it's doing some checks with foreign keys.

Do you have any foreign keys on "virtual" columns? Like where you have them on a computed column or something?

**Comment by ia-jladew** [comment]
I found a table that has an FK referencing a table that does not exist in
any schema.

How is that possible unless mysql allows a "forced" drop. Anyways, I'm
going to figure out If I can simply drop the FK or recreate table and its
FKs without breaking replication, which is my only concern here.


Jason Ladew
Senior IT Project Manager
Inductive Automation
1.800.266.7798 ext. 250 (Within USA)
1.916.456.1045 ext. 250 (International)
[image: Inductive Automation] <https://inductiveautomation.com/>

**Comment by ia-jladew** [comment]
Hello, So the above turned out to be the issue. There was a table that had a Foreign Key referencing a table that did not exist. As soon as it was dropped, the generateChangeLog was able to complete with no errors.

**Comment by FBurguer** [comment]
Thanks for figuring it out! We will add it to our queue.

**Comment by FBurguer** [comment]
I tried to reproduce this behavior, first I updated this changelog

```
    <changeSet id="1" author="TEST">
        <createTable tableName="A">
            <column name="A" type="INT">
                <constraints unique="true"/>
            </column>
        </createTable>
    </changeSet>

    <changeSet id="2" author="TEST">
        <createTable tableName="B">
            <column name="B" type="INT">
                <constraints unique="true"/>
            </column>
        </createTable>
    </changeSet>

    <changeSet id="3" author="TEST">
        <addForeignKeyConstraint constraintName="fk_a"
                                 baseColumnNames="A"
                                 baseTableName="A"
                                 referencedColumnNames="B"
                                 referencedTableName="B"/>
    </changeSet>
```
Then, forced droped Table B and used generateChangelog, this is the generated changelog:
```
    <changeSet author="FBurguer (generated)" id="1664981726130-1">
        <createTable tableName="A">
            <column name="A" type="INT">
                <constraints unique="true"/>
            </column>
        </createTable>
    </changeSet>
    <changeSet author="FBurguer (generated)" id="1664981726130-2">
        <addForeignKeyConstraint baseColumnNames="A" baseTableName="A" constraintName="fk_a" deferrable="false" initiallyDeferred="false" onDelete="RESTRICT" onUpdate="RESTRICT" referencedColumnNames="" referencedTableName="B" validate="true"/>
    </changeSet>
```
It doesnt fail, but creates changeset with the referenced column atribute empty.

**Comment by ia-jladew** [comment]
no problem. If anything thing that should be fixed or enhanced is:

   1. Add more debug to show what object it is failing on. I had DEBUG
   turned on and just got JAVA errors which is almost useless to us common
   folk.
   2. Mark these with a "warning" and log it in the liquibase log file.
   Perhaps a flag that allows to generate it into the changelog file if true.
   Don't by default.

In a way I was glad it threw up an exception as this should not exist in
any production DB and should be fixed. So Thanks.

Jason Ladew
Senior IT Project Manager
Inductive Automation
1.800.266.7798 ext. 250 (Within USA)
1.916.456.1045 ext. 250 (International)
[image: Inductive Automation] <https://inductiveautomation.com/>

**Comment by FBurguer** [comment]
Thank YOU,  for submitting this issue!

**Comment by ia-jladew** [comment]
Hello,
I'm actually going through all the table/indexes, PKs, FKs etc that don't
exist in DEV (generateChangeLog works in DEV) that exist in production and
creating them in DEV to see if I can reproduce the error in DEV. I'll check
and let you know.

Jason Ladew
Senior IT Project Manager
Inductive Automation
1.800.266.7798 ext. 250 (Within USA)
1.916.456.1045 ext. 250 (International)
[image: Inductive Automation] <https://inductiveautomation.com/>
