### ISSUE TITLE
listUnrunChangeSets throws NPE when MSSQL with case-sensitive collation

### ISSUE THREAD

**Issue by bvremmeinfor** [liquibase/liquibase#3415]
## Environment

**Liquibase Version**: 4.17.0

**Liquibase Integration & Version**: 

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: SQL Server 2019-CU11 (mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04)

**Operating System Type & Version**:

**Infrastructure Type/Provider**: 

## Description

When using collation 'Latin1_General_BIN2' Liquibase cannot list unrun change-sets.

Fails with exception:
```
Caused by: liquibase.exception.LiquibaseException: java.lang.NullPointerException
	at liquibase.Liquibase.runInScope(Liquibase.java:2452)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:2018)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:2009)
	at as.merit.portal.grid.shared.landlorddb.LandlordDatabaseMaintenance.liquibaseUpdate(LandlordDatabaseMaintenance.java:36)
	... 31 more
Caused by: java.lang.NullPointerException
	at liquibase.snapshot.jvm.ColumnSnapshotGenerator.readDataType(ColumnSnapshotGenerator.java:539)
	at liquibase.snapshot.jvm.ColumnSnapshotGenerator.readColumn(ColumnSnapshotGenerator.java:392)
	at liquibase.snapshot.jvm.ColumnSnapshotGenerator.addTo(ColumnSnapshotGenerator.java:201)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:79)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:244)
	at liquibase.snapshot.SnapshotGeneratorFactory.getDatabaseChangeLogTable(SnapshotGeneratorFactory.java:252)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:109)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1953)
```
Collation 'SQL_Latin1_General_CP1_CI_AS' is OK.

## Steps To Reproduce

Use SQL Server with collation 'Latin1_General_BIN2'.

## Additional Context
Error introduced in 4.17.0. Related to #3102, have attempted build with commit 8512769590ae3175982c34b4f91d3ff33abdf377 reverted and all is good. #3102 has undesirable side effects for MSSQL when case-sensitive collation is used.

Error occurs in ColumnSnapshotGenerator#539
`int dataType = columnMetadataResultSet.getInt("DATA_TYPE");`

The resultset created in JdbcDatabaseSnapshot.mssqlquery() has some lowercase fields (all other uppercase):
- is_filestream
- is_rowguidcol
- data_type

When collation is case-sensitive the fields *remain lowercase in the result-set* and getInt("DATA_TYPE") throws NPE.

**Comment by ivan909020** [comment]
Hello, the field alias is uses lower-case [here](https://github.com/liquibase/liquibase/blob/2010daa8396e0e7569660183851a02d387195af2/liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java#L611), but [here](https://github.com/liquibase/liquibase/blob/137ced1ed9383d4de80aebe1dc3f1ecf4b831414/liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java#L431) it uses upper-case. Maybe changing it to same format will solve this issue?

**Comment by zwhitten** [comment]
Nice @ivan909020! you beat me to it. haha
