### ISSUE TITLE
PostgreSQL 15 data export

### ISSUE THREAD

**Issue by tavoda** [liquibase/liquibase#3464]
## Environment

**Liquibase Version**: 4.17.2

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: **PostgreSQL 15**, other PSQL versions are OK

**Operating System Type & Version**: Linux

## Description
Data export doesn't work.

## Steps To Reproduce
        $LIQUIBASE_HOME/liquibase --classpath=$CLASSPATH \                                              
                generateChangeLog \                                                                     
                        --diffTypes=data \                                                              
                        --driver=org.postgresql.Driver \
                        --url=$ORIGCONN \
                        --username=$ORIGUSER \
                        --password=$ORIGPASSWORD \
                        --changelog-file=$CH_FILE   

## Actual Behavior
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
        at liquibase.diff.output.changelog.core.MissingDataChangeGenerator.fixMissing(MissingDataChangeGenerator.java:66)
        ... 47 more
Caused by: org.postgresql.util.PSQLException: ERROR: CASE types text and "char" cannot be matched
  Position: 939
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
        at liquibase.executor.jvm.JdbcExecutor$QueryStatementCallback.doInStatement(JdbcExecutor.java:511)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:78)
        at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:202)
        at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:210)
        at liquibase.executor.jvm.JdbcExecutor.queryForList(JdbcExecutor.java:275)
        at liquibase.executor.jvm.JdbcExecutor.queryForList(JdbcExecutor.java:270)
        at liquibase.diff.output.changelog.DiffToChangeLog.addDependencies(DiffToChangeLog.java:631)
        at liquibase.diff.output.changelog.DiffToChangeLog.sortObjects(DiffToChangeLog.java:369)
        at liquibase.diff.output.changelog.DiffToChangeLog.sortMissingObjects(DiffToChangeLog.java:337)
        at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:278)
        ... 44 more

## Expected/Desired Behavior
Export all tables

## Additional Context
You have to fix query in DiffToChangeLog.queryForDependenciesPostgreSql():
from this:
    `WHEN 'pg_constraint'::regclass THEN (SELECT CONTYPE FROM pg_constraint WHERE oid = objid)`
to this (add ::text cast to end):
    `WHEN 'pg_constraint'::regclass THEN (SELECT CONTYPE FROM pg_constraint WHERE oid = objid)::text`

**Comment by tavoda** [comment]
Fixed in 4.18.0
