### ISSUE TITLE
`includeAll` with `classpath:` prefix does not work anymore in 4.17

### ISSUE THREAD

**Issue by famod** [liquibase/liquibase#3524]
## Environment

**Liquibase Version**: 4.17.2

**Liquibase Integration & Version**: quarkus

**Database Vendor & Version**: MariaDB 10.6.11

**Operating System Type & Version**: Ubuntu 22.04

## Description

- module A has `src/main/resources/db/a` with some changelog files
- module B depends on A
- module B has a changelog file with  `<includeAll path="classpath:/db/a/" errorIfMissingOrEmpty="false" />`
- Liquibase is run in module B

With Liquibase 4.16.1 this works just fine but with 4.17.2 the files in `db/a`  are not executed.

## Steps To Reproduce

See description. Sorry, I don't have time ATM to provide a reproducer.

## Actual Behavior
All files are found and are included.

## Expected/Desired Behavior
Nothing is found/included.

## Additional Context
There is an *easy workaround*: Just drop the `classpath:/` prefix!

**Comment by famod** [comment]
> There is an **easy workaround**: Just drop the `classpath:/` prefix!

Turns out this only works in `@QuarkusTest`s (in a multi-module project) but not in the actual Quarkus app (which uses a different classloading setup).
So for me this is basically a blocker in 4.17+.

**Comment by famod** [comment]
FTR: Still an issue in 4.18.0.

**Comment by famod** [comment]
FTR: Still an issue in 4.19.0...sadly. :disappointed:

**Comment by famod** [comment]
Still unfixed, so I digged into this:

https://github.com/liquibase/liquibase/commit/831ca99a5200905d1f635961bbd94e1f63468f5a seems to have moved all `classpath:` logic to `SpringResourceAccessor`, but Quarkus is using `ClassLoaderResourceAccessor` (which does make sense).

I can see during debugging that the `classpath:` prefix is never removed/resolved but is instead passed on to the respective `ClassLoader` - which obviously doesn't support such a prefix and finds nothing.
So while this alone could possibly be considered a bug, it kinda makes sense to me to not use that prefix anymore.
Dropping it makes the `QuarkusTest`s run fine because the Quarkus ClassLoader provides the files in that mode as plain file paths (and not jar paths).

Now, in "prod" mode (hierarchical jar classloading, in my case JVM mode in jib-built docker container) the included files must be loaded from jars which doesn't work (reminder: this is without the `classpath:` prefix):
```
java.io.IOException: Cannot parse resource location: 'jar:file:/home/famod/proj/quarkus-quickstarts/liquibase-quickstart/target/quarkus-app/app/liquibase-quickstart-1.0.0-SNAPSHOT.jar!/db/included'
        at liquibase.resource.PathHandlerFactory.getResourceAccessor(PathHandlerFactory.java:35)
        at liquibase.resource.ClassLoaderResourceAccessor.search(ClassLoaderResourceAccessor.java:124)
        at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:662)
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:490)
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
        at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:406)
        at liquibase.Liquibase.validate(Liquibase.java:2321)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:67)
        ...
```
The problem is that `ZipPathHandler` is rejecting (in `getPriority`) the given path/url because it contains _a path within_ the respective jar which makes the path a "non-root" path: https://github.com/liquibase/liquibase/blob/v4.18.0/liquibase-core/src/main/java/liquibase/resource/ZipPathHandler.java#L30
So, the **root cause** seems to be that `ClassLoaderResourceAccessor` ignores the fact that `getPriority` of such a handler needs to be called with the root path: https://github.com/liquibase/liquibase/blob/v4.18.0/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L119-L124
Another take on the root cause might be that `ZipPathHandler` should be more lenient, but the root vs. path separation seems to be concious design decision (looking at `liquibase.resource.PathHandler` interface).

Good news: `PathHandler` is loaded via `ServiceLoader`, which opens up a way to **work around** this issue (until fixed properly):
The idea is to provide a `ZipPathHandler` that is more lenient:
```java
public class PatchedZipPathHandler extends ZipPathHandler {

    @Override
    public int getPriority(String root) {
        if (root != null && root.startsWith("jar:") && root.contains("!/")) {
            return PRIORITY_SPECIALIZED;
        }
        return super.getPriority(root);
    }

    @Override
    public ResourceAccessor getResourceAccessor(String root) throws FileNotFoundException {
        int idx = root.indexOf("!/");
        return super.getResourceAccessor(root.substring(0, idx));
    }
}
```
and register it via `src/main/resources/META-INF/services/liquibase.resource.PathHandler`.

@nvoxland WDYT?

/cc @geoand

**Comment by geoand** [comment]
@famod excellent analysis! 

I am fine with the `PatchedZipPathHandler` idea so as to get things unblocked for now

**Comment by nvoxland** [comment]
Good you found a solution so far, sorry for the slow response.

The overall goal of the ResourceAccessor setup is that paths in changelog files should be able to be consistent regardless of how the files end up being structured/stored since the same changelog files are often ran in different ways. For example, on startup of quarkus when they are in a jar but also through a CLI when they are in the `target` directory.

So file references in the changelog file should never really have a prefix or "root location" of any type on them. It should just be `path="/db/a"` and it will look that up in whatever ResourceAccessor is configured. 

However, for compatibility with older versions of liquibase we should be ignoring the "classpath:" prefix, and that ignoring is maybe too specific to the SpringResourceAccessor which was what it was originally added for back in the day. For sure it could be stripped off in ClassLoaderResourceAccessor, but maybe even more generically in liquibase?

For the comments about `jar:file:/home/famod/proj/quarkus-quickstarts/liquibase-quickstart/target/quarkus-app/app/liquibase-quickstart-1.0.0-SNAPSHOT.jar!/db/included` -- what is in the changelog file when you were hitting the problem? Was it `path="/db/included"`? Or something else?

**Comment by famod** [comment]
@nvoxland (sorry for the late reply)

> For the comments about `jar:file:/home/famod/proj/quarkus-quickstarts/liquibase-quickstart/target/quarkus-app/app/liquibase-quickstart-1.0.0-SNAPSHOT.jar!/db/included` -- what is in the changelog file when you were hitting the problem? Was it `path="/db/included"`? Or something else?

AFAIR, I tried both `path="/db/included"` and `path="db/included"`, no difference!
I believe I also tried adding a trailing slash.

**Comment by famod** [comment]
Friendly reminder @nvoxland :arrow_up: :slightly_smiling_face: 
I'd like to remove that workaround in Quarkus at some point.

**Comment by tati-qalified** [comment]
Hi @famod , I was able to replicate this issue in version 4.23, so it seems like it hasn't been fixed yet.
I'll forward it to the development team so they can evaluate how to move forward.

**Comment by famod** [comment]
Hi @tati-qalified, any news on that? Thanks!

**Comment by rastislavpapp** [comment]
I've also experienced it and tried to apply the workaround above (`PatchedZipPathHandler`), eventually finding out that Quarkus incorporated this fix into its codebase (as `io.quarkus.liquibase.LiquibaseLenientZipPathHandler`). The problem for me was that I used `includeAll="/db/v1"`, when I switched to `includeAll="db/v1"` (no starting slash), it worked.

**Comment by MalloD12** [comment]
I think this could have been already fixed by a recent change. @tati-qalified could you please try again with the latest version?

**Comment by MalloD12** [comment]
Could someone please confirm this is still an `includeAll` issue? 

Thanks,
Daniel.

**Comment by tati-qalified** [comment]
This is fixed as of Liquibase 5.0.1 with Spring Boot 3.X
