### ISSUE TITLE
NullPointerException in SequenceSnapshotGenerator

### ISSUE THREAD

**Issue by Thomas-WB** [liquibase/liquibase#3542]
## Environment

**Liquibase Version**: 4.18.0

**Database Vendor & Version**: PostgresDatabase

**Operating System Type & Version**: Windows 10

## Description

In case the `SequenceSnapshotGenerator` is used by e.g. a `sequenceExists` precondition having no schema name set, the `SequenceSnapshotGenerator` fails at line 235 with a NullPointerException: "Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null"

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.base/java.lang.String.replace(String.java:2959)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.SequenceSnapshotGenerator.getSelectSequenceSql(SequenceSnapshotGenerator.java:235)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.SequenceSnapshotGeneratorSnowflake.getSelectSequenceSql(SequenceSnapshotGeneratorSnowflake.java:35)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.SequenceSnapshotGenerator.snapshotObject(SequenceSnapshotGenerator.java:89)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:66)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at deployment.gemini-web.war//liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
	at deployment.gemini-web.war//liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
	at deployment.gemini-web.war//liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
	at deployment.gemini-web.war//liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:244)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorFactory.has(SnapshotGeneratorFactory.java:133)
	at deployment.gemini-web.war//liquibase.precondition.core.SequenceExistsPrecondition.check(SequenceExistsPrecondition.java:59)
	at deployment.gemini-web.war//liquibase.precondition.core.NotPrecondition.check(NotPrecondition.java:35)
	at deployment.gemini-web.war//liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:40)
	at deployment.gemini-web.war//liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213)
	at deployment.gemini-web.war//liquibase.changelog.ChangeSet.execute(ChangeSet.java:601)
```

Please check SequenceSnapshotGenerator#getSelectSequenceSql(Schema schema, Database database):

`
String pgSequenceQuery = COMMON_PG_SEQUENCE_QUERY.replace("SCHEMA_NAME", schema.getName());
`

This happens because of the implementation in SnapshotGeneratorFactory#has(DatabaseObject example, Database database) which triggers searching the sequences without applying any default values on the first try.

It would also perform a seconds try with a default value applied, but the NullPointerException occurred already before.

## Steps To Reproduce

Use a sequence exists precondition without a schema:

```
<changeSet author="me" id="someId">
    <preConditions onFail="MARK_RAN">
        <sequenceExists sequenceName="mySequence" />
    </preConditions>
</changeSet>
```

## Actual Behavior

A NullpointerException occurs while checking if a sequence exists.

## Expected/Desired Behavior

Checking if sequences are existing is done correctly.

**Comment by FBurguer** [comment]
I could reproduce this issue on liquibase `4.18.0` adding it to the list of issues to fix. Thanks!

**Comment by djochim** [comment]
Hi @filipelautert, when is the next release planned, that the fix could be used?

**Comment by filipelautert** [comment]
Hello @djochim - hopefully around mid of next week!
