### ISSUE TITLE
ScopeManager is STILL getting confused when dealing with a heavy thread load

### ISSUE THREAD

**Issue by MarkTJohnson** [liquibase/liquibase#3554]
## Environment

**Liquibase Version**: 4.17

**Liquibase Integration & Version**:  gradle

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Microsoft SQL Server

**Operating System Type & Version**: linux kubernetes pods

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

The same as https://github.com/liquibase/liquibase/issues/2248 which I reported and thought was fixed in 4.17. 
 We deployed today to production and I'm seeing many Kibana messages like
`liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope pymuajkpzs when currently at scope pyeogsnvjy 	at liquibase.Liquibase.runInScope(Liquibase.java:2452) 	at liquibase.Liquibase.update(Liquibase.java:236) 	at liquibase.Liquibase.update(Liquibase.java:221) 	at liquibase.Liquibase.update(Liquibase.java:207) 	at liquibase.Liquibase.update(Liquibase.java:197) 	at com.concur.reportdbservice.manager.ReportingSchemaMgr.update(ReportingSchemaMgr.java:69) 	at com.concur.reportdbservice.service.ReportingSchemaService.updateDatabase(ReportingSchemaService.java:56) 	at com.concur.reportdbservice.service.MigTaskService.entityMigrate(MigTaskService.java:51) 	at com.concur.reportdbservice.thread.MigMigrateJob.executeJob(MigMigrateJob.java:27) 	at com.concur.reportdbservice.thread.Job.run(Job.java:46) 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 	at java.base/java.lang.Thread.run(Unknown Source) Caused by: java.lang.RuntimeException: Cannot end scope pymuajkpzs when currently at scope pyeogsnvjy 	at liquibase.Scope.exit(Scope.java:230) 	at liquibase.Scope.child(Scope.java:191) 	at liquibase.Scope.child(Scope.java:179) 	at liquibase.Scope.child(Scope.java:158) 	at liquibase.Liquibase.runInScope(Liquibase.java:2447) 	... 14 more
--`

Obviously with varying scope names.
## Steps To Reproduce
Same as https://github.com/liquibase/liquibase/issues/2248

## Actual Behavior
Same as https://github.com/liquibase/liquibase/issues/2248

## Expected/Desired Behavior
Same as https://github.com/liquibase/liquibase/issues/2248

**Comment by FBurguer** [comment]
Hello! Thanks for pointing this out. Can you check if you set correctly the `ThreadLocalScopeManager` on production?

**Comment by MarkTJohnson** [comment]
Where would we be doing that?  Here is the method we have for using liquibase.

`public void update(ReportingEntity reportingEntity, String context) throws Exception{
        try (Connection c = conMgr.getReportingDBConnection(reportingEntity.getConnectionInfo())) {
            Database db = DatabaseFactory.getInstance().findCorrectDatabaseImplementation((new JdbcConnection(c)));
            Liquibase lb = new Liquibase(changelogPath, new ClassLoaderResourceAccessor(), db);
            lb.update(context);
            closeDatabase(lb);
        } catch (Exception e) {
            if (exceptionCheckForPodRestart(e.getMessage()))
            {
                try {
                    releaseLock(reportingEntity);
                } catch (Exception e1) {
                    LOGGER.error("Error releasing DB lock: " + e1.getMessage(), e1);
                    throw e1;
                }
                update(reportingEntity, context);
            }
            else
            {
                LOGGER.error("Error updating database structure: " + e.getMessage(),e);
                throw e;
            }
        }`

**Comment by nvoxland** [comment]
To use the new ThreadLocalScopeManager you'd have to call `Scope.setScopeManager(new ThreadLocalScopeManager())` before setting up liquibase. 

Probably best as the first line of your `try` block, just before `Database db = DatabaseFactory.getInstance().findCorrectDatabaseImplementation((new JdbcConnection(c)));`

Does that help?

**Comment by MarkTJohnson** [comment]
I thought the ScopeManager was within the Liquibase code.  How would it work that I was use that code OUTSIDE the Liquibase object?

**Comment by nvoxland** [comment]
The ScopeManager is what liquibase uses, but you are able to configure how it works before liquibase does it's things. The default ScopeManager is `SingletonScopeManager` which doesn't take threads into account and just treats everything as global.

But, you can change the ScopeManager liquibase should use with that call to `Scope.setScopeManager`. It's like a configuration setting prior to running liquibase.

**Comment by tinakurian-pki** [comment]
@nvoxland It seems i'm facing the same issue on version 4.18.0. I've moved to use Scope.setScopeManager(new ThreadLocalScopeManager()).

<details>
<summary>NPE Message</summary>

```
2023-01-13 14:12:18 Running Changeset: tenant-tenant.xml::SCL-230::YW
2023-01-13 14:12:18 2023-01-13T19:12:18,328 dbadmin-service [vert.x-worker-thread-12] ERROR com.my.service.LiquibaseServiceImpl - Liquibase update failed for changeset <?xml version="1.0" encoding="utf-8" standalone="no"?>
2023-01-13 14:12:18 <databaseChangeLog logicalFilePath="tenant-tenant.xml"
2023-01-13 14:12:18     xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
2023-01-13 14:12:18     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
2023-01-13 14:12:18     xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
2023-01-13 14:12:18     xmlns:pro="http://www.liquibase.org/xml/ns/pro"
2023-01-13 14:12:18     xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
2023-01-13 14:12:18             http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
2023-01-13 14:12:18             http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
2023-01-13 14:12:18             http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd">
2023-01-13 14:12:18 
2023-01-13 14:12:18     <changeSet author="YW" id="SCL-230">
2023-01-13 14:12:18             <createTable tableName="tenant_custom_domain">
2023-01-13 14:12:18                     <column name="domain" type="text">
2023-01-13 14:12:18                             <constraints nullable="false" primaryKey="true" primaryKeyName="PK_TenantCustomDomain" />
2023-01-13 14:12:18                     </column>
2023-01-13 14:12:18 
2023-01-13 14:12:18                     <column name="sso" type="text">
2023-01-13 14:12:18                             <constraints nullable="true"  />
2023-01-13 14:12:18                     </column>
2023-01-13 14:12:18 
2023-01-13 14:12:18                     <column name="created_date" type="timestamp with time zone">
2023-01-13 14:12:18                             <constraints nullable="false" />
2023-01-13 14:12:18                     </column>
2023-01-13 14:12:18 
2023-01-13 14:12:18                     <column name="modified_date" type="timestamp with time zone">
2023-01-13 14:12:18                             <constraints nullable="false" />
2023-01-13 14:12:18                     </column>
2023-01-13 14:12:18 
2023-01-13 14:12:18             </createTable>
2023-01-13 14:12:18 
2023-01-13 14:12:18             <rollback>
2023-01-13 14:12:18                     DROP table IF EXISTS tenant_custom_domain;
2023-01-13 14:12:18             </rollback>
2023-01-13 14:12:18     </changeSet>
2023-01-13 14:12:18 
2023-01-13 14:12:18 </databaseChangeLog>
2023-01-13 14:12:18 
2023-01-13 14:12:18 liquibase.exception.LiquibaseException: java.lang.NullPointerException
2023-01-13 14:12:18     at liquibase.Liquibase.runInScope(Liquibase.java:2450) ~[my-service-0.0.1-SNAPSHOT-fat.jar:0.0.1-SNAPSHOT]
2023-01-13 14:12:18     at liquibase.Liquibase.update(Liquibase.java:235) ~[my-service-0.0.1-SNAPSHOT-fat.jar:0.0.1-SNAPSHOT]
2023-01-13 14:12:18     at liquibase.Liquibase.update(Liquibase.java:220) ~[my-service-0.0.1-SNAPSHOT-fat.jar:0.0.1-SNAPSHOT]
2023-01-13 14:12:18     at com.my.service.LiquibaseServiceImpl.validateLiquibaseChangeLog(LiquibaseServiceImpl.java:113) ~[my-service-0.0.1-SNAPSHOT-fat.jar:0.0.1-SNAPSHOT]
```

</details>

<details> 
<summary>Code Snippet</summary>

```
	public Promise<Boolean> validateLiquibaseChangeLog(Connection connection, String schemaName, String path,
			String changelogName) {
		Database database = null;
		Promise<Boolean> updated = Promise.promise();

		try {
			Scope.setScopeManager(new ThreadLocalScopeManager());
			database = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(connection));
			database.setDefaultSchemaName(schemaName);
		} catch (DatabaseException e) {
			// Handle error
			updated.fail("");
		}

		File directory = new File(URI.create(path));
		try (Liquibase liquibase = new liquibase.Liquibase(changelogName, new DirectoryResourceAccessor(directory),
				database)) {
			validateLiqubaseXml(liquibase, changelogName);
			liquibase.update(new Contexts(), new LabelExpression());
		} catch (Exception e) {
			// Handle error
			updated.fail("");
		}

		if (!updated.future().isComplete()) {
			updated.complete(Boolean.TRUE);
		}
		return updated;
	}
```

</details>

**Comment by MarkTJohnson** [comment]
We are seeing that NPE in our test environment. In 4.17.1.

**Comment by MarkTJohnson** [comment]
`liquibase.exception.LiquibaseException: java.lang.NullPointerException: Cannot invoke 'String.equals(Object)' because 'currentScope.scopeId' is null
	at liquibase.Liquibase.runInScope(Liquibase.java:2452)
	at liquibase.Liquibase.update(Liquibase.java:236)
	at liquibase.Liquibase.update(Liquibase.java:221)
	at liquibase.Liquibase.update(Liquibase.java:207)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at com.concur.reportdbservice.manager.ReportingSchemaMgr.update(ReportingSchemaMgr.java:72)
	at com.concur.reportdbservice.service.ReportingSchemaService.updateDatabase(ReportingSchemaService.java:56)
	at com.concur.reportdbservice.service.MigTaskService.entityMigrate(MigTaskService.java:51)
	at com.concur.reportdbservice.thread.MigMigrateJob.executeJob(MigMigrateJob.java:27)
	at com.concur.reportdbservice.thread.Job.run(Job.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke 'String.equals(Object)' because 'currentScope.scopeId' is null
	at liquibase.Scope.exit(Scope.java:229)
	at liquibase.Scope.child(Scope.java:191)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2447)
	... 14 more
`

**Comment by MarkTJohnson** [comment]
The ... 14 more is all that is in the stacktrace, I'm not omitting anything.

**Comment by nvoxland** [comment]
Definitely a bug in there somewhere. You shouldn't have to be ignoring exceptions...

@MarkTJohnson is seeing that the NPE is from `scopeId` not being set. It looks like scopeId is only being set in Scope.enter() on line 216. That's the place where most scopes get created. BUT there is also the root scope created in Scope line 76 and 108 which does not.

I wonder if what's happening is that your code ends up exiting out of even the root scope and when it hits that point it fails with the NPE?

If you move the generation of the scopeId from the enter() method and to where the field is defined so it's always set as part of Scope object construction, does that fix the problem?

**Comment by tinakurian-pki** [comment]
The `NPE` is very strange. It doesn't happen on every run. It's intermittent for us. Sometimes it happens during `liquibase.validate()` and other times it happens on `liquibase.update(...)`. Sometimes, irrespective of the error, all the tables get created, othertimes some or no tables are created.

**Comment by MarkTJohnson** [comment]
@nvoxland , please refer to the code I posted above.  We only create a liquibase object, we are not modifying the liquibase code at all.
I'm betting it is a fault in the code that is running off the end of the chain as you stated.

**Comment by tinakurian-pki** [comment]
Correction, the NPE actually isn't intermittent. The behaviour is what is intermittent. So, after ignoring all NPE's, i've noticed that after every few runs, liquibase fails to actually execute the changelog. Sometimes i partially starts and creates the changelog (liquibase managed) tables, but then quits and doesn't create any of the tables in our changelog. Othertimes, not even the liquibase managed tables are created. The NPE's are very consistently happening though. When the changelog has failed to execute, the StackTrace points to `ChangeLogIterator.java:127`

Is there a solution for this issue @nvoxland? We would like to use liquibase in our product, but may be forced to move away due to this issue ☹️ Any help would be appreciated.

**Comment by MarkTJohnson** [comment]
Would adding a scopeId value to the default constructor fix this?

`/**
     * Creates a new "root" scope.
     * Defaults resourceAccessor to {@link ClassLoaderResourceAccessor}.
     * Defaults serviceLocator to {@link StandardServiceLocator}
     */
    private Scope() {
         scopeId = "root";
    }`

**Comment by nvoxland** [comment]
Would you be able to create that change as a PR, @MarkTJohnson ?

**Comment by MarkTJohnson** [comment]
I did, https://github.com/liquibase/liquibase/pull/3756, but it looks like it needs something for the "Check if Build should be done" check.

**Comment by nvoxland** [comment]
Thanks! I'll take a look

**Comment by nvoxland** [comment]
Does the code in the PR fix the problem for you, @MarkTJohnson ? Or have you not been able to test it?

**Comment by MarkTJohnson** [comment]
I followed the steps to build and copied the resulting SNAPSHOT jar into my project to include it, but drilling into it all I could see was stubs.  I wasn't sure what I actually had.  What do I need to do so I could drill into the jar in debug mode?

**Comment by nvoxland** [comment]
If you run `mvn install` it should install the source.jar into your local maven repo and your IDE may find it. Or, should be somewhere in your IDE to say "the sources for this file are at X" and can point to your local liquibase repo
