### ISSUE TITLE
LoadData changeset executes super slow in Liquibase 4.17.2

### ISSUE THREAD

**Issue by guoapeng** [liquibase/liquibase#3556]
## Environment

**Liquibase Version**:

org.liquibase:liquibase-core:4.17.2

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

Gradle gradle-6.6-all.zip, spring 4.1.4.RELEASE, java version "1.8.0_321"

**Liquibase Extension(s) & Version**: 

No

**Database Vendor & Version**:

postgresql-14.6-1-windows-x64 

**Operating System Type & Version**:

Windows 11

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

Laptop: 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz   2.92 GHz
RAM: 16.0 GB

## Description

Liquibase LoadData executes super slow and throw "OutOfMemoryError: GC Overhead Limit Exceeded" exception if I don't porovide  less than 1G and more JVM memory .

## Steps To Reproduce

table definition and loadData config

```xml

<changeSet author="me" id="1">
        <preConditions onFail="MARK_RAN">
            <and>
                <or>
                    <dbms type="postgresql"/>
                    <dbms type="mysql"/>
                </or>
                <not>
                    <tableExists tableName="DICTIONARY"/>
                </not>
            </and>
        </preConditions>
        <createTable tableName="DICTIONARY">
            <column name="ID"
                    type="INTEGER"
                    autoIncrement="true"
                    incrementBy="1">
                <constraints primaryKey="true"/>
            </column>
            <column name="WORD" type="VARCHAR(200)">
                <constraints nullable="false"/>
            </column>
            <column name="PHONETIC_UK" type="VARCHAR(100)"/>
            <column name="PHONETIC_US" type="VARCHAR(100)"/>
            <column name="DEFINITION" type="VARCHAR"/>
            <column name="TRANSLATION" type="VARCHAR"/>
            <column name="POS" type="VARCHAR(50)"/>
            <column name="COLLINS" type="VARCHAR"/>
            <column name="OXFORD" type="VARCHAR"/>
            <column name="TAG" type="VARCHAR"/>
            <column name="BNC" type="VARCHAR"/>
            <column name="FRQ" type="VARCHAR(50)"/>
            <column name="EXCHANGE" type="VARCHAR"/>
            <column name="DETAIL" type="VARCHAR"/>
            <column name="AUDIO" type="VARCHAR"/>
        </createTable>
    </changeSet>

 <changeSet author="me" id="2">
        <loadData encoding="UTF-8" relativeToChangelogFile="true" usePreparedStatements="true" file="dictionary.csv"
                  tableName="DICTIONARY">
            <column name="DEFINITION" type="string" />
            <column name="TRANSLATION" type="string" />
            <column name="POS" type="string" />
            <column name="COLLINS" type="string" />
            <column name="OXFORD" type="string" />
            <column name="TAG" type="string" />
            <column name="BNC" type="string" />
            <column name="EXCHANGE" type="string" />
            <column name="DETAIL" type="string" />
            <column name="AUDIO" type="string" />
        </loadData>
    </changeSet>
```

there are 770612 records in the file dictionary.csv and total size is about 83.2 MB

and example records like below

```csv
ID,WORD,PHONETIC_UK,PHONETIC_US,DEFINITION,TRANSLATION,POS,COLLINS,OXFORD,TAG,BNC,FRQ,EXCHANGE,DETAIL,AUDIO
1,hood,,"hʊd","","n. 罩；风帽；（布质）面罩；学位连领帽（表示学位种类）nv. 覆盖；用头巾包；使(马,鹰等)戴头罩；给…加罩n[网络] 胡德；兜帽；引擎盖","","","","",0,0,"","",""
2,"s Gravenhage",,",skrɑ:vən'hɑ:ɡə","","[荷兰语]海牙(= Hague)","","","","",0,0,"","",""
3,tween,,twi:n,"","prep. [诗歌用语] = between [亦作 tweeny]","","","","",0,0,"","",""

```

List the steps to reproduce the behavior.

the command to reproduce the issue 

```bash
./gradlew clean build updateLocalDBSchema -x test
``` 

the command actually called the gradle task below to update PostgreSQL database.

```
task updateLocalDBSchema(type: JavaExec) {
    classpath sourceSets.main.runtimeClasspath
    main = mainClassName
    allJvmArgs = [ '-Xms128m', '-Xmx1024m']
    args "update", "--property-file", "/application.properties"
}

```

and the gradle task is actually to call the java method to update database in customized code.

```java

protected Integer updateDatabase() {
        try{
            SpringLiquibase liquibase = new SpringLiquibase();
            LOG.info("reading properties from {}", fileName);
           // the ParameterToolBuilder is nothing special just to load properties from a file to create a datasource.
            ParameterTool parameters = ParameterToolBuilder.buildParameterTool(fileName, new String[0]);
            LOG.info("Properties loaded as the following {}", parameters);
            liquibase.setDataSource(DbmConfiguration.dataSource(parameters));
            liquibase.setChangeLog("classpath:update_database.xml");
            liquibase.setShouldRun(true);
            liquibase.setResourceLoader(new DefaultResourceLoader());
            liquibase.afterPropertiesSet();
            return 0;
        }catch (LiquibaseException e) {
            LOG.error("Error happens when updating db schema", e);
            return 1;
        }
    }

```

## Actual Behavior

the db schema can be successfully created and the data can be imported in less than 2 minutes when I using liquibase version 3.5.4.

but after upgraded to liquibase to the latest 4.17.2 as of Dec 09 2022, it starts to throw OOM excepition if I don't provide more than 1G memory and run super slow after I set the Xmx to a large value and the process seems to be not responsive  and makes the whole computer stuck.

## Expected/Desired Behavior
I expect the speed of the database schema update to normal (less than 10 minutes ) at least not to slower than manually import.

## Screenshots (if appropriate)
stack infor when OOM happens
```bash
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.opencsv.RFC4180Parser.handleQuotes(RFC4180Parser.java:231)
	at com.opencsv.RFC4180Parser.parseLine(RFC4180Parser.java:127)
	at com.opencsv.AbstractCSVParser.parseLineMulti(AbstractCSVParser.java:66)
	at com.opencsv.CSVReader.primeNextRecord(CSVReader.java:271)
	at com.opencsv.CSVReader.flexibleRead(CSVReader.java:610)
	at com.opencsv.CSVReader.readNext(CSVReader.java:204)
	at liquibase.util.csv.CSVReader.readNext(CSVReader.java:36)
	at liquibase.change.core.LoadDataChange.generateStatements(LoadDataChange.java:297)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1250)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:679)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113)
	at liquibase.changelog.ChangeLogIterator$2$$Lambda$122/533698361.run(Unknown Source)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope$$Lambda$113/843686350.run(Unknown Source)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112)
	at liquibase.changelog.ChangeLogIterator$2$$Lambda$120/1677840544.run(Unknown Source)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope$$Lambda$113/843686350.run(Unknown Source)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope$$Lambda$113/843686350.run(Unknown Source)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
```

**Comment by FBurguer** [comment]
Hello! Can you try running liquibase on the cli and use liquibase update with the option `--monitor-performance=true`? Thanks!

**Comment by FBurguer** [comment]
Closing this issue for now. Feel free to re-open if needed. Thanks!
