### ISSUE TITLE
Incorrect documentation: DatabaseChangeLog - IncludeAll - errorIfMissingOrEmpty

### ISSUE THREAD

**Issue by jasonlyle88** [liquibase/liquibase#3565]
## Description

The documentation [here](https://docs.liquibase.com/concepts/changelogs/attributes/includeall.html) states that the `errorIfMissingOrEmpty` attribute defaults to `false`. However, the code [here](https://github.com/liquibase/liquibase/blob/4b5b1acbcefcbfa33754c5fd30807881bd8c4f45/liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java#L491) shows that the default is actually true.

## Steps To Reproduce

List the steps to reproduce the behavior.
Create a changelog that includes some valid change sets and an `includeAll` attribute. For the `includeAll` attribute do not specify the `errorIfMissingOrEmpty` attribute and set the path attribute to a non-existent path.

## Actual Behavior
The `errorIfMissingOrEmpty` default is true, rather than false and liquibase will fail to run any change sets.

## Expected/Desired Behavior
Documented behavior says this should not fail. I believe the documentation should be change to reflect the default value is "true" and that the code should remain the same.

**Comment by FBurguer** [comment]
Hello! I tried to reproduce the behavior but in my case `errorIfMissingOrEmpty` is defaulted to false, can you send a changelog example? Thanks!

**Comment by jasonlyle88** [comment]
I can reproduce with the following setup and change log example. Liquibase errors for me when I leave out the `errorIfMissingOrEmpty` attribute (commented out in the example below). However, if I include `errorIfMissingOrEmpty` and set it to false (the supposed default), Liquibase runs just fine.

My structure (notice, no directory called non_existent):
```
.
├── changelog.yml
└── liquibase.properties
```

changelog.yml:
```yaml
databaseChangeLog:
- changeSet:
    id: 1
    author: jlyle
    runOnChange: true
    runAlways: true
    preConditions:
        - onFail: MARK_RAN
        - onError: HALT
        - not:
            - tableExists:
                - tableName: tab_a
    changes:
        - createTable:
            tableName: tab_a
            columns:
                - column:
                    name: id
                    type: int
                    autoIncrement: true
                    constraints:
                        primaryKey: true
                        nullable: false
- includeAll:
    path: non_existent
    # errorIfMissingOrEmpty: false
```

Output if I don't include the `errorIfMissingOrEmpty` property:
```
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 11:27:01 (version 4.18.0 #5864 built at 2022-12-02 18:02+0000)
Liquibase Version: 4.18.0
Liquibase Community 4.18.0 by Liquibase
[2022-12-13 11:27:04] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-12-13 11:27:05] INFO [liquibase.lockservice] Successfully released change log lock
[2022-12-13 11:27:05] WARNING [liquibase.configuration] Potentially ignored key(s) in file exists at path liquibase.properties
 - 'changeLogFile'
 - 'password'
 - 'url'
 - 'username'
[2022-12-13 11:27:05] SEVERE [liquibase.integration] Error parsing changelog.yml
  - Caused by: Could not find directory or directory was empty for includeAll 'non_existent'
liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: Error parsing changelog.yml
	at liquibase.command.CommandScope.execute(CommandScope.java:178)
	at liquibase.integration.commandline.Main.handleUpdateException(Main.java:2191)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1835)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:396)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.integration.commandline.Main$1.run(Main.java:395)
	at liquibase.integration.commandline.Main$1.run(Main.java:217)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:217)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
	at liquibase.command.CommandScope.execute(CommandScope.java:172)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:352)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:317)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.ChangeLogParseException: Error parsing changelog.yml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:90)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:406)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:391)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:247)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2445)
	at liquibase.Liquibase.update(Liquibase.java:235)
	at liquibase.Liquibase.update(Liquibase.java:220)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1833)
	... 32 more
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'non_existent'
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:688)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:490)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:84)
	... 43 more
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'non_existent'
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:678)
	... 46 more


Unexpected error running Liquibase: Error parsing changelog.yml
  - Caused by: Could not find directory or directory was empty for includeAll 'non_existent'

liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: Error parsing changelog.yml
	at liquibase.command.CommandScope.execute(CommandScope.java:178)
	at liquibase.integration.commandline.Main.handleUpdateException(Main.java:2191)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1835)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:396)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.integration.commandline.Main$1.run(Main.java:395)
	at liquibase.integration.commandline.Main$1.run(Main.java:217)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:217)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
	at liquibase.command.CommandScope.execute(CommandScope.java:172)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:352)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:317)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.ChangeLogParseException: Error parsing changelog.yml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:90)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:406)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:391)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:247)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2445)
	at liquibase.Liquibase.update(Liquibase.java:235)
	at liquibase.Liquibase.update(Liquibase.java:220)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1833)
	... 32 more
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'non_existent'
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:688)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:490)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:84)
	... 43 more
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'non_existent'
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:678)
	... 46 more
```

Output if I do include the `errorIfMissingOrEmpty` property set to `false`:
```
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 11:18:23 (version 4.18.0 #5864 built at 2022-12-02 18:02+0000)
Liquibase Version: 4.18.0
Liquibase Community 4.18.0 by Liquibase
[2022-12-13 11:18:26] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-12-13 11:18:31] INFO [liquibase.changelog] Reading from LB.DATABASECHANGELOG
Running Changeset: changelog.yml::1::jlyle
[2022-12-13 11:18:32] INFO [liquibase.changelog] Marking ChangeSet: "changelog.yml::1::jlyle" as ran despite precondition failure due to onFail='MARK_RAN':
          changelog.yml : Not precondition failed

[2022-12-13 11:18:33] INFO [liquibase.lockservice] Successfully released change log lock
Liquibase command 'update' was executed successfully.
```

**Comment by FBurguer** [comment]
the documentation has been fixed! Thanks again
