### ISSUE TITLE
Relation "information_schema.constraints" does not exist

### ISSUE THREAD

**Issue by ymenchik** [liquibase/liquibase#3569]
## Environment

**Liquibase Version**: 4.17.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Vertica 11.02

**Operating System Type & Version**: macos

---

## Description
When running generate-changelog command 
`liquibase generate-changelog --changelog-file=changes.sql --username=XXXX --password=XXXXX --schemas=schema_name --url=jdbc:vertica://vertica-url:vertica_port/ --log-level=debug`

we are getting the following exception:
```
Caused by: liquibase.exception.DatabaseException: java.sql.SQLSyntaxErrorException: [Vertica][VJDBC](4568) ERROR: Relation "information_schema.constraints" does not exist
	at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:105)
	at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getUniqueConstraints(JdbcDatabaseSnapshot.java:1546)
	at liquibase.snapshot.jvm.UniqueConstraintSnapshotGenerator.listConstraints(UniqueConstraintSnapshotGenerator.java:138)
	at liquibase.snapshot.jvm.UniqueConstraintSnapshotGenerator.addTo(UniqueConstraintSnapshotGenerator.java:114)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:79)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:445)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:467)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:373)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:335)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:188)
	at liquibase.command.core.InternalDiffCommandStep.createReferenceSnapshot(InternalDiffCommandStep.java:188)
	at liquibase.command.core.InternalDiffCommandStep.createDiffResult(InternalDiffCommandStep.java:98)
	at liquibase.command.core.InternalGenerateChangelogCommandStep.run(InternalGenerateChangelogCommandStep.java:67)
	at liquibase.command.CommandScope.execute(CommandScope.java:173)
```

did anyone have this issue? What are we missing?

**Comment by FBurguer** [comment]
Hello! Do you have the Vertica Extention? Maybe thats the reason its not working for you.

**Comment by ymenchik** [comment]
off-course we have.
All other commands except generate-changelog are working fine.

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
