### ISSUE TITLE
Can't connect to cosmosdb from liquibase 

### ISSUE THREAD

**Issue by yrkhanal** [liquibase/liquibase#3583]
## Environment
Mac 12.1

**Liquibase Version**:
4.18

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Liquibase Extension(s) & Version**: 
Starting Liquibase at 23:18:16 (version 4.18.0 #5864 built at 2022-12-02 18:02+0000)

**Database Vendor & Version**:
CosmosDB Azure 

**Operating System Type & Version**:
Mac OS 12.1

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
Azure

## Description

Caused by: java.lang.IllegalStateException: Timeout on blocking read for 120000000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Mono.block(Mono.java:1731)
	at com.azure.cosmos.implementation.GlobalEndpointManager.init(GlobalEndpointManager.java:77)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.init(RxDocumentClientImpl.java:479)
	at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:259)
	at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:129)
	at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:779)
	at com.azure.cosmos.CosmosClient.<init>(CosmosClient.java:31)
	at com.azure.cosmos.CosmosClientBuilder.buildClient(CosmosClientBuilder.java:791)
	at liquibase.ext.cosmosdb.database.CosmosClientDriver.connect(CosmosClientDriver.java:35)

## Steps To Reproduce

connect to cosmos from Liquibase

## Actual Behavior
Timeout
## Expected/Desired Behavior
Connection to db

## Screenshots (if appropriate)
Not able to connect

## Additional Context
Used jars from spring boot that works

**Comment by FBurguer** [comment]
Hello! Sorry for the wait, can you provide me with an example changelog? Im trying to reproduce this issue.
