### ISSUE TITLE
Liquibase v4.18.0 : NullPointerException when having preConditions with sequenceExists 

### ISSUE THREAD

**Issue by brandonfl** [liquibase/liquibase#3598]
## Environment

**Liquibase Version**: 4.18.0

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**: liquibase-gradle-plugin:1.1.1

**Database Vendor & Version**: postgresql 14

**Operating System Type & Version**: Ubuntu 22.04

**Infrastructure Type/Provider**: Docker

## Description

**The issue is not present in Liquibase 4.17.2 but is present in liquibase 4.18.0**

When updating liquibase 4.17.2 => 4.18.0, changelog started to crash with null exceptions.
The changeset crashing have a preConditions with a sequenceExists

## Steps To Reproduce

Create a changeset as following  and replace the `...` : 

```xml
<changeSet id="1" author="BrandonFL">
    <preConditions onFail="MARK_RAN">
        <sequenceExists sequenceName="..." />
    </preConditions>

    <sql>...</sql>
</changeSet>
```

## Actual Behavior

Crash with `java.lang.NullPointerException: null`

```
 Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset src/main/resources/db/changelog/db.changelog-master.xml::1:: BrandonFL:
      Reason: java.lang.NullPointerException
 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:720) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:115) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:114) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:95) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.Scope.child(Scope.java:247) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:67) ~[liquibase-core-4.18.0.jar:na]
 	... 139 common frames omitted
 Caused by: java.lang.NullPointerException: null
 	at java.base/java.lang.String.replace(String.java:2143) ~[na:na]
 	at liquibase.snapshot.jvm.SequenceSnapshotGenerator.getSelectSequenceSql(SequenceSnapshotGenerator.java:235) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.jvm.SequenceSnapshotGeneratorSnowflake.getSelectSequenceSql(SequenceSnapshotGeneratorSnowflake.java:35) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.jvm.SequenceSnapshotGenerator.snapshotObject(SequenceSnapshotGenerator.java:89) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:66) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:244) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.snapshot.SnapshotGeneratorFactory.has(SnapshotGeneratorFactory.java:133) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.precondition.core.SequenceExistsPrecondition.check(SequenceExistsPrecondition.java:59) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:40) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213) ~[liquibase-core-4.18.0.jar:na]
 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:601) ~[liquibase-core-4.18.0.jar:na]
 	... 159 common frames omitted
```

## Expected/Desired Behavior

This should not crash !

**Comment by brandonfl** [comment]
The issue is not present in Liquibase 4.17.2 but is present in liquibase 4.18.0

**Comment by rusxakep** [comment]
It can't set up defaultSchema at code.
I think, if you set defaultSchema to changeSet directly it should be work (as workaround, sure).

**Comment by inanbayram** [comment]
This issue seems to be fixed in v4.20.0

**Comment by MalloD12** [comment]
Hi @brandonfl, 

I've tried with a changelog like the one below:

```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
    <changeSet id="1.1" author="nvoxland">
        <createSequence sequenceName="seq_person" startValue="150"/>
    </changeSet>

    <changeSet id="SeqPreconditionExists" author="BrandonFL">
        <preConditions onFail="MARK_RAN">
            <sequenceExists sequenceName="seq_person" />
        </preConditions>

        <sql>SELECT nextval('seq_person')</sql>
    </changeSet>
</databaseChangeLog>
```
against the latest version and couldn't reproduce this issue? Could you please retry with the latest version or 4.20+? 

If you can still reproduce this issue, can you please share all the steps you are performing?

Thanks,
Daniel.-

**Comment by brandonfl** [comment]
Hello @MalloD12, 

Just tested on the version v4.24.0 and the issue seems to be fixed.
Since the issue is fixed, I am closing the issue 

Thanks for the fix

Regards, 
BrandonFL
