### ISSUE TITLE
Problem with valueSequenceNext and valueClobFile with insert

### ISSUE THREAD

**Issue by tavoda** [liquibase/liquibase#3645]
## Environment

**Liquibase Version**:
4.18.0

**Database Vendor & Version**:
PostgreSQL 15

**Operating System Type & Version**:
Linux Debian testing (6.0.12-1)

## Description
Changeset doesn't run. End with exception:
```
[2023-01-05 19:11:04] SEVERE [liquibase.integration] Migration failed for changeset db/scripts/V_1_0_3-InsertMenuAndConfig.xml::2212311707::tavoda:
     Reason: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
  - Caused by: ERROR: column "hibernate_sequence" does not exist                                                                                                                                 
  Position: 142                                                                                 
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/scripts/V_1_0_3-InsertMenu.xml::2212311707::XXX:                                                                                                                                                               
     Reason: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at liquibase.command.CommandScope.execute(CommandScope.java:178)                                                                                                                         
        at liquibase.integration.commandline.Main.handleUpdateException(Main.java:2191)                                                                                                          
        at liquibase.integration.commandline.Main.doMigration(Main.java:1835)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:396)  
        at liquibase.Scope.lambda$child$0(Scope.java:180)                                                                                                                                        
        at liquibase.Scope.child(Scope.java:189)                                                                                                                                                 
        at liquibase.Scope.child(Scope.java:179)                
        at liquibase.Scope.child(Scope.java:158) 
        at liquibase.integration.commandline.Main$1.run(Main.java:395)
        at liquibase.integration.commandline.Main$1.run(Main.java:217)                                                                                                                           
        at liquibase.Scope.child(Scope.java:189)         
        at liquibase.Scope.child(Scope.java:165)                                                                                                                                                 
        at liquibase.integration.commandline.Main.run(Main.java:217)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
...
Caused by: org.postgresql.util.PSQLException: ERROR: column "hibernate_sequence" does not exist
  Position: 142
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at liquibase.statement.ExecutablePreparedStatementBase.executePreparedStatement(ExecutablePreparedStatementBase.java:168)
```

## Steps To Reproduce
ERROR:
```
        <insert tableName="XXX">
            <column name="id" valueSequenceNext="hibernate_sequence"/>
            <column name="props_storage" valueClobFile="../files/GuiMenu-list.json"/>
        </insert>
```
OK:
```
        <insert tableName="XXX">
            <column name="id" valueComputed="nextval('hibernate_sequence')"/>
            <column name="props_storage" valueClobFile="../files/GuiMenu-list.json"/>
        </insert>
```

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
