### ISSUE TITLE
Spring Integration doesn't work with logs not from classpath when using includes

### ISSUE THREAD

**Issue by reallyinsane** [liquibase/liquibase#3692]
## Environment

**Liquibase Version**: 4.18.0

**Liquibase Integration & Version**: Spring Boot 2.7.7

## Description

This is a follow-up of #1540. Initially resolving the changelog outside classpath did not work. This was resolved with #1540. When using includes the problem still exists.

The problem is the code resolving files defined with an include. But the problem also exisits for different kind of locations than classpath. The probelmatic code is in liquibase.changelog.DatabaseChangeLog#include(java.lang.String, boolean, liquibase.resource.ResourceAccessor, liquibase.ContextExpression, liquibase.Labels, java.lang.Boolean, liquibase.changelog.DatabaseChangeLog.OnUnknownFileFormat, liquibase.changelog.DatabaseChangeLog.ModifyChangeSets)

`
public boolean include(String fileName,
                           boolean isRelativePath,
                           ResourceAccessor resourceAccessor,
                           ContextExpression includeContextFilter,
                           Labels labels,
                           Boolean ignore,
                           OnUnknownFileFormat onUnknownFileFormat,
                           ModifyChangeSets modifyChangeSets)
            throws LiquibaseException {
        if (".svn".equalsIgnoreCase(fileName) || "cvs".equalsIgnoreCase(fileName)) {
            return false;
        }

        if (isRelativePath) {
            try {
                fileName = resourceAccessor.get(this.getPhysicalFilePath()).resolveSibling(fileName).getPath();
                fileName = Paths.get(fileName).normalize().toString()
                        .replace("\\", "/");
            } catch (IOException e) {
                throw new UnexpectedLiquibaseException(e);
            }
        }
...
`
When the filename is based on a file url the call to Path.normalize() will fail. I would suggest to not normalize when a protocol like file is used in the filename.

## Steps To Reproduce

- Simple Spring Boot application using a changelog with include specified with file protocol rather than classpath.
- Sample project https://github.com/reallyinsane/liquibase-3692

## Actual Behavior

Changelog defined as included cannot be loaded.

`Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:D:/.../src/main/liquibase/changelog-1.0.xml
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[na:na]
	at java.base/java.nio.file.Path.of(Path.java:147) ~[na:na]
	at java.base/java.nio.file.Paths.get(Paths.java:69) ~[na:na]
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:759) ~[liquibase-core-4.18.0.jar:na]
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:438) ~[liquibase-core-4.18.0.jar:na]
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376) ~[liquibase-core-4.18.0.jar:na]
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-4.18.0.jar:na]`

A clear and concise description of what happens in the software with the **version used**.
- The correctly resolved file to included should be loaded with file protocol.
- Before parsing file name is normalizes using Path.normalize() which does not work for url based names.

## Expected/Desired Behavior
Normalize is not called when a protocol like file protocol is used. When normalize call is skipped, everything works as expected.

**Comment by FBurguer** [comment]
Hello! To solve this you need to pass the searchPath param to liquibase with the path to the changelog and the pass the changelog file on the changelog param. We checked if there were any feature that allows that on springboot but couldnt find any, maybe to solve this you need to submit pr to springboot. I think the code is over [here](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase)

**Comment by reallyinsane** [comment]
I disagree. If you don't want to support other protocols than classpath then fine. Then this should be documented as I don't want to change the Spring Liquibase Autoconfiguration just because a different protocol. But the code I pointed at just requires to be a file path always. I also don't understand how specifying the searchPath will help with the code mentioned.

**Comment by tschniewind** [comment]
I have the same issue with
Liquibase Version: 4.18.0
Spring Boot: 2.7.10

I specify "spring.liquibase.change-log=file:build/database/liquibase/migration/dbchangelog.xml" as TestPropertySource for my SpringBootTest.

If I run the maven build under `Linux` with `openjdk version "17.0.5" 2022-10-18` everything is fine. 

Running it under `Windows` (STS 4.17.s or via maven within eclipse) with `OpenJDK 17.0.2` I get:
`Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:build/database/liquibase/migration/changes/feature-01-example-table/changesets.xml
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:812)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:452)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:388)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
	... 110 common frames omitted`
 
Maybe it has something todo with the special meaning of ':' under windows?

**Comment by FBurguer** [comment]
Hello! You are right that we should improve our documentation, but thats the way liquibase is design, the reason we dont support that kind of behavior is that Liquibase use the path to the changelog as part of the identifier of a changeset, you can read that over [here](https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html) . Using searchPath tells liquibase were to look for, if try to have a path like @tschniewind have, Im asuming its for dev env, if you stage those changes the path would change and the changeset will have a different identifier. We also should fix the
