### ISSUE TITLE
Table creation fails with H2 v2 when a change set specifies `autoIncrement="true"`

### ISSUE THREAD

**Issue by CynanX** [liquibase/liquibase#3745]
# Environment

Liquibase Version: 4.19.0

Liquibase Integration & Version: SpringBoot v3.0.2

Database Vendor & Version: H2 v2.1.214

Operating System Type & Version: MacOS v13.1

# Description

Since upgrading to H2 v2 my change set no longer applies.

# Steps To Reproduce

Create a change set such as this:

```xml
 <changeSet author="mark" id="createPersonsTable">
     <createTable tableName="persons">
         <column autoIncrement="true" name="personId" type="INT(10)"/>
         <column name="lastName" type="VARCHAR(255)"/>
         <column name="firstName" type="VARCHAR(255)"/>
         <column name="address" type="VARCHAR(255)"/>
         <column name="city" type="VARCHAR(255)"/>
     </createTable>
 </changeSet>
```

The magic part is the `autoIncrement="true"`.

Recreation is [here](https://github.com/CynanX/LiquibaseH2Issue).

# Actual Behavior

An exception is throw: -

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [uk/co/mark/LiquibaseConfiguration.class]: liquibase.exception.MigrationFailedException: Migration failed for changeset changelog/0.3.0/tables/example.xml::1::test-user:
     Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "CREATE TABLE PUBLIC.EXAMPLE (ID INT[*](10) GENERATED BY DEFAULT AS IDENTITY NOT NULL, NAME VARCHAR(45) NOT NULL, CONSTRAINT PK_EXAMPLE PRIMARY KEY (ID))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE PUBLIC.EXAMPLE (ID INT(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL, NAME VARCHAR(45) NOT NULL, CONSTRAINT PK_EXAMPLE PRIMARY KEY (ID)) [42001-214] [Failed SQL: (42001) CREATE TABLE PUBLIC.EXAMPLE (ID INT(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL, NAME VARCHAR(45) NOT NULL, CONSTRAINT PK_EXAMPLE PRIMARY KEY (ID))]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[spring-core-6.0.4.jar:6.0.4]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[spring-core-6.0.4.jar:6.0.4]
	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1386) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:543) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:184) ~[spring-test-6.0.4.jar:6.0.4]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:118) ~[spring-test-6.0.4.jar:6.0.4]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:127) ~[spring-test-6.0.4.jar:6.0.4]
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:191) ~[spring-test-6.0.4.jar:6.0.4]
```

# Expected/Desired Behavior

The table should be created.

# Additional Context

The above change set works fine when using H2 v1.x.

**Comment by FBurguer** [comment]
I tried to reproduce this issue and got the same behavior, but I noticed that if I removed the size of the column I dont get the issue any longer, so instead of using `INT(10)` use `INT` or `BIGINT`.  I hope this helps.

**Comment by FBurguer** [comment]
Hello! In that case I recommend doing a new issue with the specifics and I would add it to our queue of issues to fix, but I cant tell you how much time will take, so I can recommend you to submitt a PR to speed up the process. Thanks!

**Comment by FBurguer** [comment]
It looks like its indeed the way we manage `INT(**size**)` on` liquibase.datatype.core.IntType` class.

**Comment by CynanX** [comment]
> Hello! In that case I recommend doing a new issue with the specifics and I would add it to our queue of issues to fix…

I don’t understand - this is the issue with the specifics in that I created about it ?

**Comment by FBurguer** [comment]
Yes, sorry. It me who misunderstood the issue title. I will add this issue to the queue. Thanks
