### ISSUE TITLE
Failed to create parent directories doing diff

### ISSUE THREAD

**Issue by yelkolk** [liquibase/liquibase#3762]
## Environment

**Liquibase Version**: > 4.16.1

**Liquibase Integration & Version**: gradle plugin 2.1.1

**Liquibase Extension(s) & Version**: hibernate 6

**Database Vendor & Version**: PostgreSQL

**Operating System Type & Version**: MacBook Pro (13-inch, M1, 2020)

**Infrastructure Type/Provider**: Local

## Description

Migrating the spring boot version to version 3, we have detected that the execution of `diffChangeLog` is broken because the file cannot be created.

The exception that occurs in the logs is:

```
[2023-02-01 11:38:07] INFORMACIÓN [liquibase.diff] changeSets count: 2
[2023-02-01 11:38:07] INFORMACIÓN [liquibase.diff] src/main/resources/db/migrations/changelog/20230201113757.master.postgresql.sql does not exist, creating and adding 2 changesets.
[2023-02-01 11:38:07] ADVERTENCIA [liquibase.resource] Failed to create parent directories for file src/main/resources/db/migrations/changelog/20230201113757.master.postgresql.sql
[2023-02-01 11:38:07] GRAVE [liquibase.integration] src/main/resources/db/migrations/changelog/20230201113757.master.postgresql.sql
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.nio.file.NoSuchFileException: src/main/resources/db/migrations/changelog/20230201113757.master.postgresql.sql
        at liquibase.command.CommandScope.execute(CommandScope.java:179)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:54)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:23)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:353)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:318)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.nio.file.NoSuchFileException: src/main/resources/db/migrations/changelog/20230201113757.master.postgresql.sql
        at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:221)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1565)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:394)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:393)
        at liquibase.integration.commandline.Main$1.run(Main.java:215)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:215)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
        at liquibase.command.CommandScope.execute(CommandScope.java:173)
        ... 15 more
Caused by: liquibase.exception.CommandExecutionException: java.nio.file.NoSuchFileException: src/main/resources/db/migrations/changelog/20230201113757.master.postgresql.sql
        at liquibase.command.CommandScope.execute(CommandScope.java:179)
        at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:219)
        ... 28 more
Caused by: java.nio.file.NoSuchFileException: src/main/resources/db/migrations/changelog/20230201113757.master.postgresql.sql
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at liquibase.resource.PathResource.openOutputStream(PathResource.java:76)
        at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:214)
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:135)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:129)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:86)
        at liquibase.command.core.InternalDiffChangelogCommandStep.run(InternalDiffChangelogCommandStep.java:63)
        at liquibase.command.CommandScope.execute(CommandScope.java:173)
        ... 29 more
```

## Steps To Reproduce

Run this command using a Liquibase version greater than 4.16.1
`./gradlew diffChangeLog -PrunList=diff`

## Actual Behavior
The task fails because the file with the changesets cannot be created.

## Expected/Desired Behavior
It is expected to work as in 4.16.1 version, creating the file with the changesets

## Additional Context
I think it is not necessary to provide more information, the code already existed with certain configurations and works correctly in version 4.16.1. No paths are changed, only versions of the libraries (hibernate 5 to 6 for example) and H2 is added because it was used in the tests and it seems that it is no longer available as transitive dependency.

**Comment by FBurguer** [comment]
Hi! Im adding this bug to our queue of bugs to fix. If you can submit a pr with a fix, it could speed up the process. Thanks!

**Comment by kevin-atx** [comment]
@nvoxland says this change could impact things beyond gradle - namely, springboot. We could also test the function directly - a unit test.
