### ISSUE TITLE
ConcurrentModificationException when updating multiple schema's in parallel

### ISSUE THREAD

**Issue by jurgenkleverwal** [liquibase/liquibase#3788]
## Environment

**Liquibase Version**: 4.19.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: hibernate

**Database Vendor & Version**: postgresql

**Operating System Type & Version**: various

**Application runtime**: Wildfly 26.1.2

## Description

We're updating multiple schema's in parallel. As soon as two threads attempt to start updating their respective schema, a ConcurrentModificationExecption occurs.

	liquibase.exception.ChangeLogParseException: java.util.ConcurrentModificationException
		at deployment.iridium-util.ear//liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
		at deployment.iridium-util.ear//liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408)
		at deployment.iridium-util.ear//liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:393)
		at deployment.iridium-util.ear//liquibase.Liquibase.lambda$update$1(Liquibase.java:249)
		at deployment.iridium-util.ear//liquibase.Scope.lambda$child$0(Scope.java:180)
		at deployment.iridium-util.ear//liquibase.Scope.child(Scope.java:189)
		at deployment.iridium-util.ear//liquibase.Scope.child(Scope.java:179)
		at deployment.iridium-util.ear//liquibase.Scope.child(Scope.java:158)
		at deployment.iridium-util.ear//liquibase.Liquibase.runInScope(Liquibase.java:2431)
		at deployment.iridium-util.ear//liquibase.Liquibase.update(Liquibase.java:237)
		at deployment.iridium-util.ear//liquibase.Liquibase.update(Liquibase.java:222)
		at deployment.iridium-util.ear//liquibase.Liquibase.update(Liquibase.java:208)
		at deployment.iridium-util.ear.iridium-data-update.jar//nl.topicus.iridium.update.updater.steps.LiquibaseSchemaUpdateBatchlet.process(LiquibaseSchemaUpdateBatchlet.java:75)
		at org.jberet.jberet-core@1.3.13.Final//org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:76)
		at org.wildfly.extension.batch.jberet@26.1.2.Final//org.wildfly.extension.batch.jberet.deployment.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:189)
		at org.wildfly.extension.request-controller@18.1.2.Final//org.wildfly.extension.requestcontroller.ControlPointTask.run(ControlPointTask.java:46)
		at org.wildfly.extension.batch.jberet@26.1.2.Final//org.wildfly.extension.batch.jberet.thread.pool.WildFlyJobExecutor$1.run(WildFlyJobExecutor.java:72)
		at org.jberet.jberet-core@1.3.13.Final//org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
	Caused by: java.util.ConcurrentModificationException
		at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.getMethods(ObjectUtil.java:245)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.getReadMethod(ObjectUtil.java:208)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.hasReadProperty(ObjectUtil.java:96)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.hasProperty(ObjectUtil.java:85)
		at deployment.iridium-util.ear//liquibase.change.ColumnConfig.load(ColumnConfig.java:783)
		at deployment.iridium-util.ear//liquibase.change.AddColumnConfig.load(AddColumnConfig.java:48)
		at deployment.iridium-util.ear//liquibase.change.AbstractChange.load(AbstractChange.java:639)
		at deployment.iridium-util.ear//liquibase.changelog.ChangeSet.toChange(ChangeSet.java:541)
		at deployment.iridium-util.ear//liquibase.changelog.ChangeSet.handleChildNode(ChangeSet.java:464)
		at deployment.iridium-util.ear//liquibase.changelog.ChangeSet.load(ChangeSet.java:388)
		at deployment.iridium-util.ear//liquibase.changelog.DatabaseChangeLog.createChangeSet(DatabaseChangeLog.java:822)
		at deployment.iridium-util.ear//liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:413)
		at deployment.iridium-util.ear//liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376)
		at deployment.iridium-util.ear//liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
		... 21 more

**Comment by Aigul9** [comment]
@jurgenkleverwal hi! could you please share the approach to run multiple schemas in parallel? I'm searching for the similar solution
