### ISSUE TITLE
Liquibase has problem with multiple classloader Cannot find default log service error

### ISSUE THREAD

**Issue by sonersivri** [liquibase/liquibase#3819]
## Environment

**Liquibase Version**:
4.19.0

**Liquibase Integration & Version**: 
4.19.0

**Operating System Type & Version**:
Ubuntu 20.04

**Infrastructure Type/Provider**: 
VM

## Description
```java
   public static void main(String[] args) {
        try (Connection conn = DriverManager.getConnection(
                "jdbc:postgresql://ha-ds.zextras.test:5432/ha", "ha", "ha")) {

            if (conn != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
            Map<String, Object> config = new HashMap<>();
            Scope.child(config, () -> {
                Database database = DatabaseFactory
                        .getInstance()
                        .findCorrectDatabaseImplementation(new JdbcConnection(conn));
                try (Liquibase liquibase = new Liquibase("changelog.xml", new ClassLoaderResourceAccessor(), database)) {
                    liquibase.update(new Contexts(), new LabelExpression());
                }
            });
        } catch (SQLException e) {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
Code causes Cannot find default log service error when run jdk17
```log
liquibase.exception.UnexpectedLiquibaseException: Cannot find default log service
	at liquibase.Scope.getCurrentScope(Scope.java:87)
	at liquibase.Scope.enter(Scope.java:213)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at org.example.Main.main(Main.java:31)
```
## Steps To Reproduce
Code causes Cannot find default log service error when run jdk17

**Comment by sonersivri** [comment]
If there are multiple classloader then this occurs. Can not be reproduced easily.
At line https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/servicelocator/StandardServiceLocator.java#L21
ServiceLoader.load(interfaceType, interfaceType.getClassLoader()) should be also checked

**Comment by sonersivri** [comment]
I created Pull request https://github.com/liquibase/liquibase/pull/3820

**Comment by Wasalatantri** [comment]
@sonersivri I can reproduce this issue easily. All you have to do is set up liquibase as a Java-EE war and  pack into EAR Module . Afterward try to deploy into Jboss.

**Comment by MalloD12** [comment]
Hi @sonersivri, 

We've been trying to reproduce this issue by using code the main method shared in this issue using a custom classloader, but it didn't work.

**Environment**:

```
Liquibase Version:
4.19.0

Liquibase Integration & Version:
4.19.0

Operating System Type & Version:
macOS Ventura 13.1

```
```
public static void main(String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException {
        System.out.println("Liquibase version: " + LiquibaseUtil.getBuildVersion());
//        CustomLoader customLoader = new CustomLoader(Test.class.getClassLoader());
//        Class clas = customLoader.loadClass("liquibase.resource.ClassLoaderResourceAccessor");
//        Object o = clas.newInstance();
        try (Connection conn = DriverManager.getConnection(
                     "jdbc:postgresql://localhost:5438/lbcat", "postgres", "LbRootPass1")) {

            if (conn != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
            Map<String, Object> config = new HashMap<>();
            Scope.child(config, () -> {
                CustomLoader customLoader2 = new CustomLoader(Test.class.getClassLoader());
                Class clas2 = customLoader2.loadClass("liquibase.database.DatabaseFactory");
                Method main = clas2.getMethod("getInstance", null);
                Object o3 = main.invoke(null, null);

                Database database = ((DatabaseFactory)o3)
                        .findCorrectDatabaseImplementation(new JdbcConnection(conn));

                try (Liquibase liquibase = new Liquibase("changelog-1.xml", new ClassLoaderResourceAccessor(), database)) {
                    liquibase.update(new Contexts(), new LabelExpression());
                }
            });
        } catch (SQLException e) {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

Custom Classloader code:
```
public class CustomLoader extends ClassLoader {

    /**
     *Parent ClassLoader is set through the constructor
     */
    public CustomLoader(ClassLoader parent) {
        super(parent);
    }

    /**
     * Loads the class from the file system.
     * @param name
     * Fully Classified name of the class, for example, com.monali.Foo
     */
    private Class getClass(String name) throws ClassNotFoundException {
        String file = name.replace('.', File.separatorChar) + ".class";
        byte[] b = null;
        try {
            // This loads the byte code data from the file
            b = loadClassFileData(file);
            // defineClass is inherited from the ClassLoader class, it converts byte array into a Class.
            Class c = defineClass(name, b, 0, b.length);
            resolveClass(c);
            return c;
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * If the class is in com.monali package, we will use CustomLoader classloader otherwise delegate the
     * request to parent classloader.
     * @param name
     * Full class name
     */
    @Override
    public Class loadClass(String name) throws ClassNotFoundException {
        System.out.println("Loading Class '" + name + "'");
        if (name.startsWith("com.monali")) {
            System.out.println("Loading Class using CustomLoader");
            return getClass(name);
        }
        return super.loadClass(name);
    }

    /**
     * Reads the file (.class) into a byte array.
     * @param name Filename
     * @return Byte array read from the file
     * @throws IOException if an exception comes in reading the file
     */
    private byte[] loadClassFileData(String name) throws IOException {
        InputStream stream = getClass().getClassLoader().getResourceAsStream(
                name);
        int size = stream.available();
        byte buff[] = new byte[size];
        DataInputStream in = new DataInputStream(stream);
        in.readFully(buff);
        in.close();
        return buff;
    }
}
```
But it didn't work, we could see a single classloader is being used. Is there anything you can see wrong in this code I can change to be able to reproduce this issue/test your fix?

On the other hand, I would like to ask you if you (or @Wasalatantri) have any simple webapp code you guys can share with me so that at least I can manually verify the fix you have implemented.

Thanks,
Daniel.

**Comment by sonersivri** [comment]
> Hello [@sonersivri](https://github.com/sonersivri), I'm trying to reproduce this bug in order to test the PR you've created. It would be very helpful if you could provide either some feedback on Daniel's code or a sample project that I can use. If you send a project, **please make sure that it has no sensitive information**. Thank you, Tatiana

@tati-qalified @kevin-atx @nvoxland bug can be reproduce using https://github.com/sonersivri/liquibase-bug-3820

**Comment by filipelautert** [comment]
That's some manual loading you did there, now we got it. Thanks!
