### ISSUE TITLE
Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null

### ISSUE THREAD

**Issue by victorrodrigueznadq** [liquibase/liquibase#3847]
### Search first

- [X] I searched and no similar issues were found

### Description

The log doesn't tell me what table or what column it is.  I'll try to debug it.  See the stack trace below:

```
[2023-02-20 15:48:53] SEVERE [liquibase.integration] Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.command.CommandScope.execute(CommandScope.java:186)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:352)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:317)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:270)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1586)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:396)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:395)
        at liquibase.integration.commandline.Main$1.run(Main.java:217)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:217)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.command.CommandScope.execute(CommandScope.java:186)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:268)
        ... 33 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.snapshot.jvm.ColumnSnapshotGenerator.addTo(ColumnSnapshotGenerator.java:203)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:78)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:455)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:477)
        at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:368)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:331)
        at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:214)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:187)
        at liquibase.command.core.InternalDiffCommandStep.createReferenceSnapshot(InternalDiffCommandStep.java:188)
        at liquibase.command.core.InternalDiffCommandStep.createDiffResult(InternalDiffCommandStep.java:98)
        at liquibase.command.core.InternalGenerateChangelogCommandStep.run(InternalGenerateChangelogCommandStep.java:69)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 34 more


Unexpected error running Liquibase: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.command.CommandScope.execute(CommandScope.java:186)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:352)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:317)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:270)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1586)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:396)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:395)
        at liquibase.integration.commandline.Main$1.run(Main.java:217)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:217)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.command.CommandScope.execute(CommandScope.java:186)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:268)
        ... 33 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "liquibase.structure.core.Column.isNullable()" is null
        at liquibase.snapshot.jvm.ColumnSnapshotGenerator.addTo(ColumnSnapshotGenerator.java:203)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:78)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:455)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:477)
        at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:368)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:331)
        at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:214)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:187)
        at liquibase.command.core.InternalDiffCommandStep.createReferenceSnapshot(InternalDiffCommandStep.java:188)
        at liquibase.command.core.InternalDiffCommandStep.createDiffResult(InternalDiffCommandStep.java:98)
        at liquibase.command.core.InternalGenerateChangelogCommandStep.run(InternalGenerateChangelogCommandStep.java:69)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 34 more
```

### Steps To Reproduce

This is running generateChangeLog against a schema in a redshift/postgres database.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by victorrodrigueznadq** [comment]
It seems to be happening on a view.  Removing views from LIQUIBASE_COMMAND_DIFF_TYPES makes no difference.

**Comment by nvoxland** [comment]
It looks like this was fixed by #3588 in 4.19.1 which is targeted for a release this week.

Let me know if that doesn't fix the problem.

**Comment by victorrodrigueznadq** [comment]
@nvoxland thanks. I'll try it.  do you know when this week?

**Comment by nvoxland** [comment]
Not exactly sure yet. The team is working through the wrap-up steps which can sometimes vary in how long they take.

If you'd like to try a pre-release build to see if it would help, you can download `liquibase-zip-master` from https://github.com/liquibase/liquibase/actions/runs/4223749403

**Comment by victorrodrigueznadq** [comment]
@nvoxland sure enough.  that fixed it!  I wonder if it also fixes the issue I was having with the following error when trying to process 50+ schemas with generateChangeLog...I guess I can try it and see....

```[[Amazon](500310) Invalid operation: terminating connection due to administrator command]```

**Comment by victorrodrigueznadq** [comment]
@nvoxland why does the main liquibase download page still download 4.19.1?

https://www.liquibase.com/download#download-liquibase
