### ISSUE TITLE
SnakeYaml "NoSuchMethod" issue after updating to 4.19.1

### ISSUE THREAD

**Issue by freddiN** [liquibase/liquibase#3878]
### Search first

- [X] I searched and no similar issues were found

### Description

After upgrading from 4.19.0 to 4.19.1, we noticed the following message:
`2023-03-01 17:04:23.327  WARN 20489 --- [           main] liquibase.util                           : Failed to set code point limit for SnakeYaml, because the version of SnakeYaml being used is too old. Consider upgrading to a SnakeYaml version equal to or newer than 1.32, by downloading and installing a newer version of Liquibase (which includes a newer version of SnakeYaml). Loading particularly large JSON and YAML documents (like snapshots) in Liquibase may fail if SnakeYaml is not upgraded.`

Further logs:
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
    liquibase.parser.core.yaml.YamlParser.createLoaderOptions(YamlParser.java:17)
The following method did not exist:
    'org.yaml.snakeyaml.LoaderOptions org.yaml.snakeyaml.LoaderOptions.setProcessComments(boolean)'
The calling method's class, liquibase.parser.core.yaml.YamlParser, was loaded from the following location:
    jar:file:/home/gitlab-runner/(REMOVED)/.m2/repository/org/liquibase/liquibase-core/4.19.1/liquibase-core-4.19.1.jar!/liquibase/parser/core/yaml/YamlParser.class
The called method's class, org.yaml.snakeyaml.LoaderOptions, is available from the following locations:
    jar:file:/home/gitlab-runner/(REMOVED)/.m2/repository/org/yaml/snakeyaml/1.30/snakeyaml-1.30.jar!/org/yaml/snakeyaml/LoaderOptions.class
The called method's class hierarchy was loaded from the following locations:
    org.yaml.snakeyaml.LoaderOptions: file:/home/gitlab-runner/(REMOVED)/.m2/repository/org/yaml/snakeyaml/1.30/snakeyaml-1.30.jar
Action:
Correct the classpath of your application so that it contains compatible versions of the classes liquibase.parser.core.yaml.YamlParser and org.yaml.snakeyaml.LoaderOptions

We are using it in a Spring Boot 2.7.9 service.

Looking at the dependency graph (and the above logs), I believe snakeyaml 1.30 is being referenced with a compile scope.

Looking at the changelog this may or may not be connected to https://github.com/liquibase/liquibase/pull/3632

### Steps To Reproduce

- have a liquibase configured for a spring boot 2.7.9 service
- update to 4.19.1
- start the service

### Liquibase Version

4.19.1

### Database Vendor & Version

MySQL 8.0.32

### Liquibase Integration

Spring Boot

### Liquibase Extensions

liquibase-cassandra

### OS and/or Infrastructure Type/Provider

Windows, Ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by AdnanMujkic** [comment]
Jup, same here. [Leaving comment just to follow the Issue]

**Comment by nvoxland** [comment]
That part is just a warning, but the "NoSuchMethod" problem is an error

**Comment by grossedouceur** [comment]
I workaround is to force snakeyaml 1.33 in managed dependencies of the project.
```xml
    <dependencyManagement>
        <dependencies>
            ....
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>1.33</version>
            </dependency>
            ....

        </dependencies>
    </dependencyManagement>
```

**Comment by filipelautert** [comment]
Hi @freddiN , thanks for the issue report! And you are right: PR https://github.com/liquibase/liquibase/pull/3632 introduced this. @StevenMassaro fix on https://github.com/liquibase/liquibase/pull/3807 handles the NoSuchMethodError , but 3632 code that comes right after that also uses methods that were introduced after 1.30. 

Springboot still using 1.30 for 2.7.x branch but upgraded to 1.33 in springboot 3.x -> https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-dependencies/build.gradle  .  They are aware of the vulnerabilities on the 1.3x series ( https://github.com/spring-projects/spring-boot/issues/33457 )  but are fine with that.

Anyway, we were not expecting this issue - we were focused on tackling snakeyaml security issues that we didn't check for backwards compatibility (as we already were on 1.33 for some time now). Meanwhile the fix in the following comment  https://github.com/liquibase/liquibase/issues/3878#issuecomment-1452345264 works, an we may create a PR to make sure that we catch those other methods in our next release. But menawhile upgrading snakeyaml won't hurt :)

**Comment by freddiN** [comment]
Hey @filipelautert, thanks for the explanation.

I see currently 3 viable options:
- stay on 4.19.0 for now
- force snakeyaml 1.33
- migrate to spring boot 3

I do follow the snakeyaml reports since it showed up in our dependency track a while ago, though I think I will opt for doing the spring boot 3 migration earlier than planned (even though there have been some serious regressions lately like https://github.com/spring-projects/spring-boot/issues/34363).

Anyway, your heads up is much appreciated, thank you.

**Comment by filipelautert** [comment]
I created PR https://github.com/liquibase/liquibase/pull/3904 to prevent this issue - after reviewing snakeyaml code found out that only the below method changed:

1.30
```
public void setProcessComments(boolean processComments) {
this.processComments = processComments;
}
```
    
1.33
```
public LoaderOptions setProcessComments(boolean processComments) {
this.processComments = processComments;
return this;
}
```

**Comment by mbecca** [comment]
Hi, i have the following error when i run the update task

Liquibase version: 4.20
gradlew: 8.0.2

```
####################################################2023-03-28T14:19:58.527626692-03:00
##   _     _             _ _                      ##2023-03-28T14:19:58.527934294-03:00
##  | |   (_)           (_) |                     ##2023-03-28T14:19:58.528163261-03:00
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##2023-03-28T14:19:58.528404056-03:00
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##2023-03-28T14:19:58.528771852-03:00
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##2023-03-28T14:19:58.529060345-03:00
##              | |                               ##2023-03-28T14:19:58.529273957-03:00
##              |_|                               ##2023-03-28T14:19:58.529518526-03:00
##                                                ## 2023-03-28T14:19:58.529725768-03:00
##  Get documentation at docs.liquibase.com       ##2023-03-28T14:19:58.529906761-03:00
##  Get certified courses at learn.liquibase.com  ## 2023-03-28T14:19:58.530136975-03:00
##  Free schema change activity reports at        ##2023-03-28T14:19:58.530297129-03:00
##      https://hub.liquibase.com                 ##2023-03-28T14:19:58.530425310-03:00
##                                                ##2023-03-28T14:19:58.530612172-03:00
####################################################2023-03-28T14:19:58.530756004-03:00
Starting Liquibase at 14:19:58 (version 4.20.0 #7837 built at 2023-03-07 16:25+0000)
2023-03-28T14:19:58.530879033-03:00 Liquibase Version: 4.20.02023-03-28T14:19:58.530948737-03:00

[2023-03-28 14:20:02] INFORMACIÓN [liquibase.changelog] Reading from XXXX.DATABASECHANGELOG
[2023-03-28 14:20:02] INFORMACIÓN [liquibase.executor] Changelog query completed.2023-03-28T14:20:02.327609600-03:00
[2023-03-28 14:20:02] INFORMACIÓN [liquibase.executor] Changelog query completed.
[2023-03-28 14:20:02] INFORMACIÓN [liquibase.executor] Changelog query completed.
[2023-03-28 14:20:02] INFORMACIÓN [liquibase.executor] Changelog query completed.
[2023-03-28 14:20:02] INFORMACIÓN [liquibase.lockservice] Successfully acquired change log lock
[2023-03-28 14:20:03] ADVERTENCIA [liquibase.util] Failed to perform a method call for SnakeYaml because the version of SnakeYaml being used is too old. Consider upgrading to a SnakeYaml version equal to or newer than 1.32, by downloading and installing a newer version of Liquibase (which includes a newer version of SnakeYaml). Loading particularly large JSON and YAML documents (like snapshots) in Liquibase may fail if SnakeYaml is not upgraded.2023-03-28T14:20:03.527592386-03:00
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.LoaderOptions.setCodePointLimit(int)'2023-03-28T14:20:03.527753774-03:00
	at liquibase.util.SnakeYamlUtil.lambda$setCodePointLimitSafely$0(SnakeYamlUtil.java:23)2023-03-28T14:20:03.527899108-03:00
	at liquibase.util.SnakeYamlUtil.safelyCallNewSnakeYamlMethod(SnakeYamlUtil.java:39)2023-03-28T14:20:03.528037408-03:00
	at liquibase.util.SnakeYamlUtil.setCodePointLimitSafely(SnakeYamlUtil.java:23)2023-03-28T14:20:03.528160266-03:00
	at liquibase.parser.core.yaml.YamlParser.createLoaderOptions(YamlParser.java:16)2023-03-28T14:20:03.528330329-03:00
	at liquibase.hub.core.HttpClient.<init>(HttpClient.java:49)2023-03-28T14:20:03.528478748-03:00
	at liquibase.hub.core.StandardHubService.createHttpClient(StandardHubService.java:41)2023-03-28T14:20:03.528618187-03:00
	at liquibase.hub.core.StandardHubService.<init>(StandardHubService.java:37)2023-03-28T14:20:03.528765419-03:00
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)2023-03-28T14:20:03.528902823-03:00
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)2023-03-28T14:20:03.529040608-03:00
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)2023-03-28T14:20:03.529193292-03:00
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)2023-03-28T14:20:03.529340395-03:00
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)2023-03-28T14:20:03.529490953-03:00
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)2023-03-28T14:20:03.529633877-03:00
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:24)
	at liquibase.plugin.AbstractPluginFactory.findAllInstances(AbstractPluginFactory.java:92)
	at liquibase.plugin.AbstractPluginFactory.getPlugin(AbstractPluginFactory.java:62)
	at liquibase.hub.HubServiceFactory.getService(HubServiceFactory.java:30)2023-03-28T14:20:03.529988577-03:00
	at liquibase.hub.HubUpdater.<init>(HubUpdater.java:42)2023-03-28T14:20:03.530103543-03:00
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:265)2023-03-28T14:20:03.530119871-03:00
	at liquibase.Scope.lambda$child$0(Scope.java:187)2023-03-28T14:20:03.530224213-03:00
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)2023-03-28T14:20:03.530341031-03:00
	at liquibase.Scope.child(Scope.java:165)2023-03-28T14:20:03.530495506-03:00
	at liquibase.Liquibase.runInScope(Liquibase.java:2639)
	at liquibase.Liquibase.update(Liquibase.java:236)2023-03-28T14:20:03.530621211-03:00
	at liquibase.Liquibase.update(Liquibase.java:221)
	at liquibase.integration.commandline.Main.lambda$doMigration$1(Main.java:1757)2023-03-28T14:20:03.530788003-03:00
	at liquibase.Scope.lambda$child$0(Scope.java:187)2023-03-28T14:20:03.530824439-03:00
	at liquibase.Scope.child(Scope.java:196)2023-03-28T14:20:03.530912728-03:00
	at liquibase.Scope.child(Scope.java:186)2023-03-28T14:20:03.530959325-03:00
	at liquibase.Scope.child(Scope.java:165)2023-03-28T14:20:03.531045802-03:00
	at liquibase.integration.commandline.Main.doMigration(Main.java:1756)2023-03-28T14:20:03.531145273-03:00
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:415)2023-03-28T14:20:03.531197999-03:00
	at liquibase.Scope.lambda$child$0(Scope.java:187)2023-03-28T14:20:03.531302447-03:00
	at liquibase.Scope.child(Scope.java:196)2023-03-28T14:20:03.531438766-03:00
	at liquibase.Scope.child(Scope.java:186)2023-03-28T14:20:03.531590819-03:00
	at liquibase.Scope.child(Scope.java:165)2023-03-28T14:20:03.531813636-03:00
	at liquibase.integration.commandline.Main$1.run(Main.java:414)2023-03-28T14:20:03.531944537-03:00
	at liquibase.integration.commandline.Main$1.run(Main.java:231)2023-03-28T14:20:03.532088583-03:00
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:172)2023-03-28T14:20:03.532232146-03:00
	at liquibase.integration.commandline.Main.run(Main.java:231)2023-03-28T14:20:03.532269081-03:00
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)2023-03-28T14:20:03.532371000-03:00
	at liquibase.command.CommandScope.execute(CommandScope.java:195)2023-03-28T14:20:03.532420874-03:00
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)2023-03-28T14:20:03.532508232-03:00
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)2023-03-28T14:20:03.532750292-03:00
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)2023-03-28T14:20:03.532897170-03:00
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)2023-03-28T14:20:03.533025187-03:00
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)2023-03-28T14:20:03.533157513-03:00
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)2023-03-28T14:20:03.533207017-03:00
	at picocli.CommandLine.execute(CommandLine.java:2170)2023-03-28T14:20:03.533236517-03:00
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$2(LiquibaseCommandLine.java:367)2023-03-28T14:20:03.533325653-03:00
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:332)
	at liquibase.Scope.child(Scope.java:196)2023-03-28T14:20:03.533487979-03:00
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:330)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:91)2023-03-28T14:20:03.533648693-03:00
```
