### ISSUE TITLE
calling "liquibase --version" requires resolveable hostname after updating from 4.19.0 to 4.19.1

### ISSUE THREAD

**Issue by ColinMcMicken** [liquibase/liquibase#3906]
### Search first

- [X] I searched and no similar issues were found

### Description

Context: I maintain a minimal liquibase container image based on ubi8-micro. It is built using buildah and podman. during the container build process I verify that I can run `liquibase --version`.

Using 4.19.0 this works as it did before. When updating to 4.19.1 the `liquibase --version` command tries to resolve a temporary, random hostname, example below: `12d3de1bfed7`, in the container which is not resolvable and fails. Error and debug log provided below.

I have a work around by setting the hostname to something resolvable.

This is an unexpected change in behavior for a patch update.

### Steps To Reproduce

Run `liquibase --version` with liquibase version 4.19.1 on a system where the hostname is not resolvable.

### Actual Behavior

`+ buildah run -- <redacted container name> bash -c 'docker-entrypoint.sh --logLevel=debug --version'
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for directory /liquibase
[2023-03-06 13:15:31] FINE [liquibase.configuration] No configuration value for liquibase.searchPath found
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/liquibase-core.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for directory /liquibase/lib
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/commons-text.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaybird.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/ojdbc8.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/h2.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaxb-api.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/snowflake-jdbc.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/picocli.jar
[2023-03-06 12:15:31] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jcc.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaxb-core.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/liquibase-commercial.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/mariadb-java-client.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaxb-runtime.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/postgresql.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/commons-collections4.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/snakeyaml.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/opencsv.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/mssql-jdbc.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/commons-lang3.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/sqlite-jdbc.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/hsqldb.jar
[2023-03-06 12:15:32] FINE [liquibase.resource] Creating resourceAccessor for directory /liquibase/internal/lib
[2023-03-06 12:15:32] FINE [liquibase.resource] Overall search path: 
  - /liquibase
  - /liquibase/internal/lib/liquibase-core.jar
  - /liquibase/lib
  - /liquibase/internal/lib/commons-text.jar
  - /liquibase/internal/lib/jaybird.jar
  - /liquibase/internal/lib/ojdbc8.jar
  - /liquibase/internal/lib/h2.jar
  - /liquibase/internal/lib/jaxb-api.jar
  - /liquibase/internal/lib/snowflake-jdbc.jar
  - /liquibase/internal/lib/picocli.jar
  - /liquibase/internal/lib/jcc.jar
  - /liquibase/internal/lib/jaxb-core.jar
  - /liquibase/internal/lib/liquibase-commercial.jar
  - /liquibase/internal/lib/mariadb-java-client.jar
  - /liquibase/internal/lib/jaxb-runtime.jar
  - /liquibase/internal/lib/postgresql.jar
  - /liquibase/internal/lib/commons-collections4.jar
  - /liquibase/internal/lib/snakeyaml.jar
  - /liquibase/internal/lib/opencsv.jar
  - /liquibase/internal/lib/mssql-jdbc.jar
  - /liquibase/internal/lib/commons-lang3.jar
  - /liquibase/internal/lib/sqlite-jdbc.jar
  - /liquibase/internal/lib/hsqldb.jar
  - /liquibase/internal/lib
[2023-03-06 12:15:32] FINE [liquibase.configuration] No configuration value for liquibase.shouldRun aka should.run found
[2023-03-06 12:15:32] FINE [liquibase.configuration] Configuration liquibase.shouldRun is using the default value of true
[2023-03-06 12:15:32] FINE [liquibase.configuration] No configuration value for liquibase.monitorPerformance found
[2023-03-06 12:15:32] FINE [liquibase.configuration] Configuration liquibase.monitorPerformance is using the default value of false
[2023-03-06 12:15:32] FINE [liquibase.integration] Performance monitoring disabled
[2023-03-06 12:15:32] FINE [liquibase.servicelocator] Loaded liquibase.logging.mdc.MdcManager instance liquibase.logging.mdc.NoOpMdcManager
[2023-03-06 12:15:32] FINE [liquibase.servicelocator] Loaded liquibase.logging.mdc.MdcManager instance com.datical.liquibase.ext.logging.structured.StructuredMdcManager
[2023-03-06 12:15:32] FINE [liquibase.configuration] No configuration value for liquibase.licenseKey found
[2023-03-06 12:15:32] FINE [liquibase.configuration] No configuration value for liquibase.pro.licenseKey found
[2023-03-06 12:15:32] SEVERE [liquibase.integration] 12d3de1bfed7: 12d3de1bfed7: System error
java.net.UnknownHostException: 12d3de1bfed7: 12d3de1bfed7: System error
	at java.base/java.net.InetAddress.getLocalHost(Unknown Source)
	at liquibase.integration.commandline.LiquibaseCommandLine.logMdcData(LiquibaseCommandLine.java:409)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$1(LiquibaseCommandLine.java:362)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:328)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:326)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: java.net.UnknownHostException: 12d3de1bfed7: System error
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	... 15 more

Unexpected error running Liquibase: 12d3de1bfed7: 12d3de1bfed7: System error

java.net.UnknownHostException: 12d3de1bfed7: 12d3de1bfed7: System error
	at java.base/java.net.InetAddress.getLocalHost(Unknown Source)
	at liquibase.integration.commandline.LiquibaseCommandLine.logMdcData(LiquibaseCommandLine.java:409)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$1(LiquibaseCommandLine.java:362)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:328)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:326)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: java.net.UnknownHostException: 12d3de1bfed7: System error
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	... 15 more
subprocess exited with status 1
subprocess exited with status 1
                               Error: exit status 1`

### Expected/Desired Behavior

Works as before, or changelog or release notes mentions/explains change in behavior if it now 'works as intended'.

### Liquibase Version

4.19.1

### Database Vendor & Version

not applicable

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

RHEL8

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
Thanks for the report. Yes, Liquibase should never be expecting any sort of network access. We can take a look at it
