### ISSUE TITLE
mssql liquibase 4.20.0 - precondition uniqueConstraintExists fails when the unique constraint exists

### ISSUE THREAD

**Issue by alexandru-prigoreanu** [liquibase/liquibase#3977]
- [X] I searched and no similar issues were found

Hello! thank you for this api and for your time.
i have a changeset that creates a unique constraint

        <addUniqueConstraint columnNames="NAME" constraintName="UN_TABLENAME_NAME" deferrable="false"
                             disabled="false" initiallyDeferred="false" tableName="TABLENAME"/>
i have a changeset with a precondition on unique constraint exists that fails even though the unique constraint index was created previously

    <changeSet id="CHANGESETID" author="CHANGESETAUTHOR">
        <preConditions>
            <uniqueConstraintExists tableName="TABLENAME" constraintName="UN_TABLENAME_NAME"/>
        </preConditions>
        <dropUniqueConstraint tableName="TABLENAME" constraintName="UN_TABLENAME_NAME"/>
    </changeSet>

- the application does not start because the precondition uniqueConstraintExists is not met

### Steps To Reproduce

the previous changesets will prevent the application from starting with the following stacktrace

```

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'baseLiquibase' defined in class path resource [...]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changesetfile::CHANGESETID::CHANGESETAUTHOR:
     Reason: 
          changesetfile : UN_TABLENAME_NAME on TABLENAME() does not exist

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1607)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1571)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1460)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1347)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 101 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changesetfile::CHANGESETID::CHANGESETAUTHOR:
     Reason: 
          changesetfile : UN_TABLENAME_NAME on TABLENAME() does not exist

	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:136)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:297)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:295)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Liquibase.runInScope(Liquibase.java:2639)
	at liquibase.Liquibase.update(Liquibase.java:236)
	at liquibase.Liquibase.update(Liquibase.java:221)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284)
	at ....afterPropertiesSet(....java:82)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 115 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset changesetfile::CHANGESETID::CHANGESETAUTHOR:
     Reason: 
          changesetfile : UN_TABLENAME_NAME on TABLENAME() does not exist

	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:631)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:59)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:124)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:124)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:105)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.Scope.child(Scope.java:260)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:75)
	... 134 common frames omitted
Caused by: liquibase.exception.PreconditionFailedException: Preconditions Failed
	at liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:47)
	at liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:617)
	... 154 common frames omitted


Process finished with exit code 255


```

### Expected/Desired Behavior

we expect that the precondition uniqueConstraintExists is met and the application starts.

### Liquibase Version

4.20.0

### Database Vendor & Version

mssql 19

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

mac m1, mssql 19 docker image

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by zeje** [comment]
constraint_schema = 'null'

`
select 
  const.CONSTRAINT_NAME,
  const.TABLE_NAME,
  COLUMN_NAME,
  const.constraint_schema as CONSTRAINT_CONTAINER 
from
  information_schema.table_constraints const 
  join information_schema.key_column_usage col 
    on const.constraint_schema = col.constraint_schema 
    and const.table_name = col.table_name 
    and const.constraint_name = col.constraint_name 
where const.constraint_schema = 'null' 
  and const.table_name = 'act_re_procdef' 
  and const.constraint_name = 'act_uniq_procdef' 
order by ordinal_position 
`
![image](https://github.com/liquibase/liquibase/assets/10680634/32be4081-18c5-442c-af6f-3c47e73eb186)

![image](https://github.com/liquibase/liquibase/assets/10680634/96e49ccc-f7d2-4974-98b4-566f49a79e53)

**Comment by zeje** [comment]
I had to use indexExists instead

``` xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
    <changeSet author="caizz (generated)" id="1690078543322-80">
        <preConditions onFail="CONTINUE">
            <and>
                <tableExists tableName="act_re_procdef"/>
                <not>
                    <indexExists indexName="ACT_UNIQ_PROCDEF" tableName="act_re_procdef"/>
                </not>
            </and>
        </preConditions>
        <addUniqueConstraint columnNames="KEY_, VERSION_, TENANT_ID_" constraintName="ACT_UNIQ_PROCDEF" tableName="act_re_procdef"/>
    </changeSet>
</databaseChangeLog>
```

**Comment by OsirisDBA** [comment]
I'm seeing this issue when the unique constraint is on a table not in the default schema. schemaName isn't a valid option for this precondition.

**Comment by nils-christian** [comment]
Hi,

As far as I can tell, the issue is not limited to any DB system. I encountered the issue with Postgres and H2. Following Liquibase Changeset shows the unexpected behaviour of the uniqueConstraintExists precondition. The default schema for liquibase is set to myschema1. Note that the index check works as expected, but the uniqueConstraintExists is evaluated to "true" although the unique constraints exists only in another schema.


```sql
<changeSet id="0" author="test">
	<sql>
		CREATE TABLE myschema2.a(b VARCHAR(255))
	</sql>
</changeSet>

<changeSet id="1" author="test">
	<sql>
		CREATE INDEX i_a_b ON myschema2.a(b)
	</sql>
</changeSet>

<changeSet id="2" author="test">
	<preConditions onFail="MARK_RAN">
		<indexExists tableName="a" indexName="i_a_b"/>
	</preConditions>
	<sql>
		DROP INDEX i_a_b
	</sql>
</changeSet>

<changeSet id="3" author="test">
	<sql>
		ALTER TABLE myschema2.a ADD CONSTRAINT uc_a_b UNIQUE(b)
	</sql>
</changeSet>

<changeSet id="4" author="test">
	<preConditions onFail="MARK_RAN">
		<uniqueConstraintExists tableName="a" constraintName="uc_a_b"/>
	</preConditions>
	<sql>
		ALTER TABLE a DROP CONSTRAINT uc_a_b RESTRICT
	</sql>
</changeSet>
```


Best regards
  Nils

**Comment by mpvvliet** [comment]
I think the issue is that the `UniqueConstraintSnapshotGenerator` does not use the default Liquibase schema if none is specified in the precondition. 

In the Postgres part of the code, this means the `const.constraint_schema` condition its omitted [(line 197](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java#L197)), causing Liquibase to find the constraint in any schema. The same applies to the H2 database ([line 389](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java#L389)).

In the MySQL part, there seem to be two problems:
  * if the schema name its specified, it’s not used; the catalog name is used instead ([line 175](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java#L175))
  * if the schema name is not specified, the unique constraint can not be found due to the inclusion of `const.constraint_schema='null'` in the query.

I’ve created a fix for the first MySQL-related issue, but I can’t figure out how the Liquibase default schema is supposed to get picked up in a precondition. 

Any tips would be appreciated.

**Comment by mpvvliet** [comment]
Updated the pull request to fix this issue. In my testing, this fixes all issues mentioned here.

**Comment by Bodyash** [comment]
I have similar issue on sqlserver.

My constraint is already existing in DB, so I'm trying to execute update only if it isn't exist and mark run if precondition fails.
But precondition is not failing, looks like it can't check properly if this exists or not.

![image](https://github.com/liquibase/liquibase/assets/2454569/af2ac160-9d4c-4ad8-b633-d222c5c98642)

**Comment by mpvvliet** [comment]
@Bodyash Can you try explicitly adding `schemaName` to the `uniqueConstraintExists` precondition to see if that works? If so, I think my fix will also solve your issue.
