### ISSUE TITLE
"addDefaultValue" with attributes "schemaName" and "defaultValueSequenceNext" creates invalid checksum on rollback

### ISSUE THREAD

**Issue by moberwasserlechner** [liquibase/liquibase#4184]
### Search first

- [X] I searched and no similar issues were found

### Description

Using the "addDefaultValue" in combination with "schemaName" and "defaultValueSequenceNext" on PostgreSQL database results invalid checksums on rollback.

```
Caused by: liquibase.exception.ValidationFailedException:
```
Stacktrace
```
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:357)
        at liquibase.Liquibase$10.run(Liquibase.java:1503)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Liquibase.runInScope(Liquibase.java:2714)
        at liquibase.Liquibase.rollback(Liquibase.java:1481)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1922)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:412)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main$1.run(Main.java:411)
        at liquibase.integration.commandline.Main$1.run(Main.java:228)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.integration.commandline.Main.run(Main.java:228)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:196)
```

### Steps To Reproduce

Using this changelog we wanted to rename a table and its sequence.
```
  <changeSet id="API-101-rename_postgres_table" author="Michael Oberwasserlechner">
    <renameTable oldTableName="api_old_postgres_table" newTableName="api_new_table" schemaName="non_public_schema" />
    <renameSequence oldSequenceName="api_old_postgres_table_id_seq" newSequenceName="api_new_table_id_seq" schemaName="non_public_schema" />
    <dropDefaultValue tableName="api_new_table" columnName="id" schemaName="non_public_schema" />
    <addDefaultValue tableName="api_new_table" columnName="id" schemaName="non_public_schema" defaultValueSequenceNext="api_new_table_id_seq" />
    <rollback>
      <renameTable oldTableName="api_new_table" newTableName="api_old_postgres_table" schemaName="non_public_schema" />
      <renameSequence oldSequenceName="api_new_table_id_seq" newSequenceName="api_old_postgres_table_id_seq" schemaName="non_public_schema" />
      <dropDefaultValue tableName="api_old_postgres_table" columnName="id" schemaName="non_public_schema" />
      <addDefaultValue tableName="api_old_postgres_table" columnName="id" schemaName="non_public_schema" defaultValueSequenceNext="api_old_postgres_table_id_seq" />
    </rollback>
  </changeSet>
```

The update works as expected but the rollback fails with a `liquibase.exception.ValidationFailedException` saying that the checksums did not match. I run the rollback just seconds after the update so there where no changes on the changeset.

Comparing the checksum creation in the "update" and "rollback" run results in. 

Please note, that I could not share the real names so the one-way-hashes are not accurate as they where calculated from the real names.

*Update Run*
```
[2023-04-27 13:35:19] FEIN [liquibase.util] Computed checksum for renameTable:[
    newTableName="api_new_table"
    oldTableName="api_old_postgres_table"
    schemaName="non_public_schema"
] as 321eb4adf55fbfdbed82abb9478be559
[2023-04-27 13:35:19] FEIN [liquibase.util] Computed checksum for renameSequence:[
    newSequenceName="api_new_table_id_seq"
    oldSequenceName="api_old_postgres_table_id_seq"
    schemaName="non_public_schema"
] as df21f20788ba59dec1989f1dbba6bb9f
[2023-04-27 13:35:19] FEIN [liquibase.util] Computed checksum for dropDefaultValue:[
    columnName="id"
    schemaName="non_public_schema"
    tableName="api_new_table"
] as 671466c23a2b9d19a9db007c0b4763cb
[2023-04-27 13:35:19] FEIN [liquibase.util] Computed checksum for addDefaultValue:[
    columnName="id"
    defaultValueSequenceNext="non_public_schema.api_new_table_id_seq"
    schemaName="non_public_schema"
    tableName="api_new_table"
] as e776968fb6326f6ddaf0d3063a0dbdb2
[2023-04-27 13:35:19] FEIN [liquibase.util] Computed checksum for 8:321eb4adf55fbfdbed82abb9478be559:8:df21f20788ba59dec1989f1dbba6bb9f:8:671466c23a2b9d19a9db007c0b4763cb:8:e776968fb6326f6ddaf0d3063a0dbdb2: as e2ed2e4d231c55026374de57d9dff602
```
*Rollback Run*
```
[2023-04-27 13:38:06] FEIN [liquibase.util] Computed checksum for renameTable:[
    newTableName="api_new_table"
    oldTableName="api_old_postgres_table"
    schemaName="non_public_schema"
] as 321eb4adf55fbfdbed82abb9478be559
[2023-04-27 13:38:06] FEIN [liquibase.util] Computed checksum for renameSequence:[
    newSequenceName="api_new_table_id_seq"
    oldSequenceName="api_old_postgres_table_id_seq"
    schemaName="non_public_schema"
] as df21f20788ba59dec1989f1dbba6bb9f
[2023-04-27 13:38:06] FEIN [liquibase.util] Computed checksum for dropDefaultValue:[
    columnName="id"
    schemaName="non_public_schema"
    tableName="api_new_table"
] as 671466c23a2b9d19a9db007c0b4763cb
[2023-04-27 13:38:06] FEIN [liquibase.util] Computed checksum for addDefaultValue:[
    columnName="id"
    defaultValueSequenceNext="api_new_table_id_seq"
    schemaName="non_public_schema"
    tableName="api_new_table"
] as 1f87930bedac9c077b3f423235829195
[2023-04-27 13:38:06] FEIN [liquibase.util] Computed checksum for 8:321eb4adf55fbfdbed82abb9478be559:8:df21f20788ba59dec1989f1dbba6bb9f:8:671466c23a2b9d19a9db007c0b4763cb:8:1f87930bedac9c077b3f423235829195: as d3d9e702a7a67d1876227c610a79b5d7
```

The diff reveals that the "update" uses the schema name in "defaultValueSequenceNext" but the "rollback" does not.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/1049938/234855622-ecdfd5f3-5153-40d0-a238-f93b07e06f83.png">

As a workaround we used `<sql>` instead of `<addDefaultValue />`

### Expected/Desired Behavior

The rollback should produce the same checksum as the update.

### Liquibase Version

4.19.1

### Database Vendor & Version

PostgreSQL 9.6

### OS and/or Infrastructure Type/Provider

Windows 10 with Git-Bash

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
We're running through some testing of a larger checksum fix. I'll have the team see if this is still a problem in the new code

**Comment by XDelphiGrl** [comment]
I validated [this fix](https://github.com/liquibase/liquibase/pull/4203) addresses the discrepancy between update and rollback checksums for changesets with `addDefaultValueSequenceNext` and `schemaName` properties. 

Here is the test changelog I used, based on @moberwasserlechner's repro steps.
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"  
xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"  
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:pro="http://www.liquibase.org/xml/ns/pro"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd 
http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd">

	<!-- SEQUENCE -->
	<changeSet author="erz" id="sequence">
		<createSequence sequenceName="test_sequence" dataType="int" startValue="1" incrementBy="1" minValue="1" schemaName="proschema"/>
		<rollback>
			<dropSequence sequenceName="test_sequence" schemaName="proschema"/>
		</rollback>
	</changeSet>
	
<!-- SIMPLE TABLE -->
	<changeSet author="erz"  id="table">
		<comment>Comment for 1::createTable-success</comment>
		<createTable tableName="table_1" schemaName="proschema">
			<!--column name="id" type="int" defaultValueSequenceNext="proschema.test_sequence"/-->
			<column name="id" type="int"/>
            <column name="name" type="CHAR(20)"/>
        </createTable>
	</changeSet>
	

	<changeSet author="erz"  id="defaultValue">
	    <addDefaultValue tableName="table_1" columnName="id" schemaName="proschema" defaultValueSequenceNext="test_sequence"/>
	</changeSet>

<!-- RENAMES -->
  <changeSet id="rename" author="Michael Oberwasserlechner">
    <renameTable oldTableName="table_1" newTableName="new_table_1" schemaName="proschema" />
    <renameSequence oldSequenceName="test_sequence" newSequenceName="new_test_sequence" schemaName="proschema" />
    <dropDefaultValue tableName="new_table_1" columnName="id" schemaName="proschema" />
    <addDefaultValue tableName="new_table_1" columnName="id" schemaName="proschema" defaultValueSequenceNext="new_test_sequence" />
    <rollback>
      <renameTable oldTableName="new_table_1" newTableName="table_1" schemaName="proschema" />
      <renameSequence oldSequenceName="new_test_sequence" newSequenceName="test_sequence" schemaName="proschema" />
      <dropDefaultValue tableName="table_1" columnName="id" schemaName="proschema" />
      <addDefaultValue tableName="table_1" columnName="id" schemaName="proschema" defaultValueSequenceNext="test_sequence" />
    </rollback>
  </changeSet>

</databaseChangeLog>
```

Thank you, @moberwasserlechner  for reporting this issue!
