### ISSUE TITLE
Liquibase commands are not thread safe even with ThreadLocalScopeManager 

### ISSUE THREAD

**Issue by rkesav** [liquibase/liquibase#4376]
### Search first

- [X] I searched and no similar issues were found

### Description

We are running Liquibase commands using Java APIs on multiple databases concurrently with `ThreadLocalScopeManager`. 
We are noticing that the Liquibase commands are not thread safe. The connection object is being shared across threads leading to connection closed exceptions. 

**Code Snippet**

```
Scope.setScopeManager(new ThreadLocalScopeManager());

ExecutorService executor = Executors.newFixedThreadPool(8);

for (int i=0; i<10; i++) {
            String dbName = "DB_" + i;
            executor.submit( () -> {
                try(MemoryDatabase db = MemoryDatabase.create(dbName); Connection con = db.getConnection()) {
                    final Liquibase liquibase = new Liquibase(
                            "com/example/changelog.xml",
                            new ClassLoaderResourceAccessor(),
                            new JdbcConnection(con));
                    liquibase.tag("test_started");
                    liquibase.update(new Contexts(), new LabelExpression());
                    liquibase.tag("test_complete");
                } catch (LiquibaseException e) {
                    throw new IllegalStateException(e.getMessage(), e);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
          });
  }
```

**Exception StackTrace**

```
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.command.CommandScope.execute(CommandScope.java:235)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:237)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.Liquibase.runInScope(Liquibase.java:1605)
	at liquibase.Liquibase.update(Liquibase.java:229)
	at liquibase.Liquibase.update(Liquibase.java:213)
	at com.example.persistence.dbmigration.ThreadLocalScopeManagerTest.maintainDatabase(ThreadLocalScopeManagerTest.java:89)
	... 6 more
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:337)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:254)
	at liquibase.command.core.helpers.LockServiceCommandStep.run(LockServiceCommandStep.java:37)
	at liquibase.command.CommandScope.execute(CommandScope.java:212)
	... 15 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:39)
	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:117)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:293)
	... 18 more
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:89)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.lockservice.StandardLockService.lambda$init$0(StandardLockService.java:117)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$execute$0(ChangelogJdbcMdcListener.java:33)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:32)
	... 20 more
Caused by: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1480)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1458)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:202)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:74)
	... 29 more
```

On basic investigation it looks like an issue with `LockServiceCommandStep`  where `database` is a class member. 

And looks like multiple threads are using the same `LockServiceCommandStep` object even though we have set `ThreadLocalScopeManager`. 

This seems to be because the  command objects are being created in the `rootScope` being set in the constructor of `ThreadLocalScopeManager`

```
public ThreadLocalScopeManager() {
    this.rootScope = Scope.getCurrentScope();
}
```

https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/Scope.java#L327
```
public synchronized <T extends SingletonObject> T getSingleton(Class<T> type) {
    if (getParent() != null) {
        return getParent().getSingleton(type);
 }
```

This looks to be incorrect since the expectation when using `ThreadLocalScopeManager` is that liquibase command objects are scoped to a specific thread and not reused across threads.

### Steps To Reproduce

This issue can be reproduced by running the following test in liquibase project https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy

This issue is consistently reproducible by running the above test with `@RepeatedTest(10)`. Look for exceptions in the logs.

Note: Above test is actually Ignored in the liquibase codebase (maybe due to this issue?)

### Expected/Desired Behavior

We expect Liquibase commands to be thread safe when run under a heavy thread load. 

### Liquibase Version

4.22.0

### Database Vendor & Version

PostgreSQL 12.2

### Liquibase Integration

Java API

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by sunand85** [comment]
Liquibase version 4.21.1 as well this test case is failing.

**Comment by Wenkee** [comment]
I think we need this kind of fix.
![image](https://github.com/liquibase/liquibase/assets/139210841/76791976-c152-40fa-afcf-ae5290212416)

**Comment by ligenzatomas** [comment]
I am experiencing exactly the same issue with the schema multitenancy model on Postgres 15 (and already existing DATABASECHANGELOGLOCK tables). Here is part of the log:

`2023-07-12 21:08:44.340 DEBUG 8840 --- [pool-3-thread-2] liquibase.executor                       : SET SEARCH_PATH TO ca_schema1, "$user","public","topology"`

`2023-07-12 21:08:44.340 DEBUG 8840 --- [pool-3-thread-1] liquibase.executor                       : SET SEARCH_PATH TO ca_schema1, "$user","public","topology"`

The schema value should be different for each thread.

**Comment by rkesav** [comment]
@filipelautert I've tested with @Wenkee's branch and I can confirm this has fixed the issue. 

This change to remove the database class field fixes the thread safety with `LockServiceCommandStep` but is there a possibility that there are other places in the code where global class fields are used which are not thread safe? I've not come across any other instance of global database variables so far in my use cases though.

FTR, as a temporary fix to the issue I'd added a new `CustomThreadLocalScopeManager` where I removed the logic for setting rootScope as current scope. This ensured that the singleton objects from rootScope are not shared by different child threads. Does this look like a valid fix  here?

```
public class CustomThreadLocalScopeManager extends ScopeManager {
    private final ThreadLocal<Scope> threadLocalScopes = new ThreadLocal<>();

    @Override
    public synchronized Scope getCurrentScope() {
        return threadLocalScopes.get();
    }

    @Override
    protected synchronized void setCurrentScope(Scope scope) {
        this.threadLocalScopes.set(scope);
    }

    @Override
    protected Scope init(Scope scope) {
        return scope;
    }
}
```

**Comment by filipelautert** [comment]
Hello @rkesav - yes, it seems a valid approach!
