### ISSUE TITLE
Unquoted values of valueDate and defaultValueDate in addColumn change (yaml format) don't work as expected

### ISSUE THREAD

**Issue by RadekWikturna** [liquibase/liquibase#4386]
### Search first

- [X] I searched and no similar issues were found

### Description

When adding a not-null column to an existing table using `addColumn` change, it is needed to specify either a `defaulValue` or `value` in the `column` tag. 
In case of DATETIME columns, it actually must be `valueDate` or `defaultValueDate`. We use the yaml format and according to documentation
(https://docs.liquibase.com/change-types/nested-tags/column.html):

> defaultValueDate : The default date and time value for column. The value is specified in one of the following forms: YYYY-MM-DD, hh:mm:ss, or YYYY-MM-DDThh:mm:ss.
> valueDate: The date and time value to set the column to. Accepts the following formats: YYYY-MM-DD, hh:mm:ss, or YYYY-MM-DDThh:mm:ss.

I found an example in documentation for `addDefaultValue` (https://docs.liquibase.com/change-types/add-default-value.html), which in yaml format looks like this:

`defaultValueDate:  2008-02-12T12:34:03`

i.e. the value is without quotes.

So my changelog looks like this:

```
databaseChangeLog:
  - changeSet:
      id: '1'
      author: test
      objectQuotingStrategy: LEGACY
      changes:
        - addColumn:
            tableName: team
            columns:
              - column:
                  name: date_and_time
                  type: DATETIME
                  constraints:
                    nullable: false
                  valueDate: 2023-06-15T10:21:15
```
                  
When the changelog is processed on H2 database, I can see these generated SQL's:

```
ALTER TABLE PUBLIC.team ADD date_and_time TIMESTAMP;
UPDATE PUBLIC.team SET date_and_time2 = '2023-06-15';
ALTER TABLE PUBLIC.team ALTER COLUMN date_and_time SET NOT NULL;
```

**The problem is that the UPDATE statement only sets the date portion, not the time! This is a bug.**

Then I tried using appostrophes around the value:

```
                  valueDate: '2023-06-15T10:21:15'

```

and then the generated SQL's are:

```
ALTER TABLE PUBLIC.team ADD date_and_time TIMESTAMP;
UPDATE PUBLIC.team SET date_and_time = '2023-06-15 10:21:15';
ALTER TABLE PUBLIC.team ALTER COLUMN date_and_time SET NOT NULL;
```

Notice that now the time portion is set in the UPDATE statement.

The same behavious occurs also on mySQL.

I've also tried

```
					defaultValueDate: '2023-06-15T10:21:15'
```

Which too works correctly with quotes:

```
ALTER TABLE PUBLIC.team ADD date_and_time3 TIMESTAMP DEFAULT '2023-06-15 10:21:15' NOT NULL;					

```					

But without quotes:
```
					defaultValueDate: 2023-06-15T10:21:15
```

it even fails with exception:

```
Caused by: java.lang.ClassCastException: class java.util.Date cannot be cast to class java.sql.Timestamp (java.util.Date is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform')
	at liquibase.datatype.core.DateTimeType.objectToSql(DateTimeType.java:160) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.sqlgenerator.core.AddColumnGeneratorDefaultClauseBeforeNotNull.getDefaultClauseBeforeNotNull(AddColumnGeneratorDefaultClauseBeforeNotNull.java:99) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.sqlgenerator.core.AddColumnGeneratorDefaultClauseBeforeNotNull.generateSingleColumnSQL(AddColumnGeneratorDefaultClauseBeforeNotNull.java:59) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.sqlgenerator.core.AddColumnGenerator.generateSingleColumn(AddColumnGenerator.java:130) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.sqlgenerator.core.AddColumnGenerator.generateSql(AddColumnGenerator.java:99) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.sqlgenerator.core.AddColumnGenerator.generateSql(AddColumnGenerator.java:33) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:32) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:221) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.util.SqlUtil.getSqlString(SqlUtil.java:358) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.changelog.ChangeSet.lambda$addSqlMdc$1(ChangeSet.java:1516) ~[liquibase-core-4.20.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at liquibase.changelog.ChangeSet.addSqlMdc(ChangeSet.java:1517) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:700) ~[liquibase-core-4.20.0.jar:na]
```

To sum it up - without quotes, as seen in examples it doesn't work correctly or it even fails, with quotes it works correctly.

However, I cannot use the quotes because the changelog is generated programmatically by using `YamlChangeLogSerializer`, which generates the  `valueDate` and `defaultValueDate` without quotes (see issue #4379 for background).

### Steps To Reproduce

You can test using the examples above.

I also wrote a simple SpringBoot/Kotlin/Liquibase project that tests some found Liquibase bugs. It has one test class `LiquibaseBugsApplicationTests`. For this test, its enough to run the tests
`valueDate in addColumn sets date and time` and `defaultValueDate in addColumn sets date and time`. To reproduce the exception uncomment the last changeset in `modify-table.changelog.yaml`
[LiquibaseBugs.zip](https://github.com/liquibase/liquibase/files/11768366/LiquibaseBugs.zip)

### Expected/Desired Behavior

Unquoted values of `valueDate` and `defaultValueDate` in `addColumn` change (yaml format) set both date and time.

### Liquibase Version

4.20

### Database Vendor & Version

H2, mySQL

### Liquibase Integration

SpringBoot 3

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
I was able to replicate this issue, and it does seem to be a bug, probably in the "ObjectToSQL" function in Liquibase core source code.

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
