### ISSUE TITLE
Liquibase 4.22.0 and 4.23.0 fail to run <sql> update statements

### ISSUE THREAD

**Issue by gjvoosten** [liquibase/liquibase#4443]
### Search first

- [X] I searched and no similar issues were found

### Description

A changeset fails with the following stack trace:
```
Running Changeset: migrations.xml::convert-tags-to-notes::somebody
[2023-06-27 13:46:18.847] INFO liquibase.changelog.ChangeSet: Foreign key FK_reportTags_report dropped
[2023-06-27 13:46:18.848] INFO liquibase.changelog.ChangeSet: Foreign key FK_reportTags_tag dropped
[2023-06-27 13:46:18.849] INFO liquibase.changelog.ChangeSet: Table reportTags dropped
[2023-06-27 13:46:18.851] ERROR liquibase.changelog.ChangeSet: ChangeSet migrations.xml::convert-tags-to-notes::somebody encountered an exception.
[2023-06-27 13:46:18.852] INFO liquibase.command.core.UpdateCommandStep: Update command encountered an exception.
[2023-06-27 13:46:18.860] INFO liquibase.lockservice.StandardLockService: Successfully released change log lock
[2023-06-27 13:46:18.866] INFO liquibase.lockservice.StandardLockService: Successfully released change log lock
[2023-06-27 13:46:18.866] INFO liquibase.command.CommandScope: Command execution complete
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations.xml::convert-tags-to-notes::somebody:
     Reason: liquibase.exception.DatabaseException: ERROR: cannot drop table tags because other objects depend on it
  Detail: materialized view mv_fts_tags depends on table tags
  Hint: Use DROP ... CASCADE to drop the dependent objects too. [Failed SQL: (0) DROP TABLE public.tags]
	at liquibase.command.CommandScope.execute(CommandScope.java:236)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:223)
	at liquibase.Scope.lambda$child$0(Scope.java:197)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Liquibase.runInScope(Liquibase.java:1361)
	at liquibase.Liquibase.update(Liquibase.java:215)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.Liquibase.update(Liquibase.java:183)
	at liquibase.Liquibase.update(Liquibase.java:172)
	at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:65)
	at io.dropwizard.migrations.DbCommand.run(DbCommand.java:70)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at mil.dds.anet.AnetApplication.main(AnetApplication.java:93)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations.xml::convert-tags-to-notes::somebody:
     Reason: liquibase.exception.DatabaseException: ERROR: cannot drop table tags because other objects depend on it
  Detail: materialized view mv_fts_tags depends on table tags
  Hint: Use DROP ... CASCADE to drop the dependent objects too. [Failed SQL: (0) DROP TABLE public.tags]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:122)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:74)
	at liquibase.Scope.lambda$child$0(Scope.java:197)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:73)
	at liquibase.command.CommandScope.execute(CommandScope.java:213)
	... 17 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations.xml::convert-tags-to-notes::somebody:
     Reason: liquibase.exception.DatabaseException: ERROR: cannot drop table tags because other objects depend on it
  Detail: materialized view mv_fts_tags depends on table tags
  Hint: Use DROP ... CASCADE to drop the dependent objects too. [Failed SQL: (0) DROP TABLE public.tags]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:765)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:121)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:70)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:197)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:263)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:100)
	at liquibase.Scope.lambda$child$0(Scope.java:197)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:263)
	at liquibase.Scope.child(Scope.java:267)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:74)
	... 24 more
Caused by: liquibase.exception.DatabaseException: ERROR: cannot drop table tags because other objects depend on it
  Detail: materialized view mv_fts_tags depends on table tags
  Hint: Use DROP ... CASCADE to drop the dependent objects too. [Failed SQL: (0) DROP TABLE public.tags]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:76)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1291)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1273)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:725)
	... 40 more
Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop table tags because other objects depend on it
  Detail: materialized view mv_fts_tags depends on table tags
  Hint: Use DROP ... CASCADE to drop the dependent objects too.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor218.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy2/jdk.proxy2.$Proxy38.execute(Unknown Source)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:460)
	... 45 more
```

### Steps To Reproduce

The changeset in question is:
```xml
	<changeSet id="convert-tags-to-notes" author="somebody">
		<sql>
			INSERT INTO PEOPLE (uuid, name, status, role, "createdAt", "updatedAt")
				SELECT ${uuid_function}, 'ANET Importer', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
				WHERE NOT EXISTS (SELECT uuid FROM people WHERE name = 'ANET Importer' AND role = 0);

                        -- Create one note for each tag;
                        -- since notes are only editable by their author (the ANET Importer in this case) or admin,
                        -- this is safe
			INSERT INTO notes (uuid, "authorUuid", type, text, "createdAt", "updatedAt")
				SELECT
					t.uuid,
					(SELECT uuid FROM people WHERE name = 'ANET Importer' AND role = 0),
					0,
					CONCAT('Previously tagged as ', t.name, ' - ',  t.description),
					t."createdAt",
					t."updatedAt"
				FROM
					tags t;

                        -- Link reports to the note containing their former tag
			INSERT INTO "noteRelatedObjects" ("noteUuid", "relatedObjectType", "relatedObjectUuid")
				SELECT
					rt."tagUuid",
					'reports',
					rt."reportUuid"
				FROM
					"reportTags" rt;
		</sql>
		<sql dbms="postgresql">
			DROP MATERIALIZED VIEW mv_fts_tags;
		</sql>
		<dropForeignKeyConstraint baseTableName="reportTags" constraintName="FK_reportTags_report" />
		<dropForeignKeyConstraint baseTableName="reportTags" constraintName="FK_reportTags_tag" />
		<dropTable tableName="reportTags" />
		<dropTable tableName="tags" />
		<!-- Remove tags from saved searches -->
		<!-- Requires at least SQL Server 2016: -->
		<sql dbms="mssql">
			-- Remove JSON field for the tagUuid
			UPDATE savedSearches SET query=JSON_MODIFY(query, '$.tagUuid', NULL);
		</sql>
		<!-- Requires at least PostgreSQL 9.5: -->
		<sql dbms="postgresql">
			-- Remove JSON field for the tagUuid
			UPDATE "savedSearches" SET query=query::jsonb #- '{tagUuid}';
		</sql>
	</changeSet>
```

### Expected/Desired Behavior

The latest Liquibase version with which this still works is 4.21.1.
With 4.22.0 and 4.23.0 it fails with the errors shown above.

For comparison, the output of a successful migration of the same changeset with 4.21.1 is:
```
Running Changeset: migrations.xml::convert-tags-to-notes::somebody
[2023-06-27 13:54:57.892] INFO liquibase.changelog.ChangeSet: Custom SQL executed
[2023-06-27 13:54:57.893] INFO liquibase.changelog.ChangeSet: Custom SQL executed
[2023-06-27 13:54:57.894] INFO liquibase.changelog.ChangeSet: Foreign key FK_reportTags_report dropped
[2023-06-27 13:54:57.894] INFO liquibase.changelog.ChangeSet: Foreign key FK_reportTags_tag dropped
[2023-06-27 13:54:57.895] INFO liquibase.changelog.ChangeSet: Table reportTags dropped
[2023-06-27 13:54:57.896] INFO liquibase.changelog.ChangeSet: Table tags dropped
[2023-06-27 13:54:57.897] INFO liquibase.changelog.ChangeSet: Custom SQL executed
[2023-06-27 13:54:57.901] INFO liquibase.changelog.ChangeSet: ChangeSet migrations.xml::convert-tags-to-notes::somebody ran successfully in 12ms
```
The desired behaviour is obviously that it executes all statements in the changeset in the exact same order as before.

### Liquibase Version

4.23.0

### Database Vendor & Version

PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Liquibase Integration

Dropwizard

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @gjvoosten ! I managed to reproduce it with a simpler changelog:

```
    <changeSet id="0" author="fl" >
        <sql>create table anydb(id boolean default true, status varchar(2))</sql>
        <sql dbms="oracle">create table oraculo(id boolean default true, status varchar(2))</sql>
    </changeSet>
```

When I run this on postgres none of them is executed. So seems that dbms flag is being applied to the whole changeset instead of just to that sql tag.

**Comment by gjvoosten** [comment]
Just to confirm that release 4.23.1 fixes this issue for me; thanks @filipelautert!
