### ISSUE TITLE
Unexpected error running Liquibase: class java.lang.String cannot be cast to class liquibase.database.Database

### ISSUE THREAD

**Issue by saikotaa** [liquibase/liquibase#4486]
### Search first

- [X] I searched and no similar issues were found

### Description

Error while running [liquibase update github action](https://github.com/liquibase-github-actions/update) getting this error

## ERROR
```
INFO [liquibase.ui] ####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 19:00:05 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
Liquibase Version: 4.21.1
[2023-07-12 19:00:05] INFO [liquibase.ui] Liquibase Version: 4.21.1
Liquibase Open Source 4.21.1 by Liquibase
[2023-07-12 19:00:05] INFO [liquibase.ui] Liquibase Open Source 4.21.1 by Liquibase
[2023-07-12 19:00:05] INFO [liquibase.integration] Starting command execution.
[2023-07-12 19:00:05] INFO [liquibase.command] Command execution complete
[2023-07-12 19:00:05] SEVERE [liquibase.integration] class java.lang.String cannot be cast to class liquibase.database.Database (java.lang.String is in module java.base of loader 'bootstrap'; liquibase.database.Database is in unnamed module of loader java.net.URLClassLoader @15db97[42](https://github.com/AAInternal/itfacs-pmt-paymntsvcs-sql-migrations/actions/runs/5535404127/jobs/10101653154#step:8:43))
liquibase.exception.CommandExecutionException: java.lang.ClassCastException: class java.lang.String cannot be cast to class liquibase.database.Database (java.lang.String is in module java.base of loader 'bootstrap'; liquibase.database.Database is in unnamed module of loader java.net.URLClassLoader @15db9742)
	at liquibase.command.CommandScope.execute(CommandScope.java:235)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$2(LiquibaseCommandLine.java:383)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class liquibase.database.Database (java.lang.String is in module java.base of loader 'bootstrap'; liquibase.database.Database is in unnamed module of loader java.net.URLClassLoader @15db9742)
	at liquibase.command.core.helpers.DbUrlConnectionCommandStep.obtainDatabase(DbUrlConnectionCommandStep.java:96)
	at liquibase.command.core.helpers.DbUrlConnectionCommandStep.run(DbUrlConnectionCommandStep.java:[69](https://github.com/AAInternal/itfacs-pmt-paymntsvcs-sql-migrations/actions/runs/5535404127/jobs/10101653154#step:8:70))
	at liquibase.command.CommandScope.execute(CommandScope.java:212)
	... 23 more
```

## GITHUB ACTION
```yaml
    steps:
      - uses: actions/checkout@v3
      - name: Apply Changes
        uses: liquibase-github-actions/update@v4.21.1
        env:
          DATA_SOURCE: east
        with:
          logLevel: INFO
          showSummary: summary
          rollbackOnError: true
          changelogFile: ./changelogs/database.yaml
          url: jdbc:postgresql://${{ secrets.DB-HOST }}:5432/testbackend
          database: testbackend
          username: ${{ secrets.DB-USERNAME }}
          password: ${{ secrets.DB-PASSWORD }}
```

### Expected/Desired Behavior

- expect all changelogs to be applies

### Liquibase Version

4.21.1

### Database Vendor & Version

14.3

### Liquibase Integration

github action

### OS and/or Infrastructure Type/Provider

ubuntu 22.04

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @saikotaa ! Please remove attribute  `database: testbackend`  from your configuration .  This parameter receives an instance of Database object, so it should not even show on https://github.com/liquibase-github-actions/update documentation.  We will review the docs and get rid of it.
After removing it could you confirm that it works?

**Comment by filipelautert** [comment]
@kevin-atx - btw I created https://github.com/liquibase/github-action-generator/issues/85 to track it.

**Comment by saikotaa** [comment]
trying this out. thank you @filipelautert!
