### ISSUE TITLE
Update command of Liquibase version > 4.20.0 throws CommandValidationException when changeLogFile parameter is missing

### ISSUE THREAD

**Issue by jflalande98** [liquibase/liquibase#4491]
### Search first

- [X] I searched and no similar issues were found

### Description

We are using Liquibase the following way in a java application:

- Create a Liquibase instance specifying a changeLog file and then use the listUnrunChangeSets() method to find the changesets that have not been executed
- We have custom code that filters the list of changesets based on some conditions (some changesets may be discarded because we do not want to execute them)
- Create another Liquibase instance specifying a DatabaseChangeLog in which we added the list of filtered changesets and then execute the update() method

In versions up to 4.20.0, Liquibase was executing the list of changesets contained in the DatabaseChangeLog. In version 4.21.0 and above, the changeLogFile parameter of the update command is mandatory and it is not possible anymore to execute a custom list of changesets.

### Steps To Reproduce

[liquibase_update_test.zip](https://github.com/liquibase/liquibase/files/12042666/liquibase_update_test.zip)

I uploaded a small java project containing a test that reproduces the problem. The project assumes that the test will be executed using a mysql database (this driver is included in the pom file). There are 3 static variables in the test that you need to update according to your database (DB_URL, DB_USER, DB_PASSWORD).

You just need to run the test using maven with the following command: mvn test

You should have a result similar to this:

``
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.649 sec <<< FAILURE!
liquibaseUpdateTest(test.LiquibaseUpdateTest)  Time elapsed: 2.553 sec  <<< ERROR!
liquibase.exception.CommandValidationException: Invalid argument 'changelogFile': missing required argument
        at liquibase.command.CommandArgumentDefinition.validate(CommandArgumentDefinition.java:139)
        at liquibase.command.CommandScope.validate(CommandScope.java:181)
        at liquibase.command.CommandScope.execute(CommandScope.java:206)
        at liquibase.Liquibase.lambda$update$0(Liquibase.java:223)
        at liquibase.Scope.lambda$child$0(Scope.java:197)
        at liquibase.Scope.child(Scope.java:206)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:175)
        at liquibase.Liquibase.runInScope(Liquibase.java:1361)
        at liquibase.Liquibase.update(Liquibase.java:215)
        at liquibase.Liquibase.update(Liquibase.java:197)
        at liquibase.Liquibase.update(Liquibase.java:183)
        at liquibase.Liquibase.update(Liquibase.java:161)
        at test.LiquibaseUpdateTest.liquibaseUpdateTest(LiquibaseUpdateTest.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: liquibase.exception.MissingRequiredArgumentException
        ... 46 more
``

### Expected/Desired Behavior

The changelog file included in the test contains 2 changesets. The test loads all changesets from the changelog file, filters the changeset list to keep only the first one and finally calls the update method with the filtered list of changesets. I would expect the first changeset in the file to be executed and not the second one.

### Liquibase Version

> 4.20.0

### Database Vendor & Version

irrelevant

### Liquibase Integration

irrelevant

### Liquibase Extensions

irrelevant

### OS and/or Infrastructure Type/Provider

irrelevant

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @jflalande98 , I looked into this, and it is most likely caused by a change in the Liquibase.java constructor. It used to require a changelog of type DatabaseChangeLog, but now it requires a string (a path to the changelog file).
I will be forwarding this to the dev team so they can evaluate how to move forward.
Thank you for letting us know!
Tatiana

**Comment by kevin-atx** [comment]
Per @filipelautert - adding this as a candidate for the next sprint.

**Comment by kevin-atx** [comment]
@filipelautert says we need an additional argument that allows them to pass the changelog list instead of just the changelog filename.

**Comment by kevin-atx** [comment]
@jflalande98 - would you be willing to submit a PR with this new argument?

**Comment by jflalande98** [comment]
I currently don't have time to submit a PR. I may have time later if no one can fix the problem until then.

**Comment by filipelautert** [comment]
Hello @jflalande98 ! I created PR #4653  to fix this issue. I tested with your sample code and it's working, but could you give it a try too? 
Thanks

**Comment by jflalande98** [comment]
Hi @filipelautert ! I tested your fix with my application and it is now working. Thank you very much!
