### ISSUE TITLE
YAML changelog -> No path attribute for includeAll (even though it is present)

### ISSUE THREAD

**Issue by Coronon** [liquibase/liquibase#4498]
### Search first

- [X] I searched and no similar issues were found

### Description

This is my first time using Liquibase, so I might just overlook something: I am trying to direct Liquibase to use all changesets in a specific directory using `includeAll` in a YAML `changelog.yml`. Even though I set the `path` attribute, it tells me that it is missing:

```txt
Unexpected error running Liquibase: Error parsing changelog/changelog.yml : No path attribute for includeAll
```

<details>
  <summary>Debug log</summary>

The following log is truncated to fit GitHub's max issue body length. For the full debug log see [PasteBin](https://pastebin.com/cNMBVy55).

```txt
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for directory /liquibase
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] No configuration value for liquibase.searchPath found      
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/liquibase-core.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for directory /liquibase/lib
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jcc.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/commons-lang3.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/mariadb-java-client.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/liquibase-commercial.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/opencsv.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/snakeyaml.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/sqlite-jdbc.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaybird.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/snowflake-jdbc.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/h2.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaxb-api.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/hsqldb.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/picocli.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/commons-text.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/postgresql.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaxb-runtime.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/commons-collections4.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/mssql-jdbc.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/jaxb-core.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for file /liquibase/internal/lib/ojdbc8.jar
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Creating resourceAccessor for directory /liquibase/internal/lib 
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.resource] Overall search path:
liquibase-1  |   - /liquibase
liquibase-1  |   - /liquibase/internal/lib/liquibase-core.jar
liquibase-1  |   - /liquibase/lib
liquibase-1  |   - /liquibase/internal/lib/jcc.jar
liquibase-1  |   - /liquibase/internal/lib/commons-lang3.jar
liquibase-1  |   - /liquibase/internal/lib/mariadb-java-client.jar
liquibase-1  |   - /liquibase/internal/lib/liquibase-commercial.jar
liquibase-1  |   - /liquibase/internal/lib/opencsv.jar
liquibase-1  |   - /liquibase/internal/lib/snakeyaml.jar
liquibase-1  |   - /liquibase/internal/lib/sqlite-jdbc.jar
liquibase-1  |   - /liquibase/internal/lib/jaybird.jar
liquibase-1  |   - /liquibase/internal/lib/snowflake-jdbc.jar
liquibase-1  |   - /liquibase/internal/lib/h2.jar
liquibase-1  |   - /liquibase/internal/lib/jaxb-api.jar
liquibase-1  |   - /liquibase/internal/lib/hsqldb.jar
liquibase-1  |   - /liquibase/internal/lib/picocli.jar
liquibase-1  |   - /liquibase/internal/lib/commons-text.jar
liquibase-1  |   - /liquibase/internal/lib/postgresql.jar
liquibase-1  |   - /liquibase/internal/lib/jaxb-runtime.jar
liquibase-1  |   - /liquibase/internal/lib/commons-collections4.jar
liquibase-1  |   - /liquibase/internal/lib/mssql-jdbc.jar
liquibase-1  |   - /liquibase/internal/lib/jaxb-core.jar
liquibase-1  |   - /liquibase/internal/lib/ojdbc8.jar
liquibase-1  |   - /liquibase/internal/lib
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] No configuration value for liquibase.mirrorConsoleMessagesToLog found
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] Configuration liquibase.mirrorConsoleMessagesToLog is using the default value of true
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] No configuration value for liquibase.shouldRun aka should.run found
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] Configuration liquibase.shouldRun is using the default value of true
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] No configuration value for liquibase.showBanner found      
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] Configuration liquibase.showBanner is using the default value of true
liquibase-1  | ####################################################
liquibase-1  | ##   _     _             _ _                      ##
liquibase-1  | ##  | |   (_)           (_) |                     ##
liquibase-1  | ##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
liquibase-1  | ##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
liquibase-1  | ##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
liquibase-1  | ##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
liquibase-1  | ##              | |                               ##
liquibase-1  | ##              |_|                               ##
liquibase-1  | ##                                                ##
liquibase-1  | ##  Get documentation at docs.liquibase.com       ##
liquibase-1  | ##  Get certified courses at learn.liquibase.com  ##
liquibase-1  | ##                                                ##
liquibase-1  | ####################################################
liquibase-1  | Starting Liquibase at 21:58:43 (version 4.23.0 #10709 built at 2023-06-23 21:18+0000)
liquibase-1  | [2023-07-14 21:58:43] INFO [liquibase.ui] ####################################################
liquibase-1  | ##   _     _             _ _                      ##
liquibase-1  | ##  | |   (_)           (_) |                     ##
liquibase-1  | ##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
liquibase-1  | ##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
liquibase-1  | ##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
liquibase-1  | ##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
liquibase-1  | ##              | |                               ##
liquibase-1  | ##              |_|                               ##
liquibase-1  | ##                                                ##
liquibase-1  | ##  Get documentation at docs.liquibase.com       ##
liquibase-1  | ##  Get certified courses at learn.liquibase.com  ##
liquibase-1  | ##                                                ##
liquibase-1  | ####################################################
liquibase-1  | Starting Liquibase at 21:58:43 (version 4.23.0 #10709 built at 2023-06-23 21:18+0000)
liquibase-1  | Liquibase Version: 4.23.0
liquibase-1  | [2023-07-14 21:58:43] INFO [liquibase.ui] Liquibase Version: 4.23.0
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] No configuration value for liquibase.licenseKey found      
liquibase-1  | [2023-07-14 21:58:43] FINE [liquibase.configuration] No configuration value for liquibase.pro.licenseKey found  
liquibase-1  | Liquibase Open Source 4.23.0 by Liquibase
liquibase-1  | [2023-07-14 21:58:43] INFO [liquibase.ui] Liquibase Open Source 4.23.0 by Liquibase

// Omitted to fit max issue body length (see PasteBin above)

liquibase-1  | [2023-07-14 21:58:44] FINE [liquibase.configuration] No configuration value for liquibase.secureParsing found   
liquibase-1  | [2023-07-14 21:58:44] FINE [liquibase.configuration] Configuration liquibase.secureParsing is using the default 
value of true
liquibase-1  | [2023-07-14 21:58:44] FINE [liquibase.servicelocator] Loaded liquibase.parser.ChangeLogParser instance liquibase.parser.core.xml.XMLChangeLogSAXParser
liquibase-1  | [2023-07-14 21:58:44] FINE [liquibase.servicelocator] Loaded liquibase.parser.ChangeLogParser instance liquibase.parser.core.yaml.YamlChangeLogParser
liquibase-1  | [2023-07-14 21:58:44] FINE [liquibase.executor] Release Database Lock
liquibase-1  | [2023-07-14 21:58:44] FINE [liquibase.executor] Changelog query completed.
liquibase-1  | [2023-07-14 21:58:44] INFO [liquibase.lockservice] Successfully released change log lock
liquibase-1  | [2023-07-14 21:58:44] INFO [liquibase.command] Command execution complete
liquibase-1  | [2023-07-14 21:58:44] SEVERE [liquibase.integration] Error parsing changelog/changelog.yml : No path attribute for includeAll
liquibase-1  | liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: Error parsing changelog/changelog.yml : No path attribute for includeAll
liquibase-1  |  at liquibase.command.CommandScope.execute(CommandScope.java:236)
liquibase-1  |  at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
liquibase-1  |  at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
liquibase-1  |  at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
liquibase-1  |  at picocli.CommandLine.access$1500(CommandLine.java:148)
liquibase-1  |  at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
liquibase-1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
liquibase-1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
liquibase-1  |  at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
liquibase-1  |  at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
liquibase-1  |  at picocli.CommandLine.execute(CommandLine.java:2170)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:381)      
liquibase-1  |  at liquibase.Scope.child(Scope.java:206)
liquibase-1  |  at liquibase.Scope.child(Scope.java:182)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:356)      
liquibase-1  |  at liquibase.Scope.child(Scope.java:206)
liquibase-1  |  at liquibase.Scope.child(Scope.java:182)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:354)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:94)
liquibase-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
liquibase-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
liquibase-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
liquibase-1  |  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
liquibase-1  | Caused by: liquibase.exception.ChangeLogParseException: Error parsing changelog/changelog.yml : No path attribute for includeAll
liquibase-1  |  at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:94)
liquibase-1  |  at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:114)
liquibase-1  |  at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:92)       
liquibase-1  |  at liquibase.command.CommandScope.execute(CommandScope.java:213)
liquibase-1  |  ... 23 more
liquibase-1  | Caused by: liquibase.exception.SetupException: No path attribute for includeAll
liquibase-1  |  at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:751)
liquibase-1  |  at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:498)
liquibase-1  |  at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:378)
liquibase-1  |  at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:88)
liquibase-1  |  ... 26 more
liquibase-1  | Caused by: liquibase.exception.SetupException: No path attribute for includeAll
liquibase-1  |  at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:687)
liquibase-1  |  ... 29 more
liquibase-1  | 
liquibase-1  | 
liquibase-1  | Unexpected error running Liquibase: Error parsing changelog/changelog.yml : No path attribute for includeAll    
liquibase-1  | 
liquibase-1  | liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: Error parsing changelog/changelog.yml : No path attribute for includeAll
liquibase-1  |  at liquibase.command.CommandScope.execute(CommandScope.java:236)
liquibase-1  |  at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
liquibase-1  |  at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
liquibase-1  |  at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
liquibase-1  |  at picocli.CommandLine.access$1500(CommandLine.java:148)
liquibase-1  |  at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
liquibase-1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
liquibase-1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
liquibase-1  |  at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
liquibase-1  |  at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
liquibase-1  |  at picocli.CommandLine.execute(CommandLine.java:2170)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:381)      
liquibase-1  |  at liquibase.Scope.child(Scope.java:206)
liquibase-1  |  at liquibase.Scope.child(Scope.java:182)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:356)      
liquibase-1  |  at liquibase.Scope.child(Scope.java:206)
liquibase-1  |  at liquibase.Scope.child(Scope.java:182)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:354)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:94)
liquibase-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
liquibase-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
liquibase-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
liquibase-1  |  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
liquibase-1  |  at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
liquibase-1  | Caused by: liquibase.exception.ChangeLogParseException: Error parsing changelog/changelog.yml : No path attribute for includeAll
liquibase-1  |  at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:94)
liquibase-1  |  at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:114)
liquibase-1  |  at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:92)       
liquibase-1  |  at liquibase.command.CommandScope.execute(CommandScope.java:213)
liquibase-1  |  ... 23 more
liquibase-1  | Caused by: liquibase.exception.SetupException: No path attribute for includeAll
liquibase-1  |  at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:751)
liquibase-1  |  at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:498)
```
</details>

### Steps To Reproduce

**changelog.yml**
```yml
databaseChangeLog:
  - includeAll:
    path: migrations
    relativeToChangelogFile: true
```

**Command** (ran inside a docker container with the files mounted in `/liquibase/changelog`:
```bash
liquibase update --changeLogFile=changelog/changelog.yml
```

### Expected/Desired Behavior

Liquibase runs the update command

### Liquibase Version

Liquibase Open Source 4.23.0 by Liquibase

### Database Vendor & Version

PostgreSQL 15.1

### Liquibase Integration

CLI (Docker)

### OS and/or Infrastructure Type/Provider

Docker (x86_64-pc-linux-gnu)

### Additional Context

**docker-compose.yml**:

```yml
version: "3"

services:
  # ...

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - db
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://db:5432/${DB_POSTGRES_DB}
      - LIQUIBASE_COMMAND_USERNAME=${DB_POSTGRES_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${DB_POSTGRES_PASSWORD}
    volumes:
      - ./db/liquibase:/liquibase/changelog
    command: "bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; liquibase update --changeLogFile=changelog/changelog.yml'"
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by wwillard7800** [comment]
Hello Coronon,

Try indenting the `path` attribute of `includeAll`, like

```
databaseChangeLog:
  - includeAll:
    path: subdir/

```

so that is recognized as a child attribute of `includeAll`.

Wesley

**Comment by Coronon** [comment]
Well, turns out my indentation was incorrect!

Instead of:
```yml
databaseChangeLog:
  - includeAll:
      path: subdir/
```

One has to use:
```yml
databaseChangeLog:
  - includeAll:
  # Notice the extra indent here
        path: subdir/
```

Closing the issue, but leaving this here for anyone else encountering this issue.

**Comment by wwillard7800** [comment]
No problem @Coronon glad to be of assistance
