### ISSUE TITLE
SQL File change gets deployed even when author attribute is null

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#4837]
### Search first

- [X] I searched and no similar issues were found

### Description

@jccampanero  has identified an issue when when a SQL file change is included in a changeset with `author=null` a validation error is displayed , but SQL file gets executed anyway. 

### Steps To Reproduce

Having a changelog like the one below:

```
databaseChangeLog:
  - changeSet:
      id: create-schema
      changes:
        - sqlFile:
            path: changelog/sql/storeProcedure.sql
            splitStatements: false
```

where author has not been provided, a validation error for missing author property is returned, but SQL file change gets deployed anyway.

Returned error:
```
[2023-09-04 16:59:39] SEVERE [liquibase.integration] ERROR: null value in column "author" of relation "databasechangelog" violates not-null constraint
  Detail: Failing row contains (create-schema, null, changelog/yaml/missing.author.changelog.yaml, 2023-09-04 16:59:39.031778, 1, EXECUTED, 9:f818070af488662a19fefd0af125ea34, sqlFile path=changelog/sql/storeProcedure.sql, , null, DEV, null, null, 3857578976). [Failed SQL: (0) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('create-schema', NULL, 'changelog/yaml/missing.author.changelog.yaml', NOW(), 1, '9:f818070af488662a19fefd0af125ea34', 'sqlFile path=changelog/sql/storeProcedure.sql', '', 'EXECUTED', NULL, NULL, 'DEV', '3857578976')]
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: null value in column "author" of relation "databasechangelog" violates not-null constraint
  Detail: Failing row contains (create-schema, null, changelog/yaml/missing.author.changelog.yaml, 2023-09-04 16:59:39.031778, 1, EXECUTED, 9:f818070af488662a19fefd0af125ea34, sqlFile path=changelog/sql/storeProcedure.sql, , null, DEV, null, null, 3857578976). [Failed SQL: (0) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('create-schema', NULL, 'changelog/yaml/missing.author.changelog.yaml', NOW(), 1, '9:f818070af488662a19fefd0af125ea34', 'sqlFile path=changelog/sql/storeProcedure.sql', '', 'EXECUTED', NULL, NULL, 'DEV', '3857578976')]
	at liquibase.command.CommandScope.execute(CommandScope.java:237)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:383)
	at liquibase.Scope.child(Scope.java:192)
	at liquibase.Scope.child(Scope.java:168)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
	at liquibase.Scope.child(Scope.java:192)
	at liquibase.Scope.child(Scope.java:168)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
```

As well as below log messages showing store procedure from the included sql file has been successfully deployed:
```
[2023-09-04 16:59:38] FINE [liquibase.database] Executing Statement: CREATE OR REPLACE PROCEDURE testHello()
LANGUAGE plpgsql
AS $$
BEGIN
    raise notice ' Hello From The Database! ';
END; $$
[2023-09-04 16:59:38] FINE [liquibase.executor] CREATE OR REPLACE PROCEDURE testHello()
LANGUAGE plpgsql
AS $$
BEGIN
    raise notice ' Hello From The Database! ';
END; $$
[2023-09-04 16:59:39] FINE [liquibase.executor] 0 row(s) affected
[2023-09-04 16:59:39] INFO [liquibase.changelog] SQL in file changelog/sql/storeProcedure.sql executed
```

### Expected/Desired Behavior

author null validation error should be returned, and SQL file change should not be deployed if there is any error.

### Liquibase Version

latest

### Database Vendor & Version

PostgreSQL 14.4

### Liquibase Integration

CLI

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
Thank you @jccampanero for testing #4249 and #3200 for us and finding this issue while performing your test.

Regards,
Daniel.

**Comment by jccampanero** [comment]
Sorry for the late reply @MalloD12 Daniel.

You are welcome, my pleasure.

Thank you very much for opening this new issue: I would be glad to work on it if you wish.

**Comment by MalloD12** [comment]
> Sorry for the late reply @MalloD12 Daniel.
> 
> You are welcome, my pleasure.
> 
> Thank you very much for opening this new issue: I would be glad to work on it if you wish.

That would be great, thank you @jccampanero!

**Comment by MalloD12** [comment]
Hi @jccampanero,

Is there anything I can help you with on this issue?

Thanks,
Daniel.

**Comment by jccampanero** [comment]
Sorry for the late reply @MalloD12 Daniel.

Probably Daniel 😄 , a lot of things...

Seriously: I am very sorry, mainly for personal reasons, I haven't had time to work on the issue, in any issue in fact.

I will try to do my best and work on it during this holidays.

By the way, Merry Xmas and Happy New Year my friend.

**Comment by MalloD12** [comment]
> Sorry for the late reply @MalloD12 Daniel.
> 
> Probably Daniel 😄 , a lot of things...
> 
> Seriously: I am very sorry, mainly for personal reasons, I haven't had time to work on the issue, in any issue in fact.
> 
> I will try to do my best and work on it during this holidays.
> 
> By the way, Merry Xmas and Happy New Year my friend.

No worries, that sounds good to me. Merry Xmas and Happy New Year, Jose!!

**Comment by jccampanero** [comment]
First of all, I apologize for taking so long to address this issue: I am very very sorry.

I've tested the current version of the Liquibase library, and the error persists.

In fact, the current behavior is strange for several reasons.

When the change log is written in XML, the __parser__ reports an error similar to the following if the `author` attribute is not defined:

```
ERROR: Exception Primary Class:  SAXParseException

ERROR: Exception Primary Reason:  cvc-complex-type.4: El atributo 'author' debe aparecer en el elemento 'changeSet'.
```

Conversely, when the change log is written in YAML format, an error is reported only if the configuration value `GlobalConfiguration.STRICT` is set to `true`, by `ValidatingVisitor`.

However, it seems inconsistent because, if `GlobalConfiguration.STRICT` is set to `false`, and `author` is undefined, using YAML format, the problem described in this issue arises.

What should be the correct behavior? Perhaps, defining a fallback value when `author` is not provided and `GlobalConfiguration.STRICT` is set to `true`? 

Should the XML parser permit a null `author` attribute?

Must `ValidatingVisitor` be the only actor that should perform this validation?

Thank you very much and again, sorry for the late response.

**Comment by pclaudinoo** [comment]
Hi @jccampanero are you still able to work on this? 

I believe @MalloD12 's intention (and now mine) is that the `validate` command catches this error and fails. 

I believe it is normal for users to run validate before updateSQL and update, and we expect that a badly formatted YAML that will result in an inconsistent `DATABASECHANGELOG` passes.

I made a similar test on Liquibase Community 5.0.2. The error still remains:
```
# validate
[2026-05-21 16:03:30] INFO [liquibase.ui] Liquibase Version: 5.0.2
[2026-05-21 16:03:30] INFO [liquibase.ui] 
[2026-05-21 16:03:30] INFO [liquibase.integration] Starting command execution.
[2026-05-21 16:03:33] INFO [liquibase.ext] Using percona toolkit: 3.7.1
[2026-05-21 16:03:35] INFO [liquibase.changelog] Reading from pablo_test.DATABASECHANGELOG
No validation errors found.
[2026-05-21 16:03:35] INFO [liquibase.ui] No validation errors found.
[2026-05-21 16:03:35] INFO [liquibase.command] Command execution complete
Liquibase command 'validate' was executed successfully.
[2026-05-21 16:03:35] INFO [liquibase.ui] Liquibase command 'validate' was executed successfully.

# status
[2026-05-21 16:03:36] INFO [liquibase.ui] Liquibase Version: 5.0.2
[2026-05-21 16:03:36] INFO [liquibase.ui] 
[2026-05-21 16:03:36] INFO [liquibase.integration] Starting command execution.
[2026-05-21 16:03:38] INFO [liquibase.ext] Using percona toolkit: 3.7.1
[2026-05-21 16:03:40] INFO [liquibase.changelog] Reading from pablo_test.DATABASECHANGELOG
2 changesets have not been applied to liquibase@xxx@jdbc:mysql://pablo-test-cluster-v13-1.xxx.us-east-1.rds.amazonaws.com:3306/pablo_test
     infrastructure/liquibase/pablo_test/changelog.yaml::2026-05-21-02-books-avg-review-update::null
     infrastructure/liquibase/pablo_test/changelog.yaml::2026-05-21-03-books-published-years-update::pablo.claudino
[2026-05-21 16:03:41] INFO [liquibase.command] Command execution complete
Liquibase command 'status' was executed successfully.
[2026-05-21 16:03:41] INFO [liquibase.ui] Liquibase command 'status' was executed successfully.

# update
[2026-05-21 16:03:50] INFO [liquibase.ui] Liquibase Version: 5.0.2
[2026-05-21 16:03:50] INFO [liquibase.ui] 
[2026-05-21 16:03:50] INFO [liquibase.integration] Starting command execution.
[2026-05-21 16:03:52] INFO [liquibase.ext] Using percona toolkit: 3.7.1
[2026-05-21 16:03:54] INFO [liquibase.changelog] Reading from pablo_test.DATABASECHANGELOG
[2026-05-21 16:03:56] INFO [liquibase.lockservice] Successfully acquired change log lock
[2026-05-21 16:03:56] INFO [liquibase.command] Using deploymentId: 9379430376
[2026-05-21 16:03:56] INFO [liquibase.changelog] Reading from pablo_test.DATABASECHANGELOG
[2026-05-21 16:03:56] INFO [liquibase.ui] Running Changeset: infrastructure/liquibase/pablo_test/changelog.yaml::2026-05-21-02-books-avg-review-update::null
[2026-05-21 16:03:57] INFO [liquibase.changelog] SQL in file changelog.2026-05-21.02.books_avg_review.update.sql executed
[2026-05-21 16:03:57] INFO [liquibase.changelog] ChangeSet infrastructure/liquibase/pablo_test/changelog.yaml::2026-05-21-02-books-avg-review-update::null ran successfully in 558ms
[2026-05-21 16:03:57] INFO [liquibase.util] UPDATE SUMMARY
[2026-05-21 16:03:57] INFO [liquibase.util] Run:                          0
[2026-05-21 16:03:57] INFO [liquibase.util] Previously run:              10
[2026-05-21 16:03:57] INFO [liquibase.util] Filtered out:                 0
[2026-05-21 16:03:57] INFO [liquibase.util] -------------------------------
[2026-05-21 16:03:57] INFO [liquibase.util] Total change sets:           12
[2026-05-21 16:03:57] INFO [liquibase.util] Update summary generated
[2026-05-21 16:03:57] INFO [liquibase.command] Update command encountered an exception.
[2026-05-21 16:03:58] INFO [liquibase.lockservice] Successfully released change log lock
[2026-05-21 16:03:58] INFO [liquibase.command] Logging exception.
[2026-05-21 16:03:58] INFO [liquibase.ui] ERROR: Exception Details
[2026-05-21 16:03:58] INFO [liquibase.ui] ERROR: Exception Primary Class:  SQLIntegrityConstraintViolationException
[2026-05-21 16:03:58] INFO [liquibase.ui] ERROR: Exception Primary Reason:  Column 'AUTHOR' cannot be null
[2026-05-21 16:03:58] INFO [liquibase.ui] ERROR: Exception Primary Source:  MySQL 8.0.44
[2026-05-21 16:03:58] INFO [liquibase.command] Command execution complete
[2026-05-21 16:03:58] SEVERE [liquibase.integration] Column 'AUTHOR' cannot be null [Failed SQL: (1048) INSERT INTO pablo_test.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2026-05-21-02-books-avg-review-update', NULL, 'infrastructure/liquibase/pablo_test/changelog.yaml', NOW(), 20, '9:561ceea8552ab56043d57efe7c2bfec6', 'sqlFile path=changelog.2026-05-21.02.books_avg_review.update.sql', 'update books avg_review values', 'EXECUTED', NULL, NULL, '5.0.2', '9379430376')]
```
And my data was changed anyway.

**Comment by jccampanero** [comment]
Hi @pclaudinoo,

Yes, of course, it would be a pleasure to work on this.

I completely agree with the fact that `validate` should fail if the error is present.

But, don't you think that the same check should be performed in the `update` method as well?

Best regards.

**Comment by pclaudinoo** [comment]
Hey @jccampanero ,

Yes. I was looking at my logs again, and it executes the changeset before trying to insert into `DATABASECHANGELOG `, which leaves the schema management in an inconsistent state in case of failure.
The `update` method would be more resilient if it failed hard with this check before executing the changeset.
