### ISSUE TITLE
OOM when DB has lot tables

### ISSUE THREAD

**Issue by vchepeli** [liquibase/liquibase#4867]
### Search first

- [X] I searched and no similar issues were found

### Description

  Caused by:
  java.lang.OutOfMemoryError: Java heap space
      at java.base/java.lang.StringLatin1.toUpperCase(StringLatin1.java:539)
      at java.base/java.lang.String.toUpperCase(String.java:3469)
      at liquibase.executor.jvm.ColumnMapRowMapper.getColumnKey(ColumnMapRowMapper.java:67)
      at liquibase.executor.jvm.ColumnMapRowMapper.mapRow(ColumnMapRowMapper.java:39)
      at liquibase.executor.jvm.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:72)
      at liquibase.snapshot.ResultSetCache$ResultSetExtractor.extract(ResultSetCache.java:318)
      at liquibase.snapshot.ResultSetCache$ResultSetExtractor.extract(ResultSetCache.java:287)
      at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$4.getPkInfo(JdbcDatabaseSnapshot.java:1553)
      at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$4.fastFetchQuery(JdbcDatabaseSnapshot.java:1437)
      at liquibase.snapshot.ResultSetCache$SingleResultSetExtractor.fastFetch(ResultSetCache.java:342)
      at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:69)
      at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getPrimaryKeys(JdbcDatabaseSnapshot.java:1406)
      at liquibase.snapshot.jvm.PrimaryKeySnapshotGenerator.snapshotObject(PrimaryKeySnapshotGenerator.java:39)
      at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:65)
      at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
      at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:313)
      at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:106)
      at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
      at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
      at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:214)
      at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:243)
      at liquibase.snapshot.SnapshotGeneratorFactory.has(SnapshotGeneratorFactory.java:132)
      at liquibase.precondition.core.PrimaryKeyExistsPrecondition.check(PrimaryKeyExistsPrecondition.java:83)
      at liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:39)
      at liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213)
      at liquibase.changelog.ChangeSet.execute(ChangeSet.java:644)
      at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:120)
      at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:70)
      at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:110)
      at liquibase.changelog.ChangeLogIterator$2$$Lambda$934/0x000000080138d788.run(Unknown Source)
      at liquibase.Scope.lambda$child$0(Scope.java:197)
      at liquibase.Scope$$Lambda$894/0x00000008012d13c0.run(Unknown Source)

### Steps To Reproduce

1. Create DB
2. Create 1000+ tables
3. Run migrations

### Expected/Desired Behavior

It should not throw OOM error
Analyzed dump shows
Root object j.u.ArrayList@7e4163fa0
->j.u.ArrayList 493,990Kb (94.9%), self 2,822Kb (0.5%), 1 object(s)
  {list elements} 491,168Kb (94.3%), 542,880 reference(s)  **LEAK CANDIDATE**
  ->liquibase.snapshot.CachedRow 491,168Kb (94.3%), self 8,482Kb (1.6%), 542,880 object(s)
    ->.row 482,685Kb (92.7%), 542,880 reference(s)
      j.u.LinkedHashMap 482,685Kb (92.7%), self 182,373Kb (35.0%), 542,880 object(s)
      ->{keys} 169,650Kb (32.6%), 3,257,280 reference(s)
        String 169,650Kb (32.6%), self 169,650Kb (32.6%), 3,257,280 object(s)
      ->{values} 130,662Kb (25.1%), 2,171,520 reference(s)
        String 130,662Kb (25.1%), self 130,662Kb (25.1%), 2,171,520 object(s)

### Database Vendor & Version

PostgreSQL 12

### Liquibase Integration

Micronaut-Liquibase

### OS and/or Infrastructure Type/Provider

All

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @vchepeli, I'll need some more information in order to test this effectively.
Are you creating the 1000+ tables through Liquibase? Is that part giving any errors?
Regarding the migrations: what kind of changes are you making? And are you running them for all tables?
Thank you in advance
Tatiana

**Comment by vchepeli** [comment]
Hi @tati-qalified, below are replies for your questions

Are you creating the 1000+ tables through Liquibase?
Yes, tables are created with Liquibase migrations
Is that part giving any errors?
Yes, migrations started but its frozen after and couple minutes it throws OOM
Regarding the migrations: what kind of changes are you making?
Creating tables, add/remove columns, adding checks, indexes
And are you running them for all tables?
Yes, for all tables it runs

Thanks, Vitalij

**Comment by tati-qalified** [comment]
I couldn't reproduce the out of memory error, but I analysed the memory usage when running thousands of changesets, and it looks like the garbage collector isn't being fast enough. In my program, memory usage reached 1200+Mb before the garbage collector kicked in.

Thank you for letting us know of this issue, I'll forward this to the development team so they can evaluate how to move forward.

**Comment by vchepeli** [comment]
@tati-qalified you described actually what happened, I have 500MB for tests and I truncated databasechange table, so all migrations were gone, and after run all migrations again to simulate this issue, and it start to use log of MEM >500MB, rafter limit passed OOM, if you have some drive I can try to push heap dump

**Comment by vchepeli** [comment]
@tati-qalified here is [link](https://drive.google.com/file/d/1sV7sZlmSdVAZRUUgOKcX6jq1YIPzIN5H/view?usp=sharing), try to download it and let me know

**Comment by MalloD12** [comment]
Hi @vchepeli,

If it's not too time-consuming, could you please try again with our latest version to see if you are experiencing the same performance issue? During the last couple of releases there were some PRs merged that according to some other users performance has been improved for them. 

Thanks,
Daniel.
