### ISSUE TITLE
Drop all in a schema with a postgres owned by sequence DatabaseException

### ISSUE THREAD

**Issue by alexandreBaronZnk** [liquibase/liquibase#4896]
### Search first

- [X] I searched and no similar issues were found

### Description

Owned sequence are dropped even if the table that own this sequence have been drop before.
This behavior produces this log in a Spring Boot application :

```
2023-09-12T15:48:42.861+02:00 DEBUG 12698 --- [           main] liquibase.executor                       : DROP TABLE "my_schema"."my_table" CASCADE
2023-09-12T15:48:42.864+02:00 DEBUG 12698 --- [           main] liquibase.executor                       : 0 row(s) affected
2023-09-12T15:48:42.868+02:00 DEBUG 12698 --- [           main] liquibase.executor                       : DROP SEQUENCE "my_schema"."lrn_suffix" CASCADE
Error occurred during dropAll: ERROR: sequence "lrn_suffix" does not exist [Failed SQL: (0) DROP SEQUENCE "integration_test"."lrn_suffix" CASCADE]
It is possible that not all objects were dropped.

2023-09-12T15:48:42.871+02:00 ERROR 12698 --- [           main] liquibase.command                        : Error occurred during dropAll: ERROR: sequence "test_suffix" does not exist [Failed SQL: (0) DROP SEQUENCE "my_schema"."test_suffix" CASCADE]
It is possible that not all objects were dropped.


liquibase.exception.DatabaseException: ERROR: sequence "test_suffix" does not exist [Failed SQL: (0) DROP SEQUENCE "my_schema"."test_suffix" CASCADE]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:445) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.dropDatabaseObjects(AbstractJdbcDatabase.java:814) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:94) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.command.CommandScope.execute(CommandScope.java:195) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.Liquibase.dropAll(Liquibase.java:2157) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.Liquibase.dropAll(Liquibase.java:2136) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:345) ~[liquibase-core-4.20.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:282) ~[liquibase-core-4.20.0.jar:na]
```

After some investigation, I suspect this pull request https://github.com/liquibase/liquibase/pull/3335 to be at origin of this regression.
the `AbstractJdbcDatabase.dropDatabaseObjects` use the snapshot to list objects to drop.
And as the pull request add owned sequence into the snapshot, the drop database object try to remove an non-existing object.

### Steps To Reproduce

With the following changeset :

```sql
CREATE TABLE my_table
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    test      VARCHAR
);

CREATE SEQUENCE test_suffix MINVALUE 0 MAXVALUE 99999 CYCLE OWNED BY my_table.test;
```

When I execute my integration tests inside Spring Boot with the following configuration :
```yaml
spring:
  liquibase:
    drop-first: true
```

### Expected/Desired Behavior

Don't drop sequences that owned by a table previously dropped.

### Liquibase Version

4.18.0

### Database Vendor & Version

Postgres

### Liquibase Integration

Spring Boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @alexandreBaronZnk, thank you for reporting this issue.
I haven't been able to reproduce this bug using Liquibase v4.18.0, PostgreSQL v16.0.0 and Spring Boot v3.1.4.
It might have something to do with specific dependencies, so let me know what Spring Boot and PostgreSQL versions you're using so I can re-test this.
Thank you,
Tatiana

**Comment by alexandreBaronZnk** [comment]
Hello @tati-qalified, this is my dependencies versions :

 * spring-boot `3.1.3`
 * liquibase `4.20.0`
 * postgres `14.7`

**Comment by tati-qalified** [comment]
Thank you!
I was able to replicate this issue from v4.20.0 onwards, including v4.24.0.
I'll be forwarding this to the development team so they can evaluate how to move forward.
Thanks again,
Tatiana

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
