### ISSUE TITLE
Liquibase Error while Running Junit Test Suite: Cannot end scope jdmgrymevf when currently at scope egidvwaqwr

### ISSUE THREAD

**Issue by asmaa2wavelet** [liquibase/liquibase#4920]
### Search first

- [X] I searched and no similar issues were found

### Description

I'm facing an issue running liquibase with Junit test after implementing Hikari connection pooling. I'm using the following versions:
liquibase: 3.6.2
springframework.boot: 2.6.6
Java: 16

hikari connection configurations:
dbConfig.setMinimumIdle(2);
dbConfig.setMaximumPoolSize(10);

I tried configuring one of the above attributes at a time, using very high number for max pool size, using 1-10 range for minimum idle, but still facing the same issue no matter what I set for the above two attributes.

Detailed error message:
org.testng.TestNGException: 
Cannot instantiate class app.api.core2.controller.t2t.TenantInvitationControllerTest
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:30)
	at org.testng.internal.InstanceCreator.instantiateUsingDefaultConstructor(InstanceCreator.java:193)
	at org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:113)
	at org.testng.internal.InstanceCreator.createInstance(InstanceCreator.java:79)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:114)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:172)
	at org.testng.TestClass.getInstances(TestClass.java:102)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:82)
	at org.testng.TestClass.init(TestClass.java:74)
	at org.testng.TestClass.<init>(TestClass.java:39)
	at org.testng.TestRunner.initMethods(TestRunner.java:463)
	at org.testng.TestRunner.init(TestRunner.java:342)
	at org.testng.TestRunner.init(TestRunner.java:295)
	at org.testng.TestRunner.<init>(TestRunner.java:181)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:618)
	at org.testng.SuiteRunner.init(SuiteRunner.java:196)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:127)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1265)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1093)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:23)
	... 23 more
Caused by: java.lang.ExceptionInInitializerError
	at com.bigledger.testutil.db.PrepareServer.<clinit>(PrepareServer.java:16)
	at app.api.core2.controller.t2t.TenantInvitationControllerTest.<init>(TenantInvitationControllerTest.java:35)
	... 29 more
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope jdmgrymevf when currently at scope egidvwaqwr
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope jdmgrymevf when currently at scope egidvwaqwr
	at com.bigledger.testutil.db.DbCreator.lambda$createDbAndRunLiquibase$8(DbCreator.java:67)
	at io.vavr.control.Try.getOrElseThrow(Try.java:748)
	at com.bigledger.testutil.db.DbCreator.createDbAndRunLiquibase(DbCreator.java:64)
	at com.bigledger.testutil.db.DbCreator.lambda$createMasterTenantDbs$0(DbCreator.java:34)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	... 3 more
Caused by: java.lang.RuntimeException: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope jdmgrymevf when currently at scope egidvwaqwr
	at com.bigledger.testutil.db.DbCreator.runLiquibase(DbCreator.java:141)
	at com.bigledger.testutil.db.DbCreator.lambda$createDbAndRunLiquibase$6(DbCreator.java:64)
	at io.vavr.control.Try.run(Try.java:118)
	... 6 more
Caused by: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope jdmgrymevf when currently at scope egidvwaqwr
	at liquibase.Liquibase.runInScope(Liquibase.java:2409)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.Liquibase.update(Liquibase.java:193)
	at com.bigledger.testutil.db.DbCreator.runLiquibase(DbCreator.java:139)
	... 8 more
Caused by: java.lang.RuntimeException: Cannot end scope jdmgrymevf when currently at scope egidvwaqwr
	at liquibase.Scope.exit(Scope.java:226)
	at liquibase.Scope.child(Scope.java:188)
	at liquibase.Scope.child(Scope.java:176)
	at liquibase.Scope.child(Scope.java:155)
	at liquibase.Liquibase.runInScope(Liquibase.java:2404)
	... 12 more

Process finished with exit code -1

### Steps To Reproduce

Liquibase xml file:
<?xml version="1.0" encoding="UTF-8"?> 
<databaseChangeLog
	xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
	xmlns:pro="http://www.liquibase.org/xml/ns/pro"
	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
		https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
		http://www.liquibase.org/xml/ns/dbchangelog-ext https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
		http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd">

Test cases: 5k+

### Expected/Desired Behavior

Should be able to run the test suite successfully without having connections issue

### Liquibase Version

3.6.2

### Database Vendor & Version

postgres 14

### Liquibase Integration

gradle, spring boot

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@asmaa2wavelet - I'm unsure if this is relevant, but please review this information on running Liquibase in a multi-threaded environment.

- https://github.com/liquibase/liquibase/pull/3240

"This adds a liquibase.ThreadLocalScopeManager class which custom integrations can use to replace the default SingletonScopeManager with a call to Scope.setScopeManager(new ThreadLocalScopeManager())."

Please let me know if this helps (or not).

**Comment by tati-qalified** [comment]
Hi @asmaa2wavelet, checking in on this. Were you able to look into the linked PR? Do you need some guidance? Let us know!

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
