### ISSUE TITLE
Cassandra :: 'update-sql' command doesn't create Liquibase tracking tables

### ISSUE THREAD

**Issue by loragriffin** [liquibase/liquibase#5016]
### Search first

- [X] I searched and no similar issues were found

### Description

The user is configuring Liquibase with a brand-new, clean Cassandra database. They are attempting to run their pipeline, starting with “liquibase status” followed by “liquibase update-sql” before running any scripts. However, Liquibase is failing due to missing tracking tables. Liquibase should automatically create these tables when they don’t exist, which it’s trying to do, but clearly not working.

**Current proposed workaround:** upgrade to version 4.23.2+ and run “liquibase status” before running any other Liquibase commands.

### Steps To Reproduce

1. Create a brand new Cassandra database

2. Connect LB project to new DB

3. Run 'liquibase update-sql' (this should be the very first command run on this database)

4. Error message:

`Unexpected error running Liquibase: Error executing SQL SELECT COUNT(*) FROM getnet.DATABASECHANGELOGLOCK where locked = TRUE ALLOW FILTERING: [Simba][CassandraJDBCDriver](500211) ERROR Invalid query: SELECT COUNT(*) FROM getnet.DATABASECHANGELOGLOCK where locked = TRUE ALLOW FILTERING, Cause: com.simba.cassandra.shaded.datastax.driver.core.exceptions.InvalidQueryException: table databasechangeloglock does not exist.`

```
[2023-05-15 13:39:41] FINE [liquibase.executor] Changelog query completed.
-- Create Database Lock Table
CREATE TABLE IF NOT EXISTS getnet.DATABASECHANGELOGLOCK (ID INT, LOCKED BOOLEAN, LOCKGRANTED timestamp, LOCKEDBY TEXT, PRIMARY KEY (ID));

-- Initialize Database Lock Table
TRUNCATE TABLE getnet.DATABASECHANGELOGLOCK;

INSERT INTO getnet.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE);

[2023-05-15 13:39:43] INFO [liquibase.command] Command execution complete
[2023-05-15 13:39:43] SEVERE [liquibase.integration] Error executing SQL SELECT COUNT(*) FROM getnet.DATABASECHANGELOGLOCK where locked = TRUE ALLOW FILTERING: [Simba][CassandraJDBCDriver](500211) ERROR Invalid query: SELECT COUNT(*) FROM getnet.DATABASECHANGELOGLOCK where locked = TRUE ALLOW FILTERING, Cause: com.simba.cassandra.shaded.datastax.driver.core.exceptions.InvalidQueryException: table databasechangeloglock does not exist.
liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: Error executing SQL SELECT COUNT(*) FROM getnet.DATABASECHANGELOGLOCK where locked = TRUE ALLOW FILTERING: [Simba][CassandraJDBCDriver](500211) ERROR Invalid query: SELECT COUNT(*) FROM getnet.DATABASECHANGELOGLOCK where locked = TRUE ALLOW FILTERING, Cause: com.simba.cassandra.shaded.datastax.driver.core.exceptions.InvalidQueryException: table databasechangeloglock does not exist.
        at liquibase.command.CommandScope.execute(CommandScope.java:235)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
```

**Note:** If you run "liquibase status" before running "liquibase update-sql" you do not get this error in v4.23.2+, but you do in v4.15 regardless of running "liquibase status" first.

**Note:** I tested these exact steps in v4.23.2 on a Postgres database without any issues, so this seems specific to Cassandra.

### Expected/Desired Behavior

Users should be able to run ‘update-sql’ on an empty, new database without it failing on a Liquibase tracking table not existing.

### Liquibase Version

4.23.2

### Database Vendor & Version

Cassandra

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hello @loragriffin, thank you for letting us know of this issue.
Currently, Simba Cassandra JDBC driver is not available for download, as it has been deprecated. With the newest Cassandra driver, I haven't been able to replicate the bug. Would it be possible to update to this latest driver?
Thank you,
Tatiana

**Comment by Tylorjg** [comment]
I was able to reproduce this issue with the ING driver. 

- Liquibase version 4.25.0
- Liquibase Cassandra extension version 4.25.0
- ING driver

If the DBCL & DBCLL table **doesn't exist** in the database, the following error occurs when trying to run the with the `update-sql`

`Unexpected error running Liquibase: Error executing SQL SELECT COUNT(*) FROM DATABASECHANGELOGLOCK where LOCKED = TRUE AND LOCKEDBY = '<IP>' ALLOW FILTERING: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: table databasechangeloglock does not exist`

**Comment by tati-qalified** [comment]
@Tylorjg I re-tested this with liquibase and liquibase-cassandra version 4.25.0 and I'm getting a different error, though I think it's coming from the same place.

Here's my output:
```
-- Create Database Lock Table
CREATE TABLE IF NOT EXISTS DATABASECHANGELOGLOCK (ID INT, LOCKED BOOLEAN, LOCKGRANTED timestamp, LOCKEDBY TEXT, PRIMARY KEY (ID));

-- Initialize Database Lock Table
TRUNCATE TABLE DATABASECHANGELOGLOCK;

INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE);


Unexpected error running Liquibase: Error executing SQL SELECT COUNT(*) FROM DATABASECHANGELOGLOCK where LOCKED = TRUE AND LOCKEDBY = 'MYIP' ALLOW FILTERING: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename
```

This shouldn't happen, and it doesn't with PostgreSQL. I believe Liquibase is trying to query the DBCLL table in order to add some SQL statement to the file, but it doesn't consider the case that the table could not exist.

I'll let the team know about this so they can start working on a fix. In the meantime, let me know if there's anything I can do to help out.

**Comment by filipelautert** [comment]
Hello @tati-qalified - are you to reproduce it using Liquibase and Cassandra extension v 4.28.0 ? As we are using the new driver and fixed a lot of stuff in this extension I hope that this may be fixed.

**Comment by tati-qalified** [comment]
@filipelautert it doesn't seem to be fixed - there's an error when trying to create the DBCL table, so running `update-sql` fails entirely.
```
Unexpected error running Liquibase: No keyspace has been specified. 
USE a keyspace, or explicitly specify keyspace.tablename 
[Failed SQL: (0) CREATE TABLE IF NOT EXISTS DATABASECHANGELOG( ID TEXT, AUTHOR TEXT, FILENAME TEXT, DATEEXECUTED timestamp, ORDEREXECUTED INT, 
EXECTYPE TEXT, MD5SUM TEXT, DESCRIPTION TEXT, COMMENTS TEXT, TAG TEXT, LIQUIBASE TEXT, CONTEXTS TEXT, LABELS TEXT, DEPLOYMENT_ID TEXT,PRIMARY KEY (ID, AUTHOR, FILENAME))]
```

**Comment by filipelautert** [comment]
> @filipelautert it doesn't seem to be fixed - there's an error when trying to create the DBCL table, so running `update-sql` fails entirely.
> 
> ```
> Unexpected error running Liquibase: No keyspace has been specified. 
> USE a keyspace, or explicitly specify keyspace.tablename 
> [Failed SQL: (0) CREATE TABLE IF NOT EXISTS DATABASECHANGELOG( ID TEXT, AUTHOR TEXT, FILENAME TEXT, DATEEXECUTED timestamp, ORDEREXECUTED INT, 
> EXECTYPE TEXT, MD5SUM TEXT, DESCRIPTION TEXT, COMMENTS TEXT, TAG TEXT, LIQUIBASE TEXT, CONTEXTS TEXT, LABELS TEXT, DEPLOYMENT_ID TEXT,PRIMARY KEY (ID, AUTHOR, FILENAME))]
> ```

Hi @tati-qalified - are you using cassandra or aws?  If it's AWS in master branch there is a new property called liquibase.cassandra.awsKeyspacesCompatibilityModeEnabled in the liquibase.properties file. Defining it to true means we are running against an AWS Keyspaces instance and need to use some alternative implementations to bypass the unimplemented CQL features in Keyspaces.

**Comment by tati-qalified** [comment]
@filipelautert I've been able to test this, though I'm not sure if the results are the expected behaviour or not.

Steps taken:

1. Set up Cassandra through Docker
2. Connected through DBeaver and created a keyspace
3. Ran `liquibase status`
4. Ran `liquibase update-sql`

Both commands run successfully, the `databasechangeloglock` table is created, but the `databasechangelog` table is not. 
The generated code after step 4 includes the creation of the DBCL table:
```
-- Lock Database
UPDATE cycling.DATABASECHANGELOGLOCK SET LOCKED = TRUE, LOCKEDBY = 'GXCN4031 (192.168.0.111)', LOCKGRANTED = 1721927858310 WHERE ID = 1 IF LOCKED = FALSE;

-- Create Database Change Log Table
CREATE TABLE IF NOT EXISTS cycling.DATABASECHANGELOG( ID TEXT, AUTHOR TEXT, FILENAME TEXT, DATEEXECUTED timestamp, ORDEREXECUTED INT, EXECTYPE TEXT, MD5SUM TEXT, DESCRIPTION TEXT, COMMENTS TEXT, TAG TEXT, LIQUIBASE TEXT, CONTEXTS TEXT, LABELS TEXT, DEPLOYMENT_ID TEXT,PRIMARY KEY (ID, AUTHOR, FILENAME));

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: changelog.xml
-- Ran at: 25/07/2024, 14:17
-- Against: @jdbc:cassandra://localhost:9042/cycling
-- Liquibase version: 4.28.0
-- *********************************************************************

-- Changeset changelog.xml::1::Liquibase
CREATE TABLE cycling.test_table (test_id INT, test_column VARCHAR, PRIMARY KEY (test_id));

INSERT INTO cycling.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'Liquibase', 'changelog.xml', 1721927858813, 1, '9:c31cbcc82ef990951e46cc173776542c', 'createTable tableName=test_table', '', 'EXECUTED', NULL, NULL, '4.28.0', '1927858753');

-- Release Database Lock
UPDATE cycling.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL WHERE ID = 1;
```

Is this the expected behaviour?

**Comment by filipelautert** [comment]
> -- Create Database Change Log Table
> CREATE TABLE IF NOT EXISTS cycling.DATABASECHANGELOG( ID TEXT, AUTHOR TEXT, FILENAME TEXT, DATEEXECUTED timestamp, ORDEREXECUTED INT, EXECTYPE TEXT, MD5SUM TEXT, DESCRIPTION TEXT, COMMENTS TEXT, TAG TEXT, LIQUIBASE TEXT, CONTEXTS TEXT, LABELS TEXT, DEPLOYMENT_ID TEXT,PRIMARY KEY (ID, AUTHOR, FILENAME));

Hi @tati-qalified ! this seems right and should not fail this time. So it was fixed in the last releases and we can close this one?
