### ISSUE TITLE
NPE in JdbcExecutor.showSqlWarnings

### ISSUE THREAD

**Issue by ErrorProne** [liquibase/liquibase#5063]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi there,

I've hunted an NPE, which suddenly appeared in our CI pipeline after a quarkus upgrade, down to the liquibase 4.23.0 release. I think that this change (https://github.com/liquibase/liquibase/blame/v4.23.0/liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java#L85) introduces a possible NPE if stmt is null for some reason.

Stacktrace from 4.23.0:
```java
java.lang.NullPointerException: Cannot invoke "java.sql.Statement.getWarnings()" because "stmtToUse" is null
	at liquibase.executor.jvm.JdbcExecutor.showSqlWarnings(JdbcExecutor.java:104)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:85)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:220)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:228)
	at liquibase.executor.jvm.JdbcExecutor.queryForList(JdbcExecutor.java:293)
	at liquibase.executor.jvm.JdbcExecutor.queryForList(JdbcExecutor.java:288)
	at liquibase.diff.output.changelog.DiffToChangeLog.addDependencies(DiffToChangeLog.java:630)
	at liquibase.diff.output.changelog.DiffToChangeLog.sortObjects(DiffToChangeLog.java:416)
	at liquibase.diff.output.changelog.DiffToChangeLog.sortUnexpectedObjects(DiffToChangeLog.java:385)
	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:315)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:250)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:101)
```

It works perfectly if I pin the liquibase version to 4.22.0 and breaks starting at 4.23.0.

However, the issue may be rooted in something else and the NPE is just a symptom, but for one the CI pipeline works as expected with 4.22.0 and it does not look like the NPE is wanted anyway.

I believe a simple additional null check in the JdbcExecutor:104 (showSqlWarnings()) will do the trick

```java
        if (! SqlConfiguration.SHOW_SQL_WARNING_MESSAGES.getCurrentValue() || stmtToUse == null || stmtToUse.getWarnings() == null) {
            return;
        }
```

### Steps To Reproduce

Sadly I'm not able to give an exact reproducer, since I cannot re-create the issue locally so far. But it fails when creating a diff between two postgres 14.9 DBs in a completely dockerized gitlab CI env. 

### Expected/Desired Behavior

No NPE is thrown

### Liquibase Version

\>= 4.23.0

### Database Vendor & Version

PostgreSQL 14.9, PostgreSQL 16.0

### Liquibase Integration

quarkus

### OS and/or Infrastructure Type/Provider

Ubuntu, docker gradle:8.4.0-jdk17, macos 14.0

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by ErrorProne** [comment]
Edit: I've misread this one here before, and it may have the same root cause https://github.com/liquibase/liquibase/issues/5058
