### ISSUE TITLE
Regression in Liquibase 4.25.0 with H2 DB: Using preconditions "not" + "columnExists" fails with PreconditionErrorException when column not exists

### ISSUE THREAD

**Issue by dodomanika** [liquibase/liquibase#5246]
### Search first

- [X] I searched and no similar issues were found

### Description

After Liquibase upgrade from 4.24.0 to 4.25.0, when using it with H2 database, precondition "not" + "columnExists" that worked correctly, now fails with exception `liquibase.precondition.core.ColumnExistsPrecondition@68aec50 : Column "T.MODEL" not found; SQL statement: select t.model from PUBLIC.car t where 0=1` when column not exists.

Precondition that stoped working correctly:
```
<preConditions onFail="MARK_RAN">
      <not><columnExists tableName="car" columnName="model" /></not>
</preConditions>
```

In more details:
With Liquibase 4.25.0 and H2 database, when column not exists, `liquibase.precondition.core.ColumnExistsPrecondition#checkFast` throws `PreconditionErrorException` instead of `PreconditionFailedException`. That is why in `liquibase.precondition.core.NotPrecondition#check` it is not cached and properly handled.

Exception:
```
liquibase.precondition.core.ColumnExistsPrecondition@68aec50 : Column "T.MODEL" not found; SQL statement:
select t.model from PUBLIC.car t where 0=1 [42122-224]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:712) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:128) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:184) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:193) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:183) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:162) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:117) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:184) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:193) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:183) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:162) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:250) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.Scope.child(Scope.java:254) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:84) ~[liquibase-core-4.25.0.jar:na]
	... 44 common frames omitted
Caused by: liquibase.exception.PreconditionErrorException: Precondition Error
	at liquibase.precondition.core.ColumnExistsPrecondition.checkFast(ColumnExistsPrecondition.java:183) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.precondition.core.ColumnExistsPrecondition.check(ColumnExistsPrecondition.java:83) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.precondition.core.NotPrecondition.check(NotPrecondition.java:34) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:39) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:669) ~[liquibase-core-4.25.0.jar:na]
	... 59 common frames omitted
Caused by: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "T.MODEL" not found; SQL statement:
select t.model from PUBLIC.car t where 0=1 [42122-224]
	at liquibase.database.jvm.JdbcConnection.prepareStatement(JdbcConnection.java:445) ~[liquibase-core-4.25.0.jar:na]
	at liquibase.precondition.core.ColumnExistsPrecondition.checkFast(ColumnExistsPrecondition.java:167) ~[liquibase-core-4.25.0.jar:na]
	... 64 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "T.MODEL" not found; SQL statement:
select t.model from PUBLIC.car t where 0=1 [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.command.query.Select.prepareExpressions(Select.java:1170) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.command.query.Query.prepare(Query.java:218) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.command.Parser.prepareCommand(Parser.java:489) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:316) ~[h2-2.2.224.jar:2.2.224]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar:na]
	at liquibase.database.jvm.JdbcConnection.prepareStatement(JdbcConnection.java:443) ~[liquibase-core-4.25.0.jar:na]
	... 65 common frames omitted
```

### Steps To Reproduce

1. Create a Spring Boot project with below configuration

pom.xml contains
```
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-core</artifactId>
      <version>4.25.0</version>
    </dependency>
```

application.properties
```
spring.liquibase.change-log=classpath:db/changelog/master.xml
```

master.xml
```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">

  <changeSet author="XYZ" id="1">
    <createTable tableName="car">
      <column name="id" type="INTEGER">
        <constraints nullable="false" primaryKey="true" primaryKeyName="actor_pkey"/>
      </column>
      <column name="vendor" type="VARCHAR(255)"/>
    </createTable>
  </changeSet>

  <changeSet author="XYZ" id="2">
    <preConditions onFail="MARK_RAN">
      <not><columnExists tableName="car" columnName="model" /></not>
    </preConditions>
    <addColumn tableName="car">
      <column name="model"
        type="VARCHAR(255)"
        defaultValueBoolean="false">
      </column>
    </addColumn>
  </changeSet>

</databaseChangeLog>
```

2. Run `mvn clean package`
3. Migration fails with exception attached earlier

### Expected/Desired Behavior

Full precondition is checked and Liquibase migration succeeds.

### Liquibase Version

4.25.0

### Database Vendor & Version

H2 2.1.214

### Liquibase Integration

maven, spring boot

### Liquibase Extensions

N/A

### OS and/or Infrastructure Type/Provider

N/A

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@tati-qalified - could you test this with the CLI and let us know if it's happening there as well?

**Comment by MalloD12** [comment]
@tati-qalified, I think this one #5271 could also be related. If it does not require spending a significant extra time could you please validate that one as well? Maybe a single fix solves both.

Thanks,
Daniel.

**Comment by tati-qalified** [comment]
Hi @dodomanika, thank you for reporting this issue.
I have been able to replicate it, and here's what I found:

- It is **not** replicable with versions 4.24.0 or prior - only with version 4.25.0
- It is **not** replicable with the following databases:
   - PostgreSQL
   - MySQL
   - DB2
- I think it's safe to assume that it's H2-specific
- It is replicable with `not` + `columnExists`
- It is **not** replicable with `not` + `runningAs` - so, not all preconditions cause the error  
- It is **not** replicable with `not` + `tableExists` - so, similar queries don't necessarily reproduce the same error

I will be forwarding this to the development team so they can evaluate how to move forward.
Thank you,
Tatiana

**Comment by tati-qalified** [comment]
As @MalloD12 said, it's the same issue as #5271. In that ticket I've written a comment comparing the error logs for different databases, and a user is working on a PR to hopefully fix the bug.
@dodomanika we'll keep you updated on the status of the PR.

**Comment by MalloD12** [comment]
Thanks @tati-qalified for the detailed testing! Yes, @januson has submitted this [PR](https://github.com/liquibase/liquibase/pull/5282). We haven't reviewed it yet, but if you guys wish you can give it a try and see if that fix solves this issue. 

Thanks everyone,
Daniel.

**Comment by MalloD12** [comment]
Hi @dodomanika,

Could you please pull the changes provided [here](https://github.com/liquibase/liquibase/pull/5282) and try again? I tried with your changelog and didn't get the same issue you did.

Thanks,
Daniel.

**Comment by dodomanika** [comment]
Hi @MalloD12 I checked and no issue exists after that changes.

**Comment by MalloD12** [comment]
Awesome, thanks for testing and confirming it's good with that fix.

Thanks,
Daniel.
