### ISSUE TITLE
Hibernate attempts to validate the schema against JPA before liquibase runs

### ISSUE THREAD

**Issue by Jimmy12384** [liquibase/liquibase#5330]
### Search first

- [X] I searched and no similar issues were found

### Description

# The problem
In my system, I am currently utilizing liquibase to create new tables and conditionally load test data into h2 within a Java EE environment. Currently, I am using the jee-cdi liquibase extension to add support of servlet creation, and liquibase is able to successfully run through the entire changelog without errors. 

When implementing JPA entities to connect to the database, and validating with `hibernate.hbm2ddl.auto = 'validate'` within the `persistence.xml`, liquibase seems to inject itself after hibernate, causing JPA validation to consistently fail due to the tables not being created yet. As a result, the liquibase changelog does not run and the application fails to load.

## Hibernate Logs
```
11:46:26,978 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 72) MSC000001: Failed to start service jboss.persistenceunit." [redacted]#LiquibaseExamplePersistenceUnit": org.jboss.msc.service.StartException in service jboss.persistenceunit." [redacted]#LiquibaseExamplePersistenceUnit": javax.persistence.PersistenceException: [PersistenceUnit: LiquibaseExamplePersistenceUnit] Unable to build Hibernate SessionFactory
	at org.jboss.as.jpa@7.4.12.GA-redhat-00003//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:198)
	at org.jboss.as.jpa@7.4.12.GA-redhat-00003//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:128)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.wildfly.security.elytron-private@1.15.17.Final-redhat-00001//org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:664)
	at org.jboss.as.jpa@7.4.12.GA-redhat-00003//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:213)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit:  [redacted]] Unable to build Hibernate SessionFactory
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1327)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1253)
	at org.hibernate.jipijapa-hibernate5-3@7.4.12.GA-redhat-00003//org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:44)
	at org.jboss.as.jpa@7.4.12.GA-redhat-00003//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:170)
	... 10 more
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [DATA.TABLE_NAME]
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:191)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:310)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
	at org.hibernate@5.3.30.Final-redhat-00001//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1250)
	... 12 more
```

### Steps To Reproduce

# Files Used
In this section, all files required to reproduce the issue are attached. All private data is changed to be either generic or redacted.

### LiquibaseProvider.java
`java:jboss/datasources/ExampleDS` should work with a default `JBoss 7.4.x` installation for testing purposes
```java
/**
 * Register and start Liquibase to configure the database
 */
@Slf4j
@ApplicationScoped
public class LiquibaseProvider {

   private static final String LIQUIBASE_CHANGE_LOG_LOCATION = "liquibase/changelog.xml";

   @Resource(mappedName = "java:jboss/datasources/ExampleDS")
   private DataSource datasource;

   @Inject
   @Configure(key = "[redacted]", defaultValue = "true")
   private boolean enabled;

   @Produces
   @LiquibaseType
   public CDILiquibaseConfig getConfig() {
      final CDILiquibaseConfig config = new CDILiquibaseConfig();
      config.setChangeLog(LIQUIBASE_CHANGE_LOG_LOCATION);
      config.setShouldRun(enabled);
      config.setDefaultSchema("DATA");
      LOG.info("Initializing Liquibase with {}", config.getChangeLog());
      return config;
   }

   @Produces
   @LiquibaseType
   public DataSource getDataSource() throws SQLException {
      return datasource;
   }

   @Produces
   @LiquibaseType
   public ResourceAccessor getResourceAccessor() {
      final ResourceAccessor ra = new ClassLoaderResourceAccessor(getClass().getClassLoader());
      LOG.info("Initializing Liquibase with {}", ra);
      return ra;
   }
}
```

### persistence.xml
`java:jboss/datasources/ExampleDS` should work with a default `JBoss 7.4.x` installation for testing purposes
```xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence" 
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_1.xsd">
	<persistence-unit name="LiquibaseExamplePersistenceUnit" transaction-type="JTA">
		<jta-data-source>java:jboss/datasources/ExampleDS</jta-data-source>
		<exclude-unlisted-classes>false</exclude-unlisted-classes>
		<properties>
			<!-- Properties for Hibernate -->
			<property name="hibernate.hbm2ddl.auto" value="validate" />
			<property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect" />
			<property name="hibernate.default_schema" value="DATA" />
			<property name="hibernate.show_sql" value="true" />
			<property name="hibernate.generate_statistics" value="true" />
			<property name="hibernate.use_sql_comments" value="false" />
			<property name="hibernate.jdbc.fetch_size" value="200" />
			<property name="hibernate.jdbc.batch_size" value="200" />
			<property name="hibernate.jdbc.batch_versioned_data" value="true" />
			<property name="hibernate.order_inserts" value="true" />
			<property name="hibernate.order_updates" value="true" />
			<property name="hibernate.cache.use_second_level_cache" value="false" />
		</properties>
	</persistence-unit>
</persistence>
```

### pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>liquibase-issue</artifactId>
	<packaging>war</packaging>
	<name>Liquibase Issue Dependencies</name>
	<description>A list of required dependencies for recreating the described issue</description>
	<properties>
		<liquibase.version>4.25.0</liquibase.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
			<version>${liquibase.version}</version>
		</dependency>
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-cdi</artifactId>
			<version>${liquibase.version}</version>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
			<exclusions>
				<exclusion>
					<groupId>org.jboss.logging</groupId>
					<artifactId>jboss-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
</project>
```

# Steps to Reproduce
1. Create a basic Java EE project with dependencies listed in `pom.xml` and properties listed in `persistence.xml`
2. Create a default liquibase changelog with any arbitrary changes regarding table creation
3. Create a matching JPA entity to be validate by hibernate on servlet creation
4. Configure liquibase CDI using `LiquibaseProvider.java`
5. Start application by packaging and deploying WAR file to `JBoss EAP 7.4.X`

### Expected/Desired Behavior

I expect that the `liquibase-cdi` plugin injects before hibernate schema validation to allow validation after the database is updated to the latest version.

### Liquibase Version

4.25.0

### Database Vendor & Version

H2 1.4.197

### Liquibase Integration

maven

### Liquibase Extensions

liquibase-cdi

### OS and/or Infrastructure Type/Provider

Windows 10

### Additional Context

Java EE project is deployed to a `JBoss EAP 7.4.X` server 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @Jimmy12384 ! This seems to be something managed by cdi itself as Liquibase does not know about Hibernate. Maybe hibernate option `hibernate.delay_cdi_access` could help on that? Reference: https://docs.jboss.org/hibernate/orm/6.0/userguide/html_single/Hibernate_User_Guide.html#beans-cdi

Other than that maybe it can be accomplished by those specific jboss files as jboss-deployment-structure.xml ?

Otherwise I don't have any ideas on how to make Liquibase's `@ApplicationScoped `start before Hibernate.

**Comment by lbruun** [comment]
@Jimmy12384 In general, using Hibernate DDL features (or JPA DDL features) together with Liquibase is a bad idea. There are at least two  reasons:

- Hibernate DDL / JPA DDL is solving the same problem that Liquibase does. (Liquibase does it a lot better wrt supporting _future_ evolutions of your schema)
- With some CDI frameworks there will be ordering issues: you cannot (at least not out-of-the-box) guarantee which one fires first. 

What is that ` hibernate.hbm2ddl.auto = 'validate'` gives you that Liquibase cannot? Liquibase should be your guarantee that your database objects are in the exact state that you expect.

IMO, the only justifiable use of executing some SQL _prior_ to Liquibase firing would be to setup pre-requisites for Liquibase itself (like creating the db schema where Liquibase itself lives, etc).

**Comment by kpilandjr** [comment]
I completely agree that you don't want hibernate to generate DDL when you're using Liquibase for that, but that's not the point of setting that property to 'validate'.
When you set `hibernate.hbm2ddl.auto = 'validate'`, hibernate does not generate or execute DDL SQL. Instead, it validates you JPA entities, making sure that the tables and columns defined in those entities map properly to the underlying database schema. So if you have Liquibase generate a table named 'Address' but your JPA entity says the table name is 'Addresses' the validation phase throws an exception.

**Comment by filipelautert** [comment]
I see you points @kpilandjr / @Jimmy12384  .  In this case we can see Liquibase as an CDI component that needs to be started in a certain order. 
I'm not sure if we can "optionally" hardwire it to Hibernate (neither I've any idea on how to do it) . Seems we need help from some jee/cdi experts here to implement it.

**Comment by filipelautert** [comment]
As discussed in the thread, this is a CDI container startup ordering issue — Liquibase has no control over when the CDI container initializes its beans relative to Hibernate's schema validation. The suggested approach of using `hibernate.delay_cdi_access` or JBoss deployment structure configuration may help in some cases. Since this isn't something that can be addressed in Liquibase core, closing this. If someone finds a viable approach to control CDI bean initialization order, we'd welcome a PR.
