### ISSUE TITLE
Unhelpful Exception java.lang.UnsatisfiedLinkError: Microsoft SQL Server with Windows Integrated Security

### ISSUE THREAD

**Issue by Mas2112** [liquibase/liquibase#5441]
### Search first

- [X] I searched and no similar issues were found

### Description

When using Microsoft SQL Server with Windows Integrated Security and liquibase cannot find the mssql-jdbc_auth-12.4.2.x64.dll, the following exception occurs, which is quite unhelpful:

[2024-01-05 10:29:55] SEVERE [liquibase.integration] class java.lang.UnsatisfiedLinkError cannot be cast to class java.lang.Exception (java.lang.UnsatisfiedLinkError and java.lang.Exception are in module java.base of loader 'bootstrap')
liquibase.exception.CommandExecutionException: java.lang.ClassCastException: class java.lang.UnsatisfiedLinkError cannot be cast to class java.lang.Exception (java.lang.UnsatisfiedLinkError and java.lang.Exception are in module java.base of loader 'bootstrap')
        at liquibase.command.CommandScope.execute(CommandScope.java:253)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:391)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:171)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:366)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:171)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:363)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:103)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: java.lang.ClassCastException: class java.lang.UnsatisfiedLinkError cannot be cast to class java.lang.Exception (java.lang.UnsatisfiedLinkError and java.lang.Exception are in module java.base of loader 'bootstrap')
        at liquibase.command.CommandScope.logPrimaryExceptionToMdc(CommandScope.java:287)
        at liquibase.command.CommandScope.execute(CommandScope.java:245)
        ... 21 more

- 

### Steps To Reproduce

* Download liquibase and don't setup the mssql-jdbc_auth-12.4.2.x64.dll file
* Run the following command:
C:\bin\liquibase-4.25.1\liquibase status ^
    --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver ^
    --url="jdbc:sqlserver://localhost:52457;integratedSecurity=true;trustServerCertificate=true" ^
    --changelog-file=test-changelog.xml ^
    --log-level FINE

### Expected/Desired Behavior

A more descriptive message.

From liquibase 4.24.0:

[2024-01-05 10:33:18] SEVERE [liquibase.integration] Connection could not be created to jdbc:sqlserver://localhost:52457;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:30a3b127-3a87-4878-bb88-b6bc86d963a6
  - Caused by: Unable to load authentication DLL mssql-jdbc_auth-12.4.2.x64
liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:sqlserver://localhost:52457;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:30a3b127-3a87-4878-bb88-b6bc86d963a6
        at liquibase.command.CommandScope.execute(CommandScope.java:237)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:383)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:96)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:133)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:sqlserver://localhost:52457;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:30a3b127-3a87-4878-bb88-b6bc86d963a6
        at liquibase.command.core.helpers.AbstractDatabaseConnectionCommandStep.createDatabaseObject(AbstractDatabaseConnectionCommandStep.java:105)
        at liquibase.command.core.helpers.DbUrlConnectionCommandStep.obtainDatabase(DbUrlConnectionCommandStep.java:95)
        at liquibase.command.core.helpers.DbUrlConnectionCommandStep.run(DbUrlConnectionCommandStep.java:72)
        at liquibase.command.CommandScope.execute(CommandScope.java:214)
        ... 21 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:sqlserver://localhost:52457;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:30a3b127-3a87-4878-bb88-b6bc86d963a6
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:221)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:179)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:144)
        at liquibase.command.core.helpers.AbstractDatabaseConnectionCommandStep.createDatabaseObject(AbstractDatabaseConnectionCommandStep.java:73)
        ... 24 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:sqlserver://localhost:52457;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:30a3b127-3a87-4878-bb88-b6bc86d963a6
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:35)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:218)
        ... 27 more
Caused by: liquibase.exception.DatabaseException: Connection could not be created to jdbc:sqlserver://localhost:52457;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:30a3b127-3a87-4878-bb88-b6bc86d963a6
        at liquibase.database.jvm.JdbcConnection.open(JdbcConnection.java:50)
        at com.datical.liquibase.ext.database.jvm.ProJdbcConnection.open(Unknown Source)
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
        ... 28 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:30a3b127-3a87-4878-bb88-b6bc86d963a6
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:4026)
        at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<init>(AuthenticationJNI.java:74)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5098)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5087)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7675)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4137)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3583)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3172)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3014)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1836)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1246)
        at liquibase.database.jvm.JdbcConnection.open(JdbcConnection.java:42)
        ... 30 more
Caused by: java.lang.UnsatisfiedLinkError: Unable to load authentication DLL mssql-jdbc_auth-12.4.2.x64
        at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<clinit>(AuthenticationJNI.java:63)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5097)
        ... 39 more

### Liquibase Version

4.25.1

### Database Vendor & Version

Microsoft SQL Server 2022

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @Mas2112, thank you for reporting this issue.

Reviewing the stacktrace you've provided and the relevant changes between v4.24.0 and 4.25.1, the main difference I see is the addition of the `logPrimaryExceptionToMdc` function in `CommandScope.java`. This is one more step that sends errors and exceptions through the pipeline, and it seems like somewhere in the middle there's an error that's trying to be cast as an exception.

We'll continue to look into it.

Thank you,
Tatiana

**Comment by TedKeenan** [comment]
@Mas2112 The issue is most likely that you don't have the microsoft dll that enables secure JDBC access. My recommendation is to download the zip of the JDBC files for the driver you are using from https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16, and then find the appropriate mssql-jdbc_auth-version.dll and put it in the java /lib folder of your java instance. For example if you download the sqljdbc_8.2.2.0_enu.zip zip file on a x64 machine, the dll is in the sqljdbc_8.2\enu\auth\x64 of the zip.

**Comment by Mas2112** [comment]
Hi @TedKeenan, yes, this was the issue and I was able to resolve it.

However, the error that is thrown in v4.25.1 gave me no indication of what the problem was. Whereas in v4.24, the root cause of the error was clear.

**Comment by filipelautert** [comment]
Hi @Mas2112 ! thanks for the issue. Are you to confirm if it still an issue on 4.28.0 ? I see that we changed some stuff in this class Around April, including exception handling.

**Comment by Mas2112** [comment]
With 4.28.0, the error message problem is now fixed. The error message says exactly what is wrong.

[2024-07-18 10:16:50] SEVERE [liquibase.integration] Connection could not be created to jdbc:sqlserver://localhost:20001;databaseName=MYDB;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:421af087-1ab2-4c25-913a-613e4c10b2e4
  - Caused by: Unable to load authentication DLL mssql-jdbc_auth-12.6.1.x64
liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:sqlserver://localhost:20001;databaseName=MYDB;integratedSecurity=true;trustServerCertificate=true with driver com.microsoft.sqlserver.jdbc.SQLServerDriver.  This driver is not configured for integrated authentication. ClientConnectionId:421af087-1ab2-4c25-913a-613e4c10b2e4
        at liquibase.command.CommandScope.execute(CommandScope.java:257)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:387)
        at liquibase.Scope.child(Scope.java:200)
        at liquibase.Scope.child(Scope.java:176)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:362)
        at liquibase.Scope.child(Scope.java:200)
        at liquibase.Scope.child(Scope.java:176)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:359)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:96)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)

**Comment by filipelautert** [comment]
@Mas2112 thanks for the feedback! So I'll close this ticket , anything else please reopen it.
