### ISSUE TITLE
“MultiTenantSpringLiquibase ” How to use system file directory, non -classpath directory

### ISSUE THREAD

**Issue by thousmile** [liquibase/liquibase#5460]
### Search first

- [X] I searched and no similar issues were found

### Description

includeAll path contains system file directories. How to fill it out?

I tried many times!

```java

    @Test
    public void test10() throws Exception {
        /*
         * spring-boot version : 3.2.1
         * liquibase-core version : 42.6.0
         */
        var ds1 = new MysqlDataSource();
        ds1.setURL("jdbc:mysql://192.168.0.188:3306/hello1");
        ds1.setUser("test123");
        ds1.setPassword("mht123456");
        var liquibase1 = new MultiTenantSpringLiquibase();
        liquibase1.setDataSource(ds1);
        liquibase1.setResourceLoader(new FileSystemResourceLoader());
        var changelogMaster = Paths.get("changelog/changelog-master-mysql.xml");
        liquibase1.setChangeLog(changelogMaster.toAbsolutePath().toString());
        liquibase1.setSchemas(List.of("hello1", "hello2"));
        liquibase1.afterPropertiesSet();
    }

```

```xml

<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

    <includeAll maxDepth="6" minDepth="0" path="C:\\Users\\demo\\code\\javaProjects\\dbsm\\changelog\\mysql"/>

</databaseChangeLog>


```

    
![image](https://github.com/liquibase/liquibase/assets/28520524/01ab15a5-3fa2-49e1-88d6-97fd9ca51ce2)

In the wrong log, the file address has been found!

file:/C:/Users/demo/code/javaProjects/dbsm/changelog/mysql/2024/1/10/1704965288986.xml

```log

liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: liquibase.exception.UnexpectedLiquibaseException: Could determine path for file:/C:/Users/demo/code/javaProjects/dbsm/changelog/mysql/2024/1/10/1704965288986.xml

	at liquibase.command.CommandScope.execute(CommandScope.java:237)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:222)
	at liquibase.Scope.lambda$child$0(Scope.java:184)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:183)
	at liquibase.Scope.child(Scope.java:162)
	at liquibase.Liquibase.runInScope(Liquibase.java:1371)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:193)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:331)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:286)
	at liquibase.integration.spring.MultiTenantSpringLiquibase.runOnAllSchemas(MultiTenantSpringLiquibase.java:154)
	at liquibase.integration.spring.MultiTenantSpringLiquibase.afterPropertiesSet(MultiTenantSpringLiquibase.java:95)
	at com.xaaef.dbsm.NoSpringTests.test10(NoSpringTests.java:99)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: liquibase.exception.ChangeLogParseException: liquibase.exception.UnexpectedLiquibaseException: Could determine path for file:/C:/Users/demo/code/javaProjects/dbsm/changelog/mysql/2024/1/10/1704965288986.xml
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.lambda$getDatabaseChangeLog$0(DatabaseChangelogCommandStep.java:129)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:128)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:87)
	at liquibase.command.CommandScope.execute(CommandScope.java:214)
	... 16 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: Could determine path for file:/C:/Users/demo/code/javaProjects/dbsm/changelog/mysql/2024/1/10/1704965288986.xml
	at liquibase.integration.spring.SpringResourceAccessor.getResourcePath(SpringResourceAccessor.java:97)
	at liquibase.integration.spring.SpringResourceAccessor.search(SpringResourceAccessor.java:65)
	at liquibase.resource.ResourceAccessor.search(ResourceAccessor.java:148)
	at liquibase.changelog.DatabaseChangeLog.findResources(DatabaseChangeLog.java:803)
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:732)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:505)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:385)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
	... 22 more


```

### Steps To Reproduce

Description

### Expected/Desired Behavior

Description

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @thousmile, I think you might find the `relativeToChangeLogFile` attribute useful. It allows you to use the filepath starting from the location of your changelog file, instead of starting from C:/.

In the example you've provided, it would look something like this:
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

    <includeAll maxDepth="6" minDepth="0" path="./mysql" relativeToChangeLogFile="true"/>

</databaseChangeLog>
```

You can find more information here: https://docs.liquibase.com/change-types/includeall.html

Let me know if you need any more help.

Thanks,
Tatiana
