### ISSUE TITLE
Lexical error in 4.25.1 for string containing backslash and a unicode character

### ISSUE THREAD

**Issue by instagibb** [liquibase/liquibase#5474]
### Search first

- [X] I searched and no similar issues were found

### Description

I have a change set with an insert statement that contains a string with a backslash `\` and the unicode character `≤` (\u2264)

This works fine in `4.25.0` but in `4.25.1` I get the following error:
```
Caused by: liquibase.util.grammar.TokenMgrError: Lexical error at line 190, column 9.  Encountered: '\u2264' (8804),
	at liquibase.util.grammar.SimpleSqlGrammarTokenManager.getNextToken(SimpleSqlGrammarTokenManager.java:1410)
SimpleSqlGrammarTokenManager.java:1410
	at liquibase.util.grammar.SimpleSqlGrammar.getNextToken(SimpleSqlGrammar.java:113)
SimpleSqlGrammar.java:113
	at liquibase.util.StandardSqlParser.parse(StandardSqlParser.java:42)
StandardSqlParser.java:42
	at liquibase.util.StringUtil.processMultiLineSQL(StringUtil.java:68)
StringUtil.java:68
	at liquibase.change.AbstractSQLChange.generateStatements(AbstractSQLChange.java:295)
```

I can trigger this with a number of unicode characters but the one specifically from my changeset is `≤`

I assume it is related to #5108 which mentions `\` but it is not clear how to proceed

### Steps To Reproduce

A simple changeset like the following is enough

```sql
INSERT INTO MY_TABLE (NAME, VALUE) VALUES ('test', 'This has a \ (slash) and some unicode  symbol ≤ (u2264)');
```

### Expected/Desired Behavior

The Lexical error should not occur

### Liquibase Version

4.25.1

### Database Vendor & Version

PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1)

### Liquibase Integration

Spring Boot

### OS and/or Infrastructure Type/Provider

MacOS

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by wmcshane** [comment]
Not sure if this is useful, however, I found that it would always produce the error if a unicode character with a higher hex value than UTF-16 (hex) 07EA was used. Note, if the string with the high hex value unicode didn't contain a backslash then the error wouldn't occur.

**Comment by tati-qalified** [comment]
Hi @instagibb, thank you for reporting this issue. I was able to reproduce it, as well as what @wmcshane and @mk-github-77 reported.
If there is no backslash present, the statement will be run as expected. If there *is* a backslash, it will fail, even if it's in a different string or a different statement altogether.

I also agree that it was probably caused by #5108 

@filipelautert do you think they're related? If not, what could have caused this bug?

**Comment by instagibb** [comment]
Hi @tati-qalified, thanks for confirming and yes I forgot to mention removing the backslash makes everything work. What you have confirmed about _any_ backslash being present was also my experience.

**Comment by filipelautert** [comment]
Hello  @tati-qalified - yes, both are related and surely were caused by #5108 - I don't know how yet. It would be nice to fix it before the next release.

**Comment by tati-qalified** [comment]
Further info: this bug only occurs if the backslash is **before** the unicode character. Using the string `~\` does not produce any errors.

**Comment by filipelautert** [comment]
Hello! Are you able to give PR https://github.com/liquibase/liquibase/pull/5506 a try and see if it fixes your problems? 

Liquibase ZIP file is available at https://github.com/liquibase/liquibase/actions/runs/7815163784/artifacts/1226985137 .

Or you can use the package as a maven dependency, using 

<dependency>
  <groupId>org.liquibase</groupId>
  <artifactId>liquibase-core</artifactId>
  <version>51888f3d62e63b10abe952042e4d1af3ddfb9f80-SNAPSHOT</version>
</dependency>

To use it you'll need to set up a github and a token as specified in https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry .

**Comment by instagibb** [comment]
Hi @filipelautert I have tested the fix using the maven snapshot but found I had to use a different `version` than the one above? I got the following `version` from the zip `parse-utf8-math-symbols-SNAPSHOT`

This fix seems to have resolved the issue for me.
