### ISSUE TITLE
Drop overloaded function fails

### ISSUE THREAD

**Issue by ShadowNinjaHunter** [liquibase/liquibase#5586]
### Search first

- [X] I searched and no similar issues were found

### Description

Running the dropAll command fails on overloaded functions with postgres

### Steps To Reproduce

changeset includes:

```
    <changeSet author="klaus (generated)" id="1706465573317-1715">
        <pro:createFunction functionName="add_months" path="../objects/function/add_months-da2540c8.sql" relativeToChangelogFile="true"/>
    </changeSet>
    <changeSet author="klaus (generated)" id="1706465573317-1716">
        <pro:createFunction functionName="add_months" path="../objects/function/add_months-c4a94c43.sql" relativeToChangelogFile="true"/>
    </changeSet>
```

add_months-c4a94c43.sql:
```
CREATE OR REPLACE FUNCTION dev.add_months(timestamp with time zone, integer)
 RETURNS timestamp with time zone
 LANGUAGE sql
 IMMUTABLE STRICT
AS $function$select
$1 + interval '1' month * $2;$function$
```

add_months-da2540c8.sql:
```
CREATE OR REPLACE FUNCTION dev.add_months(date_in date, nb_months integer)
 RETURNS date
 LANGUAGE plpgsql
 IMMUTABLE STRICT
AS $function$ 	DECLARE r DATE; 	BEGIN 		SELECT DATE_IN + CAST(CAST(NB_MONTHS AS TEXT)|| ' month' AS INTERVAL) INTO STRICT r; 		RETURN r; 	END; 	$function$
```

`./gradlew dropAll`

Stack trace:
```
[2024-02-09 11:53:17] SEVERE [liquibase.command] Error occurred during dropAll: ERROR: function name "dev.add_months" is not unique
  Hint: Specify the argument list to select the function unambiguously. [Failed SQL: (0) DROP FUNCTION "dev"."add_months"]
It is possible that not all objects were dropped.

liquibase.exception.DatabaseException: ERROR: function name "dev.add_months" is not unique
  Hint: Specify the argument list to select the function unambiguously. [Failed SQL: (0) DROP FUNCTION "dev"."add_months"]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:147)
        at liquibase.database.AbstractJdbcDatabase.dropDatabaseObjects(AbstractJdbcDatabase.java:845)
        at liquibase.command.core.DropAllCommandStep.run(DropAllCommandStep.java:65)
        at liquibase.command.CommandScope.execute(CommandScope.java:217)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:390)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:171)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:365)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:171)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:362)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:102)
Caused by: org.postgresql.util.PSQLException: ERROR: function name "dev.add_months" is not unique
  Hint: Specify the argument list to select the function unambiguously.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
        ... 23 more
```

### Expected/Desired Behavior

I expected that both functions are dropped.

### Liquibase Version

4.26.0

### Database Vendor & Version

PostgresSQL 14

### Liquibase Integration

Gradle 8.5

### OS and/or Infrastructure Type/Provider

Ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @ShadowNinjaHunter, thank you for reporting this issue.
I have been able to replicate it with Liquibase v4.26.0, and with both PostgreSQL and SQL Server. However, SQL Server doesn't output any errors, so it looks like everything was successful, but the function isn't dropped.

This is replicable with the CLI, so it's not a liquibase-gradle problem.

I'll be leaving this ticket open for the Community to fix. Our development team will be available to provide guidance if necessary.

Thank you,
Tatiana

**Comment by filipelautert** [comment]
Hi - this should be fixed in liquibase 4.33.0 .
