### ISSUE TITLE
[4.26.0] Provider liquibase.change.core.LoadDataChange could not be instantiated 

### ISSUE THREAD

**Issue by AizeLeOuf** [liquibase/liquibase#5604]
### Search first

- [X] I searched and no similar issues were found

### Description

Hello !

I'm in a WSL instance with a 1.8.0 JVM. 

Liquibase perfectly works with 4.25.1 release but with the last one I have two issues: a stack trace and a duplicate jar detected but just one present in the lib folder. Any idea ?

`flo@ITEM-5CG3144L3X:/mnt/z/project$ uname -a
Linux ITEM-5CG3144L3X 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
flo@ITEM-5CG3144L3X:/mnt/z/project$ java -version
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (build 1.8.0_392-8u392-ga-1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.392-b08, mixed mode)
flo@ITEM-5CG3144L3X:/mnt/z/project$ export LIQUIBASE_HOME=$(pwd)
flo@ITEM-5CG3144L3X:/mnt/z/project$ java -jar lib/liquibase-core-4.26.0.jar info
WARNING: *** Duplicate Liquibase Core JAR files ***
/mnt/z/project/internal/lib/liquibase-core.jar
/mnt/z/project/lib/liquibase-core-4.26.0.jar
Feb 19, 2024 11:22:26 AM liquibase.servicelocator
INFO: Cannot load service
java.util.ServiceConfigurationError: liquibase.change.Change: Provider liquibase.change.core.LoadDataChange could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:24)
        at liquibase.plugin.AbstractPluginFactory.findAllInstances(AbstractPluginFactory.java:100)
        at liquibase.change.ChangeFactory.getDefinedChanges(ChangeFactory.java:91)
        at liquibase.command.core.helpers.AbstractChangelogCommandStep.supportedReplaceIfExistsTypes(AbstractChangelogCommandStep.java:59)
        at liquibase.command.core.helpers.AbstractChangelogCommandStep.<clinit>(AbstractChangelogCommandStep.java:28)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:24)
        at liquibase.command.CommandFactory.findAllInstances(CommandFactory.java:243)
        at liquibase.command.CommandFactory.getCommands(CommandFactory.java:162)
        at liquibase.integration.commandline.LiquibaseCommandLine.getCommands(LiquibaseCommandLine.java:1110)
        at liquibase.integration.commandline.LiquibaseCommandLine.buildPicoCommandLine(LiquibaseCommandLine.java:216)
        at liquibase.integration.commandline.LiquibaseCommandLine.<init>(LiquibaseCommandLine.java:192)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: java.lang.NoClassDefFoundError: com/opencsv/exceptions/CsvMalformedLineException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 27 more
Caused by: java.lang.ClassNotFoundException: com.opencsv.exceptions.CsvMalformedLineException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 32 more

Feb 19, 2024 11:22:26 AM liquibase.servicelocator
INFO: Cannot load service
java.util.ServiceConfigurationError: liquibase.change.Change: Provider liquibase.change.core.LoadUpdateDataChange could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:24)
        at liquibase.plugin.AbstractPluginFactory.findAllInstances(AbstractPluginFactory.java:100)
        at liquibase.change.ChangeFactory.getDefinedChanges(ChangeFactory.java:91)
        at liquibase.command.core.helpers.AbstractChangelogCommandStep.supportedReplaceIfExistsTypes(AbstractChangelogCommandStep.java:59)
        at liquibase.command.core.helpers.AbstractChangelogCommandStep.<clinit>(AbstractChangelogCommandStep.java:28)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:24)
        at liquibase.command.CommandFactory.findAllInstances(CommandFactory.java:243)
        at liquibase.command.CommandFactory.getCommands(CommandFactory.java:162)
        at liquibase.integration.commandline.LiquibaseCommandLine.getCommands(LiquibaseCommandLine.java:1110)
        at liquibase.integration.commandline.LiquibaseCommandLine.buildPicoCommandLine(LiquibaseCommandLine.java:216)
        at liquibase.integration.commandline.LiquibaseCommandLine.<init>(LiquibaseCommandLine.java:192)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: java.lang.NoClassDefFoundError: com/opencsv/exceptions/CsvMalformedLineException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 27 more
Caused by: java.lang.ClassNotFoundException: com.opencsv.exceptions.CsvMalformedLineException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 32 more
`

### Steps To Reproduce

Run the jar.

### Expected/Desired Behavior

No stack strace

### Liquibase Version

4.26.0

### Database Vendor & Version

Oracle

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

VM

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hi @AizeLeOuf - seems that file liquibase-core-4.26.0.jar was downloaded and added to the lib folder, thus it is conflicting with the one in internal/lib and causing those other error.
To upgrade to liquibase 4.26.0 you need to download zip file from [here](https://github.com/liquibase/liquibase/releases/download/v4.26.0/liquibase-4.26.0.zip) and replace your entire liquibase directory with that.
