### ISSUE TITLE
Getting Databricks error using an Oracle jdbc URL

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase#5721]
### Search first

- [X] I searched and no similar issues were found

### Description

Using xml changelog:

` <changeSet id="create_sequence" author="doaksec">  
  <preConditions onFail="MARK_RAN">  
    <not>  
      <sequenceExists sequenceName="text_archive_seq" />  
    </not>  
  </preConditions>  
  <sql>  
    CREATE SEQUENCE text_archive_seq start with 1  
      increment by 1  
      minvalue 1  
      maxvalue 999999999999999999;  
  </sql>  
</changeSet> `
(note: it does work if the createSequence change-type is used)

Getting the following error:

Liquibase Version: 4.26.0
[2024-03-21 19:56:59] INFO [liquibase.ui] Liquibase Version: 4.26.0
Liquibase Open Source 4.26.0 by Liquibase
[2024-03-21 19:56:59] INFO [liquibase.ui] Liquibase Open Source 4.26.0 by Liquibase
[2024-03-21 19:56:59] INFO [liquibase.integration] Starting command execution.
[2024-03-21 19:57:00] INFO [liquibase.changelog] Reading from DMARCHIVE.DATABASECHANGELOG
[2024-03-21 19:57:01] INFO [liquibase.lockservice] Successfully acquired change log lock
[2024-03-21 19:57:01] INFO [liquibase.command] Using deploymentId: 1051021154
[2024-03-21 19:57:01] INFO [liquibase.changelog] Reading from DMARCHIVE.DATABASECHANGELOG
Running Changeset: src/main/resources/db/changelog/db-change-14.xml::36::beckem7
[2024-03-21 19:57:01] INFO [liquibase.ui] Running Changeset: src/main/resources/db/changelog/db-change-14.xml::36::beckem7
[2024-03-21 19:57:01] INFO [liquibase.ext] Sequences are not supported by Databricks
[2024-03-21 19:57:01] INFO [liquibase.snapshot] Creating snapshot

UPDATE SUMMARY
Run:                          4
Previously run:              40
Filtered out:                 0
-------------------------------
Total change sets:           44

[2024-03-21 19:57:01] INFO [liquibase.util] UPDATE SUMMARY
[2024-03-21 19:57:01] INFO [liquibase.util] Run:                          4
[2024-03-21 19:57:01] INFO [liquibase.util] Previously run:              40
[2024-03-21 19:57:01] INFO [liquibase.util] Filtered out:                 0
[2024-03-21 19:57:01] INFO [liquibase.util] -------------------------------
[2024-03-21 19:57:01] INFO [liquibase.util] Total change sets:           44
[2024-03-21 19:57:01] INFO [liquibase.util] Update summary generated
[2024-03-21 19:57:01] INFO [liquibase.lockservice] Successfully released change log lock
[2024-03-21 19:57:01] INFO [liquibase.command] Command execution complete
[2024-03-21 19:57:01] SEVERE [liquibase.integration] java.lang.StackOverflowError
java.lang.StackOverflowError
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:42)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)

### Steps To Reproduce

JAVA_OPTS="-Xmx1024m" /opt/liquibase/liquibase --changeLogFile=src/main/resources/db/changelog/db-changelog-master.xml --sql-log-level=INFO --showBanner=false --log-level=INFO --defaultsFile=/tmp/tmpliw8rs_j --classpath=/tmp/tmpu6su81ug update

defaultsFile contains:
username: XXXX
password: XXXX
url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=XXXXX)(PORT=XXXX)))(CONNECT_DATA=(UR=A)(SERVICE_NAME=XXXXXX)))

### Expected/Desired Behavior

Executes using Oracle code path in Liquibase, not Databricks extension.

### Liquibase Version

4.26

### Database Vendor & Version

Oracle 19c

### Liquibase Integration

CLI

### Liquibase Extensions

liquibase-oracle 4.26, liquibase-teradata 4.26, liquibase-databricks 1.1.2

### OS and/or Infrastructure Type/Provider

debian linux 11

### Additional Context

This worked fine with Liquibase 4.25.  

This is a major roadblock for us.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by doakd** [comment]
ok, after further testing various combinnations I found problems have existed since the Databricks 1.0.1 extension was release, but got much worse with extension 1.1.2.

liquibase 4.26 (and 4.25.0) and databricks 1.1.2 - Hard Fail

Liquibase 4.26  (and 4.25.0) and databricks 1.0.1 - Works but with large delay and Databricks ext messages "INFO [liquibase.ext] Sequences are not supported by Databricks"

**Comment by tati-qalified** [comment]
Hi  @doakd, thank you for reporting this issue.

I've tested this using Liquibase version 4.26.0, liquibase-databricks versions 1.1.2 and 1.1.3, using the changeset you've provided. In my case, the changeset runs with no issues and the sequence is created. 
Using `log-level=INFO` I can see that the Databricks extension is being loaded, which is probably why it's logging `Sequences are not supported by Databricks`.

On the performance side of things it's clearly something we should look into, but it isn't blocking the use of Liquibase on my part. 

Can you confirm that it's _that_ changeset that's causing the error? If you find a different one, I might be able to replicate the error and better understand what's going on.

Thank you,
Tatiana

**Comment by doakd** [comment]
Running Liquibase 4.26 with Databricks 1.1.2.

`<changeSet id="create_sequence1" author="BOB">
  <preConditions onFail="MARK_RAN">
    <not>
      <sequenceExists sequenceName="test_seq1" />
    </not>
  </preConditions>
  <sql>
    CREATE SEQUENCE test_seq1 start with 1
      increment by 1
      minvalue 1
      maxvalue 999999999999999999;
  </sql>
</changeSet>`

Getting this (error lines repeat 100s of times):

Running Changeset: db-changelog-1.xml::create_sequence1::BOB
[2024-03-28 14:18:23] INFO [liquibase.ui] Running Changeset: db-changelog-1.xml::create_sequence1::BOB
[2024-03-28 14:18:23] INFO [liquibase.ext] Sequences are not supported by Databricks
[2024-03-28 14:18:23] INFO [liquibase.snapshot] Creating snapshot

UPDATE SUMMARY
Run:                         28
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:           28

[2024-03-28 14:18:23] INFO [liquibase.util] UPDATE SUMMARY
[2024-03-28 14:18:23] INFO [liquibase.util] Run:                         28
[2024-03-28 14:18:23] INFO [liquibase.util] Previously run:               0
[2024-03-28 14:18:23] INFO [liquibase.util] Filtered out:                 0
[2024-03-28 14:18:23] INFO [liquibase.util] -------------------------------
[2024-03-28 14:18:23] INFO [liquibase.util] Total change sets:           28
[2024-03-28 14:18:23] INFO [liquibase.util] Update summary generated
[2024-03-28 14:18:23] INFO [liquibase.lockservice] Successfully released change log lock
[2024-03-28 14:18:23] INFO [liquibase.command] Command execution complete
[2024-03-28 14:18:23] SEVERE [liquibase.integration] java.lang.StackOverflowError
java.lang.StackOverflowError
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:42)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:59)

**Comment by doakd** [comment]
ok, I discovered something new.  It looks like it's the precondition that is causing the error.  Both custom sql and the change-type fail when there is a precondition, and both work fine when the precondition is removed.

**Comment by tati-qalified** [comment]
@doakd thank you for providing more info. I still can't replicate what you're reporting, but it's known that Liquibase extensions can sometimes get in the way of executions.

`liquibase-databricks` version 1.1.3 has [PR #102](https://github.com/liquibase/liquibase-databricks/pull/102) that aims to fix that problem.

Please try running your project with 1.1.3 and let me know if it works for you or not.

Thank you,
Tatiana

**Comment by doakd** [comment]
@tati-qalified 

Current configuration:
liquibase 4.27
liquibase-databricks 1.1.3

Running against an Oracle 19c database, the preconditions are now working, no longer getting the "Sequences are not supported by Databricks" error.  

But now I'm getting the following databricks extension error even though the oracle changesets are deployed successfully:

```
[2024-04-01 17:35:37] WARNING [liquibase.resource] Cannot handle classloader url file:/opt/liquibase/lib/liquibase-databricks-1.1.3.jar: zip END header not found. Operations that need to list files from this location may not work as expected
java.lang.IllegalArgumentException: zip END header not found
	at liquibase.resource.ZipResourceAccessor.<init>(ZipResourceAccessor.java:65)
	at liquibase.resource.ZipResourceAccessor.<init>(ZipResourceAccessor.java:24)
	at liquibase.resource.ZipPathHandler.getResourceAccessor(ZipPathHandler.java:55)
	at liquibase.resource.PathHandlerFactory.getResourceAccessor(PathHandlerFactory.java:37)
	at liquibase.resource.ClassLoaderResourceAccessor.configureAdditionalResourceAccessors(ClassLoaderResourceAccessor.java:72)
	at liquibase.resource.ClassLoaderResourceAccessor.configureAdditionalResourceAccessors(ClassLoaderResourceAccessor.java:86)
	at liquibase.resource.ClassLoaderResourceAccessor.init(ClassLoaderResourceAccessor.java:55)
	at liquibase.resource.ClassLoaderResourceAccessor.describeLocations(ClassLoaderResourceAccessor.java:34)
	at liquibase.resource.CompositeResourceAccessor.describeLocations(CompositeResourceAccessor.java:82)
	at liquibase.resource.SearchPathResourceAccessor.<init>(SearchPathResourceAccessor.java:50)
	at liquibase.resource.SearchPathResourceAccessor.<init>(SearchPathResourceAccessor.java:21)
	at liquibase.integration.commandline.LiquibaseCommandLine.configureResourceAccessor(LiquibaseCommandLine.java:837)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$configureScope$4(LiquibaseCommandLine.java:693)
	at liquibase.Scope.lambda$child$0(Scope.java:190)
	at liquibase.Scope.child(Scope.java:199)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:168)
	at liquibase.integration.commandline.LiquibaseCommandLine.configureScope(LiquibaseCommandLine.java:693)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:370)
	at liquibase.Scope.child(Scope.java:199)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:367)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1534)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at liquibase.resource.ZipResourceAccessor.<init>(ZipResourceAccessor.java:50)
	... 27 more

```

**Comment by filipelautert** [comment]
Hello @doakd ! Does the release tag fix works to fix this issue too?

**Comment by doakd** [comment]
I have tested this error with Databricks extension 1.1.3, and the "sequenceExists" precondition is still a problem.

Changeset:
`
<changeSet id="create_sequence1" author="doaksec">
  <preConditions onFail="MARK_RAN">
    <not>
      <sequenceExists sequenceName="test_seq1" />
    </not>
  </preConditions>
  <sql>
    CREATE SEQUENCE test_seq1 start with 1
      increment by 1
      minvalue 1
      maxvalue 999999999999999999;
  </sql>
</changeSet>
`

Deployment to Oracle:
`
[2024-05-03 13:10:26] INFO [liquibase.ui] Running Changeset: db-changelog-1.xml::create_sequence1::doaksec
[2024-05-03 13:10:26] INFO [liquibase.ext] Sequences are not supported by Databricks
[2024-05-03 13:10:26] INFO [liquibase.snapshot] Creating snapshot
[2024-05-03 13:10:31] INFO [liquibase.lockservice] Successfully released change log lock
[2024-05-03 13:10:31] INFO [liquibase.command] Command execution complete
[2024-05-03 13:10:31] SEVERE [liquibase.integration] java.lang.StackOverflowError
java.lang.StackOverflowError
	at liquibase.ext.databricks.snapshot.jvm.SequenceSnapshotGeneratorDatabricks.getSelectSequenceStatement(SequenceSnapshotGeneratorDatabricks.java:42)
`

**Comment by filipelautert** [comment]
@tati-qalified can you review this one again? thanks!

**Comment by tati-qalified** [comment]
@filipelautert I'm still not getting errors that block execution, but the extension is crowding the logs and taking up resources.
@doakd we are currently looking into improving the way Liquibase handles extensions.

**Comment by doakd** [comment]
@tati-qalified 

So if you add a changeset that use the sequenceExists precondition (as provided above), you have the databaricks extension installed, and you run an oracle deployment, you don't get the error I pasted above?

**Comment by tati-qalified** [comment]
@doakd I don't, so there's probably some mix of configurations or some collation in your environment that makes the liquibase-databricks extension fail. Still, it shouldn't have to matter as you're not using Databricks.
To confirm: the error is not blocking the execution of the changeset, right?

**Comment by doakd** [comment]
@tati-qalified 

We are using DataBricks, but this execution that gets the error was for Oracle.

It is blocking the execution.  The sequenceExists precondition has to be replaced with a sqlCheck precondition in order to workaround the issue.

**Comment by doakd** [comment]
@tati-qalified Can I get an update on this issue?

**Comment by tati-qalified** [comment]
@doakd the issue has been addressed and will be included in the next extension release, which will be either next week or the following one. You can see the changes [here](https://github.com/liquibase/liquibase-databricks/pull/133).

**Comment by doakd** [comment]
@tati-qalified Hello.  Do you have an update on the release date for the databrick 1.1.5 extension?

**Comment by filipelautert** [comment]
@doakd soon... working on the latests tests with Databricks team. The plan is to release it this week/early next week.

**Comment by kevin-atx** [comment]
@doakd - The Databricks extension v1.2.0 was released today (June 17, 2024). Please let us know if that release addresses the issue you're experiencing. Thanks!

**Comment by doakd** [comment]
@kevin-atx  I have tested DB extension 1.2.0, with Liquibase 4.28.0, and this issue has been resolved.  Thanks.

**Comment by kevin-atx** [comment]
Thank you, @doakd!

**Comment by kevin-atx** [comment]
Hi Daryl - I just saw that you reopened this issue. What are you seeing? I'd like to stay involved in the issue until it is fully fixed. Oracle and Databricks are both important DBs, and I want us to get any conflicts sorted out fully.

**Comment by doakd** [comment]
@kevin-atx 
This is an issue again with Liquibase 4.29.1.  Getting the following when running Liquibase for Oracle, with liquibase-databricks 1.20.0 installed:

Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.databricks.change.addCheckConstraint.AddCheckConstraintChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.ora.createSynonym.CreateSynonymChange class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.databricks.change.createTable.CreateTableChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.ora.createtrigger.CreateTriggerChange class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.ora.disabletrigger.DisableTriggerChange class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.databricks.change.dropCheckConstraint.DropCheckConstraintChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.ora.dropSynonym.DropSynonymChange class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.ora.droptrigger.DropTriggerChange class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.ora.enabletrigger.EnableTriggerChange class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:08 PM liquibase.change
WARNING: liquibase.ext.ora.renametrigger.RenameTriggerChange class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Starting Liquibase at 15:02:10 using Java 17.0.11 (version 4.29.1 #3316 built at 2024-07-30 20:15+0000)
Aug 01, 2024 3:02:10 PM liquibase.ui
INFO: Starting Liquibase at 15:02:10 using Java 17.0.11 (version 4.29.1 #3316 built at 2024-07-30 20:15+0000)
Liquibase Version: 4.29.1
Aug 01, 2024 3:02:10 PM liquibase.ui
INFO: Liquibase Version: 4.29.1
Liquibase Open Source 4.29.1 by Liquibase
Aug 01, 2024 3:02:10 PM liquibase.ui
INFO: Liquibase Open Source 4.29.1 by Liquibase
Aug 01, 2024 3:02:10 PM liquibase.integration
INFO: Starting command execution.
Aug 01, 2024 3:02:11 PM liquibase.lockservice
INFO: Successfully acquired change log lock
Aug 01, 2024 3:02:12 PM liquibase.change
WARNING: liquibase.ext.databricks.change.createTable.CreateTableChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:12 PM liquibase.change
WARNING: liquibase.ext.databricks.change.createTable.CreateTableChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 01, 2024 3:02:13 PM liquibase.changelog
INFO: Reading from MTRDATAT.DATABASECHANGELOG

**Comment by filipelautert** [comment]
Hello @doakd ! In fact those issues already exists and were hidden with 1.2.0 , liquibase 4.29.1 now is throwing warnings so we know that they exist to be able to fix them. 
We may release Databricks extension next week fixing it!

**Comment by kevin-atx** [comment]
@doakd - [Liquibase 4.29.1 was released](https://github.com/liquibase/liquibase/releases/tag/v4.29.1). Could you try it out when you get a chance and let us know if this is fixed (again).

**Comment by doakd** [comment]
@kevin-atx @filipelautert Using Liquibase 4.29.1 and liquibase-databricks 1.2.0, my update finishes successfully, but the following messages appear at the top, which seems like a problem still:

`
Aug 07, 2024 9:54:17 PM liquibase.change
WARNING: liquibase.ext.databricks.change.addCheckConstraint.AddCheckConstraintChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 07, 2024 9:54:18 PM liquibase.change
WARNING: liquibase.ext.databricks.change.createTable.CreateTableChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 07, 2024 9:54:18 PM liquibase.change
WARNING: liquibase.ext.databricks.change.dropCheckConstraint.DropCheckConstraintChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Starting Liquibase at 21:54:19 using Java 17.0.11 (version 4.29.1 #3316 built at 2024-07-30 20:15+0000)
Aug 07, 2024 9:54:19 PM liquibase.ui
INFO: Starting Liquibase at 21:54:19 using Java 17.0.11 (version 4.29.1 #3316 built at 2024-07-30 20:15+0000)
Liquibase Version: 4.29.1
Aug 07, 2024 9:54:19 PM liquibase.ui
INFO: Liquibase Version: 4.29.1
Liquibase Open Source 4.29.1 by Liquibase
Aug 07, 2024 9:54:19 PM liquibase.ui
INFO: Liquibase Open Source 4.29.1 by Liquibase
Aug 07, 2024 9:54:19 PM liquibase.integration
INFO: Starting command execution.
Aug 07, 2024 9:54:20 PM liquibase.change
WARNING: liquibase.ext.databricks.change.createTable.CreateTableChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 07, 2024 9:54:20 PM liquibase.change
WARNING: liquibase.ext.databricks.change.createTable.CreateTableChangeDatabricks class does not implement the 'supports(Database)' method and may incorrectly override other databases changes causing unexpected behavior. Please report this to the Liquibase developers or if you are developing this change please fix it ;)
Aug 07, 2024 9:54:22 PM liquibase.changelog
INFO: Reading from MTRDATAT.DATABASECHANGELOG
`

**Comment by filipelautert** [comment]
> Will that be fixed with the next version of the databricks extension?

@doakd you are correct! Next databricks versions will have this fix + some other improvements soon.

**Comment by doakd** [comment]
@filipelautert @kevin-atx Is there an ETA on the next version of the databricks extension?  This is preventing us from upgrading to 4.29.1.  Thanks

**Comment by filipelautert** [comment]
Hi @doakd , we just released it -> https://github.com/liquibase/liquibase-databricks/releases/tag/v1.3.0 
It may be reaching maven repo in the next hours.  Thanks for your patience and support :D
(also we added some other nice things as tblProperties support, etc)
