### ISSUE TITLE
The diffChangeLog command doesn't work for Snowflake functions

### ISSUE THREAD

**Issue by LonwoLonwo** [liquibase/liquibase#5753]
### Search first

- [X] I searched and no similar issues were found

### Description

I have two schemas in my Snowflake database. These schemas contain functions. I have the Liquibase license key and use it during the diffChangeLog command generation. And my generation process throws this error:

```
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "liquibase.structure.core.StoredDatabaseLogic.getName()" is null
	at liquibase.structure.core.StoredDatabaseLogic.equals(StoredDatabaseLogic.java:79)
	at java.base/java.util.HashMap.putVal(Unknown Source)
	at java.base/java.util.HashMap.put(Unknown Source)
	at java.base/java.util.HashSet.add(Unknown Source)
	at liquibase.structure.DatabaseObjectCollection.add(DatabaseObjectCollection.java:83)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:329)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:456)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:478)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:369)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:332)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:106)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:188)
```

As I can see in the code base - only Snowflake Procedures comparing is supported. 

You have already all logic for procedures, you can create the copy for functions, The [FUNCTIONS ](https://docs.snowflake.com/en/sql-reference/info-schema/functions) view as very close to [PROCEDURES](https://docs.snowflake.com/en/sql-reference/info-schema/procedures) view.

### Steps To Reproduce

Create schema TEST1.
And create schema TEST2.

Add simple functions in schema TEST1, like

```sql
CREATE FUNCTION pi_udf()
  RETURNS FLOAT
  AS '3.141592654::FLOAT';

CREATE FUNCTION TEST1.simple_table_function()
  RETURNS TABLE (x INTEGER, y INTEGER)
  AS
  $$
    SELECT 1, 2
    UNION ALL
    SELECT 3, 4
  $$
  ;
```

Enable the diffChangeLog command for these two schemas (use TEST1 as a target).
Error occurs.

### Expected/Desired Behavior

Result with one create function query.

### Liquibase Version

4.26

### Database Vendor & Version

Snowflake

### OS and/or Infrastructure Type/Provider

Windows

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Hello @LonwoLonwo ! Thanks for the issue. In fact the Function code is in liquibase-commercial that's why you can't find it. But anyway this is a bug in commercial code that when comparing the objects is generating a null structure for the non-existent function in the destination database - thus generating the null pointer.

**Comment by filipelautert** [comment]
@LonwoLonwo This fix is on commercial, but I guess you can't see it: https://github.com/liquibase/liquibase-pro/pull/1638 
Once I get an artifact I'll share the link.

**Comment by LonwoLonwo** [comment]
Thank you @filipelautert!

**Comment by filipelautert** [comment]
Hello @LonwoLonwo ! Are you able to give current master artifacts a try and see if it fixes the issue? https://github.com/liquibase/liquibase/actions/runs/8568825281/artifacts/1388234226 (from https://github.com/liquibase/liquibase/actions/runs/8568825281 run)

**Comment by LonwoLonwo** [comment]
Hello @filipelautert 

I'm sorry for not getting back to you sooner. I don't know how exactly I can use artifact files.
Maybe I will wait for the next release?

**Comment by filipelautert** [comment]
> Hello @filipelautert
> 
> I'm sorry for not getting back to you sooner. I don't know how exactly I can use artifact files. Maybe I will wait for the next release?

@LonwoLonwo no problems!

**Comment by filipelautert** [comment]
@LonwoLonwo I'll close this one as the fix in merged to master. We are planning to release next week so you'll be able to test, but if the problem persists please reopen this one.

**Comment by LonwoLonwo** [comment]
Great, thanks!

**Comment by LonwoLonwo** [comment]
Hello @filipelautert 

I finally tested the latest version with the fix, and now I have another issue. Unfortunately.

```
liquibase.exception.DatabaseException: Error executing SQL SELECT GET_DDL('function', 'PI_UDF()'): SQL compilation error:
Object 'PI_UDF()' does not exist or not authorized.
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:230)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:238)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:246)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:261)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:256)
	at com.datical.liquibase.ext.storedlogic.function.SnowflakeFunctionSnapshotGenerator.getBody(SnowflakeFunctionSnapshotGenerator.java:56)
	at com.datical.liquibase.ext.storedlogic.function.SnowflakeFunctionSnapshotGenerator.performSnapshotAndBuildStoredObject(SnowflakeFunctionSnapshotGenerator.java:39)
	at com.datical.liquibase.ext.storedlogic.function.FunctionSnapshotGenerator.performSnapshotAndBuildStoredObject(FunctionSnapshotGenerator.java:115)
	at com.datical.liquibase.ext.storedlogic.AbstractStoredDatabaseLogicSnapshotGenerator.snapshotObject(AbstractStoredDatabaseLogicSnapshotGenerator.java:88)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:65)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:60)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:68)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:60)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:68)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:60)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:68)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:60)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:313)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:455)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:477)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:368)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:331)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:106)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:37)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:214)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:187)
	at com.dbeaver.ee.scmp.impl.liquibase.LBCompareEngine.createDatabaseSnapshot(LBCompareEngine.java:709)
	at com.dbeaver.ee.scmp.impl.liquibase.LBCompareEngine.lambda$1(LBCompareEngine.java:222)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at com.dbeaver.ee.scmp.impl.liquibase.LBCompareEngine.compareObjects(LBCompareEngine.java:221)
	at com.dbeaver.ee.scmp.model.tasks.SCMPChangelogTaskHandler.lambda$0(SCMPChangelogTaskHandler.java:85)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Object 'PI_UDF()' does not exist or not authorized.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:129)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:70)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:456)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:366)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:464)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:192)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:129)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:742)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:652)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:251)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:136)
	at liquibase.executor.jvm.JdbcExecutor$QueryStatementCallback.doInStatement(JdbcExecutor.java:551)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83)
	... 37 more
```

It looks like you do not use the full function name in this query:
`SELECT GET_DDL('function', 'PI_UDF()')`
It should be 
`SELECT GET_DDL('function', 'TEST1.PI_UDF()')`
or, better
`SELECT GET_DDL('function', 'DATABASE_NAME.SCHEMA_NAME.PI_UDF()')`

Do I need to create another ticket for this?

**Comment by filipelautert** [comment]
> It looks like you do not use the full function name in this query: `SELECT GET_DDL('function', 'PI_UDF()')` It should be `SELECT GET_DDL('function', 'TEST1.PI_UDF()')` or, better `SELECT GET_DDL('function', 'DATABASE_NAME.SCHEMA_NAME.PI_UDF()')`
> 
> Do I need to create another ticket for this?

Hi @LonwoLonwo - so close :/

We can just reopen this one and I'll go from here, thanks for the stack trace!

**Comment by filipelautert** [comment]
@LonwoLonwo this should have been fixed in master already.
