### ISSUE TITLE
liquibase 4.25.0 mssql server case sensitive issue with sys.sp_updateextendedproperty

### ISSUE THREAD

**Issue by Aboruhen** [liquibase/liquibase#5754]
### Search first

- [X] I searched and no similar issues were found

### Description

Hi,
While migrating from MsSql DB version 2017 to newer 2019 or 2022 we find an issue with add/update table column comments.
So when using the docker DB image: `mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04` with a default collation the change log executes normally
```
<setColumnRemarks tableName="test" columnName="id" remarks="some new comment"/>
```
In case we config DB with `MSSQL_COLLATION: Latin1_General_CS_AS_KS`
The same changelog fails with an error:

```
Caused by: liquibase.exception.DatabaseException: Property cannot be added. Property 'MS_Description' already exists for 'dbo.test.id'. [Failed SQL: (15233) IF EXISTS(  SELECT extended_properties.value FROM sys.extended_properties WHERE major_id = OBJECT_ID('dbo.test') AND name = N'MS_DESCRIPTION' AND minor_id = ( SELECT column_id FROM sys.columns WHERE name = 'id' AND object_id = OBJECT_ID('dbo.test')) ) BEGIN  EXEC sys.sp_updateextendedproperty @name = N'MS_Description' , @value = N'some new comment' , @level0type = N'SCHEMA' , @level0name = N'dbo' , @level1type = N'TABLE' , @level1name = test' , @level2type = N'COLUMN' , @level2name = N'id' END  ELSE  BEGIN  EXEC sys.sp_addextendedproperty @name = N'MS_Description' , @value = N'some new comment' , @level0type = N'SCHEMA' , @level0name = N'dbo' , @level1type = N'TABLE' , @level1name = N'test' , @level2type = N'COLUMN' , @level2name = N'id' END;]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1291)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Property cannot be added. Property 'MS_Description' already exists for 'dbo.test.id'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
```

NOTE: an error appears only in case of updating. If the column didn't have the comment new remarks is set normally.

### Steps To Reproduce

Create 2 sequences of the changeset. Create any column with comments and for a second create the changelog where you try to set a new column comment via
```
<setColumnRemarks tableName="test" columnName="description"
            remarks="New description column comment"/>
```

### Expected/Desired Behavior

The column comment should be updated with any type of DB `collation`

### Database Vendor & Version

MsSql 2019

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @Aboruhen, thank you for reporting this bug.
I was able to reproduce it with Liquibase version 4.27.0, so I can confirm that it's still an issue. It only occurs when using MSSQL 2019+ and the MSSQL collation, most likely because of the case sensitivity as you've mentioned.

This issue will be left open for the community to propose a fix for. The developers will be available to provide guidance if needed.

Thank you,
Tatiana

**Comment by Acket74** [comment]
Faced the same issue.
Seems, there is a workaround to use pure SQL

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
