### ISSUE TITLE
liquibase 4.25.0 works differently for migration and first time execution  

### ISSUE THREAD

**Issue by kirangodishala** [liquibase/liquibase#5844]
### Search first

- [X] I searched and no similar issues were found

### Description

We have been using liquibase 3.10.3 and we tried to migrate to 4.13.0 but it introduced `addAfterColumn is not allowed on postgresql` issue. We worked with you to fix this issue and rased this PR- https://github.com/liquibase/liquibase/pull/3978. 
And this was included in liquibase 4.23.2. But for this fix to work, we needed to include the below yaml snippet in our changelog file under `databaseChangeLog` node. 
```yaml
- removeChangeSetProperty:
    change: addColumn
    dbms: postgresql
    remove: afterColumn
```
So we made the changes and migrated the liquibase to 4.24.0 (next version after 4.23.2). But we are getting the below checksum errors:
``` 
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     3 changesets check sum
          db/changelog/20180919-initial-schema.yml::mysql-change-state-stauts-to-enum-type::robzienert was: 8:f0bfebd55de9168e38a8ef9c7217c610 but is now: 8:d41d8cd98f00b204e9800998ecf8427e
          db/changelog/20180919-initial-schema.yml::mysql-revert-change-state-stauts-to-enum-type::afeldman was: 8:d6f5eedc195011826620cc0355e8352d but is now: 8:d41d8cd98f00b204e9800998ecf8427e
          db/changelog/20190913-task-sagaids.yml::mysql-update-state-enum-values::robzienert was: 8:9601af668599fbc12e338b9b84c66f56 but is now: 8:d41d8cd98f00b204e9800998ecf8427e

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:353)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:92)
```
Out of two changelog files, the second file(`20190913-task-sagaids.yml`) was added with `removeChangeSetProperty` node to fix `addAfterColumn is not allowed on postgresql` issue and the first file(`20180919-initial-schema.yml`) was not changed at all.

After going through the checksum issues list, I tried to test with liquibase 4.25.0 which has a different behaviour. 
It accepted the migration of changelog files from 3.10.3 to 4.25.0 in postgresql but without any changes to the files i.e., 
without adding the `removeChangeSetProperty` node to those changelog files that have changeSets with "afterColumn" feature. 
But when I tested the same set of files directly(not migrating) with 4.25.0, `addAfterColumn is not allowed on postgresql` error resurfaced.

So liquibase 4.25.0 works differently for migration and first time use. We can't proceed with this kind of behaviour. Do you have any solution for this?  

### Steps To Reproduce

Scenario 1:
1. Run the liquibase update using liquibase 3.10.0 on the following set of files -  https://github.com/spinnaker/clouddriver/tree/release-1.32.x/clouddriver-sql/src/main/resources/db 
2. And then run the update using 4.25.0 on the following set of files(some got updated with `removeChangeSetProperty` node) - https://github.com/spinnaker/clouddriver/tree/release-1.33.x/clouddriver-sql/src/main/resources/db. This gives checksum error on a couple of files.  
3. Now run the update using 4.25.0 on the first set of files - https://github.com/spinnaker/clouddriver/tree/release-1.32.x/clouddriver-sql/src/main/resources/db. This update goes successful. 

Scenario 2:

Run the liquibase update using liquibase 4.25.0 on the first set of files -  https://github.com/spinnaker/clouddriver/tree/release-1.32.x/clouddriver-sql/src/main/resources/db. This gives  `addAfterColumn is not allowed on postgresql` error.

  

### Expected/Desired Behavior

1. When we migrate from 3.10.0 to a higher version, we want to get rid of `addAfterColumn is not allowed on postgresql` error and at the same time we don't want checksum errors.
2. Whichever highr version you suggest, should work for the first time execution as well. 

### Liquibase Version

4.25.0

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @kirangodishala, I've tested the scenarios you've presented, but I'm not getting the same behaviour in all of them.

I **can** confirm that running directly with 4.25.0 the files in your 1.32 version, the execution breaks with `addAfterColumn is not allowed on postgresql`. This is also replicable with the latest 4.27.0 Liquibase version.

We'd appreciate it if you could propose a fix for this bug, though it will remain open for the community to fix if not.

However, when I follow the steps of
**1.** run your 1.32 files with 3.10.3
**2.** upgrade to 4.25.0 and 1.33
**3.** run the 1.33 files

I don't get any checksum errors - the checksums are automatically upgraded to version 9. The same thing happens with 4.27.0. Could you provide the error message and/or the stack trace?

**Comment by yevgenykuz** [comment]
Hi @kirangodishala @tati-qalified 
I stumbled across this issue while researching upgrading liquibase from 4.5 to latest (4.27), and would like to share the approach i chose.

My case:
1. I had `afterColumn` fields in existing change sets.
2. The `afterColumn` fields were not necessary since i work only with PostgreSQL instances.
3. The old liquibase version used ignored the `afterColumn` fields, the new liquibase version failed instead of ignoring.
4. I needed a solution that will work both for upgrading existing databases, and for new databases.

During my testing i found out that:
1. For an existing database, upgrading from liquibase 4.5 to 4.27 (latest) automatically changes all the checksums. The hash mechanism was changed, and liquibase patches all checksums on upgrade, hence ignoring the unsupported “addColumn” keyword in existing change sets.
2. For a new database, liquibase looks at all the change sets as new and will fail because of the unsupported “addColumn” keyword (on version 4.27).

Based on these i selected the following approach:
1. In every change set the contained the `afterColumn` keyword:
* Add the `validCheckSum` containing the current checksum for that change set (it should be the same in all DB instances).
* Remove the problematic `afterColumn` fields.
2. Upgrade to the latest liquibase version once all change sets were updated.

This allowed me to prepare for the liquibase upgrade while i kept using the current version 4.5, and then upgrade to the latest - avoiding the need to coordinate all the changed to happen at the same time, and having a solution for both upgrades and new installs.

Since using the `removeChangeSetProperty` on existing change sets will change the checksum, consider using `validCheckSum` to avoid checksum errors.

**Comment by kirangodishala** [comment]
@yevgenykuz - thanks a lot for the hack. I will try this approach.

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
