### ISSUE TITLE
Backwards compatible was broken from version 4.3.5 to 4.4.0 and above

### ISSUE THREAD

**Issue by Haster2004** [liquibase/liquibase#5944]
### Search first

- [X] I searched and no similar issues were found

### Description

Some time ago We used version 4.3.5 of liquibase.
And we have changeset what loaded data to table.
```
...
       {
            "changeSet": {
                "id": "1",
                "author": "author",
                "changes": [
                    {
                        "loadData": {
                            "columns": [
                                {
                                    "name":"CONFIG_STATE_ID",
                                    "type": "NUMERIC"
                                }
                            ],
                            "encoding": "UTF-8",
                            "file": "data/config_state.csv",
                            "primaryKey": "CONFIG_STATE_ID",
                            "separator": ",",
                            "tableName": "CONFIG_STATE",
                            "endDelimiter": ";\n/",
                            "relativeToChangelogFile": true
                        }
                    }
                ],
                "rollback" : [
                    {
                        "sql" : {
                            "sql": "delete from CONFIG_STATE;"
                        }
                    }
                ]
            }
        }
```

And we have file config_state.csv with below lines:
```
config_state_id, code, name, description
1,REGISTERED,Registered,Registered configuration
2,APPLIED,Successfully applied,The last successfully applied configuration
```
As you can see there are whitespaces between header columns.
In liquibase 4.3.5 it was not a problem... but since liquibase 4.4.0 this throw an error (" description": invalid identifier)

I do some investigation and think that problem is that in liquibase 4.3.5 columns in table and headers interpolated by index... 
so columns had correct names. But in liquibase 4.4.0 and above headers not interpolated by index... only be names... so columns names were different (for example in table it was "description" but in csv headers it was " description") so liquibase used new name with whitespace and as a result we have got an error.

Can you fix this problem? Maybe it will be a good idea to trim column names in csv headers?
We now can't delete whitespaces in csv file header and rerun script as this deleteing whitespaces changes hash of changeset and we got error about different hashes
 

### Steps To Reproduce

create changelog file
```
{
    "databaseChangeLog": [
        {
            "property": {
                "name":"id.type",
                "value":"number(10,0)",
                "dbms":"oracle"
            }
        },
        {
            "changeSet": {
                "id": "1",
                "author": "author",
                "changes": [
                    {
                        "createTable": {
                            "tableName": "CONFIG_STATE",
                            "columns": [
                                {
                                    "column": {
                                        "name": "CONFIG_STATE_ID",
                                        "type": "${id.type}",
                                        "remarks": "State ID",
                                        "constraints": {
                                            "primaryKey": true,
                                            "nullable": false
                                        }
                                    }
                                },
                                {
                                    "column": {
                                        "name": "CODE",
                                        "type": "varchar(50)",
                                        "remarks": "State code",
                                        "constraints" : {
                                            "unique" : true,
                                            "nullable": false
                                        }
                                    }
                                },
                                {
                                    "column": {
                                        "name": "NAME",
                                        "type": "varchar(100)",
                                        "remarks": "State name",
                                        "constraints": {
                                            "nullable": false
                                        }
                                    }
                                },
                                {
                                    "column": {
                                        "name": "DESCRIPTION",
                                        "type": "varchar(4000)",
                                        "remarks": "Description"
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        },
       {
            "changeSet": {
                "id": "2",
                "author": "author",
                "changes": [
                    {
                        "loadData": {
                            "columns": [
                                {
                                    "name":"CONFIG_STATE_ID",
                                    "type": "NUMERIC"
                                }
                            ],
                            "encoding": "UTF-8",
                            "file": "config_state.csv",
                            "primaryKey": "CONFIG_STATE_ID",
                            "separator": ",",
                            "tableName": "CONFIG_STATE",
                            "endDelimiter": ";\n/",
                            "relativeToChangelogFile": true
                        }
                    }
                ],
                "rollback" : [
                    {
                        "sql" : {
                            "sql": "delete from CONFIG_STATE;"
                        }
                    }
                ]
            }
        }
    ]
}
```

And create config_state.csv file
```
config_state_id, code, name, description
1,REGISTERED,Registered,Registered configuration
2,APPLIED,Successfully applied,The last successfully applied configuration
```

between headers must be a whitespace

Try to run with changelog in versions liquibase 4.3.5 and any above... result will be different
(on 4.3.5 changelog executes successfully, but on any above version with error)

### Expected/Desired Behavior

expected what all versions can "eat" whitespaces in csv files headers without any errors

### Liquibase Version

4.3.5

### Database Vendor & Version

Oracle

### OS and/or Infrastructure Type/Provider

any

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
Hi @Haster2004, @tati-qalified,

Could any of you please try with a recent version to confirm whether this is still an issue or not? 

Thanks,
Daniel.

**Comment by Haster2004** [comment]
@MalloD12 
I have checked it on last version 4.28.0 and problem is still here.

```
[2024-06-13 19:03:24] FINE [liquibase.statement] INSERT INTO SAM.MBUS_CM_CONFIG_STATE(MC_CONFIG_STATE_ID, " code", " name", " description") VALUES(?, ?, ?, ?)
. . .

[2024-06-13 19:03:24] FINE [liquibase.command] Pipeline for command 'internalRollbackOnError: com.datical.liquibase.ext.command.InternalRollbackOnErrorCommandStep
[2024-06-13 19:03:24] FINE [liquibase.command] Writing output with encoding 'UTF-8'
[2024-06-13 19:03:24] FINE [liquibase.command] Executing internal command internalRollbackOnError
[2024-06-13 19:03:24] INFO [liquibase.command] Command execution complete
[2024-06-13 19:03:24] INFO [liquibase.command] Logging exception.
ERROR: Exception Details
[2024-06-13 19:03:24] INFO [liquibase.ui] ERROR: Exception Details
ERROR: Exception Primary Class:  BatchUpdateException
[2024-06-13 19:03:24] INFO [liquibase.ui] ERROR: Exception Primary Class:  BatchUpdateException
ERROR: Exception Primary Reason:  ORA-00904: " description": invalid identifier

[2024-06-13 19:03:24] INFO [liquibase.ui] ERROR: Exception Primary Reason:  ORA-00904: " description": invalid identifier

ERROR: Exception Primary Source:  Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.11.0.0.0
[2024-06-13 19:03:24] INFO [liquibase.ui] ERROR: Exception Primary Source:  Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.11.0.0.0
[2024-06-13 19:03:24] INFO [liquibase.command] Command execution complete
[2024-06-13 19:03:24] SEVERE [liquibase.integration] Migration failed for changeset db/v8.7.0/04042019-15-tables-data.json::2::Konstantin.Samoylov:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: ORA-00904: " description": invalid identifier

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/v8.7.0/04042019-15-tables-data.json::2::Konstantin.Samoylov:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: ORA-00904: " description": invalid identifier

    at liquibase.command.CommandScope.execute(CommandScope.java:257)
    at com.datical.liquibase.ext.command.InternalRollbackOnErrorCommandStep.executeCommand(InternalRollbackOnErrorCommandStep.java:313)
    at com.datical.liquibase.ext.command.ProUpdateCommandStep.run(ProUpdateCommandStep.java:45)
    at liquibase.command.CommandScope.execute(CommandScope.java:219)
    at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
    at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
    at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
    at picocli.CommandLine.access$1500(CommandLine.java:148)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
    at picocli.CommandLine.execute(CommandLine.java:2170)
    at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:387)
    at liquibase.Scope.child(Scope.java:200)
    at liquibase.Scope.child(Scope.java:176)
    at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:362)
    at liquibase.Scope.child(Scope.java:200)
    at liquibase.Scope.child(Scope.java:176)
    at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:359)
    at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:96)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/v8.7.0/04042019-15-tables-data.json::2::Konstantin.Samoylov:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: ORA-00904: " description": invalid identifier

    at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:148)
    at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:112)
    at liquibase.Scope.lambda$child$0(Scope.java:191)
    at liquibase.Scope.child(Scope.java:200)
    at liquibase.Scope.child(Scope.java:190)
    at liquibase.Scope.child(Scope.java:169)
    at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:110)
    at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
    at com.datical.liquibase.ext.command.ProUpdateCommandStep.run(ProUpdateCommandStep.java:42)
    ... 24 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset db/v8.7.0/04042019-15-tables-data.json::2::Konstantin.Samoylov:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: ORA-00904: " description": invalid identifier

    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:812)
    at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
    at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
    at liquibase.changelog.ChangeLogIterator.lambda$run$0(ChangeLogIterator.java:131)
    at liquibase.Scope.lambda$child$0(Scope.java:191)
    at liquibase.Scope.child(Scope.java:200)
    at liquibase.Scope.child(Scope.java:190)
    at liquibase.Scope.child(Scope.java:169)
    at liquibase.changelog.ChangeLogIterator.lambda$run$1(ChangeLogIterator.java:120)
    at liquibase.Scope.lambda$child$0(Scope.java:191)
    at liquibase.Scope.child(Scope.java:200)
    at liquibase.Scope.child(Scope.java:190)
    at liquibase.Scope.child(Scope.java:169)
    at liquibase.Scope.child(Scope.java:257)
    at liquibase.Scope.child(Scope.java:261)
    at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
    ... 32 more
Caused by: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: ORA-00904: " description": invalid identifier

    at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:121)
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:175)
    at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
    at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1176)
    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:768)
    ... 47 more
Caused by: java.sql.BatchUpdateException: ORA-00904: " description": invalid identifier

    at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:9741)
    at oracle.jdbc.driver.T4CPreparedStatement.executeLargeBatch(T4CPreparedStatement.java:1447)
    at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9517)
    at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:237)
    at liquibase.statement.BatchDmlExecutablePreparedStatement.executePreparedStatement(BatchDmlExecutablePreparedStatement.java:64)
    at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:119)
    ... 51 more
```

**Comment by MalloD12** [comment]
Thank you for confirming this to me so quickly. I think a fix for this would be pretty straightforward, but I'm not sure whether this is a liquibase issue. In my opinion, it seems to be a CSV formatting issue. According to the CSV formatting specification: https://www.rfc-editor.org/rfc/rfc4180 if we have some space in a header it should be part of the column name:
```code:text
 4.  Within the header and each record, there may be one or more fields, separated by commas.  
Each line should contain the same number of fields throughout the file.  Spaces are considered 
part of a field and should not be ignored.  The last field in the record must not be followed by a comma. 
```

cc: @filipelautert 

Thanks,
Daniel.

**Comment by Haster2004** [comment]
Yep, but the problem is that old liquibase version (4.3.5) allowed whitespace in csv headers, but more modern not.
I think that it will be a good idea to trim headers in csv files (for example liquibase uses trim function for some values
https://github.com/liquibase/liquibase/blob/v4.28.0/liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java#L306

And I think it will be a good to rebuild backward compatibility ;)

**Comment by MalloD12** [comment]
Hey @Haster2004,

I want to let you know I just created this [PR](https://github.com/liquibase/liquibase/pull/6017)  to address this issue.  Feel free to look at it and share any feedback you have about it. 

Thanks,
Daniel.

**Comment by Haster2004** [comment]
@MalloD12 , PR looks great!
Thanks a lot!
