### ISSUE TITLE
liquibase execute-sql return Invalid SQL type: sqlKind = UNINITIALIZED

### ISSUE THREAD

**Issue by matteo-rama** [liquibase/liquibase#5984]
### Search first

- [X] I searched and no similar issues were found

### Description

calling 

```
"liquibase", "execute-sql",
                "--log-level=INFO",
                "--defaultsFile=props.properties",
                "--default-schema-name=TEST",
                "--delimiter=\\",
                "--sql=\"SELECT ENV FROM BC_HELPER\""

```

i did experiment with delimiter in various way, as i read it could be the issue (try with ; \ /) 

with oracle db
i got the following exception
liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: Invalid SQL type: sqlKind = UNINITIALIZED [Failed SQL: (17439) "SELECT ENV FROM BC_HELPER"]

from the log i can see that's actually connecting to db
[2024-06-10 07:35:53] INFO [liquibase.lockservice] Successfully acquired change log lock
[2024-06-10 07:35:53] INFO [liquibase.lockservice] Successfully released change log lock
[2024-06-10 07:35:53] INFO [liquibase.command] Logging exception.
ERROR: Exception Details
[2024-06-10 07:35:53] INFO [liquibase.ui] ERROR: Exception Details
ERROR: Exception Primary Class:  SQLException
[2024-06-10 07:35:53] INFO [liquibase.ui] ERROR: Exception Primary Class:  SQLException
ERROR: Exception Primary Reason: Invalid SQL type: sqlKind = UNINITIALIZED

and if i do an update with a valid changelog, the same 'props.properties' file just work, and update goes flawlessly.

i am just unable to run the "select env fom bc_helper"

bc_helper is a 1 row table, and ENV is a varchar 64

thanks for helping!

### Steps To Reproduce

"liquibase", "execute-sql",
                "--log-level=INFO",
                "--defaultsFile=props.properties",
                "--default-schema-name=TEST",
                "--delimiter=\\",
                "--sql=\"SELECT ENV FROM BC_HELPER\""

### Expected/Desired Behavior

return the actual data from the table

### Liquibase Version

Liquibase Open Source version 4.25.1

### Database Vendor & Version

oracle 19c

### Liquibase Integration

cli

### Liquibase Extensions

oracle extension

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @matteo-rama, thank you for reporting this issue. 
Are you using Liquibase through a Dockerfile, with the command you've provided as a `CMD` argument? If so, could you provide your Dockerfile?

This bug isn't reproducible using the regular Liquibase CLI.

Thank you,
Tatiana

**Comment by matteo-rama** [comment]
no, i am not using docker, just shell.
maybe is the different database the culprit, i am using oracle

**Comment by tati-qalified** [comment]
Please try using the following syntax:
```
liquibase execute-sql --log-level=INFO --default-schema-name=TEST --delimiter=\\ --sql="SELECT ENV FROM BC_HELPER"
```

**Comment by matteo-rama** [comment]
hi,

did try but without luck :(


that's a piece of log, not sure if it help

[2024-07-08 09:35:51] INFO [liquibase.lockservice] Successfully acquired change log lock
[2024-07-08 09:35:51] INFO [liquibase.lockservice] Successfully released change log lock
[2024-07-08 09:35:51] INFO [liquibase.command] Logging exception.
ERROR: Exception Details
[2024-07-08 09:35:51] INFO [liquibase.ui] ERROR: Exception Details
ERROR: Exception Primary Class:  SQLException
[2024-07-08 09:35:51] INFO [liquibase.ui] ERROR: Exception Primary Class:  SQLException
ERROR: Exception Primary Reason: Tipo SQL non valido: sqlKind = UNINITIALIZED
[2024-07-08 09:35:51] INFO [liquibase.ui] ERROR: Exception Primary Reason: Tipo SQL non valido: sqlKind = UNINITIALIZED
ERROR: Exception Primary Source: Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.22.0.0.0
[2024-07-08 09:35:51] INFO [liquibase.ui] ERROR: Exception Primary Source: Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.22.0.0.0
[2024-07-08 09:35:51] INFO [liquibase.command] Command execution complete
[2024-07-08 09:35:51] SEVERE [liquibase.integration] Tipo SQL non valido: sqlKind = UNINITIALIZED [Failed SQL: (17439) "SELECT ENV FROM BC_HELPER"]
liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: Tipo SQL non valido: sqlKind = UNINITIALIZED [Failed SQL: (17439) "SELECT ENV FROM BC_HELPER"]
	at liquibase.command.CommandScope.execute(CommandScope.java:253)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)


and the command you send is exactly what i run, aside that i add --defaultsFile=.....

to add my config file

**Comment by tati-qalified** [comment]
Hi, I still haven't been able to reproduce this, so I need some more detailed information:

1. The command you provided has a different syntax than the one I provided, yet you said that you were running the same one I sent. Have you tried with **both** syntaxes?
2. The syntax `"liquibase", "execute-sql",  ...` isn't default for CLI. Are you using PowerShell or any other CMD?
3. If not, could you provide part of the logs (like you did before) but **including** the command you ran?
4. Have you tried using single quotes `' '` instead of double quotes `" "` around your SQL code?
5. Lastly, I have a suspicion that the `--delimiter=\\` part might be the culprit. Could you try running the command without it?

Thank you,
Tatiana

**Comment by rberezen** [comment]
This issue has been inactive for an extended period with no response to the last request for information. Closing as stale. Please reopen if this is still an issue.
