### ISSUE TITLE
OSGi header missing for ValidatingVisitorGenerator

### ISSUE THREAD

**Issue by steinarb** [liquibase/liquibase#6040]
### Search first

- [X] I searched and no similar issues were found

### Description

When bumping the liquibase version from 4.27.0 to 4.28.0, the integration test failed with the following stack trace:
```
2024-06-25T21:24:02,473 | ERROR | features-3-thread-1 | SampleDbLiquibaseRunner          | 87 - no.priv.bang.karaf.liquibase.sample - 4.27.1.SNAPSHOT | Error creating sampleapp test database schema
liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "liquibase.changelog.visitor.ValidatingVisitorGenerator.generateValidatingVisitor(java.util.List)" because "generator" is null
	at liquibase.command.CommandScope.execute(CommandScope.java:257) ~[?:?]
	at no.priv.bang.karaf.liquibase.runner.LiquibaseClassPathChangeLogRunner.lambda$applyLiquibaseChangelist$0(LiquibaseClassPathChangeLogRunner.java:56) ~[?:?]
	at liquibase.Scope.child(Scope.java:200) ~[?:?]
	at liquibase.Scope.child(Scope.java:176) ~[?:?]
	at no.priv.bang.karaf.liquibase.runner.LiquibaseClassPathChangeLogRunner.applyLiquibaseChangelist(LiquibaseClassPathChangeLogRunner.java:53) ~[?:?]
	at no.priv.bang.karaf.sample.db.liquibase.test.SampleDbLiquibaseRunner.applyLiquibaseChangelist(SampleDbLiquibaseRunner.java:69) ~[?:?]
	at no.priv.bang.karaf.sample.db.liquibase.test.SampleDbLiquibaseRunner.prepare(SampleDbLiquibaseRunner.java:52) ~[?:?]
	at org.ops4j.pax.jdbc.config.impl.DataSourceRegistration.<init>(DataSourceRegistration.java:88) ~[?:?]
	at org.ops4j.pax.jdbc.config.impl.DataSourceConfigManager.lambda$null$4(DataSourceConfigManager.java:95) ~[?:?]
	at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper$1.addingService(ServiceTrackerHelper.java:132) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[osgi.core-8.0.0.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871) ~[osgi.core-8.0.0.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[osgi.core-8.0.0.jar:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[osgi.core-8.0.0.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) ~[osgi.core-8.0.0.jar:?]
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990) ~[?:?]
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838) ~[?:?]
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545) ~[?:?]
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4863) ~[?:?]
	at org.apache.felix.framework.Felix.registerService(Felix.java:3834) ~[?:?]
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328) ~[?:?]
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302) ~[?:?]
	at org.h2.util.OsgiDataSourceFactory.registerService(OsgiDataSourceFactory.java:308) ~[?:?]
	at org.h2.util.DbDriverActivator.start(DbDriverActivator.java:37) ~[?:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849) ~[?:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429) ~[?:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2335) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:1006) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:992) ~[?:?]
	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "liquibase.changelog.visitor.ValidatingVisitorGenerator.generateValidatingVisitor(java.util.List)" because "generator" is null
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:375) ~[?:?]
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:92) ~[?:?]
	at liquibase.command.CommandScope.execute(CommandScope.java:219) ~[?:?]
	... 37 more
```

### Steps To Reproduce

1. Clone [the liquibase-karaf-feature project](https://github.com/steinarb/liquibase-karaf-feature)
2. Build the project with "mvn clean install", build should not fail
3. Change liquibase.version to 4.28.0 [in the top pom](https://github.com/steinarb/liquibase-karaf-feature/blob/12aca4442861d98cda49f82f9223864bb20e6cb6/pom.xml#L29)
4. Build the project again, this time it will fail in the integration test
5. Look for the stack trace in liquibase-karaf-feature/liquibase-integration-test/karaf.liquibase.tests/target/exam/<guid-different-for-each-run>/data/log/karaf.log

### Expected/Desired Behavior

The project should build without failing in the integration test.

### Liquibase Version

4.28.0

### Database Vendor & Version

H2 2.2.224

### Liquibase Integration

java API

### OS and/or Infrastructure Type/Provider

debian 12.5 "bookworm"

### Additional Context

It's failing under OSGi because the MANIFEST.MF of liquibase-core does not contain <Provide-Capability> and <Require-Capability> for liquibase.changelog.visitor.ValidatingVisitorGenerator (similar to what was fixed in https://github.com/liquibase/liquibase/pull/5498 )

There could be more services missing.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by steinarb** [comment]
Here is a patch for the headers:
```
diff --git a/liquibase-standard/pom.xml b/liquibase-standard/pom.xml
index 850c06e97..21474f208 100644
--- a/liquibase-standard/pom.xml
+++ b/liquibase-standard/pom.xml
@@ -247,7 +247,8 @@
                             osgi.serviceloader; osgi.serviceloader=liquibase.resource.PathHandler,
                             osgi.serviceloader; osgi.serviceloader=liquibase.report.ShowSummaryGenerator,
                             osgi.serviceloader; osgi.serviceloader=liquibase.parser.LiquibaseSqlParser,
-                            osgi.serviceloader; osgi.serviceloader=liquibase.changeset.ChangeSetService
+                            osgi.serviceloader; osgi.serviceloader=liquibase.changeset.ChangeSetService,
+                            osgi.serviceloader; osgi.serviceloader=liquibase.changelog.visitor.ValidatingVisitorGenerator
                         </Provide-Capability>
                         <Require-Capability>
                             osgi.extender; filter:="(osgi.extender=osgi.serviceloader.registrar)",
@@ -284,7 +285,8 @@
                             osgi.serviceloader; filter:="(osgi.serviceloader=liquibase.resource.PathHandler)"; cardinality:=multiple,
                             osgi.serviceloader; filter:="(osgi.serviceloader=liquibase.report.ShowSummaryGenerator)"; cardinality:=multiple,
                             osgi.serviceloader; filter:="(osgi.serviceloader=liquibase.parser.LiquibaseSqlParser)"; cardinality:=multiple,
-                            osgi.serviceloader; filter:="(osgi.serviceloader=liquibase.changeset.ChangeSetService)"; cardinality:=multiple
+                            osgi.serviceloader; filter:="(osgi.serviceloader=liquibase.changeset.ChangeSetService)"; cardinality:=multiple,
+                            osgi.serviceloader; filter:="(osgi.serviceloader=liquibase.changelog.visitor.ValidatingVisitorGenerator)"; cardinality:=multiple
                         </Require-Capability>
                     </instructions>
                 </configuration>
```

**Comment by steinarb** [comment]
There now is a PR https://github.com/liquibase/liquibase/pull/6045

I have verified that this PR fixed the issue I had upgrading https://github.com/steinarb/liquibase-karaf-feature from liquibase 4.27.0 to liquibase 4.28.0

**Comment by filipelautert** [comment]
This has been fixed under https://github.com/liquibase/liquibase/pull/6045 .
