### ISSUE TITLE
ColumnExistsPrecondition throws exception when using NotPrecondition

### ISSUE THREAD

**Issue by masher82** [liquibase/liquibase#6217]
### Search first

- [X] I searched and no similar issues were found

### Description

I have a change set that should add a column if it does not exist. If the column already exist it should be marked as run. The following (simplified) change set takes care of it:

```
    <changeSet id="addSalt" author="theAuthor">
        <preConditions onFail="MARK_RAN">
            <not>
                <columnExists tableName="guest" columnName="salt" />
            </not>
        </preConditions>
        <comment>
            Add column 'salt' to table guest.
        </comment>
        <sql>
            ALTER TABLE guest ADD salt VARBINARY(128) DEFAULT NULL;
        </sql>
    </changeSet>
```

Executing the NotPrecondition results in a logged error even though this expected behavior:

```
2024-08-19T13:54:08,983+0200 ERROR [Thread-7] ....JDBC4StatementWrapper.logSyntaxError(JDBC4StatementWrapper.java:73) 
Error in SQL syntax in the following statement on schema db_5_global: select t.salt from db_5_global.guest2context t where 0=1
java.sql.SQLSyntaxErrorException: Unknown column 't.salt' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at ... JDBC4PreparedStatementWrapper.executeQuery(JDBC4PreparedStatementWrapper.java:107)
	at liquibase.precondition.core.ColumnExistsPrecondition.makeSureColumnExistsInOtherDBs(ColumnExistsPrecondition.java:162)
	at liquibase.precondition.core.ColumnExistsPrecondition.checkFast(ColumnExistsPrecondition.java:140)
	at liquibase.precondition.core.ColumnExistsPrecondition.check(ColumnExistsPrecondition.java:83)
	at liquibase.precondition.core.NotPrecondition.check(NotPrecondition.java:34)
	at liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:39)
	at liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:689)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator.lambda$run$0(ChangeLogIterator.java:131)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.changelog.ChangeLogIterator.lambda$run$1(ChangeLogIterator.java:120)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:257)
	at liquibase.Scope.child(Scope.java:261)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:113)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:111)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:220)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:216)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Liquibase.runInScope(Liquibase.java:1290)
	at liquibase.Liquibase.update(Liquibase.java:205)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:165)
```

Further processing is fine as the liquibase.precondition.core.NotPrecondition.check(Database, DatabaseChangeLog, ChangeSet, ChangeExecListener) catches the PreconditionFailedException. 

The logged exception suggests that something went wrong and the admin has to take care but its just an information that should be swallowed.

### Steps To Reproduce

Create a table guest and execute the change set mentioned above

```
            CREATE TABLE guest (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                gid VARCHAR(255) NOT NULL,
                PRIMARY KEY (id),
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

### Expected/Desired Behavior

The exception should not be logged.

### Liquibase Version

4.29.1

### Database Vendor & Version

10.11.9-MariaDB-ubu2204

### Liquibase Integration

jar

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @masher82, thank you for reporting this issue.
This logging isn't actually coming from Liquibase, but from the JDBC driver - `JDBC4StatementWrapper.logSyntaxError(JDBC4StatementWrapper.java:73)` is in the driver's code. However, I understand that logging the exception message can be confusing, especially if it's the expected behaviour.

Would you be willing to submit a PR and propose a fix? Our development team will be available to provide any guidance needed.

Thank you,
Tatiana

**Comment by masher82** [comment]
Hi Tatiana, of course this log comes from the JDBX connector. But as the NOT precondition is based on the check if the column/table/whatever exist in my opinion it should be swallowed within Liquibase. 

At the moment I do not have the time to work on this topic but I will try to submit a PR when this changes in a few weeks.

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
