### ISSUE TITLE
includeAll not working when used through a JAR

### ISSUE THREAD

**Issue by Uchiha268** [liquibase/liquibase#6264]
### Search first

- [X] I searched and no similar issues were found

### Description

I have the following file structure - 
```
src
    └── main
        ├── java
        └── resources
            └── db
                └── changelog
                    ├── db.changelog-master.xml
                    └── releases
                        ├── release1.xml
                        ├── release2.xml
```
                        
And within db.changelog-master.xml I am referring to all the changelings in the releases directory in the following way :- `<includeAll path="releases" relativeToChangelogFile="true" errorIfMissingOrEmpty="true"/>`

The liquibase update then runs perfectly while running through IntelliJ IDEA, however when I create a JAR of the same liquibase is unable to find the directory releases.

```
Caused by: java.io.IOException: Could not find/read changelogs from releases directory
	at liquibase.changelog.DatabaseChangeLog.findResources(DatabaseChangeLog.java:866) ~[liquibase-core-4.29.1.jar!/:na]
	... 40 common frames omitted
```

I have tried to change how I refer to the folder by not using relative path but by using the class path as well :-
`<includeAll path="db/changelog/releases" errorIfMissingOrEmpty="true"/>`

However again it runs perfectly through IntelliJ, applying the changelogs but fails while running the JAR of it.

```
Caused by: java.io.IOException: Could not find/read changelogs from db/changelog/releases directory
	at liquibase.changelog.DatabaseChangeLog.findResources(DatabaseChangeLog.java:866) ~[liquibase-core-4.29.1.jar!/:na]
	... 40 common frames omitted
```

I am using liquibase version 4.25.1 but I found the same issue while using the new version, 4.29.1 as well. I have also checked whether the changelogs were part of the jar by extracting the jar created and they are exactly where they should be. And that doesn't also seem to be the problem since when I refer to each changelog file individually in the master using include rather then includeAll, then everything works.

### Steps To Reproduce

The following is how I am running the liquidate update command in the java application - 

```
try {
            CommandScope update = new CommandScope("update");

            update.addArgumentValue("changelogFile", "db/changelog/db.changelog-master.xml");
            update.addArgumentValue("url", URL);
            update.addArgumentValue("username", USER);
            update.addArgumentValue("password", PASSWORD);

            update.execute();
        } catch (CommandExecutionException e) {
            logger.error("Liquibase Update failed with error message: " + e.getMessage());
            throw e;
}
```

### Expected/Desired Behavior

The only solution that works even through JAR is when I ditch includeAll altogether and reference each changelog file with it's full path using the include command, specifying the class path of each file using the file attribute. However this is a far less ideal solution. I have viewed similar problems on stackoverflow and on GitHub too but it seems to be this problem has reappeared on some versions and whatever solutions suggested by some like using "/" before the path also seems to be not working for me. Just wondering if I am doing anything wrong? Any help would be really appreciated.

### Liquibase Version

4.25.1

### Database Vendor & Version

Mysql 9.0.1

### Liquibase Integration

spring boot 3.1.12

### OS and/or Infrastructure Type/Provider

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment Temurin-17+35 (build 17+35) 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by asolntsev** [comment]
@Uchiha268 Today we got the same problem. 
The problem is that LiquiBase swallows the root case, and shows only message 
> Could not find/read changelogs from . directory

without explaining **WHY it could not read**.

I've submitted PR https://github.com/liquibase/liquibase/pull/6286 that fixes this problem.

In our case, the root problem was that we executed LiquiBase with custom JRE built with `jlink` tool. And this JRE didn't have `jdk.zipfs` module need to scan changesets inside HAR file.

**Comment by Uchiha268** [comment]
Thanks a lot. Yes debugging with the reason would be a lot easier.

**Comment by ca2q** [comment]
We also encountered this error. We have around 10000 sql files and could not figure out why liquidbase includeAll could not find them.
Only error we were getting was this `IOException: Could not find/read changelogs from releases directory`

As it turns out, we had some files with Illegal characters in the name and it broke includeAll entirely, almost impossible to diagnose without proper exception.
Thanks @asolntsev for the solution, we swapped our liquidbase with custom jar with addition from you MR and quickly found broken files.

This is the error we should have seen from the beginning:

`Caused by: java.io.IOException: Could not find/read changelogs from db/changelog/ directory
  at liquibase.changelog.DatabaseChangeLog.findResources(DatabaseChangeLog.java:866)
  ... 51 common frames omitted
Caused by: java.io.IOException: Invalid URI [jar:nested:/app/app.jar/!BOOT-INF/classes/!/db/changelog/example_ file.sql]
  at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:122)
  at org.springframework.core.io.UrlResource.getURI(UrlResource.java:271)
  at liquibase.integration.spring.SpringResourceAccessor.search(SpringResourceAccessor.java:71)
  at liquibase.resource.ResourceAccessor.search(ResourceAccessor.java:148)
  at liquibase.changelog.DatabaseChangeLog.findResources(DatabaseChangeLog.java:863)
  ... 51 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 65: jar:nested:/app/app.jar/!BOOT-INF/classes/!/db/changelog/example_ file.sql
  at java.base/java.net.URI$Parser.fail(URI.java:2974)
  at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
  at java.base/java.net.URI$Parser.parse(URI.java:3181)
  at java.base/java.net.URI.<init>(URI.java:623)
  at org.springframework.util.ResourceUtils.toURI(ResourceUtils.java:384)
  at org.springframework.util.ResourceUtils.toURI(ResourceUtils.java:373)
  at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:119)
  ... 55 common frames omitted`

**Comment by tati-qalified** [comment]
Hi @Uchiha268, could you confirm if @asolntsev's PR helped solve your problem?

**Comment by rajshreeee** [comment]
I faced the same issue, although it was running locally, executing through jar would result in the same error message. I'm using  `org.liquibase.ext:liquibase-mongodb:4.29.1`


I had to change the syntax from 
```
    <mongodb:insertMany collectionName="transactionFee">
```

to 

```
    <ext:insertMany collectionName="transactionFee">
```

**Comment by filipelautert** [comment]
Fixed by https://github.com/liquibase/liquibase/pull/6286 .

**Comment by shreyashchatterjee** [comment]
> Hi @Uchiha268, could you confirm if [@asolntsev](https://github.com/asolntsev)'s PR helped solve your problem?

Hi, I am really sorry for the extremely late reply but yes. The PR solved my problem. Thanks a lot!!

**Comment by shreyashchatterjee** [comment]
> > [@shreyashchatterjee](https://github.com/shreyashchatterjee) which Liquibase version are you getting that error with?
> 
> I just updated it to 4.32.0

Spring boot is now at 3.4.5 and jdk is 17 if that helps debugging it.
