### ISSUE TITLE
liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "defaultValue" is null

### ISSUE THREAD

**Issue by xeagle2** [liquibase/liquibase#6281]
### Search first

- [X] I searched and no similar issues were found

### Description

NPE is thrown when using a connection to the SAP database.

At class **liquibase.snapshot.jvm.ColumnSnapshotGenerator** (**method: readDefaultValue**), there is **no check defaultValue for null** in a code provided as a snippet below

```
if (database instanceof SybaseASADatabase) {
            String defaultValue = (String) columnMetadataResultSet.get(COLUMN_DEF_COL);

           // SQL Anywhere returns `CURRENT DATE` (without underscore), which no other RDBMS would understand
           defaultValue = defaultValue.replaceAll("(?i)\\bCURRENT\\s+DATE\\b", "{fn CURDATE()}");

           // SQL Anywhere returns `CURRENT TIME` (without underscore), which no other RDBMS would understand
           defaultValue = defaultValue.replaceAll("(?i)\\bCURRENT\\s+TIME\\b", "{fn CURTIME()}");

           // SQL Anywhere returns `CURRENT TIMESTAMP` (without underscore), which no other RDBMS would understand
           defaultValue = defaultValue.replaceAll("(?i)\\bCURRENT\\s+TIMESTAMP\\b", "{fn NOW()}");

           // SQL Anywhere returns `CURRENT USER` (without underscore), which no other RDBMS would understand
           defaultValue = defaultValue.replaceAll("(?i)\\bCURRENT\\s+USER\\b", "{fn USER()}");

           columnMetadataResultSet.set(COLUMN_DEF_COL, defaultValue);

           if ("YES".equals(columnMetadataResultSet.get("IS_GENERATEDCOLUMN"))) {
               Object virtColumnDef = columnMetadataResultSet.get(COLUMN_DEF_COL);
               if ((virtColumnDef != null) && !"null".equals(virtColumnDef)) {
                   columnMetadataResultSet.set(COLUMN_DEF_COL, "COMPUTE (" + virtColumnDef + ")");
               }
           }
        }
```

```
liquibase.exception.CommandExecutionException: java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "defaultValue" is null
	at liquibase.command.CommandScope.execute(CommandScope.java:237)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:383)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:133)
Caused by: java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "defaultValue" is null
	at liquibase.snapshot.jvm.ColumnSnapshotGenerator.readDefaultValue(ColumnSnapshotGenerator.java:571)
	at liquibase.snapshot.jvm.ColumnSnapshotGenerator.readColumn(ColumnSnapshotGenerator.java:291)
	at liquibase.snapshot.jvm.ColumnSnapshotGenerator.addTo(ColumnSnapshotGenerator.java:204)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:78)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:313)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:106)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:244)
	at liquibase.snapshot.SnapshotGeneratorFactory.getDatabaseChangeLogTable(SnapshotGeneratorFactory.java:255)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:111)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.checkLiquibaseTables(DatabaseChangelogCommandStep.java:141)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:91)
	at liquibase.command.CommandScope.execute(CommandScope.java:214)
	... 23 more
```

### Steps To Reproduce

It happens whenever liquibase is launched with 'update' command

### Expected/Desired Behavior

I expect to see no NPE thrown and successful execution of the code.

### Liquibase Version

4.29.1

### Database Vendor & Version

SAP ASE 12

### Liquibase Integration

CLI

### Liquibase Extensions

liquibase-core

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lbadam** [comment]
@asolntsev thank you for filing this issue and for the attached PR. We'll take a look!
