### ISSUE TITLE
ExecutablePreparedStatementBase java.io.IOException: Resetting to invalid mark

### ISSUE THREAD

**Issue by sshuvalov** [liquibase/liquibase#6316]
### Search first

- [X] I searched and no similar issues were found

### Description

The error was found by accident when trying to put a file exactly _100_000_ bytes in the database in migration.
In this case, when calculating the size of the stream inside the **ExecutablePreparedStatementBase** class, the condition for resetting the mark is not calculated correctly. 

Problem line: https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java#L417

Possible fixed condition: `in.markSupported() && (length < IN_MEMORY_THRESHOLD)` _less_ instead of _less or equal_

> Caused by: liquibase.exception.DatabaseException: Resetting to invalid mark
> 	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:335)
> 	at liquibase.statement.ExecutablePreparedStatementBase.attachParams(ExecutablePreparedStatementBase.java:218)
> 	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:118)
> 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:175)
> 	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
> 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1189)
> 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:775)
> 	... 123 more
> Caused by: java.io.IOException: Resetting to invalid mark
> 	at java.base/java.io.BufferedInputStream.reset(BufferedInputStream.java:446)
> 	at liquibase.statement.ExecutablePreparedStatementBase.toBinaryStream(ExecutablePreparedStatementBase.java:415)
> 	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:308)
> 	... 129 more

### Steps To Reproduce

Create migration and changeSet to try put a file (valueClobFile="data/somefile.dat") exactly equal to 100_000 bytes.

Test illustrating the problem:
```   
    @Test
    @SneakyThrows
    void test() {
        // BufferedInputStream.DEFAULT_BUFFER_SIZE = 8192
        var bufferSize = new Random().nextInt(10000);
        var size =  new Random().nextInt(bufferSize, bufferSize * 2);

        var data = new byte[size];

        var is = new BufferedInputStream(new ByteArrayInputStream(data), bufferSize);

        is.mark(size);

        var length = getContentLength(is);

        if (length <= size) { // <- invalid condition
            is.reset();
        }

    }

    protected static long getContentLength(InputStream in) throws IOException {
        long length = 0;
        byte[] buf = new byte[4096];
        int bytesRead = in.read(buf);
        while (bytesRead > 0) {
            length += bytesRead;
            bytesRead = in.read(buf);
        }
        return length;
    }
```

### Expected/Desired Behavior

A file of 100_000 bytes is inserted into the table without errors

### Liquibase Version

latest

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @sshuvalov, thank you for reporting this issue. I agree with you regarding the condition for resetting the input stream.
Feel free to submit your PR, our development team will be available to provide guidance if needed.
Thank you!

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
