### ISSUE TITLE
Java changeLogSync changelogparameters not working

### ISSUE THREAD

**Issue by francisud** [liquibase/liquibase#6356]
### Search first

- [X] I searched and no similar issues were found

### Description

changelog-sync called from Java is not using the changelogparameters set in Java.

Java version: 21
Liquibase core version: org.liquibase:liquibase-core:4.29.1
Springboot version: spring-boot-3.3.1

### Steps To Reproduce

To reproduce:

Sample code:
```java
Database database = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(connection));
for (int x = 0; x < masterChangeLogs.length; x++) {
  try (Liquibase liquibase = new Liquibase(masterChangeLogs[x], generateAccessor(searchPath), database)) {

    liquibase.setChangeLogParameter("client_code", CLIENT_CODE);
    liquibase.setChangeLogParameter("sync_tag", new Date());
    liquibase.setChangeLogParameter("release_type", releaseType);
    liquibase.setChangeLogParameter("target_version", targetVersion);
    liquibase.setChangeLogParameter("release_version", releaseVersion);
    
    liquibase.changeLogSync(new Contexts(), new LabelExpression());
  }
}
```

Changelog file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.29.xsd http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd"
                   logicalFilePath="sync/sync.xml">

  <include file="database-files/common-changelogs/check-version.xml"/>

  
  <includeAll path="database-files/upgradescripts/${release_type}/${release_version}"
              maxDepth="1" />
              

  <include file="database-files/common-changelogs/fix-invalid.xml"/>

  <include file="database-files/common-changelogs/tag-sync.xml"/>

</databaseChangeLog>
```

Sample error:
```
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Could not find directory, directory was empty, or no changelogs matched the provided search criteria for includeAll 'database-files/upgradescripts/${release_type}/${release_version}'
	at liquibase.command.CommandScope.execute(CommandScope.java:258) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Liquibase.lambda$changeLogSync$13(Liquibase.java:786) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Scope.lambda$child$0(Scope.java:191) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Scope.child(Scope.java:190) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Liquibase.runInScope(Liquibase.java:1290) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Liquibase.changeLogSync(Liquibase.java:779) ~[liquibase-core-4.29.1.jar:?]
	at liquibase.Liquibase.changeLogSync(Liquibase.java:762) ~[liquibase-core-4.29.1.jar:?]
	at com.configs.LiquibaseConfig.updateDatabase(LiquibaseConfig.java:198) ~[main/:?]
	at com.configs.LiquibaseConfig.initLiquibase(LiquibaseConfig.java:74) ~[main/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1780) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:211) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:174) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:169) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAdaptableBeans(ServletContextInitializerBeans.java:154) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:87) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:266) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:240) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:52) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4414) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:874) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:437) ~[tomcat-embed-core-10.1.25.jar:10.1.25]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:128) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:107) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:516) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:222) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-3.3.1.jar:3.3.1]
	... 8 more
```

### Expected/Desired Behavior

Expectation is `database-files/upgradescripts/${release_type}/${release_version}` will resolve correctly.

Liquibase update and other commands and properly resolve the variables provided.

### Liquibase Version

4.29.1

### Database Vendor & Version

AWS - 16.3

### Liquibase Integration

Gradle + Springboot

### OS and/or Infrastructure Type/Provider

Windows and Amazon Linux

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by puneet139** [comment]
hi i find the issue very interesting and believe that i can contribute to resolve this. Can you kindly assign this issue to me.

**Comment by tati-qalified** [comment]
Hi @francisud, thank you for reporting this issue.
@puneet139 feel free to submit your changes as a PR, [here](https://contribute.liquibase.com/code/) is some information on how to contribute with code. Thank you!

**Comment by francisud** [comment]
> hi [@francisud](https://github.com/francisud) i find the issue very interesting and believe that i can contribute to resolve this. Can you kindly assign this issue to me.

hi @puneet139 
sorry looks like I don't have rights to assign the issue. the gear icon is not visible on my side.

looks like we can follow @tati-qalified's comment.

thank you.

**Comment by filipelautert** [comment]
@puneet139 seems that we are not setting the arguments when running the `changelogsync `command in `Liquibase `class, like below:

`.addArgumentValue(DatabaseChangelogCommandStep.CHANGELOG_PARAMETERS, changeLogParameters)`

Probably just adding this to the code will fix it.

**Comment by MalloD12** [comment]
Hi @francisud,

I've been looking into this issue, and it seems to be working as expected. Even though, as @filipelautert mentioned, changelog parameters setup is missing for `ChangeLogSync` command, it doesn't fix this issue because changelog parameters are not visible/available in the `search()`  method implementation in the resource accessor (AbstractPathResourceAccessor). That's why we are seeing:

```
Caused by: liquibase.exception.SetupException: Could not find directory, directory was empty, or no changelogs matched the provided search criteria for includeAll 'changelog/xml/${release_type}/${release_version}'
```

I think if we want to perform something like this at the moment, our only option would be to define some properties in our changelog and then use them in the `includeAll` path. 

An example of this would looks like:

```XML
<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

    <property name="release_type" value="releaseType"/>
    <property name="release_version" value="releaseVersion"/>

 <includeAll path="database-files/upgradescripts/${release_type}/${release_version}"
              maxDepth="1" />
              
```

There is a proposal to add a variable feature similar to the properties but with the ability to change/update its value at runtime, but that's still under analysis (see #5554). 

Thanks,
Daniel.

**Comment by MalloD12** [comment]
For what @filipelautert mentioned about missing `changeLogParameters` argument #6512 has been created.

**Comment by MalloD12** [comment]
Hi @puneet139, 

What do you mean? #6512 is not an issue, it's a PR that we created to add the missing `changelogParameters` command arguments for some commands. Of course you are more than welcome to look at it and share any feedback you might have about it.

Thanks,
Daniel.

**Comment by filipelautert** [comment]
The missing `changeLogParameters` argument for `changeLogSync` was added in PR #6512 (merged Nov 2024). However, as @MalloD12 explained, using changelog parameters in `includeAll` paths is a known limitation since parameters aren't available during resource accessor search. That broader capability is tracked in #5554.

Closing the original issue since the missing argument was fixed. The `includeAll` path variable use case is covered by #5554.
