### ISSUE TITLE
RuntimeException thrown when 'generate-changelog' command tries to process a insert change for SQL changelog format

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#6396]
### Search first

- [x] I searched and no similar issues were found

### Description

While running either `PostgresThreadingTest` and `GenerateChangeLogEmptyIntegrationTest` together from `MVN` or the `IDE` it ended up making the below test:

```groovy
def "Should generate changelog file with non-empty table"() {
        given:
        def changelogFileName = "target/test-classes/changelogs/update.changelog.sql"
        def resourceAccessor = new SearchPathResourceAccessor(".,target/test-classes")
        def scopeSettings = [
                (Scope.Attr.resourceAccessor.name()) : resourceAccessor
        ]
        Scope.child(scopeSettings, {
            CommandUtil.runUpdate(db, changelogFileName, "both", null, null)
        } as Scope.ScopedRunner)

        when:
        def outputFileName = 'test/test-classes/output2.postgresql.sql'
        CommandUtil.runGenerateChangelog(db, outputFileName, "tables, data")
        def outputFile = new File(outputFileName)
        def fileContent = FileUtil.getContents(outputFile)

        then:
        fileContent.containsIgnoreCase("CREATE TABLE \"generate_changelog_test_sql\"")
        fileContent.containsIgnoreCase("INSERT INTO \"generate_changelog_test_sql\"")

        cleanup:
        outputFile.delete()
    }
```
`update.changelog.sql`:
```sql
--liquibase formatted sql

--changeset mallod:1 labels:generateChangelogWithEmptyTable,both
CREATE TABLE public.generate_changelog_test_sql (id int not null primary key, name varchar(255));

--changeset mallod:2 labels:both
INSERT INTO public.generate_changelog_test_sql (id, name) VALUES (1, 'Geronimo!');
```

to fail with the below exception:

```java
[ERROR] liquibase.command.core.GenerateChangeLogEmptyIntegrationTest.Should generate changelog file with non-empty table -- Time elapsed: 0.486 s <<< ERROR!
liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Unable to read file private/var/folders/cm/1krjp23j0j9054m7xfn_gwtc0000gn/T/liquibase-data/generate_changelog_test_sql.csv
	at liquibase.command.CommandScope.execute(CommandScope.java:258)
	at liquibase.command.util.CommandUtil.runGenerateChangelog(CommandUtil.groovy:89)
	at liquibase.command.core.GenerateChangeLogEmptyIntegrationTest.Should generate changelog file with non-empty table(GenerateChangeLogEmptyIntegrationTest.groovy:61)
	Suppressed: java.lang.NullPointerException: Cannot invoke method delete() on null object
		at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:113)
		at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:151)
		at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
		at liquibase.command.core.GenerateChangeLogEmptyIntegrationTest.$spock_feature_0_1(GenerateChangeLogEmptyIntegrationTest.groovy:70)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:187)
		at org.spockframework.runtime.model.MethodInfo.lambda$new$0(MethodInfo.java:49)
		at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:156)
		at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:407)
		at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:390)
		at org.spockframework.runtime.PlatformSpecRunner.runFeatureMethod(PlatformSpecRunner.java:324)
		at org.spockframework.runtime.IterationNode.execute(IterationNode.java:50)
		at org.spockframework.runtime.SimpleFeatureNode.execute(SimpleFeatureNode.java:58)
		at org.spockframework.runtime.SimpleFeatureNode.execute(SimpleFeatureNode.java:15)
		at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40)
		at org.spockframework.runtime.IterationNode.lambda$around$0(IterationNode.java:67)
		at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunIteration$5(PlatformSpecRunner.java:236)
		at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:156)
		at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:407)
		at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:390)
		at org.spockframework.runtime.PlatformSpecRunner.runIteration(PlatformSpecRunner.java:218)
		at org.spockframework.runtime.IterationNode.around(IterationNode.java:67)
		at org.spockframework.runtime.SimpleFeatureNode.lambda$around$0(SimpleFeatureNode.java:52)
		at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40)
		at org.spockframework.runtime.FeatureNode.lambda$around$0(FeatureNode.java:41)
		at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunFeature$4(PlatformSpecRunner.java:199)
		at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:156)
		at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:407)
		at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:390)
		at org.spockframework.runtime.PlatformSpecRunner.runFeature(PlatformSpecRunner.java:192)
		at org.spockframework.runtime.FeatureNode.around(FeatureNode.java:41)
		at org.spockframework.runtime.SimpleFeatureNode.around(SimpleFeatureNode.java:52)
		at org.spockframework.runtime.SimpleFeatureNode.around(SimpleFeatureNode.java:15)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40)
		at org.spockframework.runtime.SpecNode.lambda$around$0(SpecNode.java:63)
		at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunSpec$0(PlatformSpecRunner.java:61)
		at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:156)
		at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:407)
		at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:390)
		at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:55)
		at org.spockframework.runtime.SpecNode.around(SpecNode.java:63)
		at org.spockframework.runtime.SpecNode.around(SpecNode.java:11)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Unable to read file private/var/folders/cm/1krjp23j0j9054m7xfn_gwtc0000gn/T/liquibase-data/generate_changelog_test_sql.csv
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:236)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:126)
	at liquibase.command.core.GenerateChangelogCommandStep.run(GenerateChangelogCommandStep.java:155)
	at liquibase.command.CommandScope.execute(CommandScope.java:220)
	... 2 more
Caused by: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Unable to read file private/var/folders/cm/1krjp23j0j9054m7xfn_gwtc0000gn/T/liquibase-data/generate_changelog_test_sql.csv
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:219)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:172)
	... 5 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: Unable to read file private/var/folders/cm/1krjp23j0j9054m7xfn_gwtc0000gn/T/liquibase-data/generate_changelog_test_sql.csv
	at liquibase.change.core.LoadDataChange.generateStatements(LoadDataChange.java:244)
    at liquibase.serializer.core.formattedsql.FormattedSqlChangeLogSerializer.serialize(FormattedSqlChangeLogSerializer.java:51)
	at liquibase.serializer.core.formattedsql.FormattedSqlChangeLogSerializer.write(FormattedSqlChangeLogSerializer.java:126)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:280)
	at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:182)
	... 10 more

```

GenerateChangeLogEmptyIntegrationTest is part of this community [PR](https://github.com/liquibase/liquibase/pull/6378), and for some reason when trying to generate the statements for the insert change it’s trying to read this file from the following path private/var/folders/cm/1krjp23j0j9054m7xfn_gwtc0000gn/T/liquibase-data/generate_changelog_test_sql.csv.
 

**Note**: whole test execution details has been attached in `test-issue.txt` file.

### Steps To Reproduce

See description[test-issue.txt](https://github.com/user-attachments/files/17264266/test-issue.txt)

### Expected/Desired Behavior

Both test suites should be successfully executed

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
I've been working on this and trying to reproduce it, but I couldn't reproduce this same issue which a few weeks ago was so easy to reproduce.

I've tried to reproduce it using H2 and Postgres DBs but without any luck. I think it could be related to some other issue that might be fixed separately. I'll reopen it and keep investigating it if I see it again.

Thanks,
Daniel.-
