### ISSUE TITLE
"addForeignKeyConstraint is not supported on sqlite" error is shown when running changelog-sync-sql command in SQLite

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#6476]
### Search first

- [x] I searched and no similar issues were found

### Description

Running `changelog-sync-sql` command fails when there is an `addForeignKeyConstraint` change on the changelog in SQLite. This issue has been provided and raised by user `MDee` in a forum [post](https://forum.liquibase.org/t/addforeignkeyconstraint-is-not-supported-on-sqlite/9861).

For example, using the below changelog:

```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
    <changeSet author="mallod (generated)" id="1730494245750-1">
        <createTable tableName="child_table">
            <column name="ref1" type="INTEGER"/>
            <column name="ref2" type="INTEGER"/>
        </createTable>
    </changeSet>
    <changeSet author="mallod (generated)" id="1730494245750-2">
        <createTable tableName="father_table1">
            <column name="some_key" type="INTEGER">
                <constraints nullable="false" primaryKey="true" primaryKeyName="pk_father1"/>
            </column>
            <column name="some_value" type="VARCHAR(200)"/>
        </createTable>
    </changeSet>
    <changeSet author="mallod (generated)" id="1730494245750-3">
        <createTable tableName="father_table2">
            <column name="some_key" type="INTEGER">
                <constraints nullable="false" primaryKey="true" primaryKeyName="pk_father2"/>
            </column>
            <column name="some_value" type="VARCHAR(200)"/>
        </createTable>
    </changeSet>
    <changeSet author="mallod (generated)" id="1730494245750-4">
        <addForeignKeyConstraint baseColumnNames="ref1" baseTableName="child_table" constraintName="fk_ref1" deferrable="false" initiallyDeferred="false" onDelete="NO ACTION" onUpdate="NO ACTION" referencedColumnNames="some_key" referencedTableName="father_table1" validate="true"/>
    </changeSet>
    <changeSet author="mallod (generated)" id="1730494245750-5">
        <addForeignKeyConstraint baseColumnNames="ref2" baseTableName="child_table" constraintName="fk_ref2" deferrable="false" initiallyDeferred="false" onDelete="NO ACTION" onUpdate="NO ACTION" referencedColumnNames="some_key" referencedTableName="father_table2" validate="true"/>
    </changeSet>
</databaseChangeLog>

```

Will provided the below execution:

```terminal
[2024-11-01 18:17:45] INFO [liquibase.ui] ERROR: Exception Primary Class:  ValidationFailedException
ERROR: Exception Primary Reason:  Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)

[2024-11-01 18:17:45] INFO [liquibase.ui] ERROR: Exception Primary Reason:  Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)

ERROR: Exception Primary Source:  [local build]
[2024-11-01 18:17:45] INFO [liquibase.ui] ERROR: Exception Primary Source:  [local build]
[2024-11-01 18:17:45] INFO [liquibase.command] Command execution complete
[2024-11-01 18:17:45] FINE [liquibase.configuration] No configuration value for liquibase.analytics.devOverride found
[2024-11-01 18:17:45] FINE [liquibase.configuration] Configuration liquibase.analytics.devOverride is using the default value of false
[2024-11-01 18:17:45] SEVERE [liquibase.analytics] Analytics is disabled because this is not a release build and the user has not provided a value for the liquibase.analytics.devOverride option.
[2024-11-01 18:17:45] SEVERE [liquibase.integration] Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)
liquibase.exception.CommandExecutionException: liquibase.exception.ValidationFailedException: Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)

	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:278)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.command.CommandScope.execute(CommandScope.java:219)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:391)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:366)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:363)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:407)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:92)
	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:231)
	... 26 more


Unexpected error running Liquibase: Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)

liquibase.exception.CommandExecutionException: liquibase.exception.ValidationFailedException: Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)

	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:278)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.command.CommandScope.execute(CommandScope.java:219)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:391)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:366)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:363)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     2 changes have validation failures
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-4::mallod (generated)
          addForeignKeyConstraint is not supported on sqlite, sqlite-generatedFile.xml::1730491284340-5::mallod (generated)

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:407)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:92)
	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:231)
	... 26 more
```

### Steps To Reproduce

1- Execute `changelog-sync-sql` command in SQLite using the changelog provided above

### Expected/Desired Behavior

`changelog-sync-sql` should be executed successfully

### Liquibase Version

4.29.2

### Database Vendor & Version

SQLite

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment]
I think this original issue can be ignored, but as discussed in pre-planning, we need to update docs (see [PD-5119](https://datical.atlassian.net/browse/PD-5119). Someone from the community has also created this liquibase-docs [issue](https://github.com/liquibase/liquibase-docs/issues/105).

**Comment by MalloD12** [comment]
I am closing this, as this is a small doc change that requires an update. This change will be addressed in [PD-5119](https://datical.atlassian.net/browse/PD-5119).
