### ISSUE TITLE
Scope.child(ClassLoaderResourceAccessor) broken in 4.30.0 (worked in 4.29.0)

### ISSUE THREAD

**Issue by fateh288** [liquibase/liquibase#6517]
### Search first

- [x] I searched and no similar issues were found

### Description

My code broke when I upgraded from 4.29.0 to 4.30.0 and gives the below exception which results in the command to fail
```
Exception in thread "main" java.lang.IllegalArgumentException: java.lang.RuntimeException: Cannot end scope ceiprpiwoc when currently at scope wreimdntmc
        at liquibase.configuration.ConfigurationValueUtils.convertDataType(ConfigurationValueUtils.java:25)
        at liquibase.configuration.ConfiguredValue.getValue(ConfiguredValue.java:40)
        at liquibase.command.CommandScope.getArgumentValue(CommandScope.java:139)
        at liquibase.command.CommandArgumentDefinition.validate(CommandArgumentDefinition.java:118)
        at liquibase.command.CommandScope.validate(CommandScope.java:189)
        at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:224)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.command.CommandScope.execute(CommandScope.java:219)
        at org.apache.ranger.db.upgrade.LiquibaseCommandDriver.executeLiquibaseCommand(LiquibaseCommandDriver.java:47)
        at org.apache.ranger.db.upgrade.LiquibaseCommandDriver.tagExists(LiquibaseCommandDriver.java:64)
        at org.apache.ranger.db.upgrade.LiquibaseUpdateDriverMain.lambda$main$0(LiquibaseUpdateDriverMain.java:106)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.Scope.child(Scope.java:260)
        at liquibase.Scope.child(Scope.java:264)
        at org.apache.ranger.db.upgrade.LiquibaseUpdateDriverMain.main(LiquibaseUpdateDriverMain.java:87)
Caused by: java.lang.RuntimeException: Cannot end scope ceiprpiwoc when currently at scope wreimdntmc
        at liquibase.Scope.exit(Scope.java:241)
        at liquibase.Scope.child(Scope.java:205)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.Scope.child(Scope.java:260)
        at liquibase.configuration.ConfigurationValueUtils.convertDataType(ConfigurationValueUtils.java:22)
        ... 18 more
```

### Steps To Reproduce

My driver class looks similar to the below code (it is a snippet from my actual code).
My code worked fine in 4.29.0 but broke in 4.30.0

```
public class LiquibaseIssue {
  private static CommandResults executeLiquibaseCommand(String commandName,
      HashMap<String, Object> commandSpecificArguments) throws CommandExecutionException {
    final String url = factory.getUrl();
    final String username = factory.getUsername();
    final String password = factory.getPassword();
    final String driver = factory.getDriver();
    CommandScope commandScope = new CommandScope(commandName);
    commandScope.addArgumentValue("url", url);
    commandScope.addArgumentValue("username", username);
    commandScope.addArgumentValue("password", password);
    commandScope.addArgumentValue("driver", driver);
    for (String argumentName : commandSpecificArguments.keySet()){
      commandScope.addArgumentValue(argumentName, commandSpecificArguments.get(argumentName));
    }
    return commandScope.execute();
  }
  public static void main( String[] argv) throws Exception {
    Scope.child(Scope.Attr.resourceAccessor, new ClassLoaderResourceAccessor(), () -> {
      HashMap<String, Object> tagParams = new HashMap<>();
      tagParams.put("tag", "v1");
      CommandResults result = executeLiquibaseCommand("tagExists", tagParams);
    });
  }
}
```

### Expected/Desired Behavior

There should not be any behavior change from 4.29.0 to 4.30.0 and child scope with ClassLoaderResourceAccessor should continue to work

### Liquibase Version

4.30.0

### Database Vendor & Version

postgresql

### Liquibase Integration

java spring with CommandScope integration

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Pinako-Ana** [comment]
Hello,
I’ve tried to reproduce this issue using the following setup:

#### Environment:
- Liquibase version: 4.29.0, 4.30.0
- Database: PostgreSQL 16.2 (running in a Docker container)
- JDBC Driver: org.postgresql:postgresql:42.7.4
- Java version: Corretto 17
- OS: macOS 

#### Code
```java

public class LiquibaseTest {
	private static CommandResults executeLiquibaseCommand(String commandName,
		HashMap<String, Object> commandSpecificArguments) throws CommandExecutionException {
		final String url = "jdbc:postgresql://localhost:5432/testdb";
		final String username = "testuser";
		final String password = "testpass";
		final String driver = "org.postgresql.Driver";
		CommandScope commandScope = new CommandScope(commandName);
		commandScope.addArgumentValue("url", url);
		commandScope.addArgumentValue("username", username);
		commandScope.addArgumentValue("password", password);
		commandScope.addArgumentValue("driver", driver);

		for (String argumentName : commandSpecificArguments.keySet()){
			commandScope.addArgumentValue(argumentName, commandSpecificArguments.get(argumentName));
		}
		return commandScope.execute();
	}
	public static void main( String[] argv) throws Exception {
		Scope.child(Scope.Attr.resourceAccessor, new ClassLoaderResourceAccessor(), () -> {
			HashMap<String, Object> tagParams = new HashMap<>();
			executeApplyLog();
			addTag("v1");

			tagParams.put("tag", "v2");
			executeLiquibaseCommand("tagExists", tagParams);
		});
	}

	private static void addTag(String tagName) throws CommandExecutionException {
		CommandScope commandScope = new CommandScope("tag");
		commandScope.addArgumentValue("url", "jdbc:postgresql://localhost:5432/testdb");
		commandScope.addArgumentValue("username", "testuser");
		commandScope.addArgumentValue("password", "testpass");
		commandScope.addArgumentValue("driver", "org.postgresql.Driver");
		commandScope.addArgumentValue("tag", tagName);
		commandScope.execute();
	}

	private static void executeApplyLog() throws CommandExecutionException {
		CommandScope commandScope = new CommandScope("update");
		commandScope.addArgumentValue("url", "jdbc:postgresql://localhost:5432/testdb");
		commandScope.addArgumentValue("username", "testuser");
		commandScope.addArgumentValue("password", "testpass");
		commandScope.addArgumentValue("driver", "org.postgresql.Driver");
		commandScope.addArgumentValue("changelogFile", "changelog.xml");
		commandScope.execute();
	}
}

```
I tested both version 4.29.0 and 4.30.0, but I couldn’t reproduce the error.
Is there anything I might have missed or any additional configuration values I should include?

**Comment by tati-qalified** [comment]
As we haven't been able to replicate this problem and there haven't been any more reports about it, we'll be closing this issue. Feel free to leave a comment if you wish to reopen it.
