### ISSUE TITLE
LoadDataChange and SpringResourceAccessor can raise NPE for CLOB values

### ISSUE THREAD

**Issue by sapo-di** [liquibase/liquibase#6539]
### Search first

- [x] I searched and no similar issues were found

### Description

I am receiving the following exception after updating from liquibase 4.26.0 to 4.30.0:

<details>
<summary>Stacktrace</summary>

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Failed to initialize dependency 'liquibase' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'liquibase' defined in class path resource [org/example/db_provider/configuration/LiquibaseConfig.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset my-changeset:
     Reason: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:954)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
        at org.example.db_provider.DbProviderApp.main(DbProviderApp.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/example/db_provider/configuration/LiquibaseConfig.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset my-changeset:
     Reason: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
        ... 17 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset my-changeset:
     Reason: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:272)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
        ... 24 common frames omitted
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset my-changeset:
     Reason: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:278)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.command.CommandScope.execute(CommandScope.java:219)
        at liquibase.Liquibase.lambda$update$0(Liquibase.java:216)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.Liquibase.runInScope(Liquibase.java:1329)
        at liquibase.Liquibase.update(Liquibase.java:205)
        at liquibase.Liquibase.update(Liquibase.java:188)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:310)
        at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:262)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:255)
        ... 26 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset my-changeset:
     Reason: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:155)
        at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:114)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:112)
        at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:100)
        at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:231)
        ... 44 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset my-changeset:
     Reason: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:821)
        at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:126)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:70)
        at liquibase.changelog.ChangeLogIterator.lambda$run$0(ChangeLogIterator.java:133)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.changelog.ChangeLogIterator.lambda$run$1(ChangeLogIterator.java:122)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.Scope.child(Scope.java:260)
        at liquibase.Scope.child(Scope.java:264)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:91)
        ... 52 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at liquibase.change.core.LoadDataChange.generateStatements(LoadDataChange.java:482)
        at liquibase.changelog.ChangeSet.lambda$addSqlMdc$2(ChangeSet.java:1624)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.changelog.ChangeSet.addSqlMdc(ChangeSet.java:1623)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:774)
        ... 67 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "relativePath" is null
        at org.springframework.core.io.UrlResource.createRelativeURL(UrlResource.java:321)
        at org.springframework.core.io.UrlResource.createRelative(UrlResource.java:308)
        at liquibase.integration.spring.SpringResource.resolveSibling(SpringResource.java:44)
        at liquibase.change.core.LoadDataChange.generateStatements(LoadDataChange.java:397)
        ... 74 common frames omitted

```

</details>

While loading data from a CSV file  with the `SpringResourceAccessor` it is possible to raise a NullPointerException if the CSV contains empty values in a column. 

In `liquibase.change.core.LoadDataChange#generateStatements#generateStatements`  it is this else if branch: `else if (columnConfig.getTypeEnum() == LOAD_DATA_TYPE.CLOB)`.

The following line of code will fail if `value` is null:

 ```java
 r = Scope.getCurrentScope().getResourceAccessor().get(getRelativeTo()).resolveSibling(value);
```

**Example change set**

The logic file path value is set.

```xml
<databaseChangeLog logicalFilePath="foo/bar.xml" > 
   <changeSet author="Author 1" id="1546511546876-2" >
        <loadUpdateData commentLineStartsWith="#"
                        encoding="UTF-8"
                        file="../../../data/MyData.csv"
                        relativeToChangelogFile="true"
                        quotchar="\"
                        separator=";"
                        schemaName="public"
                        usePreparedStatements="true"
                        tableName="my-foo"
                        primaryKey="id">
            <column name="id" type="COMPUTED" defaultValueComputed="${uuid_function}"/>
            <column name="created_at" type="time" defaultValueDate="2022-01-01 00:00:00.000000"/>
            <column name="created_by" type="uuid" defaultValue="e13e576e-a783-4f24-a177-41c74eeb8b99"/>
            <column name="modified_at" type="time" defaultValueDate="2022-01-01 00:00:00.000000"/>
            <column name="modified_by" type="uuid" defaultValue="e13e576e-a783-4f24-a177-41c74eeb8b99"/>
            <column name="name" type="STRING"/>
        </loadUpdateData>
    </changeSet>
</databaseChangeLog>
``` 

**Example CSV**

```csv
id;created_at;created_by;modified_at;modified_by;name;description;empty_string
;;;;;test-value;a description;
```

### Steps To Reproduce

- Use Spring Boot Liquibase
- Use a `loadUpdateData` changeset with a csv file
- Have a column with an empty value
- Have no default value so it tries to insert `null`

### Expected/Desired Behavior

It should not fail and insert `null` for the specific column

### Liquibase Version

4.30.0

### Database Vendor & Version

PostgreSQL 17.0

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

Manjaro Linux

### Additional Context

The code was introduced in #6410.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Fixed by https://github.com/liquibase/liquibase/pull/6540 .
