### ISSUE TITLE
Liquibase loses definitions of configuration parameters when it is used from multiple threads resulting in: "Strict check failed due to undefined key(s) for 'update' command in class path resource [liquibase.properties]"

### ISSUE THREAD

**Issue by t-beckmann** [liquibase/liquibase#6541]
### Search first

- [x] I searched and no similar issues were found

### Description

I ran into an issue executing integration tests of a Spring Boot application in JUnit 5 concurrent execution. The error I am getting is:
```
java.lang.IllegalArgumentException: Strict check failed due to undefined key(s) for 'update' command in class path resource [liquibase.properties]':
 - 'liquibase.alwaysDropInsteadOfReplace'
 - 'liquibase.headless'
 - 'liquibase.onMissingIncludeChangelog'
 - 'liquibase.strict'
 - 'liquibase.supportsMethodValidationLevel'
 - 'liquibase.validateXmlChangelogFiles'
To define keys that could apply to any command, prefix it with 'liquibase.command.'
To disable strict checking, remove 'strict' from the file.
	at liquibase.configuration.core.DefaultsFileValueProvider.validate(DefaultsFileValueProvider.java:103)
	at liquibase.command.CommandScope.validate(CommandScope.java:182)
	at liquibase.command.CommandScope.execute(CommandScope.java:213)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:216)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Liquibase.runInScope(Liquibase.java:1329)
	... 174 common frames omitted
```

In order to apply `liquibase.properties` resource to configure Liquibase parameters, a `DefaultsFileValueProvider` is registered just like e.g. `LiquibaseCommandLine` main is doing. The `liquibase.properties` file looks like this:
```
# for a description see <https://docs.liquibase.com/parameters/home.html>
liquibase.alwaysDropInsteadOfReplace=true
liquibase.headless=true
liquibase.onMissingIncludeChangelog=FAIL
liquibase.strict=true
liquibase.supportsMethodValidationLevel=FAIL
liquibase.validateXmlChangelogFiles=false
```

**I debugged it and found the `LiquibaseConfiguration.definitions` being all empty!**

The reason it is empty is:
- each thread creates and a root scope when executing `Scope.getCurrentScope()` because of the thread-local at [liquibase/Scope.java#L78](https://github.com/liquibase/liquibase/blob/v4.29.2/liquibase-standard/src/main/java/liquibase/Scope.java#L78)
- the root scope object of each thread is initialized by calling `LiquibaseConfiguration.init(Scope)` at [liquibase/Scope.java#L103](https://github.com/liquibase/liquibase/blob/v4.29.2/liquibase-standard/src/main/java/liquibase/Scope.java#L103)
- init() in turn uses a `ServiceLoader` to fetch all implementations of `AutoloadedConfigurations` at [liquibase/configuration/LiquibaseConfiguration.java#L61](https://github.com/liquibase/liquibase/blob/v4.29.2/liquibase-standard/src/main/java/liquibase/configuration/LiquibaseConfiguration.java#L61), but notice these instances are not used except for logging in the loop
- this will load e.g. `GlobalConfiguration` which instantiates `ConfigurationDefinition` in a static block executing exactly once at class-load time at [liquibase/GlobalConfiguration.java#L61](https://github.com/liquibase/liquibase/blob/v4.29.2/liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java#L61)
- the definitions are registered as a side-effect of construction via the builder at [liquibase/configuration/ConfigurationDefinition.java#L362](https://github.com/liquibase/liquibase/blob/v4.29.2/liquibase-standard/src/main/java/liquibase/configuration/ConfigurationDefinition.java#L362)

In consequence the first `LiquibaseConfiguration` build for a scope gets all definitions registered, but any subsequently created one ends up all empty...

### Steps To Reproduce

Initialize liquibase scope from multiple threads.

### Expected/Desired Behavior

More than one LiquibaseConfiguration may be build in a JVM such that fresh instances have the same definitions. This is vital for integration tests running Liquibase more than once.

In particular the following code should work:
```java
Scope.getCurrentScope();
Scope.setScopeManager(null); // reset
final var liquibaseConfiguration = Scope.getCurrentScope().getSingleton(LiquibaseConfiguration.class);
assertThat(liquibaseConfiguration.getRegisteredDefinitions(true)).isNotEmpty();
```

### Liquibase Version

4.29.2

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

Java 17 running on Mac OS (dev) and/or Linux (CI)

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by t-beckmann** [comment]
To solve this I propose:
1. add an `init(LiquibaseConfiguration)` method to `AutoloadedConfigurations`
2. call it from `LiquibaseConfiguration.init(Scope)` instead of just logging the implementations found
3. move the `LiquibaseConfiguration.registerDefinition()` calls from the `build()` method to the new `init(..)` method

**Comment by MalloD12** [comment]
Hi @t-beckmann,

Have you tried version `4.30` and is still happening? If you don't, could you please try and let us know?

Thanks,
Daniel.

**Comment by t-beckmann** [comment]
Not tried as I don't have access to a dev machine right now. Yet, I scanned through the code paths outlined in the description and found no changes in master. What commit let's you assume it might be fixed already?

**Comment by MalloD12** [comment]
Hi @t-beckmann,

No, I don't have a clear indication of a specific commit that could fix this issue. I remember last week (or the week before), we were discussing with another team member, and he mentioned it would be worth first checking with the latest version, that's why, in the meantime, this person is going back from holidays, I thought we could try and make sure it keeps happening. 

Thanks,
Daniel.

**Comment by filipelautert** [comment]
@t-beckmann in 4.30.0 we had 2 changes related to threading issues:
* https://github.com/liquibase/liquibase/pull/6222
* https://github.com/liquibase/liquibase/pull/6358 - I believe this one may have fixed your issue. 

Could you give it a try and let us know if it works? Anyway your proposal seems interesting.

**Comment by t-beckmann** [comment]
The second change looks promising, am giving it a try. The error is present in 4.29.2 and it **is actually fixed** in 4.30.0! Great this is solved, many thanks!
