### ISSUE TITLE
Liquibase using PostgreSQL instead of SQL Server for version 4.27.0

### ISSUE THREAD

**Issue by sanashaikh11** [liquibase/liquibase#6579]
### Search first

- [x] I searched and no similar issues were found

### Description

Hi Team, We are using Liquibase version 4.27.0 .We use the liquibase with AWS RDS PostgreSQL, SqlServer and redshift in various environments(DEV,PROD etc) and connectivity to few RDS SQL Server instance would consistently fail with below error message.

[2024-12-13 13:53:09] INFO [liquibase.dataabse] Cannot check pg_settings
365com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'pg_settings'.
357 at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)

397[2024-12-13 13:53:09] INFO [liquibase.ext] Error getting default schema
398liquibase.exception.Database.Exception: Error executing SQL select current_schema():  'current_schema' is not a recognized build-in function name

708ERROR: Exception Details
709[2024-12-13 13:53:09] INFO [liquibase.ui] ERROR: Exception Details
710ERROR: Exception Primary Class: SQLServerException
711[2024-12-13 13:53:09] Exception Primary Reason: Incorrect syntax near 'WITHOUT'.

liquibase would fail even before applying our changesets seems like liquibase is trying to use PostgreSQL syntax

### Steps To Reproduce

We observed that when the RDS SQL Server instance name contains "ed" the liquibase operation fails.However, IF the RDS instance name does not include "ed" everything works as expected.

### Expected/Desired Behavior

Even if RDS contains "ed" liquibase execution should be successful

### Liquibase Version

4.27.0

### Database Vendor & Version

RDS SQL Server 2019,2016,2017

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @sanashaikh11, could you provide the changeset or SQL script that is failing?

**Comment by sanashaikh11** [comment]
Hi @tati-qalified 
Regardless of the changeset/sql script it executes successfully  when "ed" is not there in the endpoint of the RDS(sqlserver) but when "ed" is there in the rds endpoints it errors out with the below logs (Seems like liquibase is trying to use PostgreSQL syntax for SQLServer)

[2024-12-13 13:53:09] INFO [liquibase.dataabse] Cannot check pg_settings
365com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'pg_settings'.
357 at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)

397[2024-12-13 13:53:09] INFO [liquibase.ext] Error getting default schema
398liquibase.exception.Database.Exception: Error executing SQL select current_schema(): 'current_schema' is not a recognized build-in function name

708ERROR: Exception Details
709[2024-12-13 13:53:09] INFO [liquibase.ui] ERROR: Exception Details
710ERROR: Exception Primary Class: SQLServerException
711[2024-12-13 13:53:09] Exception Primary Reason: Incorrect syntax near 'WITHOUT'.


We are also facing similar issue when trying to connect with RDS(PostgreSQL) the query execution is successful when "ed" is not there in the endpoints of RDS(PostgreSQL) but when "ed" is there in the endpoint it errors out with the below logs (Seems like liquibase is trying to use SQLServer function for PostgreSQL)

ERROR: Exception Details
ERROR: function getdate() doesnot exist
 Hint: No function matches the given name and argument types.You might need to add explicit type casts.
position 145
ERROR: Exception primary source: PostgreSql 15.7
unexpected error running liquibase: Error executing SQL update public.databasechangeloglock SET LOCKED =TRUE , LOCKEDBY = 'XXXXXX', LOCKGRANTED = GETDATE() WHERE ID = 1 AND LOCKED = FALSE: ERROR: function getdate() doesnot exist
 Hint: No function matches the given name and argument types.You might need to add explicit type casts.

**Comment by tati-qalified** [comment]
hi @sanashaikh11, I haven't been able to replicate this issue. could you provide some more information on your setup?
- what are some endpoint names that fail?
- what are some that succeed?
- do you have any collations set up? 
- could you try running `liquibase update-sql` for each case and reviewing if the generated script contains the same error?

thank you,
Tatiana

**Comment by filipelautert** [comment]
We're currently triaging our backlog to ensure we can focus on the issues that matter most. With a large number of open issues, it becomes difficult to give each one the attention it deserves.

This issue has been closed due to inactivity — there have been no updates for over 30 days. If this is still relevant to you, please feel free to reopen it or create a new issue with updated context. We appreciate your contribution!
