### ISSUE TITLE
After Liquibase 4.30 concurrent runs across schemas fails with error "Cannot end scope sjoppdztjd when currently at scope afgkbpwawi"

### ISSUE THREAD

**Issue by palhoye** [liquibase/liquibase#6588]
### Search first

- [x] I searched and no similar issues were found

### Description

I have a multi-tenant application where each tenant has its own DB schema.
During startup I run Liquibase where I create a thread per tenant in order to run Liquibase across separate schemas concurrently. Each thread calls `liquibase.afterPropertiesSet()` to initiate the run for the schema.

This has worked fine until I upgraded to version 4.30. Now it errors with:
```
Caused by: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope sjoppdztjd when currently at scope afgkbpwawi
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:272) ~[liquibase-core-4.30.0.jar:na]

Suppressed: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope jaoaatdvyw when currently at scope xvjkpsrajj
		... 12 common frames omitted
	Caused by: java.lang.RuntimeException: Cannot end scope jaoaatdvyw when currently at scope xvjkpsrajj
		at liquibase.Scope.exit(Scope.java:241)
		at liquibase.Scope.child(Scope.java:205)
		at liquibase.Scope.child(Scope.java:193)
		at liquibase.Scope.child(Scope.java:172)
		at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:255)
```

Downgrading to Liquibase 4.29.2 resolves the issue.

### Steps To Reproduce

Spring Boot executes against separate tenant schemas concurrently by calling `liquibase.afterPropertiesSet()`

### Expected/Desired Behavior

It runs successfully without errors (as it does on 4.29.2 and before)

### Liquibase Version

4.30

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by facboy** [comment]
i've been noticing some seemingly multi-threaded related problems using `mvnd`, and am wondering whether it's also due to scope management: https://forum.liquibase.org/t/liquibase-maven-thread-safety/10117

**Comment by palhoye** [comment]
Just tried with version 4.31 and can confirm that this issue that was introduced in 4.30 is still prevalent in 4.31. 
Downgrading to 4.29.2 works.

**Comment by Gama11** [comment]
I have observed similar issues, also in an application where each tenant has its own DB schema. The symptoms seem a bit different, but that may be because we invoke Liquibase manually rather than through Spring.

In our case, we run tests in parallel, and starting with Liquibase 4.30, test execution hangs, seemingly because Liquibase doesn't manage to release the lock again (databasechangelock table entry).

**Comment by emouty** [comment]
> I have observed similar issues, also in an application where each tenant has its own DB schema. The symptoms seem a bit different, but that may be because we invoke Liquibase manually rather than through Spring.
> 
> In our case, we run tests in parallel, and starting with Liquibase 4.30, test execution hangs, seemingly because Liquibase doesn't manage to release the lock again (databasechangelock table entry).

I'm using the maven plugin ran in parallel (worked until 4.30) and I have a similar problem where even if `changelogSchemaName` and `databaseChangeLogLockTableName` are different the second liquibase execution is blocked by the lock from the first one.

I have found https://github.com/liquibase/liquibase/issues/6538 that might solve the issue

**Comment by filipelautert** [comment]
Hi! I'm afraid this may be related to the replacement of `ThreadLocal` by `InheritableThreadLocal` in Scope class. 

Could someone provide a sample project to reproduce this issue?  We may try to go back to `ThreadLocal` as in PR https://github.com/liquibase/liquibase/pull/6674 and see if it works, but the switch to `InheritableThreadLocal` had reasons. If this PR proves to work we need to revisit the other issues it will cause, so having a working failure example would be helpful.

**Comment by bvremmeinfor** [comment]
Hi, I think the comment from @filipelautert is spot on. `InheritableThreadLocal` in Scope class is related.

Updated [liquibase-threading-demo](https://github.com/bvremmeinfor/liquibase-threading-demo) project to showcase the issue. Adding a new test class that executes on the **main thread**, causes the **original multi-thread** test class to fail. Separately, they are OK.

Considering a workaround by resetting with  `Scope.setScopeManager(null);` before and after the outermost `Scope.child()` execution. Always good to clean up thread locals. This seems to work, but it might defeat the purpose of  `InheritableThreadLocal`?

**Comment by filipelautert** [comment]
@bvremmeinfor thanks for the project, I'd forgot about it. I pushed another commit to PR https://github.com/liquibase/liquibase/pull/6674, and now the test project is working again:

```
-- database maintenance OK for: DB_MT_10
-- database maintenance OK for: DB_MT_0
-- database maintenance OK for: DB_MT_8
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.462 s -- in org.example.lbthreading.LiquibaseThreadingTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.046 s
[INFO] Finished at: 2025-02-25T19:34:44-03:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

**Comment by bvremmeinfor** [comment]
Thanks @filipelautert. I haven't tried the fix in PR #6674 , but assigning a new ScopeManager to each thread as it spawns seems spot on as it is the holder of the current scope. Allows each thread to maintain separate scope hierarchies with inherited parent scope.

**Comment by filipelautert** [comment]
@bvremmeinfor btw, I hope you don't mind but I copied your tests here -> https://github.com/liquibase/liquibase/pull/6674/files

**Comment by bvremmeinfor** [comment]
No problem @filipelautert, anything to prevent regression 👍

**Comment by palhoye** [comment]
@filipelautert and @bvremmeinfor thanks a ton for working to resolve this issue, truly appreciate it. Do you know which release the fix will be in?

**Comment by filipelautert** [comment]
> [@filipelautert](https://github.com/filipelautert) and [@bvremmeinfor](https://github.com/bvremmeinfor) thanks a ton for working to resolve this issue, truly appreciate it. Do you know which release the fix will be in?

@palhoye it will be in the next one, `4.32.0`  .
